### ISSUE TITLE
URL parser thinks `>` is a valid URL character

### ISSUE THREAD

**Issue by Niggler** [thelounge/lounge#1001]
First off, thanks for this awesome irc client! ❤️ 

Ran into an issue with the following message:

```
Can I Use Node.innerText? [IE 6+ | FF 45+ | Chrome 4+ | Opera 9.5-9.6+ | Safari 3.2+ | iOS 4.0-4.1+ | Android 2.3+] Overall: 97.6% <http://caniuse.com/innertext>;
```

The expected URL is `http://caniuse.com/innertext` but lounge is grabbing `http://caniuse.com/innertext>`

**Comment by astorije** [comment]
I believe this should be addressed by #972.
@xPaw, can you confirm we have a test case for this, or if not maybe add one if you can?

**Comment by astorije** [comment]
And thanks for the kind words, @Niggler :)

**Comment by xPaw** [comment]
We indeed have a test for it in #972 called `should balance brackets`

**Comment by Bonuspunkt** [comment]
would test uri js with `<http://caniuse.com/innertext>;`

**Comment by astorije** [comment]
You mean balanced + semi colon?

**Comment by astorije** [comment]
Hey @Niggler, #972 should have fixed that. Mind testing your examples on `master`?
