### ISSUE TITLE
Add support for banlist messages

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#1008]
We ignore banlist messages which means we can't view them. Ideally a GUI would be nice eventually, but we should at least support seeing the messages.

**Comment by astorije** [comment]
Damn @YaManicKill, you really have a beef with some people! 😄
You've already opened that issue almost a year ago, ahah.
Closing as duplicate of https://github.com/thelounge/lounge/issues/285.

**Comment by YaManicKill** [comment]
Actually, @astorije, those are 2 different things.

#285 Is for a nice gui for the banlist, this one is to just view the messages themselves (because we currently filter them out).

**Comment by astorije** [comment]
Argh, ok. It's kind of a shame to have 2 open issues for this when they could be combined, but I get it.

Now that you reopened an issue, you have to close 2 to make up for it :D

**Comment by YaManicKill** [comment]
This one will be combined when I finish #1009
