### ISSUE TITLE
Use chrome's new "coverage" tools to identify potential bundle size optimizations 

### ISSUE THREAD

**Issue by MiniDigger** [thelounge/lounge#1010]
astorije found this today: https://twitter.com/addyosmani/status/848907772318015488 and I decided to play around with it a bit. he requested that I add some nice screenshots so ppl can see how this tool could help developing a webapp.

I went thru all features the lounge has and generated a report so visualize it:
![http://i.minidigger.me/2017/04/2017-04-04_20-51-45.png](http://i.minidigger.me/2017/04/2017-04-04_20-51-45.png)
for the looks of it is seems like most of bootstraps stuff is unused, all the blockquote, grid, list, h stuff gets marked red: 
![http://i.minidigger.me/2017/04/chrome_04_20-54-21.png](http://i.minidigger.me/2017/04/chrome_04_20-54-21.png)
the bundle.js stuf looks better, most of the stuff I either didn't test or it was for mobile:
![http://i.minidigger.me/2017/04/chrome_04_20-55-57.png](http://i.minidigger.me/2017/04/chrome_04_20-55-57.png)
the vendor bundle is harder for me to understand (its also way larger, lol)
I noticed that for example most methods in the json parser are not used.
![http://i.minidigger.me/2017/04/chrome_04_21-00-17.png](http://i.minidigger.me/2017/04/chrome_04_21-00-17.png)

I have no idea about the js ecosystem, but in java we have a minimizer in our buildtools that strips all methods and classes that are not used (never referenced in the source of the project). maybe something like this exists for js?

**Comment by YaManicKill** [comment]
> maybe something like this exists for js?

Kind of. Tree shaking exists, but it only works with ES6 modules. There isn't something for commonjs modules (which our code uses).

But this is definitely something we should take a look into. There are probably other ways we can do the JS removing. So, having a touch bundle that only downloads on devices that have a touchscreen, stuff like that.

Good stuff, I had noticed this went live in Chrome yesterday.

**Comment by xPaw** [comment]
Closure compiler does this. But it's quite slow (fine for production builds?). Unsure it will work correctly with all the third party code we have. Maybe someone wants to give it a try.

**Comment by xPaw** [comment]
This issue is not very specific so I'm going to close it.

**Comment by astorije** [comment]
All screenshots are 404 now. Next time, drag-and-drop your pictures to the issue itself, so we can keep them around :)

**Comment by astorije** [comment]
@xPaw, what do you mean by not very specific?

**Comment by xPaw** [comment]
It's basically a suggestion to use the tool, but we there's no reason to keep this issue open.

**Comment by MiniDigger** [comment]
urg, I really need to fix my reverse proxy,  images below

![2017-04-04_20-51-45](https://user-images.githubusercontent.com/2185527/29888151-2aff8154-8dc0-11e7-8743-b34b77a3bdaf.png)

![chrome_04_20-54-21](https://user-images.githubusercontent.com/2185527/29888165-375e70fe-8dc0-11e7-9ba9-cbd0aa61602f.png)

![chrome_04_20-55-57](https://user-images.githubusercontent.com/2185527/29888168-39b8b36e-8dc0-11e7-8017-f10b3499c894.png)

![chrome_04_21-00-17](https://user-images.githubusercontent.com/2185527/29888175-3cb63802-8dc0-11e7-82c5-5e5d9b2a8100.png)
