### ISSUE TITLE
[Feature request] Option to show MOTD by default

### ISSUE THREAD

**Issue by KlipperKyle** [thelounge/lounge#1019]
Currently, the server's MOTD is hidden unless the user checks the box in Options to show the MOTD.

Some servers put useful information for new users in the MOTD such as links to rules and howto pages.  I am currently maintaining a private server for some coworkers, and I do just that.  irc.twit.tv is an example of a public server that posts important information in the server's MOTD (i.e. rules, and if you don't follow their rules, the operators are not happy).

There are some cases where you might really want people to see the MOTD.  It would be nice to have a setting in config.js to make the "show MOTD" option default to on.  (Users can always uncheck it if they want.)

**Comment by astorije** [comment]
I think having a server-side option to configure the default value of a client-side setting is really overkill 😅. That being said, I am in favor of having MOTD on by default, [which is a simple boolean change in the code](https://github.com/thelounge/lounge/blob/master/client/js/lounge.js#L602) if you want to open your first PR on the project :)

After all, we even show modes by default, which is in general as advanced or more than the MOTD, so I think we should enable it.
