### ISSUE TITLE
Holding pageup/pagedown scrolls very slowly

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1022]
What I assume happens is that previous animation gets stopped, and it scrolls up from that position where the animation stopped.

**Comment by astorije** [comment]
@xPaw, are you still thinking of fixing this for v2.3.0 or that won't make it?

**Comment by xPaw** [comment]
Ideally it should.

**Comment by YaManicKill** [comment]
This is broken again. Jquery is never returning true on container.is(":animated") anymore. We should probably try and figure out why.

**Comment by bews** [comment]
`container.stop().animate({` -> `container.stop(true, true).animate({` fixes this.

**Comment by xPaw** [comment]
It doesn't exactly fix scrolling while holding the key down.

**Comment by YaManicKill** [comment]
As this is new functionality, how much do we care about it getting into 2.3.0? It could go into 2.3.1. It's not a hugely major bug, as it adds functionality rather than breaking old functionality. Thoughts?

**Comment by bews** [comment]
> It doesn't exactly fix scrolling while holding the key down.

Have you tried it? Works for me.

**Comment by astorije** [comment]
I'm happy with this going to v2.3.1, @YaManicKill. @xPaw?

**Comment by YaManicKill** [comment]
So, the problem with the fix suggested by @bews is that it seems to jump up a lot more when holding down the key. If you press multiple times, it works nicely, but it's very sudden and jumpy if you hold the key down (but it is at least much quicker than on master).

**Comment by YaManicKill** [comment]
Right, let's drop this from 2.3.0, and push it to 2.3.1. Let's get 2.3.0 released.
