### ISSUE TITLE
"Cycle through nicks" does not work on Chrome Android

### ISSUE THREAD

**Issue by nicofrand** [thelounge/lounge#1023]
On Chrome 57.0.2987.132 on Android 7, the "Cycle through nicks" button does not work anymore (it used to, so that may come from an update of Chrome). I can click it but that does not do anything (the keyboard seems to be set in uppercase for half a second though), does not populate the input.

It works on desktop with Chrome Version 57.0.2987.133 (64-bit) and on both mobile and desktop with Firefox.

**Comment by realies** [comment]
Couldn't get this button to work on Chrome Andorid as well. Did not work on the latest Firefox, Chrome on Win10 and macOS using version 2.2.2.

**Comment by MaxLeiter** [comment]
Works for me on: latest Chrome, Safari, and Firefox on OS X, latest Chrome and Safari iOS 10.1

**Comment by Raqbit** [comment]
Having this issue, exactly as @nicofrand described, including the uppercase thing:

Oneplus One running Lineage OS, Chrome 57.0.2987.132

**Comment by xPaw** [comment]
Can confirm, exactly as OP describes.

**Comment by Raqbit** [comment]
What would be causing this issue? Something related with manipulating the input?

**Comment by astorije** [comment]
Not sure, but I will be nuking this button once #787 lands anyway 😅 (soon™).
