### ISSUE TITLE
Cannot connect. SASL access only.

### ISSUE THREAD

**Issue by sudhanshu16** [thelounge/lounge#1026]
I set up this on my AWS EC2 instance and I got the following:
```	Network created, connecting to irc.freenode.net:6697...
22:51		Connected to the network.
22:51	adams.freenode.net	*** Looking up your hostname...
22:51	adams.freenode.net	*** Checking Ident
22:51	adams.freenode.net	*** Found your hostname
22:51	adams.freenode.net	*** No Ident response
22:51	adams.freenode.net	*** Notice -- You need to identify via SASL to use this server
22:51		Closing Link: ec2-<instance-ip>.us-west-2.compute.amazonaws.com (SASL access only) (irc)
22:51		Disconnected from the network, and will not reconnect. Use /connect to reconnect again.```

**Comment by dgw** [comment]
This isn't a thing with The Lounge, but rather with connecting to freenode from AWS. If you register your nickname with freenode using your local connection, then set up The Lounge to log in to your freenode identity using SASL, you should be good to go.

I think SASL is available in The Lounge, but am having trouble finding information on configuring it. Perhaps it is not supported, and I'm mistaken. I know it's supported by irc-framework (the library this project uses to interact with IRC) as of December, at least…

**Comment by pinkeshbadjatiya** [comment]
Lounge supports SASL authentication. Essentially, you cannot connect to freenode without a registered nick. So,
1. Register your nick first.
2. Now, pass the password in the `password` field while connecting the server. Also pass the `nick` as usual. Server will automatically pass the password to NickServ for authentication.

**Comment by hillbilly-mark** [comment]
How do you register a nick without even logging in to do it?  All freenode page on registering is all about irc commands you have to be already logged in to use

**Comment by MaxLeiter** [comment]
@hillbilly-mark sorry for late reply, use /ns help to see how to use the register command.

**Comment by jcrben** [comment]
@hillbilly-mark I think to register first you can connect from another non-SASL required way such as one of the open web clients available online - I just connected as a guest using https://web.libera.chat/ for example to register on LIbera

**Comment by rfried-nrl** [comment]
@jcrben Exactly what I did
It's kind of chicken and egg.
