### ISSUE TITLE
Dedicated PM/channel pop-up window

### ISSUE THREAD

**Issue by realies** [thelounge/lounge#1029]
It might be useful to have an option to separate a private message or a channel from the main UI by right-clicking and sending the selected item in a new window. The idea is to have its communication dedicated to the private message or channel. This is currently possible by creating a new client instance, but it also doubles the incoming data and might have some impact on the server load.

**Comment by astorije** [comment]
I get the idea, but this is extremely unlikely to happen IMO.
It probably needs a major overhaul of the backend and frontend, and that would not even be possible on mobile anyway, so I don't think it would get picked by anyone from the community. Besides, there are a lot of other things higher in terms of priority, sorry :(

I don't know what others from @thelounge/maintainers think of this but I would close this, at least for now.

**Comment by YaManicKill** [comment]
Yeah, probably unlikely to happen. You can open the same site in 2 tabs just now anyway, and you can have a channel in that one, but you can't remove the rest from the list. But implementing it would be a really big job.
