### ISSUE TITLE
Look into adding touch-action to styles

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1035]
https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners
https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

This could improve performance and remove click delays. For example message and user list containers can only scroll up and down, so there is no need to handle vertical panning gestures.

Our `viewport` has `user-scalable="no"`, so we could get rid of `pinch-zoom` too.

**Comment by astorije** [comment]
Good idea, though I don't see myself taking that up anytime soon, so I will remove my assignment for now. If anyone wants to take this up, please do.

**Comment by iamstratos** [comment]
I think I could help you. It's my first contribution though. Is it a css job?

**Comment by MaxLeiter** [comment]
Should be just CSS, @iamstratos. If you need any help, be sure to hop onto #thelounge on freenode and ask any questions.

**Comment by astorije** [comment]
That would greatly appreciated @iamstratos, thanks!

**Comment by iamstratos** [comment]
Should I PR to master or another branch?

**Comment by MaxLeiter** [comment]
To master, @iamstratos
