### ISSUE TITLE
Holding down tab eventually focuses in user search and breaks the layout

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1036]
Focus out of the input bar and hold tab until it focuses in the user list search bar. User list has to be hidden to trigger this.

![14-201253420](https://cloud.githubusercontent.com/assets/613331/25054798/d57f9a08-2167-11e7-9220-1640374f0f9b.png)
This is the entire viewport screenshot, not a cut out.

**Comment by astorije** [comment]
What the hell is this! I would have thought of an Aprils' Fools if I couldn't repro. Good job catching this, pretty amazing you got to discover this.

This kind of issues would make https://github.com/marmelab/gremlins.js worth it on The Lounge.

**Comment by xPaw** [comment]
🙈

**Comment by kode54** [comment]
Input field focus switching arrows in the auto complete bar on iOS are a much easier way to trigger this bug. They manage to focus the user list search even when it is off screen.

**Comment by astorije** [comment]
@xPaw, should we fix this for v2.3.0 if autocomplete makes this bug more likely to trigger? Or 2.3.1 maybe? :D

**Comment by kode54** [comment]
It wasn't due to the built-in autocomplete. iOS's autocomplete bar also features up and down arrow buttons, for navigating between the fields in a page. They also happen to scroll the page to bring the entire field on screen.
