### ISSUE TITLE
Back button needs 2 presses to go back to another page (or quit)

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1042]
> Testing this after your fix, I'm still seeing something odd: say I'm on page A (not The Lounge), then type the URL of The Lounge (localhost when testing), then I have to hit "Back" twice to go back to A.

**Comment by williamboman** [comment]
For anyone who tries to fix this, a good starting point to understand the issue would be to change [these lines](https://github.com/thelounge/lounge/blob/fb04f9fcbf03b3ac9a07bb9b40f686096fd3e952/client/js/lounge.js#L220-L224) to trigger click via 

```js
.trigger("click", {
  pushState: false,
})
```

to avoid pushing a state entry to the history when loading the page, and observe the effects.
