### ISSUE TITLE
Split index.html into multiple files

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#1055]
Now that we are on the way to getting the client Javascript split up, I think it would be nice to get the index.html split up as well, because that is a *behemoth*.

We are currently apparently using lodash templating for the themes and the git commit, which seems a little weird...but I guess we could keep using that or switch to handlebars which we use for everything else.

**Comment by xPaw** [comment]
We should indeed use handlebars to pre-render it, as it would introduce consistency.

**Comment by YaManicKill** [comment]
Yeah, we need to use handlebars if we want to use an include,because lodash's one doesn't have an include.

**Comment by xPaw** [comment]
Now that we switched to handlebars this is easily doable. Anyone want to do it?

**Comment by astorije** [comment]
@xPaw, would splitting this make it more difficult to localize (cf. #1271), easier, or have no effect at all, you think?

**Comment by MaxLeiter** [comment]
Wouldn't have any effect

**Comment by JemBijoux** [comment]
Hey! I'd love to help out and take this on as part of Haktoberfest. Just need an evening to orient myself a bit to some of the code, so maybe have something over the next day or so...

**Comment by astorije** [comment]
We'd love that, @JemBijoux!
If this is of any help, I had attempted it very briefly in https://github.com/thelounge/lounge/commit/32c580be5618efcdb3c8b461592943f4bb426c75 but didn't move forward.
Good luck with that!
