### ISSUE TITLE
Remove tabcomplete plugin in favor of textcomplete

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1061]
*This will be relevant once #787 is merged*

We don't need two implementation of the same feature, I think we just need to figure an elegant way of triggering testcomplete's completion when there is no trigger (like `@`).

**Comment by yashsriv** [comment]
Just putting this here for anyone wanting to work on this issue:

I have tried removing tabcomplete on my branch here: https://github.com/yashsriv/lounge/tree/wip/notabcomplete

^ The above works but the code is convoluted (see the last commit).
