### ISSUE TITLE
auto away when no frontend client is connected

### ISSUE THREAD

**Issue by gdamjan** [thelounge/lounge#107]
lounge should set the status to 'away' when there's no client connected on the front-side.

**Comment by vectr0n** [comment]
+1

**Comment by MaxLeiter** [comment]
:+1: should be a setting imo

**Comment by JustRamon** [comment]
+∞

**Comment by richrd** [comment]
Very neat idea! Would it be possible to also show who is away in the nick list? Would be very useful.

**Comment by xPaw** [comment]
This should be straight forward to implement:
- on socketio close -> no more clients? -> send away to all connected irc networks
- on irc connected -> no socketio clients -> send away
- on socketio opened -> remove away

Am I missing anything? What should the away message be?

**Comment by dgw** [comment]
Something like "Auto away at <timestamp>", is how ZNC does it.

I'm with @MaxLeiter: This should be a setting, as I already have my ZNC do this and often use a desktop client instead of keeping The Lounge open.

**Comment by xPaw** [comment]
Setting is tricky because we don't have client-sends-settings-to-server.

**Comment by dgw** [comment]
Then maybe that should be a blocker for this being implemented. I'd probably have to discontinue using The Lounge if there was no way to prevent it from setting me as away just because I don't have it open in a browser tab somewhere.

**Comment by maxpoulin64** [comment]
Maybe it would be time to get a better settings system going so this is no longer an issue. "We'd need a setting but we can't" seems to be something that comes back fairly often. It would be sad to postpone this one given how simple it would be.

I'll try to see if I can make something in the weekend for the settings, both server-side and client-side.

**Comment by dgw** [comment]
I see @maxpoulin64 has made good on that in #275. :+1:

**Comment by maxpoulin64** [comment]
Slight comment as one pointed out on IRC: I had made this branch a while ago: https://github.com/thelounge/lounge/tree/patches/auto-away

It's a quick and dirty fix, but it does add the minimum of support some people need. We're still waiting for a better handling of network preferences and all before this goes into a real PR.

**Comment by YaManicKill** [comment]
Alrighty, this should be fixed by #775, in master and should be in the next release (2.3.0).
