### ISSUE TITLE
Text Rendering

### ISSUE THREAD

**Issue by bews** [thelounge/lounge#1071]
Don't know why (intentionally or it's just a bug) right now text is rendering in subpixel mode (https://en.wikipedia.org/wiki/Subpixel_rendering), which is looking bad on my display (TFT TN LED).

Now:
![lounge_a1](https://cloud.githubusercontent.com/assets/3627488/25311724/c35f2a0a-2810-11e7-80bb-40e50d19c22a.png)

Before (Shout):
![lounge_a2](https://cloud.githubusercontent.com/assets/3627488/25311730/e0a342b8-2810-11e7-8ee4-4d6948422eb1.png)

So, I would like to make a fix, which will change this rendering into old one. What do you think?

**Comment by YaManicKill** [comment]
I'm not sure on the advantages/disadvantages of different text rendering, but from what I can see it depends on what type of display you have? Is there an easy way for us to figure out different display types and use the right rendering for them? Feel free to correct me if I'm wrong, this is a very weak area of my knowledge.

**Comment by bews** [comment]
It's impossible to detect matrix type or display model.
As for advantages, I don't know. I think if some displays have some unique features then they should have special drivers, which change rendering everywhere.

We can make rendering type changeable in settings, but is it really needed? I still believe it was a bug in the first place.

**Comment by xPaw** [comment]
So how would you fix it? We don't set subpixel rendering anywhere besides tooltips.

**Comment by bews** [comment]
> So how would you fix it?
https://github.com/bews/lounge/commit/de666c33f60acb04085c0f8b11df5d6b0d0cc714

**Comment by astorije** [comment]
Does this break sidebars?

**Comment by bews** [comment]
No, I haven't noticed any side effects.
