### ISSUE TITLE
The Lounge responds to CTCP "VERSION."

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#1075]
The Lounge responds to CTCP `VERSION.` (note the dot), but it probably shouldn't. I've tried other punctuation (`VERSION;`, `VERSION,`, etc.) and every one I tried also triggered a reply.

The CTCP command is `VERSION`, full stop (pun intended). Responding to `VERSION.` or any other variation allows other users to bypass upstream protections like ZNC's CTCP filtering, which responds to specified CTCP requests on its own instead of sending them to connected clients, and get a reply from The Lounge by adding punctuation to the CTCP request. (Other clients, like Textual, appear to ignore malformed CTCP requests like this. Only The Lounge responds if I request `/ctcp dgw version.`; no other connected client does.)

Also odd is the fact that if someone else sends me a CTCP `VERSION.`, I get a response from The Lounge too. If I send myself a CTCP `VERSION.`, I get two replies.

**Comment by dgw** [comment]
Probably related: kiwiirc/irc-framework#39

**Comment by MaxLeiter** [comment]
Problem is kiwi uses substring to check the first n characters, so VERSIONanyStringHere will be responded to as VERSION

https://github.com/kiwiirc/irc-framework/blob/7d79e3629b6127431f991b9abbce6872d1483869/src/commands/handlers/messaging.js#L87

**Comment by MaxLeiter** [comment]
can be closed when #1123 is merged
