### ISSUE TITLE
Push notifications for mobile

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#1076]
Weird that we don't already have a ticket for this, and I've seen people mention it in IRC the past few days, so let's centralise discussion.

This is a good thing for us to do, and the way to do it is to use service workers and the [push api](https://developer.mozilla.org/en/docs/Web/API/Push_API). There are other ways of doing push notifications, but they are all 1 horrible and 2 proprietary. This is the open standard. It is currently in WD, but it's likely it'll be standardised sometime this year, hopefully. I would be very against any other system getting into master. [Currently supported on Chrome and FF](http://caniuse.com/#feat=push-api) (on both desktop and mobile). Biggest issue is no Safari yet, but iOS safari doesn't even supports Apple's own web push.

**Comment by Raqbit** [comment]
I wonder if apple is ever not behind on something >.>

They'll probably 'invent' web push later this year 😛

**Comment by xPaw** [comment]
Pretty much implemented in https://github.com/thelounge/lounge/compare/xpaw/push-notifications

To do:
- Set GCM variables in config
- Persist registrations in user config
- Allow unsubscribing
- Better UI for dealing with subscriptions
- Check for active channel/focus/activity
- Deal with notifications in queries

![30-180077859](https://cloud.githubusercontent.com/assets/613331/25566738/2e37b176-2de8-11e7-882b-f40c98e3fb1a.png)

**Comment by xPaw** [comment]
As it turns out, using VAPID stuff means admins no longer need a FCM/GCM service or keys. VAPID keys can automatically be generated on the server. This means push notifications will require zero configuration from lounge admins!

**Comment by xPaw** [comment]
🚢
