### ISSUE TITLE
Link preview truncates before the right edge of the viewport

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#1084]
With user list **open** (notice the second block not taking full width):

<img width="998" alt="screen shot 2017-04-25 at 00 13 57" src="https://cloud.githubusercontent.com/assets/113730/25361160/053be700-294d-11e7-9719-ba82f7d956e7.png">

With user list **closed** (both are wrong size):

<img width="1005" alt="screen shot 2017-04-25 at 00 14 09" src="https://cloud.githubusercontent.com/assets/113730/25361163/0f331b98-294d-11e7-92a5-0780039e80fa.png">

This is anecdotic but I have noticed this several times.

@maxpoulin64, is there any chance you could help with that?

**Comment by bews** [comment]
Um, should they? This is inherited from Shout. On large displays it might look weird:

![2017-05-02_07-21-29](https://cloud.githubusercontent.com/assets/3627488/25603845/43c21f10-2f08-11e7-83c4-173a7a70b792.png)
![2017-05-02_07-20-32](https://cloud.githubusercontent.com/assets/3627488/25603846/43c313d4-2f08-11e7-82e7-7a40621afeac.png)

Not sure though. Also, what about picture previews? It's almost the same design.

I'm working on these previews right now, so can change this too.

**Comment by astorije** [comment]
> Um, should they?

Well, it's a bug, so yes 😅

It's not about Shout vs. The Lounge, because we forked long ago and things have changed for good now: if you look at the second, third and fourth preview on my screenshots, you'll see the cutoff is not at the correct location (you can see 2 dots of the ellipsis even though there is room left.

Playing with this, I might have a fix.

**Comment by bews** [comment]
Well, my PR with new (again) previews is almost ready, but you probably won't like it :sweat_smile: (spoiler: bigger pictures and old multiline descriptions). However, it fixes this. I'll upload it soon™

**Comment by astorije** [comment]
Uuuh this is really painful. Other examples of this at https://github.com/thelounge/lounge/pull/1256#issuecomment-312554455.

I have tried different ways to fix this, but couldn't find anything that wouldn't take 100% width when text does not go all the way.

@xPaw, do you have any idea about this?

**Comment by astorije** [comment]
I have noticed #1256 makes this issue more visible because most titles are now smaller, which makes the whole truncated block smaller.

**Comment by xPaw** [comment]
Okay I figured the issue out. `float: left` on the thumbnail image is not pushing the width correctly.
