### ISSUE TITLE
Channel sorting broken

### ISSUE THREAD

**Issue by PolarizedIons** [thelounge/lounge#1088]
Running on master (dd5e50f).

As you can see the order is messed up when syncing to other clients, but the strange order also persists when refreshing. (Also note how the network lobby isn't where it should be)

https://gfycat.com/TalkativeKindlyAlbino

**Comment by YaManicKill** [comment]
Assuming this is due to #1064

**Comment by YaManicKill** [comment]
Interestingly I'm not able to fix it. Have you ensured you did an npm run build, @PolarizedIons ?

**Comment by PolarizedIons** [comment]
Yep I did, @YaManicKill. Recloned to be sure and still an issue.

**Comment by astorije** [comment]
Pinging @xPaw about this.

**Comment by bews** [comment]
I don't have this problem. @PolarizedIons are you sure it's not a local change? Also, what browser do you use?

**Comment by PolarizedIons** [comment]
@bews Chromium Version 58.0.3029.81 (64-bit) on Arch Linux, but the fact that it persisted after a refresh (and diffrent in fact) leads me to believe it isn't a browser issue. No local changes - I did a fresh reclone to test that

**Comment by williamboman** [comment]
FWIW, I can repro in Safari and Chromium

**Comment by xPaw** [comment]
Probably #1064 broke it, unsure why though.

**Comment by PolarizedIons** [comment]
Just adding more info to this: it doesn't seem to happen when you "manually" join networks/channels. I connect though ZNC so it could be caused by that, or the amount of channels/queries it opens

**Comment by xPaw** [comment]
I can't reproduce this. I also connect to ZNC.

**Comment by PolarizedIons** [comment]
Fixed in #1115. I think the ZNC thing was just a red herring
