### ISSUE TITLE
Userbar causing spacing/width issues

### ISSUE THREAD

**Issue by PolarizedIons** [thelounge/lounge#1092]
The userbar automatically hides or shows under circumstances, but the width of the chat/channel doesn't change correctly leading the stuff like this:

https://gfycat.com/ThreadbareHappyHectorsdolphin
https://i.imgur.com/v7C7vvv.png

This is on master (06af65c)

**Comment by xPaw** [comment]
Yeah, this is responsive bullshit. However, has this been recently broken in such a way, or always has been?

**Comment by MaxLeiter** [comment]
cant recreate on [5281411](https://github.com/thelounge/lounge/tree/5281411)

**Comment by xPaw** [comment]
Can you bisect it?

**Comment by PolarizedIons** [comment]
bisecting pointed to c583d6e

**Comment by xPaw** [comment]
I can't reproduce this. Could you figure out what CSS is doing this effect in dev tools?
