### ISSUE TITLE
Bug: after closing private chat lobby becomes an active window

### ISSUE THREAD

**Issue by bews** [thelounge/lounge#1099]
Expected: switch back to the previous window (Shout behavior).

**Comment by astorije** [comment]
Yeah, we had numerous discussions about this.

The history behind this is this behavior was lost when working on a better client layout. It was introduced as a bug in https://github.com/thelounge/lounge/pull/465 and then fixed (to the current solution) in https://github.com/thelounge/lounge/pull/489.

We attempted to bring back Shout's behavior you mentioned in https://github.com/thelounge/lounge/pull/503, but first we did not agree on this, but also there was a bug when browsing on channels across networks.
The conclusion of this was to defer this to the future "Home tab" described in https://github.com/thelounge/lounge/issues/791 and therefore the current behavior was and will be kept as such until then.

Anyway, a classic and infamous "it's not a bug, it's a feature" 😅
