### ISSUE TITLE
Move clickable channel parser to "parse" handlebars helper

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#11]
This code: https://github.com/thelounge/lounge/blob/f87d605b53332a3478eed8efaa676337971c510f/client/js/lounge.js#L228-L247

That `click` event needs to be bound globally instead of binding it for every message.

**Comment by astorije** [comment]
What consequences does changing this or having what we have at the moment imply?

**Comment by xPaw** [comment]
This would increase consistency, as all message transformation stuff would be in a single place.

**Comment by astorije** [comment]
Ok then :-) :+1:
