### ISSUE TITLE
Scroll Back Memory Consumption

### ISSUE THREAD

**Issue by vectr0n** [thelounge/lounge#110]
Over the last day or two I have noticed TheLounge server consuming a large amount of memory. After inquiring on IRC it was as I suspected the scroll back is loaded into memory. I currently have 5 networks connected with probably close to a 100 fairly busy channels in total, TheLounge server is now eating more memory then my heavily used MariaDB server. Would be nice to have an option in the server config to set the amount of scroll back to keep in memory before say dumping to disk to be retrieved using "Show More".

**Comment by lindskogen** [comment]
Generally, the current structure of keeping all information in memory is pretty bad. One solution for this is to implement a sqlite backend and persist everything there, which would also have the added benefit of keeping data between restarts of the lounge server

**Comment by dgw** [comment]
:+1: for gaining memory efficiency and persistence in one go.

**Comment by Dr-Horv** [comment]
@lindskogen You've done some work on this right? How far along are you?

**Comment by dbkaplun** [comment]
I for one would love to see some progress on this. This is the biggest reason I switched from shout back to weechat.

**Comment by xPaw** [comment]
You can use the [`maxHistory`](https://github.com/thelounge/lounge/pull/243) option to help with this.
