### ISSUE TITLE
Time and nickname on one line, text on next line

### ISSUE THREAD

**Issue by christer88** [thelounge/lounge#1111]
![screenshot_2017-04-29-01-11-47](https://cloud.githubusercontent.com/assets/11909212/25550511/f1247aae-2c79-11e7-9999-ed03e97d5367.png) ![irccloud_mobile](https://cloud.githubusercontent.com/assets/11909212/25550467/8914e552-2c79-11e7-8949-9266e4109f13.png)

Having time, nickname and text on the same line makes it messy and harder to read on phones and other small screens. Nicknames have different lenghts and the text starts at different places.

I suggest: Time and nickname on one line, and text on next line (as seen on the above screenshot with another client).

**Comment by bews** [comment]
It's looks good only when users send few messages one of after another, which happens rare (at least in the channels I use). Take a look at your left sreen: short messages (the most common ones) take only 1 line. After this change left screen height will be increased by 3 lines, which is bad IMO.

If someone want to implement this, please make it as an option.

**Comment by dgw** [comment]
To me, this looks like something best left to themes. Whether any of the default themes do it is up to maintainers, but I don't think either way of displaying messages is going to fit everyone's preferences/devices/usage.

**Comment by MaxLeiter** [comment]
I think this can be closed; I think @thelounge/maintainers agree this should be left to themes

**Comment by YaManicKill** [comment]
Agreed. Thanks, @MaxLeiter 

This would be a good addition to a theme, and now that 2.5.0 (which will be released soon) has npm theme support, this'll be much better.

**Comment by astorije** [comment]
For this to be ideal, we'd need help revamping #815 (`help wanted` / `up for grabs` 😁).
