### ISSUE TITLE
JS exception when typing for a private message

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#1119]
To reproduce:

- Open your browser JS console
- Open a private message window (`/whois` or click, didn't try other methods)
- Start typing and enjoy the following in your console:
  <img width="449" alt="screen shot 2017-04-30 at 04 23 16" src="https://cloud.githubusercontent.com/assets/113730/25560760/dfb12496-2d5c-11e7-924f-87f82d1fb3ad.png">

**Comment by xPaw** [comment]
Check if #1095 fixes this.

**Comment by astorije** [comment]
Good try, but I just tested with #1095 and bug still exists :(

**Comment by astorije** [comment]
I confirm your changes in #1095 fix this issue! 🎉
