### ISSUE TITLE
Combine @-less nick completion with new autocompletion dropdown

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#1126]
Right now, typing `@` opens the nick autocompletion dropdown while typing a set of character + hitting <kbd>Tab</kbd> completes like it used to.

When hitting a set of characters then <kbd>Tab</kbd>, the nick autocompletion dropdown should open with that set of characters as the `term` in completion strategy.

Essentially, typing `xyz` then hitting <kbd>Tab</kbd> should open a completion dropdown with the exact same suggestions than typing `@xyz`.

Thoughts?

**Comment by xPaw** [comment]
This will make the UX worse. Pretty much every app completes the suggestion when hitting the tab key.

**Comment by astorije** [comment]
True, I was thinking about that when opening that issue. Playing a bit with Slack's completion, this is the closest of what should be the ideal UX:

- completion dropdown opens when typing `@`
- fuzzy-matching when typing something after `@`
- completion dropdown opens when typing a few chars + hitting <kbd>Tab</kbd>, and the first value of the dropdown gets used to complete the characters, essentially doing what you described.

Problem is this is going to be difficult with our current mechanism since the list of suggestions only depends on what's in the `input`, while doing the above requires keeping track of what characters were typed on top of what's displayed.
It's likely I'm not making any sense, in which case it's easier to play with Slack directly :D

Either way, dropdown should show up when hitting <kbd>Tab</kbd> for consistency (but also completing like @xPaw mentioned). It's likely tweaks will be needed to get the perfect UX.
