### ISSUE TITLE
Update handlebars

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#113]
This requires updating both the server and the client libraries.

**Comment by astorije** [comment]
:+1:

**Comment by MaxLeiter** [comment]
Blocked by #62?

**Comment by xPaw** [comment]
Don't think so, there were already 2 different PRs that removed a couple of libraries.

**Comment by astorije** [comment]
@xPaw, do you think you could take this one up? It would be very valuable regardless on any soon progress of #62, and it would be really really great to not have that `insecure` badge showing up on the README page (I believe we are not affected by the warning, but it doesn't hurt to make sure of it)...
Thanks! :-)

**Comment by xPaw** [comment]
I looked over the changelog, seems pretty straight forward upgrade.

However there are things like `Escape = in HTML content`, which might break our inline URL parser. Other than that, we should be good to go.
