### ISSUE TITLE
Show notices inline

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#114]
I'm not sure if this is part of the IRC spec, but most clients generally show notices in-line (ie like a message). At the moment, they're displayed in the network tab which isn't very intuitive.

Alternatively, notices could be displayed in a modal/popup similar to IRCcloud

**Comment by dgw** [comment]
:+1: to displaying in current channel (most clients make this a setting, but I get that this project is trying to avoid having too many preferences)

Strong :-1: on a modal/popup approach. A number of games and so on use notices to send various info to players and it would get annoying or even disruptive very quickly.

**Comment by dgw** [comment]
Noticed (ha!) tonight that if a query window is open with the user who sent the NOTICE, it goes there and generates the same type of notification it would if it had been a PRIVMSG.

That's probably not what it should do, at all, but perhaps that should be a separate issue?

**Comment by JustRamon** [comment]
+1

**Comment by dgw** [comment]
Came up while talking about `/whois` in another issue, but very relevant here as multiple/no connected clients haven't even been discussed yet.

If no client is attached, notices can go to the server window. If multiple clients are attached, is it impractical for each client to decide where to place the incoming notice depending on which window is active?

**Comment by dgw** [comment]
Is this settled in an upcoming release? Or is it "WONTFIX"?

**Comment by christer88** [comment]
I would like this issue to be reopen.

There are situations where in-line notices will be extremly helpful and in some situations critical, e.g. Uno game where the bot let you see your cards trough notices. Notices are also used to show information to users on channel join, e.g. #help channel to let them know what to do. Majority of people, especially kids, doesn't know or doesn't see the notices in server window.

I suggest either trying to find a way to display in-line notices on every active channel window OR display them in all channels at once.

**Comment by christer88** [comment]
![uno](https://cloud.githubusercontent.com/assets/11909212/25343937/d6b9e1c0-2910-11e7-9a84-7e8e54aa3716.png)

**Comment by YaManicKill** [comment]
So, I have a big issue with notices in general. If we look at the spec:

> The NOTICE message is used similarly to PRIVMSG.  The difference between NOTICE and PRIVMSG is that automatic replies must never be sent in response to a NOTICE message.  This rule applies to servers too - they must not send any error reply back to the client on receipt of a notice.  The object of this rule is to avoid loops between a client automatically sending something in response to something it received.  This is typically used by automatons (clients with either an AI or other interactive program controlling their actions) which are always seen to be replying lest they end up in a loop with another automaton.

So I feel that clients that show it in the current channel (or every channel) are misusing it. Realistically, if we are changing how notices should be done, they should be done in a separate channel like PMs currently work. I have a feeling people won't want to do that.

Posting them in every channel just sounds horrible. Showing them in the active channel window? Maybe, but I still think we are misusing them.

**Comment by christer88** [comment]
Misusing, maybe. But it's still quite a few IRC games and channels showing information directly to their users trough notices. If they are ever going to be read and used how IRC games want them to, we need them to be in the appropriate channel.

**Comment by xPaw** [comment]
I was thinking to show notices on the client in currently active channel. On the server they would be kept in network window.

**Comment by Raqbit** [comment]
I'm all in for the active channel option!

**Comment by dgw** [comment]
Sounds good, @xPaw. Notices don't _need_ to persist in the active channel if The Lounge client is closed and reopened. Letting each client handle where to show them, but having the server keep them in a specific buffer, should work out.

**Comment by astorije** [comment]
Do they need to be dismissible (like with a <kbd>&times;</kbd> button or something like that) when duplicated in active channel?
Regarding all channels, if it's dismissible, then I guess it could make sense... or not...
It's a tough UX decision because there is no clear winner, and it's a thing that depends on the use case, and gets used for multiple use cases, including some that are abusing the function.

If there are multiple ideas, I suggest we go with the "smallest" one (for example current channel only), then give it a try, and releases later introduce something else if needed (dismissible? all channels? both? else?).
Either way, I don't think I like any solutions, but I understand the mentioned use cases. (And it's not something another option will solve lol.) I won't be blocking anything, just wanted to share I find none of these ideal but I have no alternatives either....

**Comment by christer88** [comment]
Showing notices in-line in active window on client sounds good!

**Comment by YaManicKill** [comment]
Ok, @thelounge/maintainers, let's get a decision on how we want to fix this, so someone can come along and do it if they want.

Are we happy with just showing the notice in the current active window?
