### ISSUE TITLE
Autocomplete really should be mentioned in the help section

### ISSUE THREAD

**Issue by Cldfire** [thelounge/lounge#1147]
I've used lounge for a year now and did not realize that 2.3.0 introduced @ nick auto-completion until @MaxLeiter told me in IRC. In fact, the only auto-completion strategy I discovered on my own without expending effort digging up the autocomplete PR was the emoji auto complete (triggered via `:`). If it weren't for my use of other non-IRC-related chat programs, I wouldn't have known about that, either. I can easily see someone who uses IRC exclusively only figuring out that such an auto-completion exists after a chance typing of `:`.

Despite the fact that a PR was just merged to remove autocomplete from the help section, I am filing this issue. It feels extremely odd to assume that users will discover these things on their own; it's certainly not hurting anyone to dedicate a small paragraph to it in the help section. If I tell a new lounge user to check out the help page, it is only logical to want them to discover auto-completion options on their own when reading it, rather than having to manually add "oh, and don't forget about autocomplete..."

**Comment by YaManicKill** [comment]
I agree, actually. I have read the rational from @astorije in #1125 but I think that we should bring it back.

I accept that autocomplete should be intuitive, but I see no reason why we can't still have this documented in the help page. Plenty of people won't find ":", and it's not that uncommon for people not to automatically "@" a user. So, I say we bring it back. @astorije do you have any strong objections to this?

**Comment by PolarizedIons** [comment]
I agree with this. Especially after #1356, the discovering of `:` for emoji completion is much harder.

**Comment by astorije** [comment]
> @astorije do you have any strong objections to this?

Nah that's totally fair.
Put back in context, when this was removed, we didn't have color completion, and I thought the help was too blunt to be really helpful.

But I'm cool with an improved version that @dgw is working on (thanks!). It makes sense, and clearly there is a need for it considering the number of 👍 (@xPaw and I agreeing to remove it was probably experience bias 😅).
