### ISSUE TITLE
Show connection attempt status messages in network buffer

### ISSUE THREAD

**Issue by easymac** [thelounge/lounge#115]
While a network connection is brokered, no messages appear in the network buffer until the connection is successful. We should see a `Connecting to [host or name]` message when a connection is started instead of a blank screen.

Error messages should also be piped there. Currently, connections that time out leave the network buffer entirely blank while emitting the following message on the server

```
Client#connect():
Error: connect ETIMEDOUT
```

In the event that auto-reconnect or auto-retry connections come to exist, I would also like to see `Connection [lost or failed], retrying . . .` messages.

**Comment by xPaw** [comment]
One of the things required for this to work correctly, is to move this code all the way up in the function: https://github.com/thelounge/lounge/blob/master/src/client.js#L213-L216

Then we will be able to send messages to network tab with what's happening.

**Comment by astorije** [comment]
This issue seems to be fixed by #167.
