### ISSUE TITLE
Join and MOTD are always set to off on refresh

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#1152]
Pretty sure this exists in master as I just switched back to see.

If you load the page, joins and MOTD in the settings are switched off. Switch them back on, reload the page, and they will be set to off again. It seems to only be joins and MOTD, all the others work as expected.

I did a bit of debugging, and it appears that they are saved correctly into localstorage, and then we get the information out of localstorage correctly, set it all up fine. But after we have checked the box, something unchecks it for both of them.

**Comment by bews** [comment]
I don't have this bug on master.

**Comment by astorije** [comment]
That's very odd, I cannot reproduce this on `v2.3.0-rc.1` either (which is currently `master` with precompiled JS bundle). @YaManicKill, are you able to reproduce this on a different browser / private browsing / ... laptop?

**Comment by astorije** [comment]
On the other hand, this issue made me figure out #1157, so thanks for opening it 😅.

**Comment by YaManicKill** [comment]
Hmmm, yeah, this isn't happening on edge. I'm not sure if it's a cache thing, but I tried in a private window, and it happened, but then I tried on chrome just now again and it is now not happening. It's probably something weird on my Chrome. Closing.

**Comment by YaManicKill** [comment]
Incase anyone else happens to have this issue, it appears to be a lastpass issue. I disabled lastpass on the page for that and I'm not having the issue anymore.
