### ISSUE TITLE
Focus a channel by joining it

### ISSUE THREAD

**Issue by realies** [thelounge/lounge#1155]
Using the client with lots of servers and channels might be confusing at times, especially when there's no sorting capabilities. Sometimes I try to join a channel that I'm already part of and nothing happens, then I usually do CTRL+F and find it in the list, select it, etc. It would make sense if the channel goes into focus when joining no matter your presence in it. Looking into the code this seems possible by adding the following code after [this line](https://github.com/thelounge/lounge/blob/master/client/js/lounge.js#L829).

```
if (text.substring(0, 5) === "/join") {
	var cmd = text.trim();

	if (cmd !== "/join") {
		var name = cmd.split(" ").pop();
		var chan = findCurrentNetworkChan(name);

		if (chan.length) {
			chan.click();
			return;
		}
	}
}
```

**Comment by astorije** [comment]
The rationale seems reasonable. If `/join #newchannel` joins + opens, `/join #joinedchannel` should indeed open, for consistency.
I haven't thought through your example though. I'm thinking @xPaw would know the edge cases for this. Would you be OK opening a PR for this afterwards, @realies?

**Comment by realies** [comment]
Thank should be fine @astorije. I would be happy if someone can review the suggested change, there is a trim and if preventing `findCurrentNetworkChan` from being calling if a user types `/join` without a channel.

**Comment by astorije** [comment]
In terms of implementation, I think it would be better for consistency sake to emit this to the server, and the server itself would take care of ignoring the actual `/join` and simply emit an `open` event.

Not sure though, I'm all ears for a better approach.

**Comment by realies** [comment]
From efficiency prespective, the server shouldn't care that the user is trying to effectively change the active channel.

**Comment by astorije** [comment]
Actually, it should, as this impacts the unread notifications. That's why my approach seems to be the easiest to implement and maintain.

**Comment by realies** [comment]
Good point, it will end up signaling the server anyways. I will look into other ways of implementing it in the next few days.

**Comment by astorije** [comment]
Note that `chan.click();` will go to the server anyway, so I'd rather have something consistent with `/join`ing a new channel, unless I'm missing something (@xPaw?)

**Comment by YaManicKill** [comment]
Bear in mind that chan.click() will do everything we need for dealing with unread notifications. And although it goes to the server anyway, it will do 1 less. If we emit join to the server, and then we change channel, surely that's 1 more call to the server than we need.
