### ISSUE TITLE
Autoreconnect bug

### ISSUE THREAD

**Issue by bews** [thelounge/lounge#1168]
It doesn't work. Again.

![2017-05-14_04-44-23](https://cloud.githubusercontent.com/assets/3627488/26030583/26dd3d10-3860-11e7-91b2-97abbb6608f5.png)

**Comment by dgw** [comment]
Related to (but different from) #917?

**Comment by bews** [comment]
It works at first disconnect, but fails on second.

**Comment by bews** [comment]
So, problem is in `irc-framework`, line `this.socket.end();`
I'll make a PR later, after some tests.

**Comment by YaManicKill** [comment]
Alright, if it's an issue with irc-framework, I'll close this. We'll pull in the changes whenever irc-fw releases.

**Comment by MaxLeiter** [comment]
@bews could you make an irc-fw issue?

**Comment by bews** [comment]
https://github.com/kiwiirc/irc-framework/issues/96
