### ISSUE TITLE
Lounge crashes when there more than one IP in X-Forwarded-For header

### ISSUE THREAD

**Issue by bews** [thelounge/lounge#1169]
Lounge crashes when there more than one IP in X-Forwarded-For header if `reverseProxy = true`. 

Fix: `ip = req.headers["x-forwarded-for"].split(",")[0] || req.connection.remoteAddress;`

Also there should be more checks for this header, regex maybe?

**Comment by TuSuNaMi** [comment]
Any solutions?

**Comment by YaManicKill** [comment]
The fix that @bews suggested seems like the sensible one.

Regex could be as simple as https://regex101.com/r/vDPHb3/1 but that wouldn't cover ipv6 either. So we'd need something a little more complicated.

I think that the better solution is just to let the user put whatever they want in, put your fix in, and leave it at that. If a client is sending weird malformed headers, we are going to come across issues somewhere, so I feel like we just want to leave that hornets nest alone.

If someone starts working on this, mention it here so we don't have duplicated work.

**Comment by TuSuNaMi** [comment]
If client comes with IP address, lounge will crashing.
If come the forwarded cname there is no problem with @bews fix.

But if the search engine or some IP with no have the reverse dns. Lounge will crash again I seem ...

**Comment by bews** [comment]
>  If a client is sending weird malformed headers, we are going to come across issues somewhere, so I feel like we just want to leave that hornets nest alone.

:confused: I still think there should be a proper check for this, otherwise anyone could crash your instance (which is a **big** issue for public ones). This header is accessed only in `getClientIp(req)` function, so checking there should be enough.

The proper fix is simple: check it with regexp (https://stackoverflow.com/questions/9208814/validate-ipv4-ipv6-and-hostname for example), and if it fails, replace with `127.0.0.1`. Smth like that :smiley:

**Comment by YaManicKill** [comment]
> otherwise anyone could crash your instance 

Oh yeah, I guess I didn't think about that. Good plan.

That regex looks horrible, but it needs to be complicated to actually work. I wonder if there's a module for common complicated regex like this.
