### ISSUE TITLE
Latest Lounge Won't Run

### ISSUE THREAD

**Issue by spencerthayer** [thelounge/lounge#1171]
$ npm start

> thelounge@2.3.0-rc.1 start /PATH/www/MST3K/irc.mst3k.tv
> node index start

2017-05-15 04:44:34 [INFO] The Lounge v2.3.0-rc.1 (node 7.10.0 on darwin x64)
2017-05-15 04:44:34 [INFO] Configuration file: /PATH/.lounge/config.js
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1243:19)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at module.exports (/PATH/www/MST3K/irc.mst3k.tv/src/server.js:77:9)
    at Command.<anonymous> (/PATH/www/MST3K/irc.mst3k.tv/src/command-line/start.js:39:3)
    at Command.listener (/PATH/www/MST3K/irc.mst3k.tv/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:194:7)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! thelounge@2.3.0-rc.1 start: `node index start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thelounge@2.3.0-rc.1 start script 'node index start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thelounge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thelounge
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thelounge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /PATH/.npm/_logs/2017-05-15T04_44_34_823Z-debug.log

From the debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle thelounge@2.3.0-rc.1~prestart: thelounge@2.3.0-rc.1
6 silly lifecycle thelounge@2.3.0-rc.1~prestart: no script for prestart, continuing
7 info lifecycle thelounge@2.3.0-rc.1~start: thelounge@2.3.0-rc.1
8 verbose lifecycle thelounge@2.3.0-rc.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle thelounge@2.3.0-rc.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Use$
10 verbose lifecycle thelounge@2.3.0-rc.1~start: CWD: /PATH/www/MST3K/irc.mst3k.tv
11 silly lifecycle thelounge@2.3.0-rc.1~start: Args: [ '-c', 'node index start' ]
12 silly lifecycle thelounge@2.3.0-rc.1~start: Returned: code: 1  signal: null
13 info lifecycle thelounge@2.3.0-rc.1~start: Failed to exec start script
14 verbose stack Error: thelounge@2.3.0-rc.1 start: `node index start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:27$
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid thelounge@2.3.0-rc.1
16 verbose cwd /PATH/www/MST3K/irc.mst3k.tv
17 error Darwin 16.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error thelounge@2.3.0-rc.1 start: `node index start`
23 error Exit status 1
24 error Failed at the thelounge@2.3.0-rc.1 start script 'node index start'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the thelounge package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node index start
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs thelounge
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls thelounge
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by astorije** [comment]
It looks to me that you are starting on port `80`, which is a system port. Are you running `npm start` as root?

**Comment by spencerthayer** [comment]
Yeah as root.

**Comment by astorije** [comment]
It does seem like there is something already listening on port 80. Could you try with another version just to rule out this depending

**Comment by spencerthayer** [comment]
Do you have a suggested build I should try? I have been running 2.0.0-pre.6 without any problems.

**Comment by astorije** [comment]
Just 2.2.2

**Comment by astorije** [comment]
@spencerthayer, could you fix this? I believe this has to do with your setup and not with The Lounge itself. @xPaw, do you agree? Are you seeing something on the output @spencerthayer pasted above that I'm not seeing?

**Comment by astorije** [comment]
@spencerthayer, I'm closing this now, assuming you got this to work. Feel free to re-open with details if it happens again with newly released v2.3.0.

**Comment by spencerthayer** [comment]
Nah. It never worked. I just gave up. I'm waiting to try the next version.

**Comment by xPaw** [comment]
@spencerthayer The crash you're seeing `EACCES 0.0.0.0:80` means node has no permission to bind on port 80. Try changing port to something higher than 1024. Are you completely sure that v2.0.0-pre.6 works in same environment but not later version?
