### ISSUE TITLE
Channels with "##" create invalid css class names

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#1172]
The channels come with `chan-channame` class on them, but it seems to be done by just stripping off the first `#`. If a name is `##channame` you will end up with `chan-#channame` which can't be used in css at all.

This is probably a bigger issue than just that, as there aren't really any restrictions on what can go in a chan name (see [spec](https://tools.ietf.org/html/rfc1459#section-1.3)) but a css selector can only have alphanumeric chars and `-` and `_`, so we need to look into making channel (and, I guess, network) names safe for css selectors.

Sadly, it's not just as simple as url encoding, as that allows more characters, and with my very quick search I couldn't find an equivelant for css selectors.

**Comment by Bonuspunkt** [comment]
https://mathiasbynens.be/notes/css-escapes and https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape
``` js
CSS.escape('#myChannel') 
// "chan-\#channame"
```

**Comment by xPaw** [comment]
We can polyfill `CSS.escape` but that alone might not be alone, as it seems that `\` is not being escaped by that function. Any other ideas?
