### ISSUE TITLE
Link prefetch 404 will still get pushed to the client

### ISSUE THREAD

**Issue by Raqbit** [thelounge/lounge#1180]
When someone posts a link with prefetch enabled, thelounge will copy the page's og:image meta tag url to get a thumbnail to show with the link description.
[Where this is done](https://github.com/thelounge/lounge/blob/master/src/plugins/irc-events/link.js#L58)
Normally this works fine, and thelounge will check the image size and everything.

But, if there's an issue with that url (it's relative to the site, or isn't there at all), which would 404 when fetched, thelounge still pushes the url to the client, which will 404.

The way @PolarizedIons and me found out about this is because we share an instance, and he kept getting 404's, which got him banned using fail2ban. Looking at some nginx logs (I'm using a nginx reverse proxy), we were able to find the source of this 404: His client was trying to load an image from my server, related to github. After some more investigation we found out that anonymous github gists have an og:image meta tag with a relative url. (which as a sidenote, will still 404 when used relative to the gist url)

A suggested fix would be to check if the image url 404s before pushing it to the client.

Many thanks to @PolarizedIons for finding the core cause of this issue!

**Comment by slurdge** [comment]
It also seems that if there is an error downloading, the res will be empty, causing all sort of troubles [here](
https://github.com/thelounge/lounge/blob/master/src/plugins/irc-events/link.js#L48)
However I don't see the error happing when I paste an invalid link inside lounge. So maybe the catch [here](https://github.com/thelounge/lounge/blob/master/src/plugins/irc-events/link.js#L92) isn't useful.

**Comment by xPaw** [comment]
This would be fixed by using an embed library, like I did here: https://github.com/thelounge/lounge/compare/xpaw/embed

**Comment by PolarizedIons** [comment]
Just leaving this here: we've found this is a problem with anonymous gist urls, for example this one:
https://gist.github.com/anonymous/3fb15454ab7fe7616d2cf3ab7788db80
