### ISSUE TITLE
User list search resets when a client joins

### ISSUE THREAD

**Issue by vectr0n** [thelounge/lounge#1187]
I was searching for users in the nick list in a large freenode channel when I noticed the search gets wiped out whenever someone joins the channel. I would assume this is due to the nick list being updated, but not sure if this was the intended behavior or a small bug.

`$ lounge --version
v2.2.2`
`$ node --version
v7.10.0`
`$ npm --version
4.5.0
`

**Comment by xPaw** [comment]
This is fixed in 2.3.

**Comment by vectr0n** [comment]
Ok thanks
