### ISSUE TITLE
webrtc question

### ISSUE THREAD

**Issue by wokawoka** [thelounge/lounge#1203]
I can imagine that, being an IRC client, the lounge is not focused in implementing a mic/webcam function through webrtc, but I was just wondering if maybe this has at least discussed in the past. 
If not, will the lounge one day be able to have some extra functions added trough plug-ins?

**Comment by DanielOaks** [comment]
On a side note we've been investigating it in IRCv3 for a while, but afaik nobody's come up with something that works yet. There is this related thread by someone who was looking into it as well: https://groups.google.com/forum/#!topic/mozilla.dev.chat/2lP0WZiflQI

**Comment by YaManicKill** [comment]
If this were to ever be added to IRCv3, then we would add it to our roadmap (when we would get to it would be a different question). Until that happens, I think it's safe to say this will never be part of core. However, we (here we go) are working on a plugins system, and there would be nothing to stop someone making a plugin to have it work.

**Comment by cirinho** [comment]
kiwiirc has a plugin, but I couldn't put it to work
