### ISSUE TITLE
Channel join error info doesn't mention channel name

### ISSUE THREAD

**Issue by bews** [thelounge/lounge#1207]
`Cannot join channel (+l) (channel_is_full)` - which channel? No idea, when this happens on reconnection.

**Comment by YaManicKill** [comment]
Good catch, we probably just aren't sending the info to client and printing it. Shouldn't be too hard a fix, just need to find where it is.

**Comment by infinityl00p** [comment]
Hey, i'm a beginner and this would be my second contribution. I'd love to take on this issue but would probably require some guidance. Cheers @bews  @YaManicKill

**Comment by astorije** [comment]
[This](https://github.com/kiwiirc/irc-framework/blob/b54df53d4a7fcb357ad5af579e0a01410bfad89b/src/commands/handlers/generics.js#L73-L78) is where the info gets constructed. You probably want to intercept what gets sent from `irc-framework` and inspect the data that's coming back to see what's available. Does that make sense?

**Comment by infinityl00p** [comment]
@astorije yes thanks! will comment back or join the irc for future questions.

**Comment by infinityl00p** [comment]
@astorije how can i reproduce this error?

**Comment by astorije** [comment]
I'm not sure, I have never hit this. @bews, could you advise?

**Comment by bews** [comment]
@infinityl00p join new channel, set mode `+l 1`, start Lounge and try to join that channel. 

Also you can ban youself and then try to join that channel - `Cannot join channel (You're banned) (banned_from_channel)` will be triggered, which has this problem too.

**Comment by MaxLeiter** [comment]
iirc, `irc-framework` doesn't pass any more data than the message/exception when an error like these occurs. Means we either need to PR irc-fw or just record this from the channel in the command. (there's probably more/better ways to go about it)
