### ISSUE TITLE
Ability to view raw messages in client

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#1218]
Would be helpful for debugging to be able to see the raw message. No clue how this should/could be implemented

**Comment by YaManicKill** [comment]
I thought we had a PR to add raw message dub logging somewhere? Did that disappear? I'm assuming just logging would be helpful enough? No need to add it to the UI?

**Comment by xPaw** [comment]
@YaManicKill Enabling `debug.raw` option will dump raw messages to lobbies.

**Comment by astorije** [comment]
> Enabling `debug.raw` option will dump raw messages to lobbies.

And I would say that's more than enough, no?

**Comment by xPaw** [comment]
It is in my opinion.

**Comment by YaManicKill** [comment]
Ah right, that sounds like it should be good. Closing in that case. @MaxLeiter feel free to re-open if we have misunderstood, or there is something else you want.

**Comment by MaxLeiter** [comment]
Well you need to either enable them for all users or for no users - a client side option would be helpful

**Comment by YaManicKill** [comment]
Ah right, I see. That doesn't sound ideal, but afaics, the way it currently works wouldn't work for a single user and we'd need a completely new way to do it?
