### ISSUE TITLE
Undernet - issue with /connect on server-join every time

### ISSUE THREAD

**Issue by christer88** [thelounge/lounge#1223]
Network created, connecting to ix.undernet.org:6667...
Disconnected from the network, and will not reconnect. Use /connect to reconnect again"

This happens every single time I connect to Undernet. It does not happen to any of the other five IRC networks I'm connected to, e.g. FreeNode, Undernet, EFnet,PrivNET, EsperNet etc. When this happen I have to do /connect and it connects to the network as it should have the first time.

Has this something to do with Undernet require identd? which I have turned on in TheLounge config file and is working.

**Comment by starquake** [comment]
Does this happen when you reboot the server and the service is started? Or does it happen everytime? Asking because I had that problem.

**Comment by christer88** [comment]
Happens every single time, also after I have restarted TheLounge.
