### ISSUE TITLE
Show the entire topic in channels

### ISSUE THREAD

**Issue by christer88** [thelounge/lounge#1225]
![capture](https://user-images.githubusercontent.com/11909212/27060115-e6eb98a4-4fda-11e7-8270-ffdd2c9693d0.PNG)

Sometimes the topics in channels are too long to show as one line. This is especially an issue on phones and other small screens. Currently I see no way of being able to show the whole topic.

On IRCCloud you can click on the topic to see the topic (and modes for the channel). Would this be possible to implement?

![screenshot_2017-06-13-01-55-36](https://user-images.githubusercontent.com/11909212/27060261-e5ece894-4fdb-11e7-92e5-5211b0bf05a1.png)

**Comment by YaManicKill** [comment]
Just marking this as duplicate of #276
