### ISSUE TITLE
Evolution of The Lounge (Gource Visualization)

### ISSUE THREAD

**Issue by modInfo** [thelounge/lounge#1234]
VIDEO: https://youtu.be/9mFwjLWlcwA

This visualization was generated with the following command:

	gource \ 
	--path path/to/repo \
	--seconds-per-day 0.15 \
	--title "dirsearch" \
	-1280x720 \
	--file-idle-time 0 \
	--auto-skip-seconds 0.75 \
	--multi-sampling \
	--stop-at-end \
	--highlight-users \
	--hide filenames,mouse,progress \
	--max-files 0 \
	--background-colour 000000 \
	--disable-bloom \
	--font-size 24 \
	--output-ppm-stream - \
	--output-framerate 30 \
	-o - \
	| ffmpeg \
	-y \
	-r 60 \
	-f image2pipe \
	-vcodec ppm \
	-i - \
	-vcodec libx264 \
	-preset ultrafast \
	-pix_fmt yuv420p \
	-crf 1 \
	-threads 0 \
	-bf 0 \
	path/to/output.mp4

Installation (Arch Linux):
pacman -S gource ffmpeg

More information:
http://gource.io/
https://github.com/acaudwell/Gource

**Comment by dgw** [comment]
This was filed as an issue, why?
