### ISSUE TITLE
Server crashes when reloading the page on a public instance

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#124]
Not sure exactly what triggers this nor how to reproduce 100% of the time, but I got this error when doing the following:

- Run server, public instanec
- Access it on localhost
- Connect to Freenode and another IRC network
- Freenode is broken, got no channels open nor connection with it
- Reload the page
- Boom, error

The stack trace:

```
> node index "--port" "9001" "--home" "/tmp"


The Lounge is now running on http://0.0.0.0:9001/
Press ctrl-c to stop

Client#connect():
Error: connect ETIMEDOUT 185.30.166.38:6697
.../lounge/src/client.js:337
	var room = sockets.adapter.rooms[this.id] || [];
	                          ^

TypeError: Cannot read property 'rooms' of undefined
    at Client.quit (.../lounge/src/client.js:337:28)
    at Socket.<anonymous> (.../lounge/src/server.js:189:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.emit (.../lounge/node_modules/socket.io/lib/socket.js:129:10)
    at Socket.onclose (.../lounge/node_modules/socket.io/lib/socket.js:398:8)
    at Client.onclose (.../lounge/node_modules/socket.io/lib/client.js:204:12)
    at emitTwo (events.js:92:20)
    at Socket.emit (events.js:172:7)
    at Socket.onClose (.../lounge/node_modules/socket.io/node_modules/engine.io/lib/socket.js:240:10)
```

Let me know what additional info I can bring and I'll try to find that.

**Comment by astorije** [comment]
Actually, no need to do all that, just run it from master, access it on localhost (public instance) and refresh the page whenever you want.

**Comment by astorije** [comment]
@xPaw confirmed this bug, so let's not make a release until this gets fixed.

As a matter of fact, I am willing to re-purpose the `priority` badge and make it a sensible requirement for releases: can't release as long as there is a `priority` ticket (issue or PR) is open. At the moment the label is very opinion-based, everyone having preferences of things to be worked on. By re-purposing this, we make it so that important issue do get in the way of releasing and make it clear for everyone. Of course, I'll document that in the releasing process. That way, maintainers can mark a bug and make sure it doesn't get shipped by accident. Are @thelounge/maintainers OK with this? :-)

**Comment by YaManicKill** [comment]
> As a matter of fact, I am willing to re-purpose the priority badge and make it a sensible requirement for releases: can't release as long as there is a priority ticket (issue or PR) is open.

Happy with this, but not sure "priority" is the right word for it. "Blocker" or "release-critical" or something like that would probably be better.
