### ISSUE TITLE
Change the application base url

### ISSUE THREAD

**Issue by peperunas** [thelounge/lounge#1243]
It would be great to add a configuration option to run thelounge under a path. As for version 2.3.1 this is not possible to do. This would be possible if there was a `BASE_URL` or `WEBROOT` rule or something like that.

For now, the webroot is set to `/` and it can't be changed.

**Comment by YaManicKill** [comment]
So, the easiest way to do this is by proxying with apache or nginx or something. That's how we recommend people do this (and run the lounge in general).

**Comment by pengc99** [comment]
I would suggest that this topic be reopened. Currently the way the app is written, without support for base url, exposing this using a reverse proxy requires using a direct domain (domain.com) or a subdomain (sub.domain.com), but if users want to use it behind a virtual directory (domain.com/dir/) it requires the ugly use of mod_rewrite and implementing custom rules. Additionally, this effectively blocks the usage of web sockets when using mod_rewrite.

**Comment by astorije** [comment]
I'm curious to hear from other @thelounge/maintainers.

I personally haven't used Apache in years, so the `mod_rewrite` thingy doesn't speak to me, but that a web server blocks websockets when serving an app behind a path is rather surprising...

I sure would like to avoid maintaining this ourselves. This is not the core of what we offer, and every time we have to implement/maintain a feature that belongs to a real webserver (like dealing with HTTPS certificates, etc.), it affects our ability to work/maintain core features of the IRC client.

**Comment by xPaw** [comment]
Seems to be doable by Apache alone https://serverfault.com/a/623027

It would be rather weird if it wasn't.

**Comment by YaManicKill** [comment]
Yeah, I don't think we want to support this feature ourselves, as it's do-able in apache, personally.

**Comment by windware-ono** [comment]
It metions about sub folder in the document but the example is wrong.

https://thelounge.chat/docs/guides/reverse-proxies#nginx

You need this to strip out the added path through the proxied request and it worked for me for nginx.
```
rewrite /irc/(.*) /$1  break;
```

**Comment by xPaw** [comment]
The example is correct if you fully copy it (primarily the ending slash in proxy_pass)

**Comment by windware-ono** [comment]
I stand corrected, sorry.

**Comment by mozai** [comment]
Found this old bug report while I was frustrated, leaving a note what worked for me.  
The `/` on the end isn't just for the `proxy_pass` line.

```
 # location = /chat   # wrong
 # location ^~ /chat  # also wrong
   location ^~ /chat/ {
       if ($invalid_referer) { return 403; }
       error_page  502 /maintenance.html;
       proxy_pass  http://127.0.0.1:4524/;
       proxy_http_version  1.1;
       proxy_set_header Connection         "upgrade";
       proxy_set_header Upgrade            $http_upgrade;
       proxy_set_header X-Forwarded-For    $remote_addr;
       proxy_set_header X-Forwarded-Proto  $scheme;
       # default timeout is 1m, not long enough for a slow chatroom
       proxy_read_timeout  1d;
   }   
 ```
