### ISSUE TITLE
/list incorrectly ignores parameters

### ISSUE THREAD

**Issue by SnowPhoenix** [thelounge/lounge#1250]
Per [RFC 1459](https://tools.ietf.org/html/rfc1459#section-4.2.6), /list is supposed to support parameters. However, The Lounge simply returns the list of channels that would be obtained by using /list without any parameters, which can be a bit of a surprise to people attempting to use it with specific filter parameters  on larger servers.

Some servers allow things like `/list >50` to list only channels with more than 50 users, some allow wildcards in channel names such as `/list *chat*` to list all channels containing the string `chat` in their names, but regardless I'd expect it to be safe to just pass the parameters and let the server figure it out as the format of the results does not change in any case that I can remember.

**Comment by YaManicKill** [comment]
Probably the best thing to do is just pass on the parameters to the server and see what happens. We have tried intercepting and being clever with previous ones and always found that it just ends up creating bugs or missing features.

**Comment by astorije** [comment]
Agreed. It's also probably going to be a very easy win, if anyone wants to contribute :)

**Comment by swordbeta** [comment]
We already pass on any arguments to the list method as seen here: https://github.com/thelounge/lounge/blob/358852cecb53f0697f548d5b4df59377dc6c90bf/src/plugins/inputs/list.js#L7

However it's not used in irc-framework: https://github.com/kiwiirc/irc-framework/blob/1cc8892f6bf5414e677f0d37daa5984b77b58374/src/client.js#L556 introduced in this PR: https://github.com/kiwiirc/irc-framework/pull/48

**Comment by astorije** [comment]
@maxpoulin64, @swordbeta, mind taking a minute to raise this on `irc-framework` repo and to @prawnsalad if necessary?

**Comment by swordbeta** [comment]
@astorije Created an issue: https://github.com/kiwiirc/irc-framework/issues/101

**Comment by MaxLeiter** [comment]
This has now been fixed in irc-framework; now just needs to be released
