### ISSUE TITLE
lounge is installed as 'nobody' as its owner.

### ISSUE THREAD

**Issue by foxtrot9** [thelounge/lounge#1265]
```
mit@ubuntu14  /usr/lib/node_modules  ls -l
total 8
drwxr-xr-x 11 root   root 4096 Jun 23 22:02 npm
drwxr-xr-x  6 nobody mit  4096 Jun 23 22:03 thelounge
```
 
It should be owned by user who installed it. Here, `mit` should own it. Any reasons for not doing so?

**Comment by YaManicKill** [comment]
Hi, thanks for this, but this is definitely an npm thing, not a lounge thing. We don't control permissions on npm install. You can see discussion about that [here](https://github.com/npm/npm/issues/3849).
