### ISSUE TITLE
notices on display at server linux not work.

### ISSUE THREAD

**Issue by blueeyedboy** [thelounge/lounge#1268]
Here is a problem with notices display not work on linux server.?

when a client write notice to an other can see notice only at status. this is really no good?

wanna to know how can i fix it?

**Comment by dgw** [comment]
I _think_ this is a duplicate of #114.

**Comment by blueeyedboy** [comment]
dgw, I'm interest to fix issue? if i can how.?

**Comment by dgw** [comment]
See the discussion in the linked issue. It's a change that would need to be made in the code, but the maintainers have not agreed on how/whether to change it.
