### ISSUE TITLE
[feature request] listing channels

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#130]
_From @scottscreations on February 2, 2016 15:19_

would be nice to have a /list command.

Thanks.

_Copied from original issue: erming/shout#635_

**Comment by astorije** [comment]
_From @MaxLeiter on February 2, 2016 20:7_

https://tools.ietf.org/html/rfc2812#section-3.2.6 IRC spec for /list command in case someone wants to implement it

**Comment by astorije** [comment]
_From @dubzi on February 3, 2016 10:5_

Hmm, interesting. I always assumed /list accepted arguments such as /list >500 to retrieve channels with more than 500 users. But according to that document this is not part of the spec at all. 
This would require some changes in the slate/slate-irc library we use though, as far as i can tell it's not implemented there yet.

Also, would you prefer to see this in some new window, or should we just return this in the network channel, like the MOTD? That last option would be easier to implement, but definitely not as user friendly.

**Comment by astorije** [comment]
_From @YaManicKill on February 3, 2016 11:17_

I'd personally like to see stuff like this (and the /whois information as mentioned in [214](https://github.com/erming/shout/issues/214#issuecomment-58745292)) in a modal window kinda like how IRCCloud does it. But that would make it a much bigger story, and I know @astorije will jump in with some UX advice (or at least, saying we need to get some).

**Comment by astorije** [comment]
_From @MaxLeiter on February 3, 2016 19:45_

@dubzi I think it could be implemented shout-side, but I can't think of a reason not to make an upstream PR.

**Comment by astorije** [comment]
_From @dubzi on February 4, 2016 9:52_

What do we think about protecting our users with potentially destructive commands? I was testing this myself, and ran a `/list` on freenode. Without any arguments, that command works, and is valid, but will return _every channel_ on freenode. It crashed my browser :fearful: 

IMO we just shouldn't accept that command without any arguments. Perhaps returning an example of arguments you can use when you run it without arguments?

I also found an answer to my question earlier about the spec. Basically the custom arguments such as `/list >500` are handled on the irc server's side. Not sure which servers accept it since it's not part of the spec, but I assume most do.

**Comment by lindskogen** [comment]
A reasonable implementation would be for the backend to keep a cache of `/list` and return a paginated response to the client (in a modal for example).

**Comment by lindskogen** [comment]
We're doing some work on this over in https://github.com/cthit/lounge/tree/feature/list and has gotten pretty far. For now it keeps a cache from the first time `/list` is run and returns that cache every subsequent run of `/list`

**Comment by astorije** [comment]
I have never used `/list` myself, but this was transferred over here under request of @YaManicKill, maybe he can chime in. Also, I would rely on opinions from @maxpoulin64 and @xPaw, who appear to always be very insightful :-)

Thanks a lot for this though, that sounds terrific!
I'm wondering, since The Lounge is meant to run forever (I said *meant to*...), how do you keep track of channels changes (new channels, I don't know how empty channels are handled) after that first caching?
Could it be worth having a 1-day interval to refresh this caching?

**Comment by lindskogen** [comment]
We're thinking something along those lines yes!

**Comment by maxpoulin64** [comment]
#167 implements `/list`. It doesn't do caching or anything fancy. Commenting mainly so we have the ping in the PR to know what issues to close on merge :)

**Comment by DerfOh** [comment]
:+1: Would love to see this working.

**Comment by astorije** [comment]
Added by #258.
