### ISSUE TITLE
"Show more messages" button becomes disabled after clicking it once

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/lounge#1304]
When I scroll up to the oldest message and click the _Show more messages_ button, it loads some more messages as expected. I can't do that a second time, the font changes color on hover but it's not clickable and the cursor doesn't change to hand anymore. Inspecting the element, it becomes clear why: the button has the ```disabled``` property. When I remove it, I can successfully use the button to load more messages, which again disables the button.

No errors in the (browser) console.

It might be noteworthy that I do not have maxHistory set in my config (probably because my config is quite old, older than this configuration item).

**Comment by YaManicKill** [comment]
Can you confirm what version you are running, and what browser/os you are running it on?

**Comment by Jay2k1** [comment]
The Lounge source (761dfbb) (node 6.11.0 on linux x64)

Issue reproducable in
* Google Chrome Mac 59.0.3071.115
* Firefox Mac 54.0
* Vivaldi Mac 1.10.867.42
* Safari Mac 10.1.1 (12603.2.4)
* Chrome Android 59.0.3071.125

**Comment by PolarizedIons** [comment]
This was fixed with #1068, can you update to master and confirm? 761dfbb is about 3 months old at this point.
