### ISSUE TITLE
Return an error when connecting to a forbidden network in locked mode

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#133]
When setting `lockNetwork` to `true` (added in #82) and trying to connect to a server that is not the authorized one using `/connect`, we get no output at all, even though the code path accounts for an error response.

**Comment by xPaw** [comment]
I think the solution is to create server window on the client as soon as possible, instead of waiting for a connection to be opened.

**Comment by maxpoulin64** [comment]
Agreed. That's how all clients do it, we definitely should always open the server window as soon as possible to show either error messages or success messages.

**Comment by xPaw** [comment]
Closing this issue since it's practically a duplicate #115

**Comment by astorije** [comment]
Indeed, thanks and sorry @xPaw!
