### ISSUE TITLE
All networks removed when closing tab

### ISSUE THREAD

**Issue by kurobeats** [thelounge/lounge#1339]
Unsure if this is by design but after setting up all connections (roughly 10) to a ZNC bouncer and was satisfied with the functionality, I closed the tab to use later. When I navigated back to lounge, everything was gone and I was required to connect all networks again.

Am I missing a command or setting on the server that I am required to set to save networks/perform auto connects?

**Comment by christer88** [comment]
Is your Lounge configuration set to private mode?

**Comment by kurobeats** [comment]
I don't believe so. Where is this setting? config.js?

**Comment by christer88** [comment]
/usr/lib/node_modules/thelounge/
You can type 'whereis lounge' to see the path.

**Comment by xPaw** [comment]
The config is going to be in `~/.lounge` if you did not use `--home`. You can use `lounge config` to open it in the editor.
