### ISSUE TITLE
Un-focus input message when image viewer is opened

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#1342]
This describes a tiny issue that will happen once #1325 is merged.

I couldn't find how to quickly fix it, and @YaManicKill suggested to open an issue and stick its number along with the TODO so we keep track of it, so here we go.

**Comment by xPaw** [comment]
You can probably set focus on `#image-viewer`, or call blur on `#input` and then focus it back when viewer is closed.

**Comment by astorije** [comment]
> call blur on `#input`

I remember trying that and it didn't work, but I didn't investigate much further. Do you want to give it a try maybe?
