### ISSUE TITLE
URL parser adds preview placeholder divs within the part/quit reason

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#1343]
Since #1303, "placeholder" `div`s get added in the middle of the message, because of [`parse` being called inline](https://github.com/thelounge/lounge/blob/9735f2b7a112635c4e75ba8d958e3569cb3c3b24/client/views/actions/part.tpl#L5). This causes line breaks like the following:

<img width="564" alt="screen shot 2017-07-17 at 00 44 47" src="https://user-images.githubusercontent.com/113730/28255783-6c6a2db0-6a89-11e7-9e88-51fa44d2cd3b.png">
<img width="605" alt="screen shot 2017-07-17 at 00 46 07" src="https://user-images.githubusercontent.com/113730/28255784-6c7607a2-6a89-11e7-8f16-90e9f7b6db95.png">

This would also be true for [`kick`](https://github.com/thelounge/lounge/blob/9735f2b7a112635c4e75ba8d958e3569cb3c3b24/client/views/actions/kick.tpl#L5), [`list`](https://github.com/thelounge/lounge/blob/9735f2b7a112635c4e75ba8d958e3569cb3c3b24/client/views/actions/channel_list.tpl#L12), [`quit`](https://github.com/thelounge/lounge/blob/9735f2b7a112635c4e75ba8d958e3569cb3c3b24/client/views/actions/quit.tpl), [`topic`](https://github.com/thelounge/lounge/blob/9735f2b7a112635c4e75ba8d958e3569cb3c3b24/client/views/actions/topic.tpl), etc. though the consequences are not dramatic in most.

Not sure yet what are the best option(s) to fix that.
It's a regression from 2.3.2, do we need to make this a blocker for 2.4.0?

**Comment by xPaw** [comment]
Easiest way to fix would be to make `.preview` hidden until it gets content loaded.

**Comment by astorije** [comment]
In this spirit, `.preview:empty { display: none; }` would probably do the trick. But it would be really nice to do this differently, just not sure how.
