### ISSUE TITLE
socket.io 400 bad request

### ISSUE THREAD

**Issue by loconox** [thelounge/lounge#1349]
Hi,

I'm using lounge behind a nginx reverse proxy and a varnish cache (not sure if it may cause the issue). I want use websocket and not the pulling method but it seems that there is an issue somewhere. In my browser log I got this:
``` 
400 GET https://webirc.jeremielibeau.fr/socket.io/?EIO=3&transport=websocket&sid=-Snc_L_vXSjzNCZ8AAAA
```
and next, it's fallback to the pulling method:
```
200 GET https://webirc.jeremielibeau.fr/socket.io/?EIO=3&transport=polling&t=LrKfzG9&sid=-Snc_L_vXSjzNCZ8AAAA
```
When I try to connect directly on the 9000 port with `ssh -L` tunnel everything is working.
My nginx config:
```
server {
	listen 8080;
	listen [::]:8080;

	server_name webirc.mydomin.tld;

	location / {
		proxy_pass http://127.0.0.1:9000/;
		proxy_http_version 1.1;
		proxy_set_header Connection "upgrade";
		proxy_set_header Upgrade $http_upgrade;
	#	proxy_set_header X-Forwarded-For $remote_addr;

		# by default nginx times out connections in one minute
		proxy_read_timeout 1d;
	}

	access_log /var/log/nginx/webirc_access.log;
	error_log /var/log/nginx/webirc_error.log;

}

server {
        listen 80;
        listen [::]:80;

        server_name webirc.mydomin.tld;

	return 301 https://$host$request_uri;

        access_log /var/log/nginx/webirc_access.log;
        error_log /var/log/nginx/webirc_error.log;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name webirc.mydomin.tld;

	ssl on;
	ssl_certificate /etc/letsencrypt/live/webirc.mydomin.tld/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/webirc.mydomin.tld/privkey.pem;
	ssl_session_cache shared:SSL:10m;
	ssl_session_timeout 10m;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers ALL:!aNULL:!eNULL:!LOW:!EXP:!RC4:!3DES:+HIGH:+MEDIUM;
	ssl_prefer_server_ciphers on;

	location / {
		proxy_pass http://127.0.0.1:81; # varnish is listening on the port
		proxy_set_header X-Real-IP  $remote_addr;
		#proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_set_header X-Forwarded-Proto https;
		proxy_set_header X-Forwarded-Port 443;
		proxy_set_header Host $host;
	}

	access_log /var/log/nginx/webirc_access.log;
	error_log /var/log/nginx/webirc_error.log;
}
```
Nginx handle tls and redirect to varnish which is listening on port 81. Varnish redirect to nginx on port 8080 and finally nginx redirect to port 9000.
This is a generic conf for all my webapp. I maybe can make a specific conf in varnish to directly redirect to node but this is not the point. This setup should works.

**Comment by bews** [comment]
Lounge works behind nginx fine, problem is in your config. 

If you want to use `ssl`, then you should use it all the way through:
`proxy_pass httpS://127.0.0.1:9000/;`

Lounge also should be configured in ssl mode.

**Comment by xPaw** [comment]
> If you want to use ssl, then you should use it all the way through:

@bews This is not true and not required.


@loconox You have 2 different server blocks. I assume the one with port `8080` works fine as it hits Lounge directly avoiding Varnish? You should show your Varnish config and make sure it is configured correctly, like so https://www.varnish-cache.org/docs/3.0/tutorial/websockets.html

**Comment by loconox** [comment]
@xPaw I have added varnish conf for websocket but this doesn't change anything
Varnish conf:
```
#
# This is an example VCL file for Varnish.
#
# It does not do anything by default, delegating control to the
# builtin VCL. The builtin VCL is called when there is no explicit
# return statement.
#
# See the VCL chapters in the Users Guide at https://www.varnish-cache.org/docs/
# and https://www.varnish-cache.org/trac/wiki/VCLExamples for more examples.

# Marker to tell the VCL compiler that this VCL has been adapted to the
# new 4.0 format.
vcl 4.0;

# Default backend definition. Set this to point to your content server.
backend default {
    .host = "127.0.0.1";
    .port = "8080";
}

sub vcl_recv {
    # Happens before we check if we have this in cache already.
    #
    # Typically you clean up the request here, removing cookies you don't need,
    # rewriting the request, etc.
    if (req.http.Upgrade ~ "(?i)websocket") {
         return (pipe);
     }
}

sub vcl_backend_response {
    # Happens after we have read the response headers from the backend.
    #
    # Here you clean the response headers, removing silly Set-Cookie headers
    # and other mistakes your backend does.
}

sub vcl_deliver {
    # Happens when we have all the pieces we need, and are about to send the
    # response to the client.
    #
    # You can do accounting or modifying the final object here.
}

sub vcl_pipe {
     if (req.http.upgrade) {
         set bereq.http.upgrade = req.http.upgrade;
     }
}
```

Architecture summary:
[browser] = TLS => [nginx:443] = clear => [varnish:81] => [nginx:8080] => [node:9000]

I've just tested every block I have.
- directly node on port 9000 => **ok**
- in clear HTTP to nginx on port 8080 => **ok**
- in clear HTTP to varnish on port 81 => **ok**
- in HTTPS to nginx on port 443 => **websocket not ok, falling back to pulling**

I seems the the issue is with my nginx conf.

**Comment by xPaw** [comment]
That seems like an overly complicated setup. Why is the varnish hitting nginx again? In fact, why do you need varnish at all in this setup?

**Comment by xPaw** [comment]
I just tried visiting `http://webirc.jeremielibeau.fr:8080/` which does have working websockets. This is either an issue with proxying via so many steps, or varnish is breaking it. Either way, this is not an issue with The Lounge, and we can not fix it.

**Comment by loconox** [comment]
Ok thanks for your help.

**Comment by bews** [comment]
> If you want to use ssl, then you should use it all the way through:

> @bews This is not true and not required.

It didn't work (error 500) until I made that change, also this advice helped another person on IRC.

**Comment by xPaw** [comment]
@bews TLS is terminated on nginx site, there is no reason to do another TLS request locally (nginx->lounge), as http will do just fine. nginx has the decrypted request, and it can perform a proxy request using plain http (there is no reason to encrypt localhost requests). I know for a fact The Lounge works just fine like this.

Your error 500 is most likely an unrelated misconfiguration.

Here's digitalocean guide: https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-load-balancing-with-ssl-termination

**Comment by loconox** [comment]
@bews I'm using nginx as TLS termination and it's working well. In this case, you should configure your backend, node for instance, in clear http.
For the record, I finally decided to remove varnish from my setup and put  node directly after nginx as follow:
```
server {
        listen 80;
        listen [::]:80;

        server_name webirc.mydomain.tld;

	return 301 https://$host$request_uri;

        access_log /var/log/nginx/webirc_access.log;
        error_log /var/log/nginx/webirc_error.log;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name webirc.mydomain.tld;

	ssl on;
	ssl_certificate /etc/letsencrypt/live/webirc.mydomain.tld/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/webirc.mydomain.tld/privkey.pem;
	ssl_dhparam /etc/cozy/dh.pem;
	ssl_session_cache shared:SSL:10m;
	ssl_session_timeout 10m;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers ALL:!aNULL:!eNULL:!LOW:!EXP:!RC4:!3DES:+HIGH:+MEDIUM;
	ssl_prefer_server_ciphers on;

	location / {
		proxy_pass http://127.0.0.1:9000/;
		proxy_http_version 1.1;
		proxy_set_header Connection "upgrade";
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header X-Forwarded-For $remote_addr;

		# by default nginx times out connections in one minute
		proxy_read_timeout 1d;
	}

	access_log /var/log/nginx/webirc_access.log;
	error_log /var/log/nginx/webirc_error.log;
}
```
Not sure which was the issue, maybe linked with headers ...

**Comment by loconox** [comment]
@xPaw Could you please remove my domain from you previous message. Thanks :)
