### ISSUE TITLE
Incorrect mode in kick message for target

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1351]
> @xPaw has kicked @lounge-user27 (hello world)

`lounge-user27` takes `@` from `xPaw` which is wrong. In server code it should look up correct mode for the kicked user, and template needs to display it correctly.

**Comment by MaxLeiter** [comment]
Can be closed as of #1352

**Comment by astorije** [comment]
Not exactly, #1352 removes wrong mode, but doesn't add the correct one. It's an improvement towards this, yes, but not the end of it.

**Comment by dgw** [comment]
Just wanted to drop a note that I'm working on fixing both this and #1522, so both the kicker and the target will display the correct modes. Might have something by tomorrow, even, assuming I have time to kick the tires enough to make sure that it's PR-worthy.
