### ISSUE TITLE
Open emoji autocomplete menu after two characters have been entered (instead of just the leading colon)

### ISSUE THREAD

**Issue by easymac** [thelounge/lounge#1355]
Example: Typing `:` currently opens the menu and selects 💯.
Instead: Do not open the menu until the leading character (`:`) and two additional have been entered.

When attempting to send a message that ends in an emoticon, the emoji menu attempts to autocomplete and replaces the emoticon with an emoji.

The user is required to either hit `ESC` after typing their emoticon or, as often happens to me, delete the emoji, type the traditional emoticon again, and then hit `ESC` before hitting `Enter`.

The emoticon...
...`:x` becomes ❌ 
...`:o` becomes ⭕️ 
...`:3` becomes 🥉 
...`:p` becomes 😔

This interaction is very frustrating.

The solution I believe is best (and is also employed by Discord) is to require two characters after the leading character (`:`) before opening the menu. Thus, typing `:` doesn't suggest anything (which makes sense); typing `:p` doesn't attempt to autocomplete (which allows unfettered use of traditional emoticon); and typing `:pe` will still bring up the menu and attempt to autocomplete with 😔.

**Comment by astorije** [comment]
👍 I would like this change to happen, but we have to keep in mind that the following emoji will not be available anymore:

```js
> Object.keys(map).filter(k => k.length <= 1).map(k => [k, map[k]])
[ [ 'v', '✌' ],
  [ 'a', '🅰️' ],
  [ 'b', '🅱️' ],
  [ 'x', '❌' ],
  [ 'o', '⭕' ],
  [ 'm', 'Ⓜ️' ] ]
```

A solution I see for that is to force-open the completion dropup when hitting Tab, so that typing `:x` then hitting <kbd>Tab</kbd> would open a single suggestion, pre-selected, for ❌
(Interestingly, I just noticed with this comment that GitHub does what we do currently)

**Comment by starquake** [comment]
Why not open up a single selection when entering `:x: :o:`

**Comment by xPaw** [comment]
@starquake That probably would work, yeah.
@MaxLeiter do you want to take this?

**Comment by MaxLeiter** [comment]
So, if we make it two characters **after** the `:`, that will remove emojis autocorrecting such as `:+1` (:+1:)  and `:ox` (:ox:)

**Comment by xPaw** [comment]
@MaxLeiter the idea is to make it 2 characters including the colon. So `:ox` is 3.

**Comment by dgw** [comment]
I'm really glad there's a PR open to implement this. Since updating to 2.4.0 the autocomplete interfering with simple emoticons has been my number one annoyance.
