### ISSUE TITLE
Preserved whitespaces are causing issues with previews

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#1357]
#1242 broke a few things related to previews:

1. The toggle button now triggers a new line. This is due to jQuery's `after()` that inserts a new line instead of inserting on the same line. I tried to look into this without much luck.
2. Image previews have empty lines above/below them.
3. When collapsed, image previews still show an empty line.

These are shown in the following screenshots:

<img width="604" alt="screen shot 2017-07-20 at 19 16 32" src="https://user-images.githubusercontent.com/113730/28442756-f9ad85d4-6d7f-11e7-84f1-eb605664c171.png">
<img width="503" alt="screen shot 2017-07-20 at 19 16 54" src="https://user-images.githubusercontent.com/113730/28442763-02ea6a04-6d80-11e7-932c-b28a27737212.png">

**Comment by astorije** [comment]
@xPaw, could you take a look at the first bug here? I tried to fix it but didn't succeed...

**Comment by MiniDigger** [comment]
Uuh, I thought it's a bug in my theme since I was playing around with that yesterday after updating my instance. 
I couldn't find any fix however.

**Comment by astorije** [comment]
I am actually fixing bugs 2 and 3 as part of #1353 but bug 1 is still unknown to me.
