### ISSUE TITLE
Channel names in topics are not clickable

### ISSUE THREAD

**Issue by TheSonAlsoRises** [thelounge/lounge#136]
![y5avlgz - imgur](https://cloud.githubusercontent.com/assets/8591366/13509697/0fcdbfee-e18d-11e5-8e2a-4ea51f7a5152.png)

The URL is clickable but the channel name is not parsed. Ideally I should be able to click on the channel name and join it.

**Comment by xPaw** [comment]
#128 should fix this.

**Comment by maxpoulin64** [comment]
I confirm #128 fixes this. It lacks a hover effect but the link is clickable and works.
