### ISSUE TITLE
Typing up messages calls up the submission history

### ISSUE THREAD

**Issue by TheSonAlsoRises** [thelounge/lounge#137]
![cap](https://cloud.githubusercontent.com/assets/8591366/13510687/fd2dbf6a-e191-11e5-8dc2-93879694b261.png)

For some reason my browser sometimes suggests previously-typed messages as I type new ones. Using Opera 35.

**Comment by dgw** [comment]
This should have been resolved in #88, but there were side effects. Hopefully it can be resolved in the short term, or medium term, because it is a usability concern on mobile.

**Comment by nornagon** [comment]
I think this is fixed now?

**Comment by dgw** [comment]
This issue should be sidestepped completely by the switch to a `textarea` for input (#379), since browsers do not save input history for that particular form element.

**Comment by TheSonAlsoRises** [comment]
I am on master and this is indeed no longer a problem.
