### ISSUE TITLE
Weird mouseenter effect on nicknames in certain themes

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/lounge#1372]
When nickname colors are disabled, on current master (2a7dadd), there's a weird flashing effect when you hover over nicknames and use the Morning or Zenburn themes:

![image](https://thumb.gyazo.com/thumb/1200/_6e1be0e505af11f76b30530de4d3e5fb-gif.gif)

Tested in Firefox and Chrome on macOS. Does not happen with colored nicks enabled.

**Comment by MaxLeiter** [comment]
Was added here: https://github.com/thelounge/lounge/commit/7fb527847e9da2e3a25eff9fc535f6f6a42201ee#diff-97db1f70168fb5f12457b238ff6052b5R352

**Comment by astorije** [comment]
I do break things, don't I? 😂

**Comment by astorije** [comment]
@Jay2k1, I could reproduce, and fixed this in #1374. Feel free to review this fix there :)
Thanks for noticing this, good eye!
