### ISSUE TITLE
Fix font declarations to inherit from body

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#138]
This will make it easier to change fonts by applying `font-family` on `body`.

There are only a couple of declarations that specifically specify `Lato`, should be trivial to get rid of these, so it automatically inherits.

**Comment by wesleyParriott** [comment]
I might be misunderstanding, but it would appear that the font is already declared on the body.

**Comment by xPaw** [comment]
The problem is that it's being re-declared in some selectors, e.g. here https://github.com/thelounge/lounge/blob/9f179c75664753760ea69e5b52801c24fb52784d/client/css/style.css#L131

**Comment by wesleyParriott** [comment]
I'd be more than happy to fix that then
