### ISSUE TITLE
Autocomplete for channels should maybe only show channels for current server

### ISSUE THREAD

**Issue by milindl** [thelounge/lounge#1381]
Current behaviour:
Autocomplete shows the list of channels across all servers that I'm connected to when I type `#`

Is it possible that only the channels for the current server to be displayed (since referencing someone to a channel in _another_ server is not usual I think).

How does this suggestion sound? I might also be able to help out if needed.

**Comment by MaxLeiter** [comment]
Am definitely a fan 👍

**Comment by milindl** [comment]
Is it reasonable/useful if I come up with a PR for this idea?

**Comment by astorije** [comment]
Hi @milindl! I would wait for @xPaw to give his opinion on this before jumping on it.

I admit that I often use this "feature" myself, but it's more of a development/testing purpose, so I don't want this to impact the decision. Whatever @xPaw recommends will be fine by me, but I'm pretty sure he'll agree with you.

**Comment by dgw** [comment]
This has been bugging me recently, 👍 

I could see a case for including channels from other servers if something like Textual's `/goto` command was implemented (which jumps to a fuzzy-matched buffer matching whatever you type after it), but not usually in normal IRC conversation.

Ping @xPaw :)

**Comment by astorije** [comment]
Yeah okay, I'm on board 😅 

<img width="318" alt="screen shot 2018-01-14 at 21 02 38" src="https://user-images.githubusercontent.com/113730/34923958-524c4b88-f96e-11e7-85f3-aa7961a51528.png">

**Comment by astorije** [comment]
@milindl, do you want to help with a PR for this?

**Comment by milindl** [comment]
@astorije Yes, but it might take me a couple days to get to it since I've not worked on the lounge before, so I might be a bit slow.

**Comment by astorije** [comment]
No worries at all, whenever you can, and take all the time you need :)
Feel free to open a PR early, even if it doesn't work, if you're stuck and need help.
Good luck!
