### ISSUE TITLE
User list empty after refreshing page until user joins/parts a channel [v2.4.0]

### ISSUE THREAD

**Issue by easymac** [thelounge/lounge#1389]
Details:
- Running from source at [v2.4.0 (8e4582f)](https://github.com/thelounge/lounge/commits/v2.4.0)
- Running  in private mode

Not sure what other details may be relevant.

Upon starting The Lounge for the first time and loading the web app, all of the user lists are available. (I assume this is because I am joining the channels for the first time)

Upon joining a new channel, its user list is available.

However, when you reload the page the user list in every channel empties. (Reads "0 users"). The user list remains empty until a user joins or leaves the channel.

**Comment by astorije** [comment]
@xPaw, I believe that, if issue there is, it would be related to https://github.com/thelounge/lounge/pull/1194. Would you mind looking into it when you get the chance?

I can see the "0 users" becoming a "X users" on refresh, but it takes a fraction of seconds, so I can't reproduce this issue.

**Comment by xPaw** [comment]
Odd, it indeed should load, I tested it and it works fine. If you're running from git, did you run `npm run build`?

**Comment by easymac** [comment]
Oops. Yeah, that did it. Sorry.

Closing.
