### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by mlncn** [thelounge/lounge#1393]
```
node -v
v0.10.48

npm -v
2.15.1
```
Installed as instructed (had to select the package to get the one available per `curl -sL https://deb.nodesource.com/setup | sudo -E bash` as described on on https://www.npmjs.com/package/thelounge/tutorial )

`lounge start`

> /usr/lib/node_modules/thelounge/src/command-line/index.js:28
> 	log.info(`Configuration file created at ${colors.green(Helper.CONFIG_PATH)}.`
> 	         ^
> SyntaxError: Unexpected token ILLEGAL
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/usr/lib/node_modules/thelounge/index.js:16:1)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>

**Comment by astorije** [comment]
Hi @mlncn, welcome to The Lounge!

Unfortunately for your setup, The Lounge is only compatible with Node v4 and up, which seems to be your issue here.
