### ISSUE TITLE
Log in, reload page, "Authentication failed", have to re-login

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#1398]
On master ([ff85b61](https://github.com/thelounge/lounge/tree/ff85b61)), probably due to #1199

**Comment by astorije** [comment]
@MaxLeiter, could you post your resolution here, for reference?

**Comment by MaxLeiter** [comment]
It was an issue with my reverse proxy/Nginx setup and was unique enough to the point where I'm sure no one else will run into it. Basically my client was using the JS from a public instance due to a missing /
