### ISSUE TITLE
Hex based colours are not stripped in cleanIrcMessage

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1413]
We have a regex to clean the message (currently used in link prefetcher, and then will be used by push notifications) which does not clean hex based colours.

https://github.com/thelounge/lounge/blob/0bc12681970ddd99450de827368805d463bf4f15/src/helper.js#L134-L137

**Comment by astorije** [comment]
This function is a great candidate for unit tests :)
In general, functions that involve regex should be tested, or you never really know what edge cases you support...
