### ISSUE TITLE
Expanded joins do not fill chat window properly

### ISSUE THREAD

**Issue by Raqbit** [thelounge/lounge#1414]
![Screenshot](http://i.imgur.com/se3GMB2.png)

Picture should speak for itself.

**To reproduce:**

* You should be running latest master (after condense-joins merge)
* Have someone join/leave a couple of times so lounge condenses it into a condensed join view
* Expand it on a non-mobile device

**Comment by YaManicKill** [comment]
Just a quick note that this should fix it when applied to the messages inside the condensed:

```
flex-basis: 100%;
```

**Comment by astorije** [comment]
Will fix tonight, thanks!
