### ISSUE TITLE
"true" default options can override user settings

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#1420]
How to reproduce:

* Go into options
* See that "Auto-expand websites" is checked
* Uncheck
* Refresh page
* Go into options

What should happen: auto-expand websites should still be unchecked
What actually happens: auto-expand websites is checked again

It's due to [this change](https://github.com/thelounge/lounge/commit/b508783101dfc979e92221a884f87812b27633b7#diff-03ed49e301a4e588ec406bc5aace2a02R31) where it will only set the user option if it is truthy, and so if the default is truthy and the user's option is falsy, it will use the default.

We should have an undefined check instead.

**Comment by astorije** [comment]
Sorry, another bug of mine 😅

> We should have an undefined check instead.

Shouldn't we have checked [one of these](https://stackoverflow.com/a/22728565) instead?
