### ISSUE TITLE
Tab-completion of channels unavailable with auto-complete disabled

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#1433]
I disabled auto-complete for the time being because I kept ending up with emoji instead of simple emoticons (see #1355), and am consistently surprised that I can tab-complete nicks, but not channels with auto-complete turned off.

Personally, I would like tab-completion to be available for both nicks and channels, even with the full auto-complete functionality disabled—hence the issue title—but at the very least I think this should be consistent (both nicks and channels completed on <kbd>Tab</kbd> even with auto-complete disabled, or neither).

The only somewhat relevant issue I found before posting this was #1316, which is about rotating the completed value on subsequent presses of <kbd>Tab</kbd>, but it's not even possible to worry about rotating the value if it won't complete in the first place. :)

**Comment by xPaw** [comment]
Nicks can still be completed because it's handled by a different library (we have two at the moment, one for just the tab key and the other for @ and the UI). Ideally your issue should be handled whenever we get rid of the secondary library.
