### ISSUE TITLE
Allow to "/cycle" current channel

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#1436]
I occasionally find it necessary to part and rejoin channels, be it to fix some permissions issue with ChanServ or to prod ZNC into rejoining a stuck channel, etc.

Not to keep stealing ideas from Textual :grin: but it does have a `/cycle` command that does precisely this: It parts the current channel, and then rejoins it.

Maybe this would even be a good first "real" contribution (code, not just ideas) for someone like me?

**Comment by xPaw** [comment]
> Maybe this would even be a good first "real" contribution (code, not just ideas) for someone like me?

Yes!

**Comment by astorije** [comment]
I'm not sure I get the use case for it as I have never needed it, but I'm not using ZNC nor have had issues with ChanServ, so I'm not the best person to be in favor or against this, I'm fine with it if @xPaw is fine with it.

However, reading your description, I don't think `/cycle` is the best terminology for it. I think `/rejoin` would work better (after all, you've used that word 3 times in your description :D). And once #1430 gets a fix, `/rejoin [<channel>]` could allow an optional channel name to part-and-join.

And yup, totally open to a contribution :)

**Comment by dgw** [comment]
> However, reading your description, I don't think `/cycle` is the best terminology for it. I think `/rejoin` would work better

I stole the command name from Textual too :grin:, what if both commands are exposed? The Lounge is the most Textual-like IRC experience I've found, either for web or non-Mac in general, so if I'm gravitating toward it for that reason I can't be the only one.

> Yes! You can figure out how part/join commands work and combine them.

Presumably by using parts of the internals from each command, not calling their functions directly? I'll give the command code a closer look soon-ish.

**Comment by xPaw** [comment]
> I don't think /cycle is the best terminology for it. I think /rejoin would work better

While true, `/cycle` is a decade old command and we shouldn't have our own name for it. https://www.google.com/search?q=irc+cycle+command

**Comment by astorije** [comment]
> While true, /cycle is a decade old command and we shouldn't have our own name for it.

I don't think that's the right way to look at it. The Lounge is not a decade-old client, and is not trying to look like a decade-old one either. People have reported switching to The Lounge for its modernity, we shouldn't think like that.
If something is more logical and practical to use, then it should be what we go for.

Anyway, in this very case, we should definitely have a `/cycle` alias, but I still believe `/rejoin` makes more sense.

**Comment by YaManicKill** [comment]
> Anyway, in this very case, we should definitely have a /cycle alias, but I still believe /rejoin makes more sense.

I'm good with this.

I definitely think `/cycle` should be included, becasus ethat's the terminology that many people use, but I'm fine with `/rejoin` being added as well.

**Comment by Jay2k1** [comment]
I learnt this command as `/hop` (that's what mIRC uses). Textual, fwiw, has both commands (`/hop` and `/cycle`) for the same action.

The reason behind naming it "hop" might be that the mIRC command has an optional channel argument, and if given, it parts the current channel and joins the give one. If you omit it, it just rejoins the current channel by `part`ing and `join`ing it. It also has an optional message argument which is used as part message.

I'm not sure if `hop` should be made at least an alias for `cycle`, given that it most likely won't accept an argument (and I don't see the point of using it to part a channel and join another instead).

**Comment by YaManicKill** [comment]
That seems like an odd command, to be honest. And `/hop` could be confusing as it could be expected to be like `/op` instead of `/cycle`.

I suggest we do `/cycle` and `/rejoin`, and when we get plugins started (I'll be starting work on this once #1266 is merged, I promise) then someone can create one to make this command if they want. Sensible?

**Comment by dgw** [comment]
`src/plugins/inputs/mode.js` already exports a `/hop` command (and `/dehop`), for halfop.

Is it just me or is there no input plugin for `/join`? I found `src/plugins/inputs/part.js` but no corresponding file for `/join`… :confused:

**Comment by xPaw** [comment]
`/join` is just bypassed to the server, as there is no need to implement it for us.

> "rejoin" is usually attached to rejoining channels upon being kicked.

That basically still does what cycle does, so we don't have any confusion there.
