### ISSUE TITLE
"show older messages" does not work if the buffer is empty

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1460]
Use `/clear` and click the button, it won't work.

**Comment by astorije** [comment]
This is true on v2.4.0 as well :man_facepalming:

**Comment by YaManicKill** [comment]
Oh of course :man_facepalming: ... that'll be because of [this change](https://github.com/thelounge/lounge/commit/e01e21cdbe237c2ed58b9175587c8f5b6efd2252). If there are no messages, we can't send the last ID. Sigh.
