### ISSUE TITLE
Keeping original user colors in themes for highlighted messages

### ISSUE THREAD

**Issue by bews** [thelounge/lounge#1467]
In my theme I want to keep the original user color in highlighted message:

![2017-08-28_11-56-33](https://user-images.githubusercontent.com/3627488/29766613-0c6067a6-8be8-11e7-8e52-f84059946c86.png) 

This is what I want to achieve:
![2017-08-28_11-56-56](https://user-images.githubusercontent.com/3627488/29766616-0e038b4c-8be8-11e7-8d88-09f68c9aa1d7.png)

But it is not possible to disable color overriding in theme in order to keep user colors:

![hc2](https://user-images.githubusercontent.com/3627488/29766726-69e0900e-8be8-11e7-980f-d0a75b17a86d.png)

The possible solution I see is to move this css https://github.com/thelounge/lounge/blob/master/client/css/style.css#L1173 from style.css to themes

**Comment by astorije** [comment]
Hi @bews,

> But it is not possible to disable color overriding in theme in order to keep user colors

Actually, you can do that in your theme:

```css
#chat.colored-nicks .highlight .user.color-1 {
    color: #1396cf;
}
```

The trick is that you re-apply the colors to the `.highlight` versions. If you have custom colors in your theme, that means just adding a second selector for the `.highlight` version, re-using your custom colors.

It's not idea, but it's possible.

**Comment by bews** [comment]
I tried to do this without overriding user colors and stuck. Thx @astorije :smiley: 

Also, it turned out that overriding user colors is enough to deal with this, no need for `.highlight` selector.
