### ISSUE TITLE
Make image viewer push state to history

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/lounge#1497]
When using the built-in image viewer on the phone, I always instinctively press the back button trying to close it, but the image stays open, I just go to the previous channel underneath. I don't know if I am the only one thinking the back button should close the image and take me _back_, but I think it's a good idea.

**Comment by YaManicKill** [comment]
Yeah, this annoys me as well, I keep forgetting this happens every time I open an image on my phone.
