### ISSUE TITLE
Inline channel parser easily breaks

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#15]
A message like `&lt;<span` will easily cause it to fail. `<[color code here]test>` will too.

![2016-02-12_19-20-44](https://cloud.githubusercontent.com/assets/613331/13015831/ef0d10a8-d1c3-11e5-873e-9a8a3461b7bd.png)

**Comment by astorije** [comment]
:+1: 

@xPaw, do you think it's an easy fix or is it more involved?

Actually, what would be terrific is if we could have some tests for this!!

**Comment by maxpoulin64** [comment]
There are still many issues with the channel parser, should we keep this one open or make a new issue?

**Comment by xPaw** [comment]
Reopen then

**Comment by maxpoulin64** [comment]
Reopening. @xPaw I'm referring to the breakage we saw not so long ago:

```
17:33	+xPaw	I'm not sure how we would even tokenize properly to fix all the issues
17:34	+xPaw	#test class='irc-fg11'>test
17:34	+xPaw	hey look another way to break parser
17:35	+xPaw	#test\x0311teshttp://example.com#wtft' target='_blank'>x0311teshttp://example.com#wtft">#test\x0311teshttp://example.com#wtft
17:35	+xPaw	absolute madness
17:36	+xPaw	I'm scared to paste output it produced because I think it will break it even further
17:36	+xPaw	https://gist.github.com/xPaw/a42ee9615b4ecc8731d7
17:37	+xPaw	just look at that output, I don't even know where to begin
```

I might give it a shot this weekend.
