### ISSUE TITLE
/expand should not expand status messages

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#1502]
`/expand` expands nicks, so `/collapse` should collapse them

Before: ![before](https://sr.ht/G4qo.png)

after `/expand`:  ![after](https://sr.ht/CoJ9.png)

after `/collapse`:  ![after](https://sr.ht/eruz.png)

**Comment by astorije** [comment]
I am surprised that `/expand` expands nicks, I missed that for sure. I really am not in favor of `/expand`/`/collapse` applying to status messages, only previews. Thoughts?

**Comment by MaxLeiter** [comment]
Agreed - not a fan of nicks expanding/collapsing

**Comment by astorije** [comment]
Mind renaming this into "/expand should not expand status messages" or something?

**Comment by MaxLeiter** [comment]
Done
