### ISSUE TITLE
Don't intercept /(c|h|n)s shortcut commands

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#153]
Intercepting `/ns`, `/cs`, and `/hs` and converting them to PRIVMSGs means the application has to assume that the services will have the expected names. There is a risk of the user accidentally sending a services command to another user who is using a common services nickname on a network that doesn't follow the convention.

By contrast, passing through `/ns`, `/cs`, and `/hs` to the server directly will either execute the services command as expected, or fail with an unknown command response—at which point the application can either retry using the conventional name of the service (more user-friendly) or pass the failure on to the user (safer).

Generally I'm in favor of aliases, but personally I'd rather risk a failed `/ns identify` command than risk The Lounge silently sending my password to an unknown user squatting on the name `nickserv`.

As a side note, it's also not entirely fair to Rizon that `/bs` isn't intercepted also. :stuck_out_tongue:

**Comment by maxpoulin64** [comment]
Yeah this is a known issue :+1:. Command overhaul is a project that will likely happen relatively soon. I was supposed to work on that today but #152 took a bit more time than I expected. I might give it a shot tomorrow if xPaw haven't done it already.

**Comment by dgw** [comment]
Glad to hear this is on the radar. :+1:
