### ISSUE TITLE
Tab-complete common network service names

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#1534]
I was thinking of other little quality-of-life things that my favorite desktop clients do, and one of them is tab-completing the names of network services (NickServ, ChanServ, MemoServ, etc.) along with nicks from the channel. (Here's an [example](https://github.com/Codeux-Software/Textual/blob/2c02fa4dcd5d87d1c4e828c5a9bdab8502e97a1b/Classes/Library/TLONicknameCompletionStatus.m#L278-L284) from Textual.)

This could be my next little project for The Lounge. I'd have service names always be at the end of the autocomplete sort order, so nicks in the channel are always completed first. Thoughts from the maintainers? Yay/nay?

**Comment by xPaw** [comment]
I don't think it's a good idea to auto complete *nicknames* of these services. However adding shortcut commands like `/ns` is a better idea.

**Comment by dgw** [comment]
Lite version of this PR'd with the shortcut commands. Still happy to work on the nickname part unless it's been vetoed outright.

**Comment by LFlare** [comment]
@xPaw, close this?
