### ISSUE TITLE
Open correct channel when clicking on push notifications

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1550]
This should be done after #1468 is merged. @MaxLeiter added support for `#chan-` location hashes, so it should be doable if the app is offline.

If there is a web page open already open however, it needs to use `postMessage` to send `open` command to the open client.

**Comment by miguelsaldivar** [comment]
Can I give this a go, and can you elaborate a bit more on what you want added 😄

**Comment by xPaw** [comment]
Here you need to pass `#chan-xxx` to the url (it's already stored in notification data as `tag`.
https://github.com/thelounge/lounge/blob/40722601a20ebea0272b61ee072fe4b6a4da75a3/client/service-worker.js#L52

There's also separate line that *focuses* the channel if page is already open, in that case I'm not entirely sure what needs to be done to open correct channel.
