### ISSUE TITLE
Auto reconnect

### ISSUE THREAD

**Issue by ssk2** [thelounge/lounge#1557]
I use Lounge on my laptop and frequently move between meetings, suspending and resuming my laptop. Typically it'll disconnect when I suspend and then fail to connect when I resume. I normally go back to the tab and then realise that it has disconnected. It'd be helpful if there was a mechanism to automatically reconnect when able to (or to periodically retry).

**Comment by xPaw** [comment]
It's coming in next version.

**Comment by ssk2** [comment]
That's great to hear, thanks @xPaw.

**Comment by varac** [comment]
Is this feature already implemented in current release version ?

**Comment by xPaw** [comment]
Why are you commenting on random issues? Either test it yourself on latest release, or join the IRC channel to ask about stuff.

**Comment by varac** [comment]
I'm not commenting on random issues, I seek for clarification on the exact issue which addresses my problem.
If the context would be clear to me I wouldn't have asked. Wonder why you make such a fuss about it instead of simply clarifying.
