### ISSUE TITLE
Fonts are huge after 3eaf12

### ISSUE THREAD

**Issue by Zbob750** [thelounge/lounge#1558]
[This commit bumped font sizes](https://github.com/thelounge/lounge/commit/3eaf12cc36400f6698286dda8c9200cf546d6104) and, in my opinion, you've gone to the extreme.
On Desktop it feels just a little big, but really not anything that should cause problems. However, on mobile this change impacts usability. It has diminished the amount of content that fits on screen. 

<img src=https://i.imgur.com/cdgdv3F.png width=300>

In my opinion, this change is unnecessary on the desktop and hurtful to mobile.
I would like to see the change just reverted. I realize that CSS can be used to alter this for my own personal tastes, however I really don't think I should need to maintain a theme to make the mobile client show more information. I also think that many people who upgrade from the current release to the upcoming release will find this change jarring.

Thanks

**Comment by astorije** [comment]
> However, on mobile this change seriously impacts readability. The change has seriously diminished the amount of content that fits on screen.

I understand about the reduced amount of content (though 25 lines as shown on your screenshot is still more than what Telegram would show you for example) but readability _is_ better as it is right now, as in it's less hard to read.

I'm going to run some more tests to tweak the current size, but I am certainly against a simple revert.

**Comment by astorije** [comment]
Resolved by #1561.
