### ISSUE TITLE
Feature request:  Allow non-interactive user creation.

### ISSUE THREAD

**Issue by MatthewDwyer** [thelounge/lounge#1560]
When I add a new user to The Lounge, the password entry is interactive only.  I have not found a way to provide the password as part of the command line.  Am I missing something?

**Comment by astorije** [comment]
Hi @MatthewDwyer!

It is indeed not possible (nor desired security-wise) to enter the password on the command line.
This was already suggested in https://github.com/thelounge/lounge/issues/353, and I believe that will give you a good overview of the consequences of doing so, as well as alternatives to create users non-interactively :)

Hope that helps!
