### ISSUE TITLE
Image prefetch: Abort if Content-Length exceeds maximum

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#1563]
Discussion in #1554 got me to look at the link prefetch code for images, which I had assumed would not try to fetch images in excess of the configured `prefetchMaxImageSize`. Apparently, the code instead fetches image data until either the response ends (the image size is below the limit) or the buffered data exceeds the limit (at which point the request is aborted).

With the default maximum image size now being 2MB (as of #1490), that means potentially 2MB of "wasted" network traffic every time a link to an image bigger than the limit is received. I'm not sure when the response headers become available (and #1554 will change how the code works anyway), but I do think it would be sensible to abort the request as soon as possible if the `Content-Length` header indicates that the image exceeds the limit, in the interest of using bandwidth as efficiently as possible on both The Lounge's end and on the image host's end.

_Edited to add:_ I'm interested in tackling this after #1554 lands (and likely after 2.5.0 stabilizes), if the idea is approved. I'm not just idly demanding it :laughing:

**Comment by xPaw** [comment]
This can be handled in `response` callback which is unaffected by that PR.
https://github.com/thelounge/lounge/blob/f85686bcb247dcd59b8bbe195f204f82a6f723ad/src/plugins/irc-events/link.js#L161-L167

Maybe along with aborting we should start emitting errors "Image is too big, not displaying preview".

**Comment by astorije** [comment]
> Maybe along with aborting we should start emitting errors "Image is too big, not displaying preview".

I wish I kept my commit doing that 😅
