### ISSUE TITLE
Auto reconnect doesn't change where the unread markers are

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#1571]
Reproduction steps:

1. Open page A
2. Remove connection from page A to server
3. Open page B (ensure page A still isn't connected, so you'll probably need to use another computer
4. Read some messages on page B for channels that had unread messages on page A
5. Wait for some new messages on those channels (without reading them)
6. Reconnect page A

What should happen: unread marker moves to the newest "unread" message
What actually happens: unread marker stays where it was, but the number of unread messages in the channel sidebar changes to the correct number

**Comment by xPaw** [comment]
Gotta add unread marker syncing in this block: https://github.com/thelounge/lounge/blob/90ae5dbefc3a5864e11d200e3c9fa905e0dab0e6/client/js/render.js#L191-L210

**Comment by astorije** [comment]
Pretty sure we should make this part of v2.5.0, no?
