### ISSUE TITLE
"init" does heavy cloning on the server

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1575]
Every chan object is cloned in `toJSON`. And on reconnection the entire network is deep cloned to implement lastMessage.

https://github.com/thelounge/lounge/blob/da31317156047000819fa0363c435005104aa572/src/server.js#L435-L437
https://github.com/thelounge/lounge/blob/da31317156047000819fa0363c435005104aa572/src/models/chan.js#L129-L130

**Comment by astorije** [comment]
I read on the channel it's more noticeable now. Would that need to be fixed v2.5.0? Totally fair if it does.
