### ISSUE TITLE
CSS: Separator between nick and message is a bit off

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/lounge#1581]
I just updated to da31317 and noticed that using the morning theme, said separator is not a continuous line anymore, hence messages start at different x offsets:

(increased contrast to make separator more visible)
![image](https://user-images.githubusercontent.com/2070503/30969356-688ea71c-a462-11e7-93de-6e94610132c7.png)

Apparently this happens due to different timestamp widths (if it contains many 1's, it's narrower, making the following elements (nick, message) more indented or less, especially visible here:
![image](https://user-images.githubusercontent.com/2070503/30969714-82cd1824-a463-11e7-935b-3aba01a829de.png)

This can be verified by looking at the computed element dimensions of the timestamp element in web inspector.

Tested on Chrome, Firefox and Vivaldi on Mac.

**Comment by astorije** [comment]
This was introduced by #1540 and I remember now why I stopped when I played with native font stack a while ago. Lato had fixed width for numbers if we had kept it (and I'm not saying we should have, I'm very happy with native stack!).
Actually, are you using a custom font, @Jay2k1?

Apart from giving a fixed width to the time column, I'm not sure what alternatives we have. Thoughts?
By the way, totally a candidate for v2.5.0 :/

**Comment by Jay2k1** [comment]
Nope, just using the morning theme, no custom font. I actually disabled my custom CSS to test before filing the bug, just to be sure.

And I agree that this should be fixed somehow before release.

**Comment by astorije** [comment]
@Jay2k1, by "native font stack", we refer to using the system font of your OS, see [this](https://github.com/thelounge/lounge/pull/1540/files#diff-97db1f70168fb5f12457b238ff6052b5R18).
This also means width will slightly differ based on OS, so relying on fixed width is a bit clumsy...

@xPaw, do you have any idea?

**Comment by xPaw** [comment]
@astorije set width on `.time` like it is set on `.from`.
