### ISSUE TITLE
New messages line disappears occasionally

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#1582]
When loading a channel with new messages, I'm occaisionally seeing the "New Messages" heading, but not the line that goes along with it. If I switch to another channel and wait for new messages in that one again, the line is still not there. It won't come back until a refresh, but then it'll start happening with other chans. Not sure what causes it in the first place.

Example: ![](https://files.yamanickill.com/KRJhr34e.png)

**Comment by xPaw** [comment]
This happens when zooming the page down. It rounds the 1px border down and that hides it.

**Comment by YaManicKill** [comment]
> It rounds the 1px border down and that hides it.

Sometimes. Not all the time. It's a very odd bug.

**Comment by astorije** [comment]
If that's a zooming bug, then it's a browser bug and there isn't much we can do about it, no?

**Comment by xPaw** [comment]
Yeah this is browser behaviour, there is not much we can (or should) do.

**Comment by YaManicKill** [comment]
Yeah, fairynuff. I'll write up a plugin to make it become less of an issue by making the line thicker once I've finished #1447
