### ISSUE TITLE
Highlight with user mode prefixes

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#159]
Sometimes people who are new to IRC copy the entire display nick they see, including the mode symbol, as some clients show it in the nick list (including The Lounge, at least when using zenburn). I've gotten my fair share of HLs as `+dgw` or `@dgw`.

The Lounge already strips out `@` when checking for highlights, but IMO it should ignore any symbol listed in `PREFIX` sent with 005 ISUPPORT numeric by the server (commonly `+%@`, often also `&~`).

This does directly contradict #158, but my own IRC experience has shown that a not insignificant number of highlights could be missed if mode prefixes are not ignored.

**Comment by astorije** [comment]
That's a good point. I have to admit I thought of that when opening #158...
Is it easily possible to know what is the "moded" nick on a specific channel? For example, mine would be "+astorije" on #thelounge (also highlighting on "astorije"), "astorije" on #shout-irc, ... That would offer a more fine-grained control on highlights, and you would not be highlighted with +dgw unnecessarily on channels where you're not voiced.

**Comment by dgw** [comment]
Well, `PREFIX` actually looks something like `PREFIX=(vhoaq)+%@&~` (as on Rizon). Taking the contents of the parentheses as the modes, discarding the parentheses themselves, and using the remaining characters as the prefixes, the character indexes of the modes and prefixes line up. The first mode is represented by the first prefix symbol, etc.

That said, I'm not sure it's worth worrying about unnecessarily highlighting on the "wrong" prefix character. In all likelihood, the incidence of that will be so low as to be irrelevant. It does make a good long-term goal, though. I just poked through the code a bit and it doesn't look that trivial to figure out what the user's mode is on the channel where the message came from. (Granted I have about 15 minutes' familiarity with this part of the code, so I might have missed something.)

**Comment by maxpoulin64** [comment]
As I discussed on IRC with xPaw already, we probably could also simply match nicks as long as it's surrounded by non-valid nick characters. This would not only match the modes, but also match it when colored or even wrapped like `(nick)` or `<nick>`.  It should be really easy with a regex, and I think that would cover a lot of cases. The only condition in which I think I shouldn't be highlighted is when my nick is part of someone else's nick (thus the check for non-nick characters).

**Comment by dgw** [comment]
Sounds good to me :+1:

**Comment by astorije** [comment]
I agree with what @maxpoulin64 said, good thinking!
I'll be that guy saying we should test our regexes :-P (And will help for that obviously!)
