### ISSUE TITLE
Custom highlights

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#160]
So, I wrote a PR for shout and it never got merged in. I should bring the code over and tidy it up and create a PR.

I'll take this one.

**Comment by shazeline** [comment]
@YaManicKill - any plans on picking this up soon? I trialled your branch when I used to use shout and thought it was a great feature.

**Comment by maxpoulin64** [comment]
@shazeline That was part of the things I wanted to implement once #275 is done. I still have some things to move around in that PR, but that should make a lot of configurable features like this one very easy to implement.

**Comment by shazeline** [comment]
Hey @maxpoulin64 . Is #275 still being worked on? 

This is the last real feature I'm looking for so I can make lounge my default IRC client. If you think it could still be some time, please let me know so I can create a dev branch from [this](https://github.com/erming/shout/pull/580) and run that for the time being.

**Comment by maxpoulin64** [comment]
@shazeline: actually, #425 is merged if the custom highlights are what you want. But yes, it's still being worked on but it will take some time as I'm basically rewriting a lot of the core of Lounge for it as part of #444.

Since #425 is merged, I will close this issue.

**Comment by shazeline** [comment]
Awesome. Just ran master locally and it looks great! Thanks a bunch @YaManicKill and @maxpoulin64
