### ISSUE TITLE
mysql uri causes crash

### ISSUE THREAD

**Issue by ElizabethIsAwesome** [thelounge/lounge#1618]
Someone pasting `removed` will cause thelounge to crash, and won't even launch if it's in the log. Even with preloading disabled, it will affect clients. Required me to remove the line from my logfiles before it would even launch again.

**Comment by MaxLeiter** [comment]
Please remove the URI from the issue... (also, fwiw, I cant repro on master)

**Comment by ElizabethIsAwesome** [comment]
I'm using latest version supplied via npm if that makes any difference

**Comment by dgw** [comment]
Version 2.4.0 or `next` (2.5.0 rc)?

Would be interesting if this is somehow related to urijs. @xPaw mentioned a possible crash fix by updating the library in #1604.

**Comment by xPaw** [comment]
So I just tested it, it's not reproducible on master (so we fixed it as a side effect), but is indeed reproducible on 2.4.0, and #1604 should help prevent such issues in the future.
