### ISSUE TITLE
Remove moment.js

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#162]
We only use it to format `HH:mm` and `HH:mm:ss`, completely unnecessary to use a library for that.

**Comment by YaManicKill** [comment]
:+1: 

Moment is a great library if dealing with loads of dates and stuff, but we aren't, we are dealing with 1 date.

**Comment by lindskogen** [comment]
Currently, the main reason for keeping it are for timezones, it saves the current time with the message as UTC and converts it into local time on the client. As long as this functionality is kept intact, I'm all for it!

**Comment by astorije** [comment]
#183 removed Moment.js on the client. @xPaw, do you want to close this issue due to #183 having shipped or are you also planning on removing it on the server?
I'd vote for closing this issue as getting rid of Moment.js on the server is not a priority or in progress (I believe) right now.
