### ISSUE TITLE
Whitelist IPs that can send X-Forwarded-For header

### ISSUE THREAD

**Issue by xnite** [thelounge/lounge#1622]
While configuring nginx to forward traffic to a set of remote lounge instances, I realized then when accessing those instances directly I could set my own IP through the X-Forwarded-For header.

I'm not sure if I'm just missing something or the feature doesn't exist, but it would be nice to be able to white list IP addresses that are allowed to send the X-Forwarded-For header.

**Comment by xPaw** [comment]
Why don't you just make lounge listen on localhost or unix socket? That would solve the problem.

**Comment by spangborn** [comment]
Shouldn't your instances not be accessible except through nginx? This seems like a configuration issue.

**Comment by xnite** [comment]
@xPaw Yes I have done that, but even behind nginx if you don't overwrite X-Forwarded-For and X-Real-IP both, then it will allow this to happen. It's very easy to misconfigure.

**Comment by xPaw** [comment]
If you don't set `X-Forwarded-For` in nginx but enable `reverseProxy` in Lounge that is entirely on the admin, and whitelist will not help.

**Comment by xnite** [comment]
@xPaw true, and bad example. What about load balancing setups (such as cloudflare loadbalancing) where you have no choice but to use remote? There is no IP connection whitelisting, or x-forwarded-for white listing.

**Comment by xPaw** [comment]
I would just recommend using a web server in front of Lounge if you want more advanced filtering and whitelisting. `reverseProxy` exists with that in mind, that it would be behind a proper server that can handle it for us.

I just don't think it's worth it doing IP filtering in Lounge.
