### ISSUE TITLE
On slow devices, message pre loading causes login to time out

### ISSUE THREAD

**Issue by kode54** [thelounge/lounge#1630]
On my iPad mini 2, using my crappy WiFi link, the login to my personal instance, which is connected to just over 120 channels across a dozen servers, times out every time it reaches the “rendering” state. I can see the channel list and unread message counts if I pull the left side into view. Using 2.5.0-rc.5.

**Comment by dgw** [comment]
Sounds very similar to #1574, which was closed as duplicate of #1145. (This is a known issue.)
