### ISSUE TITLE
Broken edit CLI command

### ISSUE THREAD

**Issue by JocelynDelalande** [thelounge/lounge#164]
```js
$ ./index.js edit testuser

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by MaxLeiter** [comment]
Any information on how to reproduce this? Did you create "testuser"?

**Comment by astorije** [comment]
Why `$ ./index.js edit testuser` and not `$ lounge edit testuser` as in the doc: https://thelounge.github.io/docs/server/users.html ?

**Comment by JocelynDelalande** [comment]
> Why `$ ./index.js edit testuser` and not `$ lounge edit
> testuser` 

As I'm not using global install (but I don't think it change
anything, and all other commands work well that way).

Did you try to reproduce without success ?

**Comment by maxpoulin64** [comment]
It would seem that it tries `EDITOR` and then `vi` if it's not set, and fail if you don't have vi installed: https://github.com/thelounge/lounge/blob/master/src/command-line/edit.js#L18

I'm not sure how we could handle this apart from trying a bunch of editors. Any ideas? As a workaround you can set your `EDITOR` environment variable (`export EDITOR=nano` in bash/zsh).

**Comment by JocelynDelalande** [comment]
> It would seem that it tries EDITOR and then vi if it's not set, and fail if you don't have vi installed: https://github.com/thelounge/lounge/blob/master/src/command-line/edit.js#L18
> 
> I'm not sure how we could handle this apart from trying a bunch of editors. Any ideas? As a workaround you can set your EDITOR environment variable (export EDITOR=nano in bash/zsh).

Will do further testing. The issue IMHO is more that we should fail gracefully, and not with a stacktrace…

@maxpoulin64 may be a stupid question but… Does the edit command works at all for you ?

**Comment by maxpoulin64** [comment]
Yes it works fine for me, but I have my `EDITOR` variable set to nano already and I have vi installed as well.

**Comment by xPaw** [comment]
By the way, this command doesn't work on Windows too, and I don't think it will the way it's done.

**Comment by JocelynDelalande** [comment]
> Yes it works fine for me, but I have my EDITOR variable set to nano already and I have vi installed as well.

Ok, troubleshooted a bit more. The issue is when there are arguments passed to the EDITOR, the crash seems reproducible with :

    EDITOR='nano -w' ./index.js edit test

Working on a patch.

**Comment by JocelynDelalande** [comment]
> Yes it works fine for me, but I have my EDITOR variable set to nano already and I have vi installed as well.

vi is part of the Linux Standard Base and iirc is installed default on OSX, so except for Windows, falling back on vi is a sane default IMHO (still, we should fail nicely if it cannot be found).

**Comment by MaxLeiter** [comment]
Can't duplicate this, is anyone able to or can this be closed?

**Comment by xPaw** [comment]
This command relies on `vi` being installed, so it definitely can fail.

**Comment by MaxLeiter** [comment]
I don't see a way to fix it - there isn't one editor all OS's have. At least it attempts to use $EDITOR before defaulting to vi.

**Comment by xPaw** [comment]
It should gracefully print a message, not crash.
