### ISSUE TITLE
Tab-Complete for nickname postfix

### ISSUE THREAD

**Issue by radosroka** [thelounge/lounge#1640]
Hi,

it would be nice to have tab completion with some postfix that can be customized.

e.g. :

I want to type nickname "rsroka" so I will type "rs" and press TAB. Lounge will complete it to "rsroka".
I want to set postfix " :" or ", ". So Lounge should complete "rsroka :" or "rsroka, ".

**Comment by xPaw** [comment]
Duplicate of #1176.
