### ISSUE TITLE
:-P should not trigger emoji autocompletion 

### ISSUE THREAD

**Issue by starquake** [thelounge/lounge#1648]
When you type something like this you will get autocompletion, which I think is annoying in this case. Especially at the end of a sentence.

`Well that was fun :-P`

You get this:
![image](https://user-images.githubusercontent.com/1044544/31726107-58425362-b426-11e7-8aa0-f3e5a126d1ca.png)

How should this be handled? Ignore anything beginning with :- ?

I can give it a go at fixing.

**Comment by YaManicKill** [comment]
> Ignore anything beginning with :- ?

Can't do this, as @xPaw mentioned there is :-1: which would be broken by this.

An easy fix for this particular one is to change the emoji on that on to "non_potable_water" which would fix this, but that won't fix any future ones.

We need to discuss whether using `enter` to select an emoji is the right way to do things, or whether it should be `tab` instead. Also, whether we should change to the actual unicode emoji, or whether we should change to the textual representation, making it potentially easier to remove the characters that we don't want, and we replace it with the emoji on send.

**Comment by starquake** [comment]
I would argue `enter` is the right way to select an emoji. Here's a list of applications that uses enter to select something from an autocompletion list:

- Visual Studio Code
- The GitHub website
- Office Teams (Skype for business)
- JIRA
- Telegram
- Whatsapp Web
- Twitter
- Discord

Which made me wonder. Why is this not an issue in those apps? Discord changed to "non_potable_water"

So here are some thoughts. Maybe we should add an autocompletion blacklist? It looks like that is how GitHub works. And I don't think :-P should ever be replaced by a unicode emoji. You could make it an option though.

**Comment by xPaw** [comment]
#1651 changes shorthands to not include dashes.
