### ISSUE TITLE
Background tab activity not changing favicon

### ISSUE THREAD

**Issue by BradCOnGitHub** [thelounge/lounge#1652]
I upgraded from 2.4.0 to 2.5.0 last night. Yesterday if there was any activity in the channel while the tab was in the background the favicon would change to a red version. Today this doesn't happen anymore.

Did this functionality go away with the new notification options that were added in 2.5?

**Comment by dgw** [comment]
I just tested this on my 2.5.0 instance with a delayed highlight from a bot. The notification sound played in the background, and the tab's favicon turned red.

What settings are you using?

**Comment by BradCOnGitHub** [comment]
OK, I see what happened now. I'll post it here in case anyone else stumbles across the issue.

I turned on the new browser notifications and was getting spammed with popups for every message in the channel because I had "Enabled notifications for all messages" turned on. So I turned that off and added some keywords for stuff I wanted popups for. I did not realize this would also disable my changing favicon color since that's just another aspect of being notified.

I guess maybe you could call this a feature request for the two notification types to have different settings.
