### ISSUE TITLE
Whois results in double info listing in new query

### ISSUE THREAD

**Issue by kode54** [thelounge/lounge#1658]
I am running 9b065608990f5673cfb82d45d1ffb44189500cd0 plus #1631 merged into a temporary branch. Clicking on someone's name, or using /whois on them, results in a fresh query with two listings of the whois info. I traced the server<->znc and client<->server traffic:

S-Z: `WHOIS MiniDigger MiniDigger`
Z-S: `:orwell.freenode.net 311 kode54 MiniDigger ~MiniDigge some.random.host.cause.default.is.boring.minidigger.me * :Martin`
Z-S: `:orwell.freenode.net 319 kode54 MiniDigger :#thelounge`
Z-S: `:orwell.freenode.net 312 kode54 MiniDigger orwell.freenode.net :Amsterdam, NL, EU`
Z-S: `:orwell.freenode.net 330 kode54 MiniDigger MiniDigger :is logged in as`
Z-S: `:orwell.freenode.net 318 kode54 MiniDigger :End of /WHOIS list.`
S-C: `["join",{"shouldOpen":true,"network":9,"chan":{"type":"query","name":"MiniDigger","id":229,"messages":[],"key":"","topic":"","firstUnread":0,"unread":0,"highlight":0,"users":[]}}]`
S-C: `["msg",{"chan":229,"msg":{"type":"whois","whois":{"nick":"MiniDigger","user":"~MiniDigge","host":"some.random.host.cause.default.is.boring.minidigger.me","real_name":"Martin","channels":"#thelounge","server":"orwell.freenode.net","server_info":"Amsterdam, NL, EU","idle":"2995","logon":"1506486847","account":"MiniDigger","idleTime":1508627362816},"from":"","id":359548,"previews":[],"text":"","self":false,"time":"2017-10-21T23:59:17.816Z"}}]`
S-C: `["open",229]`
S-C: `["more",{"chan":229,"messages":[{"type":"whois","whois":{"nick":"MiniDigger","user":"~MiniDigge","host":"some.random.host.cause.default.is.boring.minidigger.me","real_name":"Martin","channels":"#thelounge","server":"orwell.freenode.net","server_info":"Amsterdam, NL, EU","idle":"2995","logon":"1506486847","account":"MiniDigger","idleTime":1508627362816},"from":"","id":359548,"previews":[],"text":"","self":false,"time":"2017-10-21T23:59:17.816Z"}]}]`

Somehow it's receiving both the initial msg of the query contents, as well as triggering a "more" data request?

**Comment by xPaw** [comment]
That's #1631 causing it, comment there instead.
