### ISSUE TITLE
Only the first nick is displayed when multiple people are Opped/Voiced

### ISSUE THREAD

**Issue by lpoujol** [thelounge/lounge#166]
When multiple users are opped/Voiced/deoped/Devoiced, only the nick of the first person is displayed. :/

<img width="485" alt="capture d ecran 2016-03-08 10 00 17" src="https://cloud.githubusercontent.com/assets/110898/13596743/af9c4e34-e514-11e5-97e1-931d9c7152f6.png">
Meanwile on an other IRC client (Hexchat here)
<img width="522" alt="capture d ecran 2016-03-08 10 00 02" src="https://cloud.githubusercontent.com/assets/110898/13596744/b13b6db0-e514-11e5-9d3b-0547864b06a2.png">

**Comment by dgw** [comment]
I'm guessing this is related to either the handlebars template or slate-irc. Probably the template.

**Comment by maxpoulin64** [comment]
From what I hear from xPaw on IRC it's apparently fixed with the move to irc-framework :)

**Comment by dgw** [comment]
That would make it a slate-irc issue, then. Let's look forward to xPaw's work on switching over. :)
