### ISSUE TITLE
Longer nicks overflow on two lines, redux

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#1667]
As of v2.5.0, nicks in the user list may wrap onto a second line:

![image](https://user-images.githubusercontent.com/164140/32132690-cecdf590-bb8d-11e7-8fea-9d781faf1abc.png)

It appears that this only occurs with long nicks containing hyphens; I was unable to reproduce with any other non-alphanumeric characters allowed in nicks.

(Redux because #577 covered a similar issue already for the chat view.)

**Comment by LFlare** [comment]
Attempting to fix this in #1671...
