### ISSUE TITLE
Make index.html static, send defaults over WS

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1672]
Currently index.html is rendered on the server with handlebars, which is rather unnecessary, this also leaks `defaults` from config in private mode.

Making index.html static would also completely remove client dependency on the server.

Related to #1055

**Comment by MaxLeiter** [comment]
Worth doing with #1271 somewhat around the corner?

**Comment by xPaw** [comment]
Both of them are kinda tied to each other.
