### ISSUE TITLE
Clicking on a username in a query window outputs userinfo again as new messages.

### ISSUE THREAD

**Issue by creesch** [thelounge/lounge#1674]
## Steps 
1. Click on a user in a regular window for which no query window is open.
2. After the query window opens click on the username. 

## Expected 
Nothing happens as we already have a query window open so the conversation is already ongoing. 

## Actual 
The user information is shown again. 

![image](https://user-images.githubusercontent.com/2502190/32232207-d2c3a560-be57-11e7-84bc-86b9b8758c13.png)

## Impact 

I'd say the impact is rather low, it mostly confused me on mobile as it is easier to accidentally click on a user in chat there than on desktop. 
When this happens in a channel and it opens up a window with the user it is clear what happend. 
In this case when that window is already open it just is confusing, I personally thought at first that I found a bug with how the backscroll is loaded.

**Comment by xPaw** [comment]
Are you using #1631?

**Comment by creesch** [comment]
No, I use the npm installed version. Also I am not entirely sure if they are related as it isn't technically a duplicate message, from what I can see what happens is that lounge simply sends another query and pastes the response back into already existing window. 

I guess what I am specifically saying is that when a username is clicked for which a query window is already open lounge should simply switch to that window instead of sending out query again.

**Comment by xPaw** [comment]
Ah yes, this kinda works as expected.

#533 is kinda related here.

**Comment by creesch** [comment]
Right, I see. As I said it is a rather low impact thing but since it works slightly different from how other client do this it confused me for a moment. 

I totally understand that there are higher priority things to work on.

**Comment by YaManicKill** [comment]
> Ah yes, this kinda works as expected.

Sure, it's what we know happens. But that doesn't mean it should do it. It clearly shouldn't, it's such a weird UX thing.

**Comment by creesch** [comment]
Actually, now that I had a look at it a bit more (and saw ot is whois and not query command)  I think it isn't even correct. It means that every time I click on someone it sends out a whois even though I do not intend to do so.

On most networks this isn't really an issue except that soms IRCds notify users if a whois is done on them. (I think that unrealIRCd does this with certain user modes). Meaning that every time I accidentally click on someone they'll get notified.

Wouldn't it be better to offer users a choice of what they want to do when they click another user's name? Similar to how irccloud does this for example. Out the top of my head when clicking a user there you get a pop-up with 

- Username 
- Hostmask
- Whois
- Send message 
- Invite 
- Ignore

And if applicable also OP related things like op, voice, kick, ban, deop.

I realize I just expanded the scope hugely and I wouldn't be surprised if this already has an issue but figured I'd mention it anyway.

**Comment by creesch** [comment]
So I just found out that right clicking on a channel or user shows a context menu. 

https://github.com/thelounge/lounge/blob/15e9ea5001420fa08466335f4abc1fe9558939ec/client/js/lounge.js#L77

Which from what I can gather is actually intended for what I propose. To me it makes sense to do maybe one of the following things: 

1. Change this [this bit of code](https://github.com/thelounge/lounge/blob/15e9ea5001420fa08466335f4abc1fe9558939ec/client/js/lounge.js#L287) to open the context menu on click and include whois as one of the options. 
2. At the very least add the proposed actions to the context menu so people have a choice. This works sort of fine for desktop users but leaves the menu out of reach for mobile users. 

Personally I am thinking 1. makes most sense, the context menu is already accessible in other areas through left click so.

**Comment by creesch** [comment]
I did some work on this earlier today to see how easy it would be to implement this. Resulting in this 

![image](https://user-images.githubusercontent.com/2502190/32275634-4a6355ca-bf0c-11e7-9164-94e3f7575764.png)

Where whois and conversation work. The OP related actions do not yet work. 

@YaManicKill & @xPaw would this be something worthwhile for me to develop a bit further and put in a pull request?

**Comment by MaxLeiter** [comment]
I had a PR for kick / ban - https://github.com/thelounge/lounge/pull/348

One major issue is banning should be by hostname, which the client can't get. Additionally, banning does not kick, so at the time we added a Kickban option.
However, I think we can make ban kick as that's what most users will expect.

**Comment by creesch** [comment]
Interesting, how did you handle context for showing those options?

**Comment by MaxLeiter** [comment]
What do you mean by context?

**Comment by creesch** [comment]
Well not everyone has the permissions to kick or ban people, so it doesn't make sense to show the options where they cannot be used.

**Comment by MaxLeiter** [comment]
I didn't get that far -- the reason I closed the PR was due to lack of information being available client side, like hostnames and op status.
