### ISSUE TITLE
Handling empty queries

### ISSUE THREAD

**Issue by realies** [thelounge/lounge#1675]
Sending an empty `/query` creates a new empty PM. Assuming this is not the expected behaviour.

**Comment by creesch** [comment]
Empty as in `/query nickname` or just `/query` ? because with a nickname that is expected behavior as that signals the start of a conversation (it is actually the difference between `query` and `msg` afaik).

**Comment by realies** [comment]
@creesch, empty as in just `/query`

**Comment by creesch** [comment]
Odd, I asked because I couldn't replicate.

**Comment by realies** [comment]
Odd, it happened earlier on when I autocompleted a `/query` and pressed enter. Now it only seems to happen if I send a space character after it.

**Comment by xPaw** [comment]
Just need to check length here and tell user to enter a name if length is zero.

https://github.com/thelounge/lounge/blob/15e9ea5001420fa08466335f4abc1fe9558939ec/src/plugins/inputs/query.js#L14

**Comment by realies** [comment]
Will #1676 going to handle empty characters? Isn't [`args.length`](https://github.com/thelounge/lounge/blob/master/src/plugins/inputs/query.js#L10) supposed to prevent this?
