### ISSUE TITLE
Change add <user> to allow updates, if user already exists

### ISSUE THREAD

**Issue by abrahamvarricatt** [thelounge/lounge#1686]
When updates are posted to thelounge, I run an automated script to create a new user. It will be useful to modify the add user command with the following,

* pass along password as an optional CLI argument (similar to mysql -u -p command)
* just update password if the user already exists, but leave other options intact

NOTE: I have a patch for this and will be updating this soon.

**Comment by astorije** [comment]
Hi there @abrahamvarricatt!

Just FYI, if you look at https://github.com/thelounge/lounge/issues/353, you can see why we do not wish to pass the password as a CLI argument (tr;dr security).

**Comment by xPaw** [comment]
This seems like a very niche use case, you should update your scripts to do what you want instead of modifying the `add` command. There is a `reset` command which does what you want -- change the password.

**Comment by astorije** [comment]
Closing this until we have more details, see https://github.com/thelounge/lounge/pull/1687#issuecomment-346229124 for info.
