### ISSUE TITLE
History not shown after restart (but present in logs)

### ISSUE THREAD

**Issue by gertvdijk** [thelounge/lounge#1710]
Running a 2.5.0 server with docker image `thelounge/lounge:2.5.0-alpine`, using a volume for data. Enabled logs. To reproduce:

1. Connect to an IRC server as a user.
2. Observe logs are written to disk.
3. Restart server while still logged in.
4. Refresh client web browser.
5. All history inaccessible from webinterface. Observe that logs on server disk are present, content of both before and after the restart.

I don't see why the logs aren't shown in the web interface. Is that a missing feature or a bug what I'm looking at?

**Comment by MaxLeiter** [comment]
Known problem, reading from logs/keeping history on restart isn’t implemented. There are a few PRs working towards this/

**Comment by xPaw** [comment]
#663
