### ISSUE TITLE
Sending channel and link together generates duplicate text

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1718]
Sending `#test-https://google.com` generates `#test-https://google.comhttps://google.com`

HTML:
```html
<span class="inline-channel" role="button" tabindex="0" data-chan="#test-https://google.com">#test-https://google.com</span><a href="https://google.com" target="_blank" rel="noopener">https://google.com</a><button class="toggle-button toggle-preview  opened" data-url="https://google.com" aria-label="Toggle website preview"></button>
```

cc @Bonuspunkt, any idea?

**Comment by Bonuspunkt** [comment]
yes

- channel and url pattern matches.
- the simple concat is non sufficient for this case ( https://github.com/thelounge/lounge/blob/master/client/js/libs/handlebars/parse.js#L66-L68 )

what would be your expected result?

**Comment by xPaw** [comment]
I guess simpler solution would be consider entire thing a channel and not detect the url (intersection?), but this still has to work for colors and stuff like that.

**Comment by Bonuspunkt** [comment]
https://github.com/Bonuspunkt/ircmessageparser/commit/23986736f52444fc24a2f6d9bdf08eeb0fe2eb51

**Comment by xPaw** [comment]
@Bonuspunkt Could you make a PR with that please?
