### ISSUE TITLE
Multiple 'New message' markers appearing

### ISSUE THREAD

**Issue by PolarizedIons** [thelounge/lounge#1721]
Running 56a9ad1 when it happened, not sure what caused it, or how to reproduce. It's a pretty recent commit, so @xPaw didn't think it would be fixed yet, so making this issue. 

They appear in the correct position (ie. before new messages), but way too many of them. When clicking on the channel again they are all at the bottom, and not hidden. Will update when I can reproduce it.

![image](https://image.prntscr.com/image/wb522hD6Q1ehbXNH2pAw3A.png)

**Comment by metsjeesus** [comment]
I got same result when i was connected with PC and tablet. And only when i registered push notification on tablet. Getting private message ended up both PC and tablet lounge having new message spam.

**Comment by gl-sergei** [comment]
Noticed the same recently

<img width="649" alt="screen shot 2018-01-22 at 02 22 10" src="https://user-images.githubusercontent.com/371194/35198049-7d1a0c26-ff1b-11e7-84be-4ba84d15984f.png">

There is another issue which may be related. When I switch to the channel which has like 200 unread messages and it keeps rolling, the "New messages" marker won't be set correctly. It will be set to the first untrimmed message in the channel. However, if the channel is idle, the marker will be placed correctly no matter how many times I need press button to load previous messages.
