### ISSUE TITLE
Performance issues with 2.5.0?

### ISSUE THREAD

**Issue by ssk2** [thelounge/lounge#1732]
Hi! I just upgraded to 2.5.0 and I've noticed that if I leave the tab open for a long amount of time, Chrome becomes sluggish. Closing the tab and re-opening solves the issue.

I'm running the latest version of Chrome: Version 62.0.3202.94 (Official Build) (64-bit), and macOS High Sierra (10.13.1). 

There doesn't appear to be anything obvious in the logs:
```
sunilsh@<host>:~$ docker logs -f sunilsh-thelounge
2017-11-17 01:08:52 [WARN] Referring to CSS files in the theme setting of /home/lounge/data/config.js is deprecated and will be removed in a future version.
2017-11-17 01:08:52 [INFO] The Lounge v2.5.0 (node 6.11.4 on linux x64)
2017-11-17 01:08:52 [INFO] Configuration file: /home/lounge/data/config.js
2017-11-17 01:08:52 [INFO] Available at http://:::9000/ in private mode
2017-11-17 01:08:52 [INFO] New VAPID key pair has been generated for use with push subscription.
2017-11-17 01:08:52 [INFO] User sunilsh loaded
``` 

Having just reopened my laptop for the first time in the morning, I don't see this problem - and the Chrome Task Manager entry looks pretty ordinary too:
![image](https://user-images.githubusercontent.com/355705/33140167-0b1a8042-cf64-11e7-917c-3360de5f4c87.png)

I'll check it again later when I experience this issue again.  Meanwhile, is there any other output I can check to see what might be the issue here?

Thanks!

**Comment by xPaw** [comment]
We've heard about this problem on IRC, and my conclusion so far is that this is a Chrome problem, and not Lounge.

Even from performance captures from devtools there is nothing visible that takes a long time. And even if it did, it would freeze the tab, but not the entire browser.

However we haven't been able to gather any meaningful information to create a Chrome bug report.

**Comment by astorije** [comment]
@ssk2, as a side note, you probably want to upgrade to v2.6.0 that was released a few days ago. That will not fix this issue though.

Maybe worth looking at the Chrome bug reports, maybe there is already an issue related to that?

**Comment by vectr0n** [comment]
Also seeing this behavior on Opera (49.0.2725.39) as well as Chrome (62.0.3202.94), running TheLounge 2.6.0.

**Comment by xPaw** [comment]
Can you guys test `master`? There's one particular fix that may help with the issue.

**Comment by vectr0n** [comment]
@xPaw sure no problem, I will report back anything I notice, usually takes 24+ hours before the browser crawls or locks up.

**Comment by xPaw** [comment]
This sounds like a related issue: https://bugs.chromium.org/p/chromium/issues/detail?id=765311

**Comment by vectr0n** [comment]
I am still seeing the same behavior on Opera (49.0.2725.39), Chrome (62.0.3202.94), and Firefox (58.0b6) running on Linux. All browsers will eat RAM like a memory leak is present, causing the degraded performance. I have checked out version [823ed01](https://github.com/thelounge/lounge/tree/823ed01) and see no difference over 2.6.0. Seeing as all three browsers have the same issue, I am not to confident it is an issue with all three browsers causing the same performance issues after TheLounge has been left open for 12-24 hours. If you guys need anymore info let me know.

**Comment by xPaw** [comment]
Are you seeing Lounge tab specifically leaking memory or browser itself?

Try taking memory snapshot in dev tools and check if you can see any offenders.

**Comment by vectr0n** [comment]
From what I have seen it's usually all the browser processes, but it only happens when TheLounge is left open for long periods of time. I will take a look into memory snapshots and if I figure it out I will report back, thanks.

**Comment by xPaw** [comment]
Thing is, if Lounge was leaking memory, it would be showing up specifically as lounge tab memory usage increasing, and not the whole browser.

I have seen a couple of memory leak bug reports for Chrome, specifically for Linux. It might be related. Very weird that you are also seeing this on Firefox though.

**Comment by vectr0n** [comment]
Ya that confused me as well, and even the fact it's their "new" browser I have installed. I still have a feeling it could be something in TheLounge, the browsers only eat RAM when TheLounge is left open, I can leave 30+ tabs open w/o TheLounge, no issues for days and days, so it's a bit confusing.

**Comment by vectr0n** [comment]
After checking out the procedure for a memory snapshot in Chrome, I have no idea what any of the info means, so I suppose I will deal with it for now and hope someone else with the knowledge can provide info. Thanks

**Comment by ssk2** [comment]
Chrome has since auto-updated to: Version 63.0.3239.132 (Official Build) (64-bit) and this problem is no longer occurring, so  will close this issue! Thanks for the assistance!
