### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by y-lohse** [thelounge/lounge#175]
Hi,
there seem to be encoding problems with the messages of some user. Certains characters like `é` or `ê` show up with `�` instead.
It's probably because those users are not using utf-8 enconding. The issue is likely to be the same as [this one](https://github.com/erming/shout/issues/279), and seems related to [this one from slate-irc](https://github.com/slate/slate-irc/issues/19).

**Comment by xPaw** [comment]
Might be fixed by #167

**Comment by xPaw** [comment]
Can you test current `master` and see if this issue is fixed?

**Comment by ErKaNs** [comment]
![ekran alintisi](https://cloud.githubusercontent.com/assets/1409558/15358374/c398c676-1d0c-11e6-8c89-bb9e89846523.PNG)

**Comment by xPaw** [comment]
@ErKaNs Is this on 1.5.0 or master?

**Comment by ErKaNs** [comment]
version 1.5.0

**Comment by xPaw** [comment]
This issue may be fixed on master, do you mind testing it? https://github.com/thelounge/lounge#development-setup

**Comment by ErKaNs** [comment]
when i use npm start
`0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.7.1
3 info using node@v0.10.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle thelounge@1.5.0~prestart: thelounge@1.5.0
6 silly lifecycle thelounge@1.5.0~prestart: no script for prestart, continuing
7 info lifecycle thelounge@1.5.0~start: thelounge@1.5.0
8 verbose lifecycle thelounge@1.5.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle thelounge@1.5.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/***/lounge/node_modules/.bin:/usr/local/bin:/usr/local/jdk/bin:/home/***/perl5/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11R6/bin:/home/***/bin
10 verbose lifecycle thelounge@1.5.0~start: CWD: /home/***/lounge
11 silly lifecycle thelounge@1.5.0~start: Args: [ '-c', 'node index' ]
12 silly lifecycle thelounge@1.5.0~start: Returned: code: 8  signal: null
13 info lifecycle thelounge@1.5.0~start: Failed to exec start script
14 verbose stack Error: thelounge@1.5.0 start: `node index`
14 verbose stack Exit status 8
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at EventEmitter.emit (events.js:98:17)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
14 verbose stack     at maybeClose (child_process.js:730:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:797:5)
15 verbose pkgid thelounge@1.5.0
16 verbose cwd /home/***/lounge
17 error Linux 2.6.32-573.7.1.el6.x86_64
18 error argv "node" "/usr/local/bin/npm" "start"
19 error node v0.10.4
20 error npm  v3.7.1
21 error code ELIFECYCLE
22 error thelounge@1.5.0 start: `node index`
22 error Exit status 8
23 error Failed at the thelounge@1.5.0 start script 'node index'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the thelounge package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs thelounge
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls thelounge
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by xPaw** [comment]
`node@v0.10.4` is way too old. You should upgrade.

**Comment by ErKaNs** [comment]
![2](https://cloud.githubusercontent.com/assets/1409558/15361608/d740f8ca-1d1a-11e6-8f0f-d7bafa396022.PNG)

**Comment by YaManicKill** [comment]
@ErKaNs When you post an image, could you give a little more information. This is like pulling teeth. Is that an image from running master, or are you still running 1.5.0? Have you updated node? etc, etc...

**Comment by ErKaNs** [comment]
> root@224hh8lrz [~]# node -v
v4.4.4
root@224hh8lrz [~]# npm -v
2.15.1

im use this
https://github.com/thelounge/lounge#development-setup

**Comment by YaManicKill** [comment]
@ErKaNs Is this still an issue on the latest version?

**Comment by astorije** [comment]
Lacking details, closing this. We can remove if this is an issue, but many things have changed since then.
