### ISSUE TITLE
Add an indicator to STATUSMSG

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#176]
Currently receiving a statusmsg opens a new query window, however #167 will fix that as irc-framework supports these natively. The only remaining problem is to somehow add a visual indicator showing that it was a statusmsg and not just a normal message.

**Comment by YaManicKill** [comment]
@xPaw Was this fixed with #167?

**Comment by YaManicKill** [comment]
So, I'll consider this bug closed, and we can have a discussion about how we **should** show these int he future. But the big bug (of a new private message everytime we got a message through) is fixed.

I don't think there is a nice solution to all of this...
