### ISSUE TITLE
Nick and modes for users when a message is sent, isn't kept

### ISSUE THREAD

**Issue by PolarizedIons** [thelounge/lounge#1765]
Everything looks fine if lounge is open while receiving messages, but after a reload, messages display the user's *current* mode and nick, even if they didn't have that nick or mode when the message was sent.

Running master (c9e340e)

before reload:
![](https://i.imgur.com/1eknyOP.png)

after reload:
![](https://i.imgur.com/MNRizDp.png)

**Comment by xPaw** [comment]
This happens because all messages were updated to send user object which is retrieved with `getUser`, but only it's reference is getting stored, not a copy.
