### ISSUE TITLE
lounge crashes on start when running TLS

### ISSUE THREAD

**Issue by mellowcandle** [thelounge/lounge#1786]
Dec 01 09:06:26 practical-trainings systemd[1]: Started The Lounge IRC client.
Dec 01 09:06:27 practical-trainings lounge[23984]: 2017-12-01 09:06:27 [INFO] The Lounge v2.6.0 (node 4.2.6 on linux x64)
Dec 01 09:06:27 practical-trainings lounge[23984]: 2017-12-01 09:06:27 [INFO] Configuration file: /root/.lounge/config.js
Dec 01 09:06:27 practical-trainings lounge[23984]: 2017-12-01 09:06:27 [INFO] Available at https://:::443/ in private mode
Dec 01 09:06:27 practical-trainings lounge[23984]: 2017-12-01 09:06:27 [INFO] User rfried loaded
Dec 01 09:06:31 practical-trainings lounge[23984]: node: ../src/util-inl.h:196: TypeName* node::Unwrap(v8::Local<v8::Object>) [with TypeName = node::TLSWrap]: Assertion `(object->InternalFieldCount()) > (0)' failed.

**Comment by mellowcandle** [comment]
Ubuntu 16.04 

node --version
v4.2.6

Installed lounge using npm

**Comment by xPaw** [comment]
That's a nodejs crash, we don't have any native code.

**Comment by mhrivnak** [comment]
I see a similar TLS-related crash on centos7 with 2.6.0. It works fine with 2.5.0. This is with nodejs-6.12.0-1.el7.x86_64 from EPEL and thelounge installed via npm.

This is on a linode VPS running kernel 4.9.68-x86_64-linode89

The process starts fine, but when I try to connect, the segfault happens immediately.

I'm using certs from letsencrypt. I don't know if it's related, but I previously encountered this problem when using 2.4.0: https://github.com/nodejs/node/issues/9551

But I was able to get around that by using ``cert.pem`` instead of ``fullchain.pem``, per this comment: https://github.com/nodejs/node/issues/9551#issuecomment-291585619

Log output:

```
Dec 17 19:10:09 herschel systemd[1]: Starting The Lounge IRC client...
Dec 17 19:10:09 herschel lounge[17423]: 2017-12-17 19:10:09 [INFO] The Lounge v2.6.0 (node 6.12.0 on linux x64)
Dec 17 19:10:09 herschel lounge[17423]: 2017-12-17 19:10:09 [INFO] Configuration file: /var/lib/lounge/config.js
Dec 17 19:10:10 herschel lounge[17423]: 2017-12-17 19:10:10 [INFO] Available at https://:::9000/ in private mode
Dec 17 19:10:10 herschel lounge[17423]: 2017-12-17 19:10:10 [INFO] User mhrivnak loaded
Dec 17 19:10:23 herschel kernel: node[17423]: segfault at 1 ip 00007f45647f1acc sp 00007ffc96027550 error 4 in libcrypto.so.1.0.2k[7f45646cd000+234000]
Dec 17 19:10:23 herschel systemd[1]: thelounge.service: main process exited, code=killed, status=11/SEGV
Dec 17 19:10:23 herschel systemd[1]: Unit thelounge.service entered failed state.
Dec 17 19:10:23 herschel systemd[1]: thelounge.service failed.
```

**Comment by xPaw** [comment]
Are you guys still seeing this crash? Have you tried updating to newer node version?

**Comment by mellowcandle** [comment]
When I updated to a newer node version the problem vanished.

**Comment by mhrivnak** [comment]
I still see the problem, now updated to nodejs-6.12.2-1.el7.x86_64

I'll investigate upgrading to a newer nodejs than ships with epel, which probably means the nodejs 8 software collection:

https://www.softwarecollections.org/en/scls/rhscl/rh-nodejs8/

**Comment by xPaw** [comment]
@mellowcandle Glad to hear that!

I'm gonna close this issue as there's not exactly much we can do on our side since it crashes in native library code.
