### ISSUE TITLE
Reconnect on lost IRC connection

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#18]
- All connection messages should be shown in server window
- Use exponential back off
- Do not reconnect on errors like "bad password"
- Re-join all previous channels
- Existing `chan.id` must be reused for networks/channels/query windows when reconnecting to maintain history.

**Comment by astorije** [comment]
Yes!

I would like some design being shared before starting coding though, because there are multiple ways we could deal with this IMO.

I would add "Re-join all previous channels" to the list btw.

**Comment by W7PEA** [comment]
as in bug #71
Any connection related log message should specifically state which connection by name.

close #71

**Comment by vectr0n** [comment]
Would be a great option to have available.

**Comment by nomadturk** [comment]
I concur.

Re-connect the networks and re-join all the channels.
Meanwhile keeping the backlog intact would be a great improvement.

When there's a disconnection due to X reason, I hate to re-connect, kill screen, restart it all the time and since I don't want to lose the backlog I don't want to automate this by means of monit or such either.

**Comment by williamboman** [comment]
If you run lounge with docker you could try adding

```
RUN curl https://gist.githubusercontent.com/williamboman/f5e7d5e7a851a54e474ec4fe0cde26ab/raw/fcc96a431451b8e639c59698c67374c7848e96af/0001-src-client.js-kill-process-on-disconnect.patch | git apply
```

to your Dockerfile and running your container with `--restart=on-failure`. I haven't tested this yet but I feel like it might make disconnects a bit friendlier.

**Comment by xPaw** [comment]
That's an awful patch. `irc-fw`

**Comment by williamboman** [comment]
sorry
