### ISSUE TITLE
Warn if user config ends up being loaded as an empty object

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1805]
https://github.com/thelounge/lounge/blob/3df1e9d7315e57d77f51f614d7567662094ea5a6/src/helper.js#L71

If user config is messed up (e.g. `module.exports` is missing), then `userConfig` is an empty object.

We just had an user on IRC debug this problem because their config became `module.ex = {`

**Comment by astorije** [comment]
Warn or error? No strong opinion on this.

**Comment by xPaw** [comment]
Warn will do.
