### ISSUE TITLE
incorrect command on front page

### ISSUE THREAD

**Issue by Cightline** [thelounge/lounge#1840]
```thelounge start``` should be ```lounge start``` (on Arch Linux at least)

**Comment by MaxLeiter** [comment]
Update your instance of Lounge

**Comment by Cightline** [comment]
I installed it on Debian as well, the command is still ```lounge```

Let me know if you want any logs or other info.

**Comment by dgw** [comment]
@MaxLeiter The responsible commit, aca2325, is only present in 2.7.0 pre-releases for now, which production users might not want and package repositories probably don't have.

@Cightline The readme displayed on GitHub is from the latest development version. `thelounge` will be the canonical CLI command once 2.7.0 goes stable. v2.6.0 and below only support `lounge`. See #1708.

**Comment by Cightline** [comment]
@dgw Ok sounds good
