### ISSUE TITLE
Accessing timestamps on mobile

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#186]
Right now, if the window width is below 480px, timestamps are hidden. This means that on mobile, timestamps are not available.

Several times since I started using The Lounge on my phone instead of a native client, I've had varying degrees of wanting or needing to see when a message was sent, and I can't.

I realize that showing all timestamps might present a UX issue (crowding the chat display), but there is a strong case for at least making them available.

**Comment by lindskogen** [comment]
Like Facebook Messenger - pressing on a message bubble making it appear.

**Comment by maxpoulin64** [comment]
Another option that I really like is how Snapchat does it: on Snapchat, if you slide the conversation to the right, then the timestamps appear on the left, and then hide again when you release.

http://screenshots.fr.sftcdn.net/blog/fr/2014/05/Time-when-the-messages-were-sent-Snapchat-568x402.jpg

It would probably require a lot more code though.

**Comment by Jay2k1** [comment]
> Several times since I started using The Lounge on my phone instead of a native client, I've had varying degrees of wanting or needing to see when a message was sent, and I can't.

Yes you can, turn your phone into landscape :)

I miss timestamps on default portrait mode too though, and I'd welcome good ideas to make them show.

**Comment by dgw** [comment]
Should be resolved by #376 being merged. Closing.
