### ISSUE TITLE
missing defaults in function getClientConfiguration()

### ISSUE THREAD

**Issue by jw1992victory** [thelounge/lounge#1861]
in sever.js function getClientConfiguration(), why we are not loading defaults from config?

**Comment by xPaw** [comment]
Because they're loaded in helper where config is loaded.

**Comment by jw1992victory** [comment]
How is it loaded in helper?

**Comment by xPaw** [comment]
When then server starts, it loads defaults then applies config to it.

**Comment by jw1992victory** [comment]
oh I see, but
```
	if (config.displayNetwork) {
		config.defaults = Helper.config.defaults;
	}
```
why it's only loading when displayNetwork is true?
and then in connects.tpl 
```
				Connects
				{{#unless displayNetwork}}
					{{#if lockNetwork}}
					to {{defaults.name}}
					{{/if}}
				{{/unless}}
```
it uses defaults.name when displayNetwork is not true

**Comment by xPaw** [comment]
That's the point, yes. If you're hiding the network it will lock to whatever is defined in the config. If you want to ask general questions come to our IRC channel.
