### ISSUE TITLE
option to join only default channel / chatroom

### ISSUE THREAD

**Issue by bayparwah** [thelounge/lounge#1866]
There should be an option to enable / disable default channel / chatroom only

**Comment by dgw** [comment]
Like a `lockChannels` setting to go with `lockNetwork`?

**Comment by bayparwah** [comment]
dgw, absolutely there should be an option to lockChannels same like lockNetwork

**Comment by xPaw** [comment]
We can't possibly enforce channel locks on the client. This is a job for the IRC server.

This was discussed before but I can't find the issue right now. Basically it boils down to the fact that user can join a channel in myriad of ways (e.g. sending join via `raw`). If you simply ignore channel joins and not render them, you're still effectively in that channel and receiving messages.

**Comment by bayparwah** [comment]
there used to be a java based client namely PJIRC and in it's config u can set channel names which can be joined and only those channels can be joined, even by using /j #channel it doesnt work except those channels defiend in the config and even if someone parts those channels it rejoins them automatically, for your testing you can download and test it frm https://sourceforge.net/projects/pjirc/ and for your ease see the screenshot of it's config file is http://www.pjirc.com/wp-content/uploads/2016/06/Screen-Shot-2016-06-21-at-2.26.58-PM.png I am not comparing both projects but just sharing my thoughts that there can be a possibility if a Network can be locked Channel should also be locked.

**Comment by xPaw** [comment]
@thelounge/maintainers What do you guys think? My stance is that it's not the client's job to filter channels.

**Comment by astorije** [comment]
I can see use cases for this, but indeed, it would have to be pretty hacky.
At the very least, if we do this, it probably should be done at `irc-framework` level, which gets all the raw traffic.

Closing this for now as "Won't Fix", we can re-evaluate in the future if necessary or if someone comes up with a good solution (which I don't think there will be any on our end).

**Comment by fuzzy76** [comment]
Just adding another way of bypassing this: auto-join on invite.
