### ISSUE TITLE
Controls of audio/video HTML5 elements are invisible

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#1900]
<img width="673" alt="screen shot 2017-12-24 at 19 36 32" src="https://user-images.githubusercontent.com/113730/34329951-d93476b8-e8e1-11e7-8072-5cea187dff5e.png">

<img width="805" alt="screen shot 2017-12-24 at 19 48 07" src="https://user-images.githubusercontent.com/113730/34330018-65b0b650-e8e3-11e7-823c-9c81d6070607.png">

I spent some time on this and for the life of me could not figure this out. Nothing I could find on the web, but even when stripping down every CSS or HTML around it, still nothing shows up.

There were some CSP issues with the controls sprites (`data:image/png...`), so I thought that was it, but no dice.

Any ideas?

**Comment by MaxLeiter** [comment]
I had this too for a bit, but no one else did so I figured it was local.

**Comment by xPaw** [comment]
I can see this bug on my phone, but not desktop. Both use same theme.

**Comment by MaxLeiter** [comment]
Can't dupe in FF56 and up. Can in chrome.

**Comment by astorije** [comment]
Testing now with the same URL (https://www.quirksmode.org/html5/videos/big_buck_bunny.mp4) on `master`, it seems to work fine now :man_facepalming: 

I'm wondering if #1904 didn't actually fix it, but the consequences were not obvious immediately (caching or whatnot).

I'll leave this open for a bit, as we have a couple other things to close before 2.7 release, and will check periodically to see if bug re-appears or not. If others can test on `master`, that would be helpful.

**Comment by MaxLeiter** [comment]
yeah, fixed for me on master.

**Comment by xPaw** [comment]
Can confirm, I cleared cache in Chrome on my phone and it's fixed.

**Comment by astorije** [comment]
I also noticed this now works for me on pre.4. WTF happened here, I don't know.
