### ISSUE TITLE
Cryptic warning for push notifications on Firefox

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#1902]
<img width="490" alt="screen shot 2017-12-25 at 18 47 20" src="https://user-images.githubusercontent.com/113730/34343611-2622c084-e9a4-11e7-967d-986fbb30eaf7.png">

**Comment by TheMythPT** [comment]
Having the same issue on Ubuntu 17.10 (latest release). All packages are up-to-date on my Ubuntu.
Below, screenshot about my Firefox version:
![ff_version2](https://user-images.githubusercontent.com/25697531/34482897-480987b0-efbb-11e7-9998-1593ca27eb39.png)

**Comment by astorije** [comment]
@xPaw, with your commit above (8d0bdfc), I get:

<img width="474" alt="screen shot 2018-01-13 at 00 52 59" src="https://user-images.githubusercontent.com/113730/34903268-28aefe4c-f7fc-11e7-8d52-6f95b898210c.png">
