### ISSUE TITLE
Hash user tokens

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#1934]
1. Avoids leaking other tokens via the session list (disconnect button currently needs to know the token to function)
2. Hashed on disk (in user config) because we don't need to store actual token at this point.

Only the users' local storage will have original token stored to perform login. What algorithm should we use for this?

**Comment by YaManicKill** [comment]
> What algorithm should we use for this?

Bcrypt? I think that's pretty standard hashing for storing secrets just now.

**Comment by astorije** [comment]
On IRC, @xPaw said bcrypt is designed for plaintext passwords with low entropy, we're generating secure binary data for tokens, so sha256 should be just fine.

I'm fine with whatever, assuming we don't need a new dependency for that as we already have one for bcrypt. So either use something Node-native, or the dependency we already have.

But 👍 overall, as I suggested in the first place :)
