### ISSUE TITLE
Make it more obvious that sending a message to a channel was denied

### ISSUE THREAD

**Issue by mortie** [thelounge/lounge#1946]
If you don't have permission to speak in a channel (because someone unvoiced you, or because only registered people are allowed to speak in that channel, or whatever), it looks like your message went through. I've a few times tried to talk to people, gotten annoyed at being ignored, then getting suspicious about being ignored, and finally checking messages from the IRC network, where there'd be a couple of ` Cannot send to channel (cannot_send_to_channel)` messages. There should probably be some visual indicator, visible from within the channel you're trying to send messages to, that your messages aren't being sent.

**Comment by astorije** [comment]
@mortie, this should be made easier with https://github.com/thelounge/lounge/pull/1380 in v2.7.0.

I've proposed the following there, as a future feature:

<img width="500" alt="screen shot 2017-12-05 at 00 31 59" src="https://user-images.githubusercontent.com/113730/33591526-0510372e-d954-11e7-8382-8b10fe5e7b0a.png">

I'm hoping to do something like this for v3.

**Comment by astorije** [comment]
Closing as your specific issue should be addressed once we release v2.7.0.
Just to check, what version are you using?

**Comment by mortie** [comment]
You're right, this is fixed in v2.7.0. I was encountering the issue in v2.6.0, and didn't think to test whether it's still an issue in 2.7.
