### ISSUE TITLE
Support port in /connect command

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#195]
That means passing in `args[1]` and also splitting if the input contains `:`

**Comment by maxpoulin64** [comment]
> and also splitting if the input contains :

Hmm, that might be a problem with IPv6 addresses. If I want to connect to `/connect [::1]:6697` that might be an issue. If we go that route, we'll need to make sure to split only the last `:6697` out of it. We could use `/connect server [port=6667]` instead.

Adding to this, it would probably be good to have some kind of way to also set SSL. So, likely parsing a port with "+" in it as SSL.

There's also the `server/port` connection strings I have seen at some places, but I think this one is too silly to be worth bothering with.

**Comment by xPaw** [comment]
>  We could use /connect server [port=6667] instead.

No need for the weird construct. `/connect chat.freenode.net [+]6667` is fine.
