### ISSUE TITLE
Trying to join a channel after you've been kicked/banned results in nothing

### ISSUE THREAD

**Issue by RockyTV** [thelounge/lounge#1959]
This bug occurs on the next release branch (master). 

How to reproduce: Launch Lounge, join a channel. Get someone to set the channel to invite only and ask them to kick you. Type `/join #channelname` and you'll see that instead of sending the command, Lounge switches to the channel tab instead.

I thought this was an issue with the autocomplete but it's not, if you type a space after the channel name, Lounge will still switch to the channel tab. If you want to actually join the channel, you must close the tab, which will result in the "you are not in channel" error (probably because closing the tab sends a `/PART`).

**Comment by jimmybrancaccio** [comment]
I can confirm this is still an issue in 2.7.0.

**Comment by RockyTV** [comment]
I can confirm that as of commit 0b37418, the issue is still present. If you set Lounge to auto join a channel when it connects to a network and for some reason you can't join that channel, the channel tab will still be present, and clicking to leave the channel results in a `not_on_channel` error. 

And even then, you still can't send the join command. The same thing happens: TL will just focus on the tab instead, no matter where you send the command.

**Comment by xPaw** [comment]
@RockyTV That's a slightly different issue, with leaving channels, not joining them. Make a new issue for that. Sounds like we need to handle `not_on_channel` to remove the channel.

**Comment by RockyTV** [comment]
Or just handle being kicked/not being able to join a channel to remove the channel from the list.

However, you still can't send the join command if the channel is present on the list, even though you're not on that channel.

**Comment by xPaw** [comment]
> Or just handle being kicked/not being able to join a channel to remove the channel from the list.

Getting kicked is one of these cases where we'd want to keep the channel.

> However, you still can't send the join command if the channel is present on the list
We don't block `join` from being sent though. Did you rebuild when you tested?

**Comment by RockyTV** [comment]
I think so, with `npm build`. Is there any other way to rebuild it?
