### ISSUE TITLE
Supress highlighting message if matches to fixed expression

### ISSUE THREAD

**Issue by Somebodyisnobody** [thelounge/lounge#1977]
Surpessing sounds of a highlighted message could be worthwhile if nicks with similar names are in the channel. For example user "Master" and "TheMaster". Master will be always highlighted when someone calls TheMaster.
Also useful with ingame-chatrelays to block the sound if messages with for example the fixed expression "[ingame] Somebodyisnobody" are being send.

**Comment by xPaw** [comment]
This should be handled by #1655.
