### ISSUE TITLE
URL parser incorrectly escapes characters

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/lounge#199]
If a URL followed by a " is posted, the " becomes part of the clickable link which leads to the browser opening a wrong address and the user most likely getting a 404 or worse.
Additionally, a semicolon (;) is being added after the " following the URL.

![image](https://cloud.githubusercontent.com/assets/2070503/13808274/b1128fd8-eb65-11e5-82b0-2174f12fcf48.png)

**Comment by maxpoulin64** [comment]
Yep, one more in the already long list of parser issues.

**Comment by xPaw** [comment]
The url parser is generally quite buggy. For example `www.` gets parsed as a link, despite there not being any domain.

**Comment by YaManicKill** [comment]
Is there any reason we can't use something like [linkifyjs](https://www.npmjs.com/package/linkifyjs) for this? It has to be better than what we are currently using.

**Comment by xPaw** [comment]
@YaManicKill should be fixed in #699 either way.

**Comment by astorije** [comment]
Also, bumping URI.js to latest version would fix some of our issues too.

**Comment by astorije** [comment]
Hey @Jay2k1, #972 should have fixed that. Mind testing your examples on `master`?

**Comment by Jay2k1** [comment]
Yes, my example now works as you'd expect it to. Thanks!
