### ISSUE TITLE
Do not close a channel's window on immediately when a user runs /part

### ISSUE THREAD

**Issue by crosma** [thelounge/lounge#1991]
Currently when you type /part in lounge it immediately closes the channel's window client side. Some networks require users to be in a channel and will deny PART commands for that channel. The result is that the user is still in the channel on the server and still receives messages but is unable to properly reopen the channel's window.

Lounge should instead wait until the server sends the PART back before it closes the channel window.

**Comment by xPaw** [comment]
Should be as simple as adding a check in `inputs/part.js` to see if we're currently connected to IRC. If not connected, remove the channel as it does now, if it's connected just send the `part` and return.

Do you want to make a PR for this?

**Comment by astorije** [comment]
> Should be as simple as adding a check in `inputs/part.js` to see if we're currently connected to IRC. If not connected, remove the channel as it does now, if it's connected just send the `part` and return.

Unfortunately, it's not as simple as that if we want to keep a decent UX.
If we do this, then there will be a delay between clicking <kbd>&times;</kbd> and having the channel close when it can be closed (which will be 99% of the cases).
Depending on network, this may add a few hundred milliseconds at best, and maybe a second or 2 on spotty networks. Considering that channels that can't be closed are rather niche, this would be a substantial delay in most cases.

Is there a way to know if a channel can be closed while being _on_ the channel (like via a mode check or something)? If so, then we know at closing time if a channel can be closed. We can close it instantly when it's possible to close it, and we can simply remove / disable (with a tooltip or something) the <kbd>&times;</kbd> button and the "Leave" action in context menu.

**Comment by xPaw** [comment]
@astorije, there's still the network lag of lounge server sending part to client. Also, I've actually seen it glitch out when I closed a channel and a message came in before part was registered by the server which caused that last message to open a query window.

**Comment by astorije** [comment]
Interesting. Clicking on <kbd>&times;</kbd> should be modified to close the channel immediately then, and not be subject to network lags. If a message arrives after that, just ignore it.

But for this specific issue, it would be better to know in advance if we can leave the channel. Do servers inform on that before actually running `/part`?

**Comment by xPaw** [comment]
@astorije The lag issue you are describing is unrelated, in my opinion.

As for knowing if we can leave the channel, not that I know of, but that also isn't unrelated to the issue I described above.

**Comment by astorije** [comment]
> @astorije The lag issue you are describing is unrelated, in my opinion.

It is unrelated indeed, but that's because I didn't realize there was such thing. I thought clicking on &times; would close instantly and fixing the current issue would introduce a lag. Turns out, we already have it :man_shrugging: 

> As for knowing if we can leave the channel, not that I know of, but that also isn't related to the issue I described above.

If I understand correctly, then that I disagree about: if we have a way to tell if a channel can be closed prior to trying to closing it, we can disable actually closing it. That would fix the issue in a nicer way, because we could then both get rid of that lag described above (as opposed to relying on server-side only) **and** make it nicer in the UI (preemptively disabling the &times; button and adding a tooltip on it explaining why it can't be closed).

**Comment by xPaw** [comment]
I'm talking about this:

> I've actually seen it glitch out when I closed a channel, and a message came in before part was registered by the server which caused that last message to open a query window.

Knowing whether or not you can close the channel does not fix the race condition on that.

**Comment by crosma** [comment]
At least on our network, it does not indicate in anyway that you may not leave until you attempt to do so.

**Comment by astorije** [comment]
> Knowing whether or not you can close the channel does not fix the race condition on that.

Fair enough, I was not talking about this specifically. Agreed that we need to fix the race condition.

> At least on our network, it does not indicate in anyway that you may not leave until you attempt to do so.

Well, that settles it 😕
