### ISSUE TITLE
Change Password Does Nothing

### ISSUE THREAD

**Issue by pengc99** [thelounge/lounge#2001]
Using the webUI to change the password for the user does nothing. Inputting the current password and new password and then clicking "Change Password" grays out the input fields and then there's no feedback from the server.

Checking the websocket connection shows the submission of the password to the server over the websocket connection, but there is an empty response from the server.

Entering a bad original password and then attempting to change the password results in a bad current password response.

**Comment by astorije** [comment]
Hey @pengc99, what version are you using? On current `master` (which is also `2.7.0-rc.2`), I just tested that this works.
I do recall someone mentioning it, but I can't find the issue/PR so it might have been on the channel. I'm wondering what fixed it. @xPaw, does that ring a bell?

**Comment by xPaw** [comment]
This was fixed by #1978 afaik.

**Comment by pengc99** [comment]
Okay, thanks! I can confirm that adding the changes in #1978 fixed the issue. I'm running 2.6.0, the latest version in the npm repository.
