### ISSUE TITLE
/expand command expands collapsed items, /collapse doesn't collapse expanded items

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#2005]
`/expand` does collapse them (it just toggles them)

**Comment by astorije** [comment]
I think issue is not exactly that, but yeah, there is a bug. `/expand` seems to affect the status messages again. `/collapse` seems to work fine.

**Comment by astorije** [comment]
2.7.0-worthy bug? :(

**Comment by MaxLeiter** [comment]
Depends if we think they should or shouldn’t affect status messages (but you’re right - we previously decided they shouldn’t affect them)

**Comment by astorije** [comment]
Yeah so I confirm that:

- `/collapse` works exactly as intended on previews
- `/expand` works exactly as intended on previews, *but toggles status messages*

That last part is the bug. We had this bug before and already fixed it. Not sure where it came back (what did I break again...)

> Depends if we think they should or shouldn’t affect status messages (but you’re right - we previously decided they shouldn’t affect them)

Shouldn't, for several reasons. There is probably a thread somewhere that explains why we decided on that (and it still applies IMO).
