### ISSUE TITLE
new install or upgrade print many warning

### ISSUE THREAD

**Issue by dateno1** [thelounge/lounge#2016]
old version (2.4.0) work well

now i upgrade nodejs 4 -> 8 by https://nodejs.org/en/download/package-manager and upgrade thelounge by npm
![thelounge](https://user-images.githubusercontent.com/12645246/35561589-1ca25486-05f4-11e8-9b37-a80b7dcf0bc8.png)

remove thelounge and new install is same

also account sudoer and use root prompt by 'sudo su'

**Comment by dateno1** [comment]
ok it fixed with --unsafe-perm

**Comment by McInkay** [comment]
What command did you use to install?

**Comment by dateno1** [comment]
'npm -g install thelounge'
it not work with root

try 'npm -g install thelounge --unsafe-perm' work well
