### ISSUE TITLE
I cann't use new version

### ISSUE THREAD

**Issue by dateno1** [thelounge/lounge#2017]
![version](https://user-images.githubusercontent.com/12645246/35562592-2e188b88-05f7-11e8-9689-ad0ec5d3fa10.png)
like this

npm -g install thelounge or npm -g install thelounge@2.7.0 result same

try remove and reinstall but same result

**Comment by TheMythPT** [comment]
do you get any errors using `npm install -g thelounge`?
If yes, what are the errors?

**Comment by xPaw** [comment]
You have two Lounge versions installed, you will have to correctly uninstall the previous version.

**Comment by dateno1** [comment]
![version](https://user-images.githubusercontent.com/12645246/35564074-466fe622-05fc-11e8-9bb5-43d68f30b3ba.png)
no error

no two version
