### ISSUE TITLE
[reopen]I cann't use new version

### ISSUE THREAD

**Issue by dateno1** [thelounge/lounge#2018]
![version](https://user-images.githubusercontent.com/12645246/35564273-f8b34e8c-05fc-11e8-8d1d-a54e0ec0ea0b.png)
like this

npm -g install thelounge or npm -g install thelounge@2.7.0 result same

try remove and reinstall but same result

![list](https://user-images.githubusercontent.com/12645246/35564283-0209e108-05fd-11e8-9a43-fb5317cd5aab.png)
no error

no two version

**Comment by xPaw** [comment]
Please stop making issues for every question you have, come to our IRC channel instead.

You most likely have issues because you upgraded your node/npm. This isn't a problem with The Lounge. Try doing `npm link thelounge`.

**Comment by dateno1** [comment]
I dont' know about IRC channel

where i can join that channel?
