### ISSUE TITLE
Include some kind of timestamp in push notifications 

### ISSUE THREAD

**Issue by MiniDigger** [thelounge/lounge#2026]
It would be cool to see when the message that caused the notification was send or at least when I got the notification. Take a look at the notification pushbullet send me, it tells me it's been waiting for me to click it for 29min. Could it be possible to implement that for lounge push notifications too?
https://imgur.com/hhlOVwE

**Comment by xPaw** [comment]
Lounge notifications do set timestamp field as well. I just tried it and it showed the time for me on both Android and Windows just like the pushbullet one.

If you have updated to v2.7, you might still have older serviceworker version.
