### ISSUE TITLE
[Feature Request] Ability To Disable Highlight Notification For Certain Nicknames

### ISSUE THREAD

**Issue by vectr0n** [thelounge/lounge#204]

**Comment by YaManicKill** [comment]
So, the question is what the best way to do this is. Options:

1. A new CSL textbox for anti-highlights
2. Using the custom highlights box (I'm just assuming it'll be merged) and anything that starts in "!" counts as an anti-highlight

There might be others, not sure.

Other question:
1. Do we just do anti-highlights for a nick, or for any text in the message? (I think this is possibly the simplest way to deal with this, to stop other issues with it. Anyone know how other clients work?)
2. Do anti-highlights have priority over all highlights? (this is probably the easiest way to do it)

**Comment by vectr0n** [comment]
I have only ever seen a box or option for anti highlight, but I suppose ! could would, not sure if would confuse some of the less advanced users. Both seem like viable options to me, # 1 probably being the easiest for people to understand, not sure about the back end. I think it would be best to do any text in the message as I get highlights even for host names with "vectr0n" in the message. I think it would be best for them to take priority over all highlights otherwise it would be kind of pointless, or I am miss understanding that aspect.

**Comment by YaManicKill** [comment]
Alright, if you are going to be awkward and delete everything, then fine. I will close this and add another issue. You really don't have to be awkward about it all, @vectr0n.
