### ISSUE TITLE
Display network 'false' shows empty user preferences and missing IRC network name

### ISSUE THREAD

**Issue by variablenix** [thelounge/lounge#2044]
After going from thelounge `2.6.0-1 -> 2.7.0-2` I noticed if `displayNetwork` is set to `false`, the network is _not_ displayed as it should, but the user preference fields are empty.

The displayed headline also drops the IRC network name, so it only shows as
> The Lounge - Connect to

![thelounge - user preferences](https://user-images.githubusercontent.com/472631/35960887-4fb880b2-0c60-11e8-85fe-c3d952c2fa30.png)

When I set `displayNetwork: true,` while the network is locked (maybe unlocked, too) the headline is missing the IRC network name.

![thelounge - connect](https://user-images.githubusercontent.com/472631/35961161-7cad55d8-0c61-11e8-803f-b90742ad5dc8.png)

I'm not entirely sure if this behaviour is intentional with the new 2.7.0 release, but I wouldn't think so. In any case, I do like the new Lounge logo! 👍

**Comment by xPaw** [comment]
That's fixed in 2.7.1
