### ISSUE TITLE
Text-user interface for just command-line

### ISSUE THREAD

**Issue by kutsan** [thelounge/lounge#2051]
I know lounge is intended to work under browser but is there any plan to work in just command-line as TUI program, maybe with [blessed](https://github.com/chjj/blessed)?

**Comment by dgw** [comment]
If you want a terminal-based IRC client, look into weechat, ircII, BitchX, irssi, or another of the numerous already-existing CLI clients (many of which are listed [here](https://en.wikipedia.org/wiki/Comparison_of_Internet_Relay_Chat_clients)). The Lounge isn't going to add a completely different interface. Its focus is on running in the browser and being accessible from anywhere you can open a browser window. (Look into running one of the terminal clients inside `screen` or `tmux` or the like for a similar terminal-based effect. Connect The Lounge to a dedicated IRC bouncer like ZNC for the flexibility to use any client you want on each of your devices.)

**Comment by MaxLeiter** [comment]
Worth noting this is possible. I had a rough one a while back on top of blessed. May put it on git sometime in case someone wants to work on it

**Comment by dgw** [comment]
Could this be plugin territory, once the plugin system is finalized? It wouldn't ship with core, probably, but could be installed later as a plugin if desired?

**Comment by MaxLeiter** [comment]
A TUI wouldn’t be a plug-in, it would just connect via sockets to the
lounge server

**Comment by kutsan** [comment]
@dgw I am already using weechat. It's not like there isn't any alternative. It would be good to have. Lounge API is there and it shouldn't be hard to connect to another UI with blessed or some other one.

**Comment by astorije** [comment]
@kutsan, we will not be adding a terminal interface to The Lounge. @dgw has summarized the reasons very well. It is simply not what this project is trying to accomplish, and any extra effort we have to spend on those slow us down in the key components of the project.

That said, like @MaxLeiter said, the client discusses with the server using a standard websocket, so it is possible to make it work, with some effort.
@MaxLeiter, you should really publish what you have on your GitHub account, and if you don't want to maintain it, mention that it's up for grab for whoever wants to implement further or something. However I believe this should not be part of https://github.com/thelounge.

> [...] it shouldn't be hard to [...]

Famous last words 😁
