### ISSUE TITLE
PrefetchStorage wrong link when reverse-proxying in a subdirectory 

### ISSUE THREAD

**Issue by poVoq** [thelounge/lounge#2056]
It seems like the PrefetchStorage can't be configured to work properly when TheLounge is running in a sub-directory?

I have it running as "mydomain.com/thelounge" through a reverse-proxy and everything works great except for the PrefetchStorage which links pictures to "mydomain.com/storage/..." instead of "mydomain.com/thelounge/storage/..." like it would need to work.

Is there some way to configure a subdirectory for it?

Thanks!

**Comment by xPaw** [comment]
Are you visiting `mydomain.com/thelounge/`? the ending slash is important. Stored images start with `storage/` and not `/storage/`, so it would load under the subfolder.

**Comment by poVoq** [comment]
Hmm yes that seems to make a difference.

Maybe a possible improvement to make both work?

**Comment by xPaw** [comment]
We're relying on the browser for subpaths to work here (that's by design as to how URIs work).
