### ISSUE TITLE
Cant login to ZNC anymore due to username field change

### ISSUE THREAD

**Issue by stev-it** [thelounge/lounge#2057]
Using the newest version.

My problem is i cannot connect to my ZNC server, as the username field in the network configuration window got removed and it uses now the username of my thelounge account.
But i need to connect with a specific username, like "admin/network" and not with "admin".

picture:
![image](https://user-images.githubusercontent.com/17822893/36099154-e8a28756-1001-11e8-8626-acd2c8130342.png)

Is there anything i can do to resolve this? I tried to modify the config to put in the username i need, but it wont work. I cant login.

**Comment by xPaw** [comment]
Username field was not removed. Are you sure you're not hiding it with CSS or editing index.html?

What lounge version?

**Comment by stev-it** [comment]
@xPaw 2.7.0

Nope, i didnt edit anything and i dont use costum CSS

**Comment by xPaw** [comment]
Try incognito (no extensions) or another browser, another theme. We haven't touched anything in regards to that field and I can't repro it.

**Comment by stev-it** [comment]
@xPaw Tried now several browsers in incognito mode, and another themes, it stays that way, no username field

**Comment by TheMythPT** [comment]
afaik, you can use the password field which will override anything else.
just put there `username/network:password` and give it a shot.

**Comment by xPaw** [comment]
Does the field exist in the html if you look in devyools?

**Comment by stev-it** [comment]
@TheMythPT That worked! OMG! Thank you!!!

@xPaw Nope, doesnt exist

**Comment by TheMythPT** [comment]
@stev-it, no problem. glad it did worked. :)

**Comment by xPaw** [comment]
How did you install lounge?

**Comment by stev-it** [comment]
@xPaw Via the Docker container from linuxserver.io

**Comment by xPaw** [comment]
Can you try official image? I don't know how they possibly screw it up

**Comment by stev-it** [comment]
@xPaw the struggle by changing image, okay i changed the image now. But no username field either xD

**Comment by isra17** [comment]
has you `useHexIp` set to true in your config?
See: https://github.com/thelounge/lounge/blob/489bb8e395b5e2c1f5900d7f6b7f453753be6e5a/client/views/windows/connect.tpl#L64

**Comment by stev-it** [comment]
@isra17 i have... should i disable it

**Comment by isra17** [comment]
Yes

**Comment by stev-it** [comment]
Omg im so stupid, thanks @isra17 
i thought it would encode my ip, not my username...
