### ISSUE TITLE
Automatically load more history when scrolling up

### ISSUE THREAD

**Issue by tomnx** [thelounge/lounge#207]
When I am reading channel logs backwards it forces me to keep clicking "Show More" (and after a while clicking again and again becomes annoying). Please enable auto-scrolling. Thanks.

**Comment by YaManicKill** [comment]
Just to clarify, when you say auto-scrolling, you mean when you scroll to the top of the existing scrollback, thelounge should automatically load x number more mesages and put them above where you are so you can keep scrolling back rather than having to press the "Show More" button?

**Comment by tomnx** [comment]
@YaManicKill Yes.

**Comment by tomnx** [comment]
https://github.com/thelounge/lounge/blob/eadcca0b5e54bb653072edab5fbe0730698076db/client/js/lounge.js#L825

	chat.on("click", ".show-more-button", function() {
		var self = $(this);
		var count = self.parent().next(".messages").children().length;
		socket.emit("more", {
			target: self.data("id"),
			count: count
		});
	});

**Comment by astorije** [comment]
@davibe, do you want to take a look at this now that you've nailed https://github.com/thelounge/lounge/pull/496? :-)
Maybe @tomnx's suggestion is enough (or maybe not otherwise there would be a PR :D), not sure.

**Comment by davibe** [comment]
I am lazy, but i could try
