### ISSUE TITLE
Consider self-signed certificates secure

### ISSUE THREAD

**Issue by realies** [thelounge/lounge#2083]
After updating to master all servers become yellow with an unlocked padlock icon. Thelounge connects to a local ZNC instance with a self-signed certificate via a local IP. The connection is secure and encrypted but Thelounge displays it as it is not. Consider self-signed certificates secure or allow for a config flag that enables this.

**Comment by dgw** [comment]
I think your (and my, though I don't run The Lounge @ `master` and haven't run into this yet) self-signed ZNC certs would be handled just fine by #2081, because they're on localhost.

As worded, I would say :-1: to this because blanket hiding the validity state of all self-signed certificates is an awful idea. But I would :+1: a flag per-network to ignore certificate checks.

**Comment by astorije** [comment]
I think @dgw's answer is on point and I have little to add :)
This is similar to the warning browsers give on self-signed certificates.

I saw @xPaw is also not in favor of this and mentioned it as won't fix, so I'm going to close this issue as such.
Thanks for the feedback!

**Comment by realies** [comment]
What do you suggest to be the way forward when ZNC and Thelounge live in separate docker containers? Thelounge has to connect to the IP of the host or docker bridge network which is different than localhost.

**Comment by astorije** [comment]
It's not really in the realm of The Lounge at this point. We just inform that the certificate is not 100% fine, and it's up to the user or the admin to make a decision based on this.
In your example, you can either ignore this, or sign your certificate with Let's Encrypt.

And again, this is exactly how browsers behave with signed certs, so I'm inclined to follow this trend.

**Comment by realies** [comment]
The current visual indication suggests the connection is not secure which in the case described is not true. In the context of how browsers behave, most have the ability to add an exception for a self-signed certificate and can consider the connection secure. In my knowledge, having a server (i.e. bouncer) not exposed to the public internet makes it impossible for usage with Let's Encrypt services. Perhaps there could be a global or per network flag to ignore certificate checks as @dgw suggested?
