### ISSUE TITLE
/msg doesn't open a window

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#214]
When doing `/msg nickname text`, The Lounge does not open a query window with the target nickname. The window is opened if and when the other user replies to the PM, but the initial message vanishes into the ether. This is contrary to most mainstream IRC clients, which immediately open a window and place the user's initial message in it.

Came up during discussion in #208, and I just confirmed by testing. Figured it had a place in the issue list, for the next time someone feels like mucking with the command handlers. :wink:

**Comment by xPaw** [comment]
That happens because we only emit a "privmsg" to ourselves if a window is already open. Should we be opening a new window for every `/msg` target (that would include channels, and that gets even more trickier).

https://github.com/thelounge/lounge/blob/95f2f1e9f974706e02a475543866359d185af460/src/plugins/inputs/msg.js#L22-L24

**Comment by Jay2k1** [comment]
From mIRC, I am used to `/msg <nick> <msg>` sending a PRIVMSG without opening a query window, and `/query <nick> [msg]` to open a query window and send a PRIVMSG. I like this behaviour...

**Comment by YaManicKill** [comment]
From my experience, that is pretty common. I think IRSSI did it as well, I can't remember though, I've been using the lounge/shout for so long :stuck_out_tongue: 

Having said that, I don't know **why** people insist on that happening. It seems like something you would expect a chat application of any type to do, to open a window/tab/whatever with the user you sent the message to.

So...I don't know. I'll accept whatever people want for this one.

**Comment by YaManicKill** [comment]
(just so long as there is a way to open a query window with a command)

**Comment by maxpoulin64** [comment]
Closing this, as this is fixed by #216 which is also closed. The prefix and chantype bug is fixed in #167.
