### ISSUE TITLE
Re-add /query command to open query window with the specified user

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#216]
`/query` was previously an alias for `/whois`, which was not in line with what other clients do. That alias was removed in #208, so currently the `/query` command does nothing.

Discussion in #214 (specifically, from @YaManicKill) requested "a way to open a query window with a command". Adding back `/query` to do just that seems apt, regardless of how it is eventually decided `/msg` should work.

**Comment by xPaw** [comment]
So it should just open a new window, correct?

**Comment by dgw** [comment]
Yes, `/query nickname` should open a new, blank, query window between the current user and that nick.

If passed a channel name it should probably do nothing, unless other people can provide examples of alternative behavior (all clients I tested just now do nothing for `/query #channel`).

**Comment by xPaw** [comment]
Just looked at HexChat sourcecode, it checks if entered name isn't a channel (compared against `CHANTYPES`). I'm thinking we should also check against `PREFIX`.

**Comment by dgw** [comment]
SGTM. I'd rather see The Lounge get switched over to irc-framework before too many more of these little details get tweaked, anyway. And I was kind of just logging this in because I'd seen interest from others, rather than because it's something I want myself.

So a big :+1: to checking against `CHANTYPES` and `PREFIX`, and this can go in once that becomes possible.

**Comment by astorije** [comment]
@xPaw, the next release will add a regression, as now `/query` does not open a chat window anymore. It would be great if we can provide a quick implementation of this issue in the next release.

Also, I'm not sure to understand, why is checking against `PREFIX` necessary?

**Comment by xPaw** [comment]
> Also, I'm not sure to understand, why is checking against PREFIX necessary?

You can't have a name that starts with a PREFIX, e.g. `@xPaw`
