### ISSUE TITLE
Disabling "Show joins" opt distorts UI

### ISSUE THREAD

**Issue by williamboman** [thelounge/lounge#229]
$subj

![foobar](https://cloud.githubusercontent.com/assets/6705160/14193530/f97c43a8-f7a5-11e5-9931-90cdb0fbf3a0.gif)

**Comment by maxpoulin64** [comment]
Known issue, fixed already in master by #227 :)

**Comment by williamboman** [comment]
Ah, my bad. My Search Fu wasn't strong enough.
