### ISSUE TITLE
Link and icon glitches when hovering

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#236]
On Mac OS X 10.11.4, Chrome 49.0.2623.75:

![hover-bug](https://cloud.githubusercontent.com/assets/113730/14228482/03059f70-f8e4-11e5-9dcc-67437a024329.gif)

I have noticed that on links, icons, clickable nicks too... Quite a blurry description but I haven't found a way to reproduce this consistently yet.

**Comment by MaxLeiter** [comment]
Can't reproduce on irc-framework, Windows 7, Chrome 49.0.2623.110

**Comment by MaxLeiter** [comment]
@astorije are you still experiencing this?

**Comment by astorije** [comment]
I actually haven't noticed this in a while! Actually since... I am using 2.0.0-prereleases.
My guess is that this was fixed along with the many changes on icons, font-aliasing, etc. happening in v2.
Thanks for triaging!
