### ISSUE TITLE
Keep a look out on irc-framework

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#24]
https://github.com/kiwiirc/irc-framework

@prawnsalad is working on a new framework for use in his Kiwi IRC client, and has suggested that combining efforts would be a good idea towards better clients altogether.

`slate-irc` is practically dead, and would require a lot of work to add many of the features that are already supported in `irc-framework` (mostly IRCv3 stuff, including SASL, server-time and others.)

**Comment by YaManicKill** [comment]
Yeah, I think we need to look into the difference in effort of:

1. Changing the irc framework we use
2. Adding new features to slate (because, as oyu say, it's dead)

@astorije Can you add a discussion label, I don't see one currently.

@xPaw Are you willing ot look into how much work it would be to move frameworks?

**Comment by xPaw** [comment]
It should be a matter of renaming events and parameter names, as they differ. Other than that, they're both event based, so it shouldn't be terribly difficult to move.

**Comment by YaManicKill** [comment]
Alrighty then, marked this as an enhancement, and if someone wants to pick it up, feel free. 

As usual, feel free to open a PR early, so we can see how it's going to work rather than getting absolutely everything done and having to change some stuff.

**Comment by xPaw** [comment]
Hold on the PR until Kiwi itself switches to using that framework.

**Comment by xPaw** [comment]
There are another reason why I see switching to `irc-framework` will help, it will have proper channel/user state tracking, so that our client won't need to do hacky stuff like requesting `names` from the server whenever any users' mode changes.

https://github.com/thelounge/lounge/blob/30b8a419cdb711808b68df08fe9612f0c646dbe8/src/plugins/irc-events/mode.js#L9-L11

**Comment by xPaw** [comment]
Another thing: whenever `mode` event is received, it requests `NAMES` for that channel:

https://github.com/thelounge/lounge/blob/master/src/plugins/irc-events/mode.js#L9-L11

**Comment by xPaw** [comment]
Just found out another thing: `errors` event does not include `from` field.

thelounge: https://img.avora.xyz/uploads/big/6ea7aa202ce04329b2b3d431f24cb24d.png
hexchat: https://img.avora.xyz/uploads/big/b1d5934840ce801141629faa731fe004.png

**Comment by lindskogen** [comment]
The support for middleware gets me excited!

**Comment by xPaw** [comment]
I started working on this: https://github.com/thelounge/lounge/compare/master...xPaw:irc-framework

It connects, handles userlist (although with issues), joins, messages, notices (not tested), and ctcp (not tested).

**Comment by xPaw** [comment]
:tada:
