### ISSUE TITLE
Display Full Topic On Hover

### ISSUE THREAD

**Issue by vectr0n** [thelounge/lounge#241]
At the moment to see the full topic you have to use the /topic command. It would be handy to have the ability to hover over the topic bar with mouse pointer and have it display the full topic. Or if maybe another solution would fit better, just an idea I thought of.

**Comment by MaxLeiter** [comment]
Currently, a tool tip shows on the desktop, do you mean something should show on mobile as well?

**Comment by vectr0n** [comment]
So weird, it wasn't doing it yesterday, sorry I will close this as it working today... lol
