### ISSUE TITLE
NaN:NaN time

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#244]
I'm not sure if I've mucked something up in my merge to my fork (don't think so, but will check later to see what the issue is) but I'm getting NaN:NaN in the time field for link previews on 1.4.3.

![c95f28224f773da651f4a7ddf52f4220](https://cloud.githubusercontent.com/assets/2162657/14240430/d5bb72f6-fa3c-11e5-89cb-d31fdbbb66a0.png)

**Comment by xPaw** [comment]
This is fixed in irc-fw branch for sure.

**Comment by MaxLeiter** [comment]
This is currently an issue on master; it's not just your fork (and can confirm it doesn't occur on irc-framework)

**Comment by xPaw** [comment]
This is fixed in master now.
