### ISSUE TITLE
Per-channel notification configuration

### ISSUE THREAD

**Issue by Zenith-One** [thelounge/lounge#248]
I would love to be able to configure my notification preferences on a per-channel basis. For instance, there's a channel directly related to a project (#project) I'm working on that I would like to be notified by each time a message is received in that channel. In contrast, there's a general channel (#general) for everyone that's very busy and almost never relevant to me.

So in the examples above, I would like to receive notifications for all messages in #project, while only receiving notifications in #general if I'm mentioned.

**Comment by Zenith-One** [comment]
Just me?

**Comment by xPaw** [comment]
This is planned for settings overhaul, see #85.
