### ISSUE TITLE
Cache getConfig()

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#249]
Currently it `require`s the config file from disk every time the function is called, it should be cached.

**Comment by maxpoulin64** [comment]
node caches require() calls, so I don't know if there will be any benefit apart from one less function call.

**Comment by xPaw** [comment]
Well that entirely works not how I would expect it to. But it's still a bit odd to be calling getConfig everywhere, which then calls require. having an object we can use would be better, probably.

**Comment by xPaw** [comment]
If we do this, we will also be able to correctly set all the default variables in one place instead of spreading `cfg || false` everywhere in the code.

Probably by loading the defaults config and merging user config into it.
