### ISSUE TITLE
Unread message marker

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#25]
Can be based on https://github.com/erming/shout/pull/382

**Comment by astorije** [comment]
:+1: as long as UX implications are discussed beforehand.

**Comment by nomadturk** [comment]
+1

It's hard to find what we read and what we didn't.

**Comment by vectr0n** [comment]
+1

**Comment by xPaw** [comment]
Would be super nice to have something like gitter.im does:

![chrome_2016-02-24_12-16-30](https://cloud.githubusercontent.com/assets/613331/13282210/84aa2fe4-daf0-11e5-9652-ac8a33871e7e.png)
![chrome_2016-02-24_12-16-45](https://cloud.githubusercontent.com/assets/613331/13282211/84c32df0-daf0-11e5-8d21-bcde139a6154.png)

**Comment by dgw** [comment]
Right now I'm just missing the line Textual leaves in each buffer at the last read position, so the original proposal would do me just fine. Maybe bring in the horizontal line now as a minimum viable feature and then work on emulating gitter.im if there's interest?

**Comment by MaxLeiter** [comment]
Can be closed now #332
