### ISSUE TITLE
Ubuntu 15.10 Install Errors

### ISSUE THREAD

**Issue by scriptzteam** [thelounge/lounge#250]
root@root:~# sudo npm install -g thelounge
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine escodegen@1.8.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
/usr/local/bin/lounge -> /usr/local/lib/node_modules/thelounge/index.js
thelounge@1.4.3 /usr/local/lib/node_modules/thelounge
├── bcrypt-nodejs@0.0.3
├── read@1.0.7 (mute-stream@0.0.6)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── event-stream@3.3.2 (stream-combiner@0.0.4, duplexer@0.1.1, from@0.1.3, pause-stream@0.0.11, map-stream@0.1.0, split@0.3.3, through@2.3.8)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── slate-irc@0.8.1 (irc-replies@2.0.1, debug@2.2.0, slate-irc-parser@0.0.2)
├── express@4.13.4 (escape-html@1.0.3, array-flatten@1.1.1, utils-merge@1.0.0, cookie-signature@1.0.6, merge-descriptors@1.0.1, fresh@0.3.0, methods@1.1.2, range-parser@1.0.3, vary@1.0.1, path-to-regexp@0.1.7, cookie@0.1.5, parseurl@1.3.1, content-type@1.0.1, etag@1.7.0, content-disposition@0.5.1, serve-static@1.10.2, depd@1.1.0, qs@4.0.0, on-finished@2.3.0, finalhandler@0.4.1, debug@2.2.0, proxy-addr@1.0.10, send@0.13.1, accepts@1.2.13, type-is@1.6.12)
├── socket.io@1.4.5 (has-binary@0.1.7, debug@2.2.0, socket.io-parser@2.2.6, engine.io@1.6.8, socket.io-adapter@0.4.0, socket.io-client@1.4.5)
├── request@2.69.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, tunnel-agent@0.4.2, oauth-sign@0.8.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.7, combined-stream@1.0.5, qs@6.0.2, tough-cookie@2.2.2, mime-types@2.1.10, aws4@1.3.2, form-data@1.0.0-rc4, bl@1.0.3, http-signature@1.1.1, har-validator@2.0.6, hawk@3.1.3)
├── spdy@3.2.3 (http-deceiver@1.2.4, handle-thing@1.2.4, select-hose@2.0.0, debug@2.2.0, spdy-transport@2.0.10)
├── moment@2.12.0
├── lodash@4.6.1
└── cheerio@0.20.0 (entities@1.1.1, dom-serializer@0.1.0, css-select@1.2.0, htmlparser2@3.8.3, jsdom@7.2.2)
root@root:~# npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/root/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /root/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
root@root:~# ls
l  npm-debug.log
root@root:~# cat
^C
root@root:~# cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
2 info using npm@1.4.21
3 info using node@v0.10.25
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 error install Couldn't read dependencies
6 error package.json ENOENT, open '/root/package.json'
6 error package.json This is most likely not a problem with npm itself.
6 error package.json npm can't find a package.json file in your current directory.
7 error System Linux 3.14.32-xxxx-grs-ipv6-64
8 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
9 error cwd /root
10 error node -v v0.10.25
11 error npm -v 1.4.21
12 error path /root/package.json
13 error code ENOPACKAGEJSON
14 error errno 34
15 verbose exit [ 34, true ]

**Comment by MaxLeiter** [comment]
You only need to run `npm install` when building from source; you used npm so TheLounge is correctly installed. Just run 'lounge --help` to get started :)

**Comment by scriptzteam** [comment]
aha it works now thx :)
