### ISSUE TITLE
Store user token in users' config file for persistency

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#26]
This line specifically: https://github.com/thelounge/lounge/blob/2201e2b941bd13427c38d6934b84ceda245aa20e/src/client.js#L69-L71

This would mean that restarting the server wouldn't require users to re-login.

**Comment by YaManicKill** [comment]
Assuming that there aren't any security issues with storing it in the config file (we already store passwords there anyway, so meh) then this is a really easy fix, so I've added up for grabs to it.

**Comment by xPaw** [comment]
The only issue is that token will never be regenerated (we never do while the instance is running either way), but perhaps we need to consider that.

Like when the password is changed, regenerate the token (both CLI and GUI).
