### ISSUE TITLE
hostmasks on topic set messages not built correctly

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#265]
On master, the 'Topic set by' message shows the hostname of the client which set it

![image](https://sr.ht/ZjdI.png)

While this is expected, with slate-irc the link on the hostmask would open a PM with the client. Now, on irc-framework, Lounge tries to PM a client that's name is the hostname.

![image](https://sr.ht/D0Ut.png)

**Comment by YaManicKill** [comment]
Looks like the @ sign is stripped out, so that might be part of the problem.

**Comment by stepie22** [comment]
The issue lies at irc-framework, and xPaw has made an issue kiwiirc/irc-framework#37

(just commenting so that no-one else starts digging around and wasting time trying to figure it out like I did)

**Comment by astorije** [comment]
The according issue on `irc-framework` was closed. @MaxLeiter @PolarizedIons, can you confirm this is now fixed in The Lounge?

**Comment by MaxLeiter** [comment]
It's now fixed.
