### ISSUE TITLE
Embedded images/links count as unread messages

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#271]
If someone posts a link, and you have auto-expand [thumbnails/links], the message count on the sidebar will increase.

**Comment by maxpoulin64** [comment]
Caused by: https://github.com/thelounge/lounge/blob/master/src/plugins/irc-events/link.js#L35

**Comment by xPaw** [comment]
It's caused by the client side not ignoring it when increasing the counter.
