### ISSUE TITLE
v1.5.0 (tag) displays chat lines with large amount of whitespace due to stylesheet rules

### ISSUE THREAD

**Issue by diddledan** [thelounge/lounge#274]
https://github.com/thelounge/lounge/blob/master/client/css/style.css#L767

The `white-space: pre-wrap` line causes extreme white-space in Firefox on every line of chat. Removing/disabling that rule fixes everything to display correctly on Firefox.

Current (this is affecting both v1.5.0 tag and trunk):
![Current behaviour](https://cloud.githubusercontent.com/assets/147548/14770313/6e833166-0a66-11e6-85bd-96199f4616fe.png)

After turning-off `white-space: pre-wrap`:
![behaviour after turning-off `white-space: pre-wrap`](https://cloud.githubusercontent.com/assets/147548/14770312/6e827b90-0a66-11e6-8e8d-ef01fca516f7.png)

**Comment by xPaw** [comment]
You must rebuild the templates for this to be fixed.
