### ISSUE TITLE
Store user autocomplete order

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#289]
It was mentioned in #217 that we autocomplete order resets on refresh. It might be worth storing this in localstorage so we get consistency on a machine between refreshes. Would be nice.

**Comment by xPaw** [comment]
Using the server to keep track of it is nicer in multiple ways:
- No need to waste space in users' storage
- The sorting is consistent across all your client instances (e.g. different machines)
- If your client is shut down for a long period of time, the sorting is still consistent (xPaw sent the last message to the channel, he's the first to be completed when doing `x<tab>`

**Comment by YaManicKill** [comment]
Alrighty, well obviously that's better, but I wasn't sure if we would ever get that done. If you think it's not unachievable, then that's cool.

**Comment by xPaw** [comment]
We should be able to do it by simple reodering the user list on the server, instead of sorting it. Basically what the client does now.

Whenever there's a userlist update, sort it on the client.

**Comment by YaManicKill** [comment]
Is that the only thing that changes the autocomplete list? It doesn't do it based on who you

**Comment by YaManicKill** [comment]
Sorry, was typing a comment and decided against it. Meant to delete, but clicked the "close and comment" button. Sigh...

**Comment by astorije** [comment]
As mentioned in #217, I'm fairly against having a custom/obscure autocomplete order for nicks and would much rather be alphabetical, which is actually the current behavior on `master`. It is more practical from a user perspective.
Officially doing so would remove the need for the enhancement discussed here.

**Comment by xPaw** [comment]
Noticed we had this already.

My suggestion was: 
> This probably can be implemented by adding lastMessage timestamp on user object in channel, and updating it when a message is received on the server. Later this timestamp can be used to fix the order on the client.

**Comment by xPaw** [comment]
This is fixed by #1194
