### ISSUE TITLE
User list doesn't get re-sorted when users join

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#29]
The user list on the right is most of the time correctly sorted, except when a user joins the channel. For example:

<img width="825" alt="screen shot 2016-02-13 at 14 11 07" src="https://cloud.githubusercontent.com/assets/113730/13030668/46b597d2-d280-11e5-860d-a3958e2c09f2.png">

It looks like something as simple as clicking on another open channel and going back to it re-sorts the list, but not right when the user joins.

**Comment by xPaw** [comment]
There's a `sortUsers` call when a user joins, and looks like it doesn't work?
https://github.com/thelounge/lounge/blob/30b8a419cdb711808b68df08fe9612f0c646dbe8/src/plugins/irc-events/join.js#L23
