### ISSUE TITLE
Colon (:) is not correctly escaped in messages without spaces

### ISSUE THREAD

**Issue by PugaBear** [thelounge/lounge#293]
If I have a message starting with : , the semi-colon does not show. I've tested this on: my lounge->znc setup, just plain lounge, with a different client (it worked then), and multiple IRC servers, and I even had vectr0n duplicate it: 
```
19:45	PugaBear	hey guys, random question. Do you guys see my eyes in this smiley face?
19:45	PugaBear	:D
19:45	vectr0n		nope but shows the same in hexchat, so i blame my znc, lol
19:46	PugaBear	Can you try pls vectr0n ?
19:46	vectr0n		D
```

Update: If you add text after, it works fine. O.o

**Comment by maxpoulin64** [comment]
Fixed in irc-framework, waiting for it to be merged. https://github.com/kiwiirc/irc-framework/pull/45

**Comment by xPaw** [comment]
irc-fw has been merged.
