### ISSUE TITLE
Sending too-long message gets cut off without indication

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#295]
When you send a message above the IRC limit for a single message, it appears to have gone through correctly, but obviously it is cut off for everyone else.

We should either split the message and send as multiple (that's probably the better solution) or at least show the message as cut off. That's the simplest solution, if the IRC limit is a standard (I assume it is)

**Comment by dgw** [comment]
> IRC messages are always lines of characters terminated with a CR-LF
   (Carriage Return - Line Feed) pair, and these messages SHALL NOT
   exceed 512 characters in length, counting all characters including
   the trailing CR-LF. Thus, there are 510 characters maximum allowed
   for the command and its parameters.

— [RFC 2812](https://tools.ietf.org/html/rfc2812), Section 2.3 "Messages"

**Comment by DanielOaks** [comment]
This is especially important for `PRIVMSG`/`NOTICE` commands.

One thing I've seen clients do is wrap outgoing text to ~400 characters (a decently-large buffer of about 100 characters for server overhead and the nickmask+message framing overhead when being send to the target user) and send multiple messages.

The main problem with just showing it as cut off is that it's hard to tell exactly where it will be cut off, thanks to the output message containing nickmasks and other details. Wrapping and sending multiple makes for a better experience when generally chatting.

**Comment by YaManicKill** [comment]
Yeah, I definitely agree that sending multiple messages is ideal. Was just
throwing all the options I could think of out there.

**Comment by xPaw** [comment]
This appears to work just fine on master, as irc-fw has built in message splitting.

**Comment by YaManicKill** [comment]
Yeah, I'll close because it's fixed on master. Will be included in the next release.
