### ISSUE TITLE
Add tooltips to all icon buttons

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#304]
At the moment, only the icon buttons in the sidebar have a tooltip. The `Send` button even uses a `title` at the moment instead of a tooltip.

I tried to quickly add tooltips to all the icon buttons that did not have one as part of #303, but it turned out to be a bit more tricky than just adding the `.tooltipped*` classes / wrapping `<span>` elements so I gave up...

**Comment by astorije** [comment]
@xPaw, do you think you could help with this?

**Comment by xPaw** [comment]
You would need to wrap the buttons into `span` to add the tooltip (due to css wonkiness).
