### ISSUE TITLE
Road to complete IRCv3 support

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#312]
http://ircv3.net/irc/

### IRC Version 3.1
- [x] Capability Negotiation
- [x] `multi-prefix`
- [ ] `account-notify`
- [ ] `away-notify`
 - Requested but we don't do anything with it
- [ ] `extended-join`
 - Requested but we don't do anything with it
- [ ] `tls`

### IRC Version 3.2
- [ ] Capability Negotiation
 - Being worked on in https://github.com/kiwiirc/irc-framework/tree/cap_32
- [x] Message Tags
- [ ] `metadata`
- [ ] `monitor`
- [ ] `account-tag`
- [ ] `batch`
- [ ] `cap-notify`
 - This should be done in irc-fw
- [ ] `chghost`
- [x] `echo-message`
 - Also supports `self-message` for ZNC
- [ ] `invite-notify`
- [ ] `sasl`
 - Broken kiwiirc/irc-framework#43
- [x] `server-time`
- [ ] `userhost-in-names`

**Comment by astorije** [comment]
@xPaw, should we close this now that we have entries in http://ircv3.net/software/clients.html#web-clients or do you want to keep this around still? I'm fine either way.

**Comment by xPaw** [comment]
This issue was made for our own tracking, not their site.

**Comment by astorije** [comment]
Yes I get that, but I sense some duplication, hence my question. We can add more details here though, as you did.

On the contrary, I see that their tables has less columns than your lists. Is there anything worth doing on their side?

**Comment by DanielOaks** [comment]
We choose to not explicitly track Message Tags on that table because it's better for us there to track the features actually allowed by it there -- stuff like server-time and account-tag (it also just didn't fit in there nicely!).

**Comment by xPaw** [comment]
https://github.com/thelounge/lounge/projects/1
