### ISSUE TITLE
Enable/Disable logs on the settings

### ISSUE THREAD

**Issue by pierrevdk** [thelounge/lounge#314]
I'm using The Lounge on a [Cozy](http://cozy.io) and I don't have access to the line command side of the server.
Would it be possible to enable or disable the logs within the graphical interface? Because right now every time I update the app I loose my logs which is bothersome.
Thanks :)

**Comment by maxpoulin64** [comment]
The logs option you are referring to actually has nothing to do with the logs disappearing on the client after an update. The log options in the config only controls logging to file on the server. When then server restarts, it doesn't read said log file back. This is however a known issue (#110), so I am marking this issue as `invalid` for the first reason and `duplicate` for the other one. Thank you for your report anyway!

We hope to be able to fix that soon, long time known issue that a lot of us wants fixed. The only problem is that doing so is more complicated than it seems, as normal text IRC logs don't have enough context for us to replay it properly on the client.

**Comment by pierrevdk** [comment]
Alright thanks, and sorry about that!
