### ISSUE TITLE
Next release planning

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#326]

**Comment by astorije** [comment]
#325 ?

**Comment by xPaw** [comment]
@astorije Possibly, will see how the discussion goes.

**Comment by astorije** [comment]
#288 (ping @williamboman so he gets notification in case yes) ?

**Comment by YaManicKill** [comment]
#325 would be good to get in, because it's a big problem for people with dark themes. If we got that in, I would probably be happy with that being enough to push it to major release.

Especially as we generally seem happy with it, but yeah, let's have discussion on the actual topic.

**Comment by YaManicKill** [comment]
By the way, if we are planning on organising releases proper like this rather than just whenever we feel like it, we should probably use the milestones on github. They work really nicely for dealing with that.

**Comment by astorije** [comment]
Closing this now that we have a proper milestone.
