### ISSUE TITLE
Update some IRC colors to be readable in all themes

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#335]
For example blue and purple colors in Morning themes are barely readable due to being too dark.

We should check that all the colors we define are readable and work in themes we ship (not necessarily pass AA, but not completely dark).

**Comment by JustRamon** [comment]
What if you made several presets that themes can define themselves?

**Comment by xPaw** [comment]
It's already a preset. https://github.com/thelounge/lounge/blob/e6990e0fc7641d18a5bcbabddca1aacf2254ae52/client/css/style.css#L1441-L1508

The point is to fix some colors in different themes so they all look good and readable.

**Comment by xPaw** [comment]
Made test page: https://s.xpaw.me/lounge-colors.html

**Comment by astorije** [comment]
***Complete off-topic***

> Made test page: https://s.xpaw.me/lounge-colors.html

This is a great idea. It would be to have a static HTML page following this idea to help designing themes, pre-filled with content, URLs, etc.
