### ISSUE TITLE
Nick color changes when nickname changes 

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#340]
When someone changes their nickname the nick color changes as well (see bottom half of image, will crop once on desktop)

<img src="https://sr.ht/CqUS.png" width=300>

**Comment by astorije** [comment]
Following-up the discussion on the IRC channel:

> **+xPaw**	Giraffe_, we can't fix that in any non complicated way
> **+Max-P**	I should make myself invisible in that room
> **+Max-P**	Giraffe_: yeah, to extend on what xPaw said it's really hard to do because we'd need to keep track of all nick changes and persist that. This is going to end up with a massive database. For every nick lookup, of course.
> **+Max-P**	Another alternative would be to derive the color from the ident+hostname, but then there's chances of duplicates and it's not all that reliable either.
> **+Max-P**	Our best chance or that would be to use the nickserv accounts when available, but from there that's clearly the matter for a plugin and bot a default feature

To me, it's a non-trivial issue that will most likely lead to bigger issues. My take on this is that we shouldn't care about it and leave it as is on purpose, or think about it to a much, much later time.

**Comment by dgw** [comment]
This is, indeed, non-trivial. In my experience it's rare for a client to try to persist nick colors across nick changes, likely for precisely the reasons @maxpoulin64 pointed out on IRC.

**Comment by maxpoulin64** [comment]
Should we close this as a wontfix?

**Comment by astorije** [comment]
> Should we close this as a wontfix?

I say yes.
