### ISSUE TITLE
CTCP ACTION messages do not split

### ISSUE THREAD

**Issue by omnicons** [thelounge/lounge#342]
Seems to be an irc-fw bug, was told to post it here for tracking.

**Comment by xPaw** [comment]
It's not really a bug, due to somewhat undefined CTCP behaviour. Would we want to split all the CTCP messages, or specifically just the actions?

**Comment by omnicons** [comment]
I'd at least want the actions split since most other CTCP messages aren't
long enough to split. And that's the biggest current problem that the
people on my bouncer using it have (Many of them roleplay and such)

**Comment by maxpoulin64** [comment]
Fixed in irc-framework, now waiting for a version bump.

**Comment by maxpoulin64** [comment]
Huh, apparently the upstream merge closed this issue. Reopening until irc-framework does a version bump and this is fixed in thelounge as well.
