### ISSUE TITLE
Channel name placeholder in input

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#343]
This was suggested in the irc:

```
15:42   Parabola requests that my name next to the editbox be replaced with the current channel name
15:42   Parabola    seems like seeing my own name is pointless anyway
15:43   gweedo767   channel name could be more help in the mobile view too
15:44   gweedo767   since the channel list isn't visible then
```

I quite like this idea. Thoughts?

**Comment by xPaw** [comment]
Don't know about removing the username, but having a placeholder like `Write to #channel` might be helpful.

**Comment by astorije** [comment]
I really don't like the original idea from a user experience standpoint and, like it or not, when you're on several networks, it's useful to have your nick displayed. Also, it's going to be a very nice place to update your nick.
Plus, the channel name is already repeated at least twice: in the sidebar and in the title bar.

That being said, 👍 to @xPaw's idea, very clever, very simple and rather appropriate! Plus screen readers will be able to read it, so there is that.

**Comment by YaManicKill** [comment]
> when you're on several networks, it's useful to have your nick displayed

As someone who uses the same username everywhere, I don't really mind about that. But if other people find it useful, I'll keep it. I'll just keep it hidden in my css :-P

> but having a placeholder like Write to #channel might be helpful.

Yup, I like this.

**Comment by maxpoulin64** [comment]
I'm not sure I like the idea of a placeholder. I think it makes the UI feel more bloated than it needs to be, and there isn't much customization available to placeholder texts. I really don't see the need for this as the channel name is already in the top bar anyway.

**Comment by YaManicKill** [comment]
I thought this (the placeholder) got implemented at some point, but I guess not.

**Comment by astorije** [comment]
I forgot about this @YaManicKill (what happens when there are too many issues :D), so just opened #832.
