### ISSUE TITLE
Difference between Shout and Lounge

### ISSUE THREAD

**Issue by kabarca1** [thelounge/lounge#349]
What's the difference between Shout IRC and Lounge IRC clients? The websites both look the same.

**Comment by vectr0n** [comment]
https://github.com/thelounge/lounge/wiki/Differences-between-The-Lounge-and-Shout

**Comment by MaxLeiter** [comment]
See "Why the fork?" on the [README](https://github.com/thelounge/lounge/blob/master/README.md) and the link @vectr0n just commented

**Comment by maxpoulin64** [comment]
I'll also add that [Shout also references The Lounge](https://github.com/erming/shout/blob/master/README.md#official-forks) as the actively maintained community fork. Shout was erming's personal pet project and he prefered to keep it as is, thus why a fork and a new name. The fork is more community oriented and we focus on building a client that fits most people's needs.
