### ISSUE TITLE
Put thelounge in ircv3 compat table

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#350]
It was pointed out in the irc that there is a [compat table](http://ircv3.net/software/clients.html) for irc clients and what irc v3 specs they have.

It would be good if we were there, would increase our visibility. 

Very easy ticket that anyone can pick up.

**Comment by xPaw** [comment]
#312 shows our current status

**Comment by astorije** [comment]
This is a great idea!

**Comment by omnicons** [comment]
I've submitted a PR on their end for it  [ircv3.github.io PR #93](https://github.com/ircv3/ircv3.github.io/pull/93)

**Comment by YaManicKill** [comment]
Brilliant, looks like it's merged.

Thanks, @omnicons

**Comment by omnicons** [comment]
You're welcome! Glad to be able to help.

**Comment by xPaw** [comment]
Nit: I think it should have been called `The Lounge` in the list.

**Comment by omnicons** [comment]
Why? Everyone around just calls in Lounge.

**Comment by xPaw** [comment]
That's what the software is called, look around the site, readme, etc.

**Comment by omnicons** [comment]
Sure I guess.

**Comment by astorije** [comment]
Thanks for this, @omnicons!

I also opened an issue to point to the official website rather than the repo. This matches what all other entries in this table do.

Will be great to track how we expand our compat :-)
