### ISSUE TITLE
Add to up-for-grabs

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#351]
[Up for grabs](http://up-for-grabs.net) is a great service that shows a list of projects that have an "up for grabs" label. This label is specifically for very small tickets that can be fixed by someone who has never contributed to open source software before, or for people who want to get involved in a new project.

We just need to create a PR to add us to the list.

I'm going to be meta now, and add the "up for grabs" label to this ticket.

**Comment by dgw** [comment]
Nice meta. 👍  I'll do this if nobody else has gotten to it by Friday night.

**Comment by maxpoulin64** [comment]
Sounds like a good idea, :+1:

**Comment by astorije** [comment]
Is this actually used though? FYI we were using a `quick and easy` label for that exact purpose, and I don't recall seeing it used/useful even once... :-)
But if it helps us and helps people get into FOSS, for sure!

**Comment by YaManicKill** [comment]
We were? I didn't notice a label with that name. If it wasn't being used,
probably because people didn't know? Happy to use the quick and easy one
instead.

**Comment by dgw** [comment]
As a side note, it looks like the maintainers of up-for-grabs might want to see some open issues tagged for display over there before merging. If a maintainer could go through and label some easy open issues, that'd be great!

I'm ready to do this, but am still waiting to actually open a PR until the time I stated yesterday.

**Comment by maxpoulin64** [comment]
Could also be useful to add that we have an IRC channel to help those people complete their tasks. I also volunteer to give access to my own Lounge instance if they need a bouncer and possibly mentor them as well if needed. I'm on IRC a lot (even if usually busy) so I can generally help quickly :P

Maybe we could make a wiki page detailing that.

**Comment by dgw** [comment]
Where would you add that? The only real free-text area is the description. I haven't looked at *all* the projects listed on their site, but none of the top 25% or so (dozens of projects) have anything but the actual project description there, as it might appear in a Github repo tagline or at the top of a README.

Or did you mean just adding a link to the description pointing at a wiki page with contribution tips/help? I could get behind that. A link wouldn't be too tacky.

**Comment by YaManicKill** [comment]
@dgw  I have added a bunch of tickets to the label. Hope that's enough to get us started.

**Comment by dgw** [comment]
The Lounge has been added to Up For Grabs. See [IRC tag](http://up-for-grabs.net/#/tags/IRC).

**Comment by YaManicKill** [comment]
Thanks, @dgw.

**Comment by astorije** [comment]
Great @dgw, thanks!

Sorry @YaManicKill, I meant on Shout: https://github.com/erming/shout/issues?q=is%3Aopen+is%3Aissue+label%3A%22quick+and+easy%22
But the idea is the same, except that this time it's used more broadly, love it!
