### ISSUE TITLE
Can't join multiple channels separated by comma

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#358]
Using the Connect screen, you can't join multiple channels separated by a comma (and by default the channels input is filled with two channels separated by a comma).

![image](https://sr.ht/1adj.png)
https://sr.ht/hEfd.webm

**Comment by xPaw** [comment]
It parses join string by space, and first part is used as channels, and second part used as join key.

So there shouldn't be a space after comma.
