### ISSUE TITLE
Clicking on a user with an existing query window open doesn't bring focus to it

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#362]
If you have a user query window open, clicking on it does a whois, but doesn't bring the focus to that query window. Clicking on a channel brings focus to that channel, and this is what I would expect.

**Comment by dgw** [comment]
Can confirm. I am on 1.5.0, though, not master.

**Comment by xPaw** [comment]
Sounds like this can be fixed client side by directly focusing the query window if there's one.
