### ISSUE TITLE
Use and respect environment variables?

### ISSUE THREAD

**Issue by williamboman** [thelounge/lounge#365]
E.g. stuff like `LOUNGE_HOME`;

```diff
diff --git a/src/command-line/index.js b/src/command-line/index.js
index d81988b..e368db3 100644
--- a/src/command-line/index.js
+++ b/src/command-line/index.js
@@ -13,7 +13,7 @@ program.option("    --home <path>" , "home path");
 
 var argv = program.parseOptions(process.argv);
 
-Helper.setHome(program.home);
+Helper.setHome(program.home || process.env.LOUNGE_HOME);
 
 if (!fs.existsSync(Helper.CONFIG_PATH)) {
 	mkdirp.sync(Helper.HOME, {mode: "0700"});

```

**Comment by xPaw** [comment]
We previously (ab)used `HOME` env variable, but then fixed it to only rely on the `--home` variable. I don't see why would want to support env variable along with the input argument.

**Comment by williamboman** [comment]
It quickly becomes quite cumbersome to use the cli as soon as you want to use another path. This would mainly be very handy in contained setups, such as Docker, for seamlessly interacting with the cli without the need of `--home`-ing everything.
