### ISSUE TITLE
[DNSBL] Blacklists

### ISSUE THREAD

**Issue by Arkadietz** [thelounge/lounge#373]
Hello,

I believe and many others like me this is a must future. Will be total blaster if we have this future.
Here is the example. Anyone user join and before join in any network he is checked in databases. 
Databases can be modified. From my nearly 17 years expirience in IRC i can say here is the list with the best:

```
blacklist {
        host = "rbl.efnetrbl.org";
        type = ipv4;
        reject_reason = "${nick}, your IP (${ip}) is listed in EFnet's RBL. For assistance, see http://efnetrbl.org/?i=${ip}";

        host = "dnsbl.dronebl.org";
        type = ipv4;
        reject_reason = "${nick}, your IP (${ip}) is listed in DroneBL. For assistance, see http://dronebl.org/lookup/";

        host = "tor.kewlio.net.uk";
        type = ipv4;
        reject_reason = "${nick}, your IP (${ip}) is listed in tor.kewlio.net.uk. For assistance, see https://www.dan.me.uk/torcheck?ip=${ip}";

        host = "tor.dnsbl.sectoor.de";
        type = ipv4;
        reject_reason = "${nick}, your IP (${ip}) is listed in tor.dnsbl.sectoor.de. For assistance, see http://www.sectoor.de/tor.php?ip=${ip}";
};
```

**Comment by xPaw** [comment]
Isn't it the job of irc servers to check the blacklists, why should we (the client) do it?

**Comment by dgw** [comment]
Could be used for public instances of The Lounge that allow user registration? But it should still be the network's job to check, because The Lounge will pass through the client's details using WEBIRC.

**Comment by maxpoulin64** [comment]
Please don't put `must have feature` in the title. It's arrogant and doesn't serve any purpose other than actually lowering the priority of the issue.

As for the issue itself, seems reasonable. It's already up to the servers to check for themselves, but decreasing the number of attempts right on the frontend isn't a bad thing :+1:. As the others said, for now it can be done with a reverse proxy.

**Comment by astorije** [comment]
I don't think we will ever get to implement this ourselves. @Arkadietz, are you willing to give a shot at coding this?
Otherwise @thelounge/maintainers, I suggest closing this since there is an alternative on the server side of things.

**Comment by maxpoulin64** [comment]
Discussed on IRC, we'll close it. If anyone wants to implement it, feel free to do so! But we currently don't see this as a bug as anyone with an instance open to public registration really *want* to have webirc or hexip support from the network they connect to. Even with a blacklist and a captcha, you still need one single person to abuse it to get your whole IP banned: it doesn't do much. Webirc or hexip will pass that information through to the network and solve that issue at the network level.

Another possible workaround would be to do it via your web server. I'm sure Apache or nginx support DNS blacklists.
