### ISSUE TITLE
HEX (hexadecimal) ident

### ISSUE THREAD

**Issue by Arkadietz** [thelounge/lounge#374]
Hello,

In the moment you can set only one ident. And for example if someone ban this ident multiple uses will be impact and that's not good for me. This future is already done in webirc clients like qwebirc and lightirc. 

Example:

[19:28:58] \* BGChat70516 (5ec578c8@BGChat.html.chat) has joined #Bulgaria

Where the ident : 5ec578c8 = IP ( 94.197.120.200 )

**Comment by dgw** [comment]
WEBIRC support has already been merged: #240

**Comment by maxpoulin64** [comment]
This is partly being addressed in #256. The hex indent is non-standard and so far I think only Freenode uses that. If the user connects over IPv6 the number won't fit anymore. For that purpose webirc is a better solution.

**Comment by MaxLeiter** [comment]
Can be closed as of #749

**Comment by astorije** [comment]
Can someone open an issue with details in https://github.com/thelounge/thelounge.github.io ? The moment that I'll go into heavily improving our docs is getting closer and closer, and that would help making sure there is room for this.
