### ISSUE TITLE
Remove mkdirp in favor of fs-extra

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#380]
@astorije added `fs-extra` in 8ebe29fca53c30618b322168a969733d2f314174, and it has duplicate functions of `mkdirp`

**Comment by xPaw** [comment]
Quickly looked at the code, and there's `mkdirp.sync` all over the place. We should only be creating the folders when starting the process.

**Comment by astorije** [comment]
@xPaw, to be fair, I was not trying to replace or supplement `mkdirp` in #361. Actually... I didn't even look that we were already using `mkdirp` when I added `fs-extra`, so my fault on that.

Now, there are 2 ways we could go with this: do you think we should replace `mkdirp` calls to `fs-extra`'s `ensureDir` counterpart, or replacing using `fs-extra` in the build script with `mkdirp` and find a way of copying files cross-OS in JS?
The [vanilla-Node solution](https://stackoverflow.com/questions/11293857/fastest-way-to-copy-file-in-node-js) I found when implementing the script did not strike me as something nice to maintain, but on the other hand, `fs-extra`'s `copy` does not handle wildcards (yet?).
I have no strong opinion on this, solution might even be a third option. Right now, I'm leaning towards using `fs-extra` as you mention here. A bit more maintained, a bit more solid.

> We should only be creating the folders when starting the process.

Clearly, [creating the users folder when attempting to get the list of users](https://github.com/thelounge/lounge/blob/4f56200067b522b1f761aa68c5089d5976006565/src/clientManager.js#L55) is not something very reasonable :-)

**Comment by astorije** [comment]
Also, this seems to me like a good candidate to the `up for grabs` label, feel free to add.

**Comment by xPaw** [comment]
`fs-extra` has some nice methods that we might use in the future. I would opt into using it.

**Comment by hogofwar** [comment]
Is it needed to check the directories each time, such as in the[ example](https://github.com/thelounge/lounge/blob/4f56200067b522b1f761aa68c5089d5976006565/src/clientManager.js#L55) astorije posted? Would simply removing that sync and ensuring the folders exist at startup be enough?

**Comment by xPaw** [comment]
@hogofwar That's exactly what I pointed out in the issue.

**Comment by hogofwar** [comment]
Was just checking that there is no need to ensure the folders exists at those points, so no need to have any sort of folder-checking code to replace the sync calls.

**Comment by hogofwar** [comment]
This should be closed as fixed in #390.
