### ISSUE TITLE
messages without a whitespaces are not sent to the server

### ISSUE THREAD

**Issue by TurBoss** [thelounge/lounge#383]
hi

I'm implementing a lounge client and when i try to comunicate with others in some char room
some messages are sent but not all

thelounge console shows nothing and the javascript console nothing too :(

sry the poor info but I don't have any more ...
here is an screenshoot about the problem 

1º  shout 2º  lounge 3º the game client
http://imgur.com/DNAyuVD
thx!

**Comment by TurBoss** [comment]
maybe my server...

**Comment by TurBoss** [comment]
I noticed that when I add a whitespace to the end of the msg 
this msg goes to the server

**Comment by TurBoss** [comment]
any msg without a whitespace in any place are not sent

**Comment by dgw** [comment]
Seems to be your server. I can send single words without any whitespace to IRC just fine.

**Comment by xPaw** [comment]
This is midly related to #293. It sounds like we must always put a colon when sending a PRIVMSG.

**Comment by YaManicKill** [comment]
@TurBoss Can you check if this works on master now that #293 is fixed?

**Comment by xPaw** [comment]
@YaManicKill It won't. His issue is that the proxy he's using does not respect the IRC RFC and always requires a `:` in PRIVMSG, which is incorrect.

**Comment by TurBoss** [comment]
I have tested and does not work

**Comment by YaManicKill** [comment]
Oh, right. In that case, if it's an issue with his proxy not respecting the
rfc, does that mean we should close this? I don't think we want to be
fixing things for broken servers or proxies.
