### ISSUE TITLE
Document nginx routing

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#385]
This is mainly just a reminder to myself to do this.

People constantly asking about nginx/apache routing etc. So I will stick up my config on the wiki.

**Comment by xPaw** [comment]
https://github.com/thelounge/lounge/wiki/Reverse-Proxies

Anything missing?

**Comment by cnf** [comment]
I just tried this, and I only get "Cannot GET /irc/".

Did I miss something?

**Comment by xPaw** [comment]
I don't know how Caddy does the routing, but perhaps the ending `/` is breaking it?

**Comment by maxpoulin64** [comment]
> I don't know how Caddy does the routing, but perhaps the ending / is breaking it?

I don't know it either, but I know nginx does two different things depending on how the `proxy_pass` is written:

```
location /irc/ {
	# Passes the whole /irc/ along to localhost
	proxy_pass http://localhost:9000;
}

location /irc/ {
	# Maps /irc/ => / on the backend server
	proxy_pass http://localhost:9000/; # notice the leading / meaning the root path to proxy to
}
```

We require the latter, which works fine as we use only paths relative to the index.html file on the client so it just works without us having any knowledge of the proxy setup. So you'll want to achieve the same setup with Caddy, or use a real webserver.

**Comment by cnf** [comment]
so caddy needs 

```
proxy /irc http://172.17.0.1:9000 {
    proxy_header X-Forwarded-For {remote}
    without /irc
    websocket
}
```

which isn't the cleanest way, and might make asset management etc more difficult in the future. Most software I proxy for let me set the path, or detect it from `proxy_header X-Script-Name /<path>`

but the above works for Caddy, so maybe you can include it in the documentation.

**Comment by xPaw** [comment]
We should also add `location` routes for `js|css|img|audio|themes` as it's all static content, and there's no need to pass on the request onto node.

**Comment by konstin** [comment]
The [nginx guide](https://github.com/thelounge/lounge/wiki/Reverse-Proxies) said, that the lounge had to bind to 127.0.0.1. But for me it only worked when leaving `undefined` instead of 127.0.0.1. Otherwise the guide works fine and should be included in the official documentation.

**Comment by YaManicKill** [comment]
I think this is done then, apart from the issue with what exactly to use as the host?

**Comment by astorije** [comment]
@konstin, I will be adding this in the official documentation in a few days. Note that "official documentation" means "supported and maintained", which is not a responsibility to take lightly.

Also, note that this is an open source project being entirely managed during volunteers' free time, and as a consequence, "expecting" as a user has a different meaning than professional services. Also, I would argue that this is not essential information to install and run the project, even though it's a nice to have.

**Comment by konstin** [comment]
I'm maintaining two open source website myself, so I totally get your point with responsibility and expectations. I didn't mean "expect" in the way of being an obligation towards the user but rather from an UX point of view, as it is quite surprising to find this in the github wiki. And though most users are likely fine with the standard nodejs setup, installing it besides other services without switching to a different port requires a reverse proxy, so having this in the official documentation is imho something worthwhile, even it if that configuration isn't a hundred percent up-to-date and tested.

**Comment by astorije** [comment]
Alright, all good then :)
And yeah, I'll definitely include this in the docs, thanks for your input.
