### ISSUE TITLE
Alpine based Dockerfile for the lounge

### ISSUE THREAD

**Issue by rgarrigue** [thelounge/lounge#39]
Hi guys

I made a Dockerfile for the lounge, based on Alpine linux. It's quite space saving

    root@vps: ~ # docker ps -s --format "{{.Names}}: {{.Size}}"
    w7pea_lounge: 4.013 kB (virtual **719.7 MB**)
    alpine_lounge: 0 B (virtual **66.81 MB**)

[It's here](https://github.com/rgarrigue/docker-thelounge). I could make a pull request but I'm not sure where I should put that in thelounge sources?

**Comment by astorije** [comment]
Can @W7PEA or other Docker experts advise on this?

Regarding where to put it, I am strongly in favor of exporting Docker-specific stuff to a different repo in the organization, but I would like to get an opinion from others (if it should stay for minor convenience only then this is not good enough, it's quite inconvenient for us to keep it inside).

**Comment by rgarrigue** [comment]
Updated link in my initial message, I moved it around to plug a hub.docker automated build.

**Comment by W7PEA** [comment]
Hey @rgarrigue can you post the link to your container on hub.docker.com.
Definitely its own repro.
The question in my mind is does it pull the code from the tagged releases in github or does it use npm install to do so. Both are valid. I'm not sure if the install of a nodejs app from gh is much different than the npm install method, one of you would need to answer that.

**Comment by rgarrigue** [comment]
Hey, sorry for the late reply, was kinda busy

I'm using the `npm install` way. Here is the [docker hub page](
https://hub.docker.com/r/rgarrigue/thelounge/), but I'm hitting the WTF
wall here. It build on my server, but there's this npm compilatiion issue
on hub.docker.com.... driving me nutty. Gonna fix that whenever I find out
what's wrong.

Anyway, the whole point is about size as far as I'm concerned. I'm running
my own little vps with little disk space, using alpine as a base is a real
difference.

2016-02-19 7:29 GMT+01:00 Patrick <notifications@github.com>:

**Comment by astorije** [comment]
A new repo specific to the Docker container has been created: https://github.com/thelounge/docker-lounge.

Therefore I'm going to close this issue, but I encourage you to re-open it on the new repo (with a link to this issue) if it's still relevant.

Thanks!
