### ISSUE TITLE
Remember history between connections

### ISSUE THREAD

**Issue by karbowiak** [thelounge/lounge#392]
Hi there..

Currently when Lounge reconnects / get restarted, all history is lost - would be nice if this wasn't the case :)

**Comment by dgw** [comment]
Duplicates #110. (See #253)

**Comment by vpicavet** [comment]
#110 is closed but history seems not to be restored when the server restarts. Anyone confirms ?

**Comment by xPaw** [comment]
It's not restored on server restart. But there is a PR to do it #663.
