### ISSUE TITLE
Slideout menu bar for mobile

### ISSUE THREAD

**Issue by karbowiak** [thelounge/lounge#393]
Hi there..

Currently i find myself constantly sliding my thumb from the left side, to the right, to get to the sidebar with all the channels, all to no avail.

Something like https://mango.github.io/slideout/ could fix that i'm sure (i suck at JS to be honest) :)

**Comment by astorije** [comment]
Whoever takes this, please share design decision here. In particular, if using a third-party library, explore options and let us know why one more than the others :-)

**Comment by xPaw** [comment]
Yeah it's really hard to find an actually good library for this. Just tried Slideout.js, it's not awful, but it has some delay/lag issues.

**Comment by maxpoulin64** [comment]
I just swapped the label to help wanted, because it's really not an easy one so it's definitely not an up for grabs.

**Comment by dgw** [comment]
Caught myself trying to slide out the side menu yesterday, but it's not exactly a common feature for webapps to support. I can't think of one that does off the top of my head.

Would be a real feather in The Lounge's cap if this was implemented, though. The few, the proud, the menu-sliders!

**Comment by maxpoulin64** [comment]
[Annnnd here we go!](https://d.max-p.me/irc/slideout.html)

Probably needs a bit of tweaking to fit The Lounge, but it works.

**Comment by maxpoulin64** [comment]
Alternatively, it seems like [this is the cause](https://github.com/Mango/slideout/blob/master/index.js#L170-L176) of the delay in the existing one, so it should be relatively easy to fix upstream and we could then use this implementation and throw away mine.

**Comment by astorije** [comment]
For what it's worth, I was pointed to https://events.google.com/io2016/ as a decent-looking implementation of a slideout menu. I haven't looked at the code at all, so I don't know if we can make any use of this (like if it's not possible to know which lib they are using...).
