### ISSUE TITLE
electron lounge shell

### ISSUE THREAD

**Issue by pguth** [thelounge/lounge#404]
This really should get an electron stand-alone release :D

**Comment by dgw** [comment]
So…it would run the server and the client on the local machine, and quit the server when the user closes the window?

**Comment by pguth** [comment]
To give Lounge (and other webapps) a native feeling Chrome offers the `--webapp` flag but that solution has two downsides:

- When switching Wifis the client goes down and does not come up again when the connectivity is restored.
- `Assign to: [Desktop 1...n]` is not available on MacOS.

That's why I think an electron container that just cares about reloading on restored connectivity would be quite an improvement on MacOS.

<img width="249" alt="screen shot 2016-06-13 at 23 20 23" src="https://cloud.githubusercontent.com/assets/85259/16023542/7a461f12-31bd-11e6-8225-7d86679c785c.png">

**Comment by williamboman** [comment]
[nativefier](https://github.com/jiahaog/nativefier) might be of interest.

**Comment by pguth** [comment]
Oh, yes. Thanks @williamboman!

Maybe give that hint in the readme right away like so https://github.com/thelounge/lounge/pull/405?
