### ISSUE TITLE
Don't use protocol-relative URLs for external links

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/lounge#406]
This sounds confusing, so I'll explain.

Assume someone posts a link like this: `www.some.domain`
Lounge's URL parser will make that clickable, turning it into `<a href="//www.some.domain"` (note that no protocol is given).
Assuming you're using The Lounge over HTTPS, the browser will open `https://www.some.domain` when you click. **This is problematic** because many websites still run http only, leading to The Lounge giving you dead links. Also, when someone links to a webpage without protocol, chances are they mean http and not https.

When you type `www.some.tld` into your browser's URL bar, it will assume http (unless you use a plugin like HTTPS everywhere, which will fall back to http if https does not work), so I think The Lounge should do the same.

Consequently, I suggest that Lounge adds `http://` to protocol-less URLs, instead of just adding `//`.

I am assuming that the most common cases are:
- Server is running http only (in which case nothing listens on 443)
- Server is running http and https (you get what you surf to)
- Server is running http and https (you're being redirected to https when you access http)

In each of these cases it's safe to always link to http (when no protocol is given in the URL), whereas in one case always linking to https will lead to a browser error message, leaving the user thinking they were just given a dead link.

**Comment by YaManicKill** [comment]
Yeah, although there is a possibility of http being wrong, I think we should go to http.

Reason being that if you type in the url to a browser without a protocol, it will send you to http by default. So we should do the same as that.

**Comment by xPaw** [comment]
Looks like an easy fix right here: https://github.com/thelounge/lounge/blob/ee5a64436c5ad673072fde2d6466f3cf2e5446cf/client/js/libs/handlebars/parse.js#L17

**Comment by dgw** [comment]
Up for grabs?

**Comment by astorije** [comment]
It's pretty sad that we have to go for that direction and not the other (default to HTTPS).
After all, using HTTP on all requests does have a security impact, as it leaks the request through the network! Plus there are still many websites that serve both without a redirect...

I guess using browser behavior (which may change someday soon) is the conservative choice then. Maybe when we do that we should add a note in the documentation, recommending to use something like HTTPS Everywhere to ensure maximum privacy.

**Comment by dgw** [comment]
Running The Lounge over HTTPS itself will prevent at least leaking the referrer to insecure sites, [per RFC 7231](https://tools.ietf.org/html/rfc7231#section-5.5.2) (and 2616 before it). That's small consolation, though.

It would be nice to default to HTTPS, yes, but sadly the Internet isn't ready for that. Probably the vast majority of sites that offer HTTP but not HTTPS do not even listen on port 443. It's a slow transition, to be sure. We'll get there…eventually.

**Comment by xPaw** [comment]
@astorije Like it or not, but browsers default to using http as majority of the sites only work over http.

It's up to the site maintainers to redirect to https properly, if they have it set up.

**Comment by astorije** [comment]
@dgw and @xPaw, I fully agree. Hopefully things will change someday soon :-)
