### ISSUE TITLE
Join keys are not stored

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#412]
https://tools.ietf.org/html/rfc2812#section-3.2.1

We need to store them in `Chan` object and need to write them to user config to correctly rejoin the channels. To fix this in the user config, I think we need to deprecate the `join` string, and store the `channels` array properly (only name and join keys).

**Comment by amcgee7** [comment]
I'd like to optionally store the join key's in the json file and allow users to enter the key with the channel when they add the network?  Any guides out there?  I don't know the code that well.

**Comment by spookhurb** [comment]
I have a fix for this!
