### ISSUE TITLE
Check if ssl key files exist instead of crashing with a cryptic error

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#416]
We need to report user friendly messages, instead of messages like `Error: ENOENT: no such file or directory, open ''`

**Comment by toXel** [comment]
Should the server still shutdown after the missing key file error? Or should it just print out the error message and continue in HTTP mode without SSL?

**Comment by astorije** [comment]
> Should the server still shutdown after the missing key file error?

That, yes!

> Or should it just print out the error message and continue in HTTP mode without SSL?

No, if you set up your server to run with HTTPS, making it run in HTTP as a fallback is very unsecure-looking.

**Comment by toXel** [comment]
> No, if you set up your server to run with HTTPS, making it run in HTTP as a fallback is very unsecure-looking.

Oh yes that's definitely a point.

So I would like to look into this issue. It's Hacktoberfest! ;)
And I really like this project of course 👍

**Comment by astorije** [comment]
> So I would like to look into this issue. It's Hacktoberfest! ;)

Awesome! :)
Post here if you run in any trouble or need to make some design decision.

**Comment by toXel** [comment]
Yea I have one question: would it be better to check if the key files exist before loading them? Or should I just add a try/catch?
