### ISSUE TITLE
Add a CLI param to override config variables

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#419]
Something like `-c https.enable=true`.

This would remove the need to have ip/port/public/private params.

**Comment by toXel** [comment]
Should the ip/port/public/private params be removed in the same PR? I'll look into this issue

**Comment by xPaw** [comment]
@toXel We'd want to deprecate them as not to break backwards compatibility for now.

**Comment by astorije** [comment]
@xPaw, I'm a bit on the fence about this idea. What's wrong with having explicit `--port`, `--private` etc. instead of `-c port`, `-c private=true`, etc.?
It might result in argument parsing duplication, but it's nicer from a CLI user point of view.

I'm not close to the idea, I just want to discuss the outcome before someone spends time on this :-)

**Comment by toXel** [comment]
The thing is: at the moment the parameters are not working correctly. For example:
`lounge start --port 1234` or `lounge start -P 1234` starts Lounge on default port 9000. Same with `lounge --port 1234 start` (That's the way `lounge -h` describes the usage)
To make it work you have to do `lounge --port 1234`, `lounge -- start --port 1234` or `lounge -- --port 1234 start` which is not the way it should be, I think.
The whole CLI params parsing implementation has a problem.

**Comment by astorije** [comment]
Thinking back at this, and after fiddling with command line code and discovering the madness there, I agree with this.

A few random thoughts about the CLI, some of them being related to this very issue:

- `lounge <subcmd>` is a nice thing, àla git. Problem is, it is very poorly handled at the moment. This should be improved by respecting [this](https://github.com/tj/commander.js#git-style-sub-commands) (we use `cmd`, just not correctly 😅)
- `config` subcommand is pointless and should be deprecated. Config will most likely always be this config file and can be edited with any text editor (as opposed with user management which might evolve and subcommands for that are just a nice abstraction over that).
- `private`/`public`/`host`/`bind`/`port` are indeed not necessary here for a normal use case. Esoteric use cases can use your suggested option.
- Some options are still good to have: location of the configuration (currently `home`, but I'm not too happy with how it's handled), `--help`, `--version`, and maybe `--debug`? (even though this latter one can be enabled with your suggestion, there might be some benefits in having it at this level, like debugging configuration file issues, etc.)

So anyway, 👍 on the idea with some suggestions.
