### ISSUE TITLE
Using The Lounge on a flaky network leads to a very schizophrenic front-end

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#421]
The client is not particularly good at recovering from network problems, it seems. Even in 2.0.0-pre.3 any timeout while the client is open leads to a full-page reload.

Unfortunately my LAN is very, very flaky tonight and can't keep connections open for more than about 30 seconds. I was hoping The Lounge would be more stable than a desktop client, but neither allows me to reliably send and receive IRC messages; lines both to and from the server are randomly dropped without any warning in both.

I don't suppose The Lounge's architecture would support falling back to some kind of polling if the network is so flaky that persistent connections simply don't work?

**Comment by YaManicKill** [comment]
> I don't suppose The Lounge's architecture would support falling back to some kind of polling if the network is so flaky that persistent connections simply don't work?

Socket.io already does this.

The real problem is that when we lose connection, we tell the page to reload. Ideally, we should not do that, and let socket.io reconnect. The problem with just switching that one (we've tried) is that the server never expects this to happen, so we get a bunch of initial connection information and we send all the channels and their messages again, and it becomes a mess.

**Comment by dgw** [comment]
I see. So the client could do it, in theory, but it would require server-side changes (I'm simplifying a lot).

Could making those changes to the server be a goal for 2.1? 3.0? There's already a lot slated for the 2.0.0 release—and it's been 3 pre-releases already anyway—but improving the reconnection support seems like a good goal now that it's at least implemented for both client<->server and server<->network.

**Comment by YaManicKill** [comment]
> Could making those changes to the server be a goal for 2.1? 3.0?

**Comment by astorije** [comment]
So, if someone ever wants to tackle with this one (which would be really awesome) and wants some history/archives, @unconed gave a try at this in #267.
Feel free to stop by the channel (`#thelounge`) if you need help with this.

**Comment by kode54** [comment]
Absolutely useless on my Android tablet, as it times out by the time it finally finishes Authorizing after a login. It takes about 30 seconds to Authorize, then briefly flashes the last channel viewed buffer, then the names list appears empty, then it immediately flashes back to Authorizing... repeat until I grow bored of watching my tablet cycle itself to death.

**Comment by xPaw** [comment]
Will close this issue as #1471 most likely fixes this, and there's not any specific problem we can tackle besides that.
