### ISSUE TITLE
Docker installation failed

### ISSUE THREAD

**Issue by Chouchen** [thelounge/lounge#436]
I followed [the instructions](https://thelounge.github.io/docs/deployment/docker.html) and everything seemed to work.

Anyway, going to the page gives somes 404 and the app doesn't work (obviously).
![2016-06-28 23_39_41-the lounge](https://cloud.githubusercontent.com/assets/383673/16433282/b893f12c-3d89-11e6-8361-7790afb23851.png)

When I `ls -al /home`, I don't see a `lounge` home which should be here if I understand "Step 2 : RUN useradd --create-home lounge"

It must be something I forget but I can't put my finger on it.

Any idea?

Regards

**Comment by MaxLeiter** [comment]
I'm not familiar with docker, but I believe those instructions are outdated. Have you tried following the instructions [here](https://github.com/thelounge/docker-lounge/blob/master/README.md)?

**Comment by williamboman** [comment]
Those docs are outdated. https://github.com/thelounge/thelounge.github.io/pull/28 fixes that. #288 should probably be merged asap too

**Comment by maxpoulin64** [comment]
@williamboman: just merged the doc, waiting for second review on #228. Great work on the Docker stuff btw.

**Comment by Chouchen** [comment]
Thanks, it worked greatly with [those instructions](https://github.com/thelounge/docker-lounge/blob/master/README.md)
