### ISSUE TITLE
Make custom highlights case-insensitive

### ISSUE THREAD

**Issue by williamboman** [thelounge/lounge#439]
There are currently no clarification whether the keywords are case-sensitive or not

**Comment by astorije** [comment]
Should they be case-sensitive?

**Comment by dgw** [comment]
I would say the code should be modified to make them case-insensitive.

**Comment by YaManicKill** [comment]
Yeah, this is definitely a bug with the code, they shouldn't be case-sensitive. I just didn't thin kabout that.
