### ISSUE TITLE
Per-channel settings

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#44]
Would allow disabling notifications, joins/quits/kicks, etcetera per separate channel.

#9 adds a context menu that has a button for settings which will help with this.

**Comment by astorije** [comment]
Hey @xPaw! I have lots of ideas on better settings in general, let me come up with a design doc whenever I can :)

**Comment by astorije** [comment]
Closing this to centralize discussions about settings to #85. Feel free to re-open if you feel this still needs to be discussed outside of #85 or when it's time to break it into multiple features/PRs.
