### ISSUE TITLE
Including an IRC bouncer as well

### ISSUE THREAD

**Issue by sakshamsharma** [thelounge/lounge#446]
I guess it'd be nicer if lounge could also include an IRC bouncer perhaps, and was made in a way which let lounge connect through that bouncer.
Expected use case: I keep lounge open and deployed on OpenShift, but I would sometimes like to connect to my chats from Emacs, or Weechat, or any other IRC client as well.
Comments?

**Comment by maxpoulin64** [comment]
Unfortunately, this is not possible at the moment. The underlying IRC library we use doesn't give us the required information to even do that, but it would also be an enormous job to implement an IRC server. I actually had that idea before, and might eventually do it for fun as a plugin, but we have lot more urgent things to do before.

In the meantime, Lounge integrates very well with ZNC, so I would definitely recommend that solution instead! ZNC does one job and does it pretty well, I barely even remember I'm using ZNC.

**Comment by sakshamsharma** [comment]
Hmm well that surely is an option. Deploying another node with ZNC, and then connecting lounge to that. I was just wondering whether this much is possible. Thanks for the quick response!

**Comment by dgw** [comment]
I run The Lounge on the same (virtual) node as my ZNC server with no issues. I think it disconnects from localhost maybe once every month or two, due to load on other virtual hosts, but is otherwise very stable.

ZNC is kind of the de facto standard bouncer. Anything else would have a lot of catching up to do even after implementing all the base features a bouncer requires.

**Comment by ssbarnea** [comment]
How about packaging ZNC inside docker-compose.yml file and integrating them by default. It may need some tuning to integrate them.

If done well the bouncer functionality could be transparently offered by the "embedded" znc. Even forking znc to make it load our config may prove a smaller effort than writing a bouncer.

**Comment by xPaw** [comment]
You can create your own docker container for what if you so desire. The Lounge won't do that.
