### ISSUE TITLE
Message textbox shows on loading screen

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#463]
Initially fixed by #420, #379 causes the message box to show on the loading screen

<img alt="textbox showing" src="https://sr.ht/LbbZ.png" width=200>

**Comment by astorije** [comment]
Can reproduce the regression on `master` branch.

**Comment by omnicons** [comment]
I am also experiencing this on the master branch.

**Comment by astorije** [comment]
This happens on all pages, such as settings:

<img width="600" alt="screen shot 2016-07-05 at 17 19 59" src="https://cloud.githubusercontent.com/assets/113730/16600376/c30d9914-42d4-11e6-9a4c-56765e5246b4.png">

Ouch
