### ISSUE TITLE
Unread marker counts embed (...) button as new message even if sent from self

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#466]
![unread marker bug](https://sr.ht/q74a.png)

Relevant code: https://github.com/thelounge/lounge/blob/9c07f2b0f2f5bb0bc14ac2900fc75bf1f12e5e82/src/plugins/irc-events/link.js#L34-L37

**Comment by astorije** [comment]
This is indeed an issue, but FYI not something related to the recent bugged merges. Attempted a fix in #473, help to test this welcome.
