### ISSUE TITLE
Fallback to actual defaults when a configuration item is not set

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#475]
At the moment, when starting the app for the first time, `defaults/config.js` is copied over the home folder of The Lounge with its default values.

If the file is half complete, however, the app might crash (for example, see #474) or we might use some hardcoded, inline defaults (see [here](https://github.com/thelounge/lounge/blob/548a8d71308680d5b63b65512b7dabbc2ee4f974/client/index.html#L112) for example).

A nice alternative would be to default all values with `defaults/config.js` itself. So this file would be created the first time (ideally at install time and not runtime, but that's a different story), but also used as fallback for missing keys in the configuration. That would centralize all default values.

Thoughts?

**Comment by maxpoulin64** [comment]
Isn't it already the case with #387? Code still appears to be in: https://github.com/thelounge/lounge/blob/master/src/helper.js#L31

**Comment by astorije** [comment]
Argh, you're right, I was hitting that on a PR that doesn't include that change! Dammit. I'll test that this is the case now and will cleanup use of defaults similar to what #474 is doing.

**Comment by xPaw** [comment]
This was fixed by #387.
