### ISSUE TITLE
Flooding other clients with NAMES lists

### ISSUE THREAD

**Issue by wiiaam** [thelounge/lounge#476]
Whenever a channel mode is changed, it is requesting the NAMES list in that channel. This isn't an issue on lounge itself, but when I have it connected to my bouncer, I am seeing names list flooding on my other clients (especially when the channel has a lot of users). 

Most clients tend to update the users list with channel ranks as soon as they are spotted, and will periodically send out a WHO command to different channels to update the userlists manually, in case one was missed.

**Comment by omnicons** [comment]
Turn on route replies in your bouncer. This isn't really a bug, you just
haven't properly enabled the feature on your own bouncer, don't blame the
client for something that's not its fault.

**Comment by wiiaam** [comment]
@omnicons but the client shouldn't be sending out NAMES requests anyway, it should just be logging the channel most when it sees it. NAMES is a user command to print the user list, it wasn't designed to be used to track channel modes by the client (it even states this in [RFC 1459](https://tools.ietf.org/html/rfc1459)). This also means that until this is fixed, users are unable to use the /names command properly in the client. It would be better to use WHO instead as it is parsed in the background of pretty much every IRC client.

**Comment by omnicons** [comment]
Fair enough, until then or if it's not something they prioritize, I suggest
using route replies. Its not this client's fault that you're on a bouncer
and not using that module. It's really useful anyway, and should probably
be enabled. Thanks for the information though, I don't read the IRC RFC so
I suppose that's somewhat enlightening.
