### ISSUE TITLE
Text in chat input invisible in landscape mode (mobile)

### ISSUE THREAD

**Issue by williamboman** [thelounge/lounge#482]
https://streamable.com/h6dc

**Comment by astorije** [comment]
Ouch, that's pretty bad. Any idea where this comes from?
IMO, this could be a side-effect of the new textarea (#379), or the recent layout fix (#465). @maxpoulin64, what do you think?

**Comment by astorije** [comment]
I could reproduce this on mobile (Android 5, Chrome) but sadly not on laptop emulating mobile(Mac OS X, Chrome) :(
Can someone with iOS test this on mobile please?

**Comment by astorije** [comment]
- Tested that the bug doesn't exist **right before merging #379**, which is commit 51666b6db688278186dcbda0abeebec6f123ee87.
- Confirmed that the bug exists **right after merging #379**, which is commit 114295a1bdd8416fb598392fe2e4a383c6ba534e.

@MaxLeiter confirmed this bug doesn't appear on iOS 9.2.
