### ISSUE TITLE
Drag'n'dropping channels wrongly positions the channel in flight

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#494]
Easier to explain with a GIF:

![drag-drop-channel-broken](https://cloud.githubusercontent.com/assets/113730/16757654/5ae7feae-47db-11e6-8e00-aa0264ccb02e.gif)

Note that:

- This happens on channels only, not networks.
- Reproducing this requires some playing on the drag'n'dropping, it looks good at first, then for no reason it breaks, and then it's consistently broken until next refresh.
- This happens both on `master` and `2.0.0-pre.4`, not sure about previous pre-releases and stable releases (if someone wants to try with other versions, that'd be helpful).

**Comment by metsjeesus** [comment]
Its dependent from where you start dragging element. Problem is only if you drag from upper side on the area. Might be fixed with updating jquery.

**Comment by metsjeesus** [comment]
It seems if you grab bottom side of the grabbing area, there are no problems, but if top side of the area, bug happens.

**Comment by stepie22** [comment]
I belive #702 fixed this completely? Is so, this issue should be closed.
