### ISSUE TITLE
jquery

### ISSUE THREAD

**Issue by inexist3nce** [thelounge/lounge#498]
http://youmightnotneedjquery.com/

**Comment by dgw** [comment]
Vote close per what the site says right up top:

> jQuery and its cousins are great, and by all means use them if it makes it easier to develop your application.

**Comment by YaManicKill** [comment]
Closing as not constructive.

**Comment by maxpoulin64** [comment]
I don't like jQuery either, but:

* We inherited it from Shout
* We have much, much bigger priorities than rewriting the frontend.
* We already have a buttload of other libraries (and a few of which requires jQuery as well)
* In the meantime, it doesn't hurt anyone that we have it.

As we say in the open source world: patches welcomed.

**Comment by astorije** [comment]
<img src="https://cloud.githubusercontent.com/assets/113730/16848257/ec265800-49c2-11e6-9384-17e74f513d23.png" width=200>

But yeah, @inexist3nce, if you want to give a shot at helping rewriting the entire UI, feel free to open an issue to give details of the plan, stop by the IRC channel if you need to chat about it, and open a PR that we'll happily review 😉
