### ISSUE TITLE
List and cherry-pick all missing changes that were merged in Shuo

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#5]
https://github.com/Shuo-IRC/Shuo

Maybe @Xe and @floogulinc could help us, at least to list the missing pieces :-)

**Comment by YaManicKill** [comment]
* https://github.com/Shuo-IRC/Shuo/pull/83
* https://github.com/Shuo-IRC/Shuo/pull/18

These are the 2 main ones in terms of functionality that Shuo had that we don't. Obviously, the theme selector should probably be a bit better (if we integrate it with @astorije and my plan for packages, we don't need to update the config, etc) but afaik, these are the only real "functionality" ones that haven't been merged in.

**Comment by astorije** [comment]
@YaManicKill:

- Regarding the "Show timestamp" toggle, I had some concerns in the original PR: https://github.com/erming/shout/pull/484 It definitely should be added here but after addressing them.

- Theme selector seems to be a killer feature for plenty of folks, which I can understand. So I propose that we stick to the plan of having themes been handled like packages (although we would still leave the user choose the theme among those installed by the admin), but in the meantime a simple theme selector would do and provide minimum viable feature for the users. What do you think?

Thanks for digging through the commits! I have no idea how you efficiently went through the changes...

**Comment by YaManicKill** [comment]
Just doing a quick look through some old issues. I'm going to close this There was just the 2 mentioned above. The first is #186 and the second could be included in #85. If anyone thinks the theme selector should be a seperate issue, feel free to create it.
