### ISSUE TITLE
IPv4 IPs are reported in 4in6 format to webirc

### ISSUE THREAD

**Issue by maxpoulin64** [thelounge/lounge#502]
Discovered on IRC debugging a problem of silently failing webirc. Turns out when `host` is undefined, IPv4 addresses are reported in the 4in6 format (`::ffff:1.2.3.4`) since it actually listens in IPv6. However, the WEBIRC command explicitely forbids that. Need to add a check for this and transform the address appropriately to fix.

**Comment by xPaw** [comment]
Fixed by #535
