### ISSUE TITLE
Add doctor command

### ISSUE THREAD

**Issue by williamboman** [thelounge/lounge#505]
Having a `lounge doctor` command, similar to [`yo doctor`](https://github.com/yeoman/doctor), might be of interest.

Was thinking it could do stuff like checking directories, environment variables, Node/npm versions, parse configuration files, e.t.c.

**Comment by xPaw** [comment]
I'm not sure there's any use in having a command like this, really. @astorije what do you think?

**Comment by astorije** [comment]
Yeah, I'm 😕 on this too. Most of these things should be checked at startup.

I could however see use (and I have a use case already) in having something that checks configuration files. Something like what's described [here](https://github.com/ansible/ansible/issues/11048) for other software.
That would make for better and simpler validation checks in integrations such as [my Ansible one](https://github.com/astorije/ansible-lounge/blob/master/tasks/main.yml#L63-L81).

**Comment by astorije** [comment]
Alright, let's close this for now and re-consider later if needs arise or if someone wants to implement this.
