### ISSUE TITLE
Inconsistent link colors

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#510]
On the default theme at least, links show up either in blue or green:

| Loading page | Chat messages | Settings |
| --- | --- | --- |
| <img width="420" alt="screen shot 2016-07-16 at 22 50 56" src="https://cloud.githubusercontent.com/assets/113730/16898423/1a1ed606-4ba8-11e6-843c-31aa26f593ad.png"> | <img width="425" alt="screen shot 2016-07-16 at 22 51 23" src="https://cloud.githubusercontent.com/assets/113730/16898424/1a1f6274-4ba8-11e6-9b02-235190ad259c.png"> | <img width="425" src="https://cloud.githubusercontent.com/assets/113730/16795135/b7071002-48a9-11e6-8c8f-aa812096a1ea.png"> |

Need to not just fix one or the other, but make sure that defaults are consistent so that it doesn't happen again if we add links or new pages.

**Comment by xPaw** [comment]
Not only are they not consistent, but are also incorrectly colored when using irc colours.

**Comment by astorije** [comment]
> incorrectly colored when using irc colours

Meaning that when setting an IRC color around a link keeps the default CSS, green color?

**Comment by wad3g** [comment]
IMO the real solution to this issue is to rewrite the base `style.css` and each theme's css. 

As more theme's are added or iterated variation/inconsistencies from theme-to-theme will continue with the inclusion of Bootstraps default CSS, your app's base `style.css` and each theme's styles.

This would be a breeze with addition of PostCSS or some other pre processor.

**Comment by ryzokuken** [comment]
I would love to give this a swing as my first contribution to a project.

Off-topic, but the organization I'm participating in Google Summer of Code for, Publiclab, uses lounge (http://chat.publiclab.org/)

**Comment by YaManicKill** [comment]
> I would love to give this a swing as my first contribution to the project.

Great, @ryzokuken, welcome. Feel free to swing by our irc channel (#thelounge on freenode) to chat through anything if you raen't sure. Our CSS is a little bit of a mess, so it would be nice to get it sorted out.

> Off-topic, but the organization I'm participating in Google Summer of Code for, Publiclab, uses lounge (http://chat.publiclab.org/)

Awesome, that's really good to know. We should start a list somewhere of people using this.

**Comment by ryzokuken** [comment]
@YaManicKill Awesome. I will fork the repo and join the channel for any queries. Thanks.
