### ISSUE TITLE
NaN:NaN as time for link toggle

### ISSUE THREAD

**Issue by michaelowens** [thelounge/lounge#514]
As seen on screenshot:

![NaN:NaN](http://i.imgur.com/KT7h0za.png)

**Comment by YaManicKill** [comment]
Are you on version 1.5.0 just now? This should be fixed on 2.0.0-pre4, hoping to release that soon.

**Comment by michaelowens** [comment]
Ah yes, I got it off NPM which is 1.5.0. My bad!

**Comment by YaManicKill** [comment]
No problem :-) duplicate of #244
