### ISSUE TITLE
Mode flags for "start" command don't work

### ISSUE THREAD

**Issue by nirvdrum** [thelounge/lounge#517]
I may just be doing something wrong, but it looks like the `--public` and `--private` flags to the `start` command are completely ignored. The value from the config.js file always prevails. I started poking around at [the source](https://github.com/thelounge/lounge/blob/412f28aaee784bc395da2fcc61b66f962d62711f/src/command-line/start.js#L18-L20) a bit and `program.public` and `program.private` are always undefined.

I'm running 2.0.0-pre.4.

**Comment by maxpoulin64** [comment]
Hmm, [I think the params are assigned the wrong way](https://github.com/thelounge/lounge/blob/master/src/command-line/start.js#L10-L11) and that might be why they are undefined.

Just as a note, there was discussion about deprecating those options in favor of a more generic one that would allow to override any config options through the command-line. So those will likely go in the near future. I would always recommend to use the config.js anyway: it is created and loaded either way, so might as well use it.

**Comment by nirvdrum** [comment]
Fair enough. I was just working through the docs in order and was confused when it didn't work the way I expected. Only then did I start looking at the config file in detail.
