### ISSUE TITLE
Restarting Lounge Kills ZNC Logs

### ISSUE THREAD

**Issue by xnaas** [thelounge/lounge#52]
Couldn't summarize this well in the title, sorry.

So I connect to my ZNC through Lounge. This works great! However...if I need to restart Lounge for whatever reason, when I launch it again and sign in via the web...I have no logs waiting for me when I get back.

If I use a dedicated client like Hexchat, I can see everything that happened in ZNC when I get back. Lounge seems to actually **log me out** of every server/channel on ZNC until I relaunch Lounge or ZNC attempts auto-reconnects.

Not sure if this is a configuration issue on my side, a bug, or a feature I need to be requesting. Whichever it is, then...please advise. :)

**Comment by kode54** [comment]
This is a ZNC setting for backlog buffering, which defaults to clearing whenever a client is connected to it.

**Comment by maxpoulin64** [comment]
I will mark this issue as invalid and close it, as nobody was able to report back on this issue. We are many in #thelounge using ZNC and it seems to be working fine for everyone. We don't do anything anything special that could do that, we don't even quit/part channels on shutdown so I'm pretty sure it's a ZNC config issue in relation to auto clearing buffers, as mentionned by @kode54.
