### ISSUE TITLE
The --help option shouldn't create config directory

### ISSUE THREAD

**Issue by nirvdrum** [thelounge/lounge#520]
I've been working on a startup script for lounge and found it convenient to use the `--home` option with the `start` command to store the files in a good location. Confusingly, using the `--help` option auto-creates the config directory and it's almost certainly not the location I want, since I didn't pass the `--home` option along with the `--help` option. I think it would make more sense if `--help` didn't touch the filesystem.

**Comment by dgw** [comment]
Hmm. Looks like the home directory's existence [is ensured before](https://github.com/thelounge/lounge/blob/ee5a64436c5ad673072fde2d6466f3cf2e5446cf/src/command-line/index.js#L14-L19) the `--help` argument could possibly be used.

Arguments like `--help` and `--version` shouldn't touch the file system at all. I don't know that it's a *nix guideline necessarily, but if the program is just outputting usage information or a version string and exiting, it stands to reason that it shouldn't be mucking with config files.

**Comment by maxpoulin64** [comment]
Yeah that's definitely a bug. Lots of stuff in Lounge race to be initialized before other things and this is what happens. We need proper dependency injection that doesn't depend on when a particular file was first `require()`ed. Right now it's a free for all, we even had users being loaded before the config is loaded at one point.
