### ISSUE TITLE
URLs surrounded by HTML entities are not properly parsed

### ISSUE THREAD

**Issue by anthonynguyen** [thelounge/lounge#522]
For example, in Freenode ##archlinux, the topic is 
```
Welcome to Arch Linux World Domination, Inc. <+> Channel stats at <https://theos.kyriasis.com/~kyrias/stats/archlinux.html> Contact demize to opt out <+>
```
but since the `>` at the end of the URL is actually encoded at `&gt;`, it isn't stripped by the URL parser and is treated as part of the URL, thus rendering it invalid:

![screen shot 2016-07-21 at 3 37 49 pm](https://cloud.githubusercontent.com/assets/1484987/17036170/1f0f6216-4f59-11e6-8c4b-3183998c2896.png)

I have a fix for this on the `uri-decode-entities` branch in my fork but I'm not sure if it's the best approach; I'm resolving all HTML entities in a string before giving it to the parser to find a URL.

**Comment by maxpoulin64** [comment]
Duplicates #15 and #199
