### ISSUE TITLE
Not loading after upgrade

### ISSUE THREAD

**Issue by agucova** [thelounge/lounge#525]
I cloned the repo directory, and tried to run it using my existing .lounge from 1.5.0, it started without any problems on the console, but when entering, I all get is the "loading" message.
The console on 2.0.0:

<img width="642" alt="thelounge-2" src="https://cloud.githubusercontent.com/assets/4694408/17076693/c4c65b64-5086-11e6-828a-189d16339f6f.png">

The console on 1.5.0:

<img width="556" alt="lounge-15" src="https://cloud.githubusercontent.com/assets/4694408/17076694/cb413e64-5086-11e6-83d6-271e9747fff8.png">

The loading message:

<img width="424" alt="loading" src="https://cloud.githubusercontent.com/assets/4694408/17076697/dba74b4a-5086-11e6-99f0-669833cca07d.png">

Maybe the config is not being loaded correctly?
I noticed this on chrome inspector:

<img width="1173" alt="errors" src="https://cloud.githubusercontent.com/assets/4694408/17076705/05a28acc-5087-11e6-9eaa-cab249b82ee2.png">
(This errors are not present on 1.5.0)
NOTE: the older lounge was installed via npm, but it was not running.

Any ideas?

**Comment by agucova** [comment]
This is on node v4.2.6, ubuntu 16.04 and latest version of npm.

**Comment by maxpoulin64** [comment]
You need to run `npm install` and possibly also need to run `npm run build`. That will fix your problem.

You can't just clone the repo and run it, you need to minify and pack the scripts together and generate the templates ☺

**Comment by astorije** [comment]
@agucova, can you confirm this fixes your issue and then close this ticket please?
