### ISSUE TITLE
Themes needs to be updated for the new textarea

### ISSUE THREAD

**Issue by maxpoulin64** [thelounge/lounge#530]
Due to the structure changes some CSS overrides in the themes are no longer specific enough to theme the textarea. Right now this causes font-size and styles inconsistencies.

**Comment by astorije** [comment]
Would this be any improved or made worse by https://github.com/thelounge/lounge/pull/377?

**Comment by astorije** [comment]
Also, is this a regression since 2.0.0-pre.4? /Cc @vectr0n

**Comment by vectr0n** [comment]
To be 100% honest, I noticed it a bit ago, I apologize I have no accurate time frame, probably within the last week or two, and just never said anything about as I figured it was pretty noticeable to me and someone else would probably report it, but it wasn't till I had pulled a fresh copy of master and ran the npm install && npm run build to check out the unread marker (most recent fix) and noticed the smaller text was still an issue, so I spoke up and reported and provided the screenshots.

**Comment by maxpoulin64** [comment]
It is a regression, since it's a CSS override that doesn't apply anymore since I'm using a more specific selector in the base theme. It's definitely the textarea update that changed that.
