### ISSUE TITLE
Option to enable notification sound for channel in view

### ISSUE THREAD

**Issue by shazeline** [thelounge/lounge#538]
I get an initial audio ping when a custom highlight is matched in a channel that is not in view or if the browser tab with lounge running is not in view. 

When the channel and browser are in view, I do not receive the ping. It would be useful for me to receive an audio ping on any custom highlight, whether my client/browser are in view or not.

**Comment by astorije** [comment]
This seems like is a very niche need, and, as a use, seems like a rather unexpected behavior. It's very unlikely that an option gets added for this, but when we can settle APIs, I'm expecting this will not be difficult to implement.

**Comment by astorije** [comment]
Closing this as it's extremely unlikely we'll implement this as described in the original post.
