### ISSUE TITLE
Add extra commands

### ISSUE THREAD

**Issue by v0l** [thelounge/lounge#54]
Add commands:

* /j alias for /join
* /list command https://github.com/erming/shout/issues/635

**Comment by xPaw** [comment]
I kinda disagree with adding one char aliases. Tab completion also works for commands.

**Comment by v0l** [comment]
would it be possible to add a config option to add aliases to commands?

**Comment by astorije** [comment]
I agree with @xPaw regarding `/j`. Typing `/j` + <kbd>Tab</kbd> is not much harder (tab completion is so common we are not being esoteric).
With the package system in the works (or about to be in the works), I don't think adding this option is something we will or should implement. However, we should definitely make sure the API for the package system lets developers make packages to do this sort of things.

For `/list` it's a different issue and I believe it would be much appreciated. Would like opinion from others.

**Comment by astorije** [comment]
Closing this as `wontfix` for triaging purposes. We can re-open if needed.

**Comment by YaManicKill** [comment]
@astorije did you add a story for /list? I can't see one.

**Comment by astorije** [comment]
I admit I overlooked the second part of the issue :-)
I just copied https://github.com/erming/shout/issues/635 over to #130 using https://github-issue-mover.appspot.com/. Conclusion: I'm not using this tool again :-)
