### ISSUE TITLE
Configuration on a per-server basis

### ISSUE THREAD

**Issue by manuelbieh** [thelounge/lounge#542]
Feature request: I'm currently joining EUIrc and Freenode - both with a different username. In most irc clients I have used so far I can configure different usernames for joining different servers. This would be a nice feature to have an option to add different configs (ssl yes/no, username, ...) for different servers.

**Comment by astorije** [comment]
I'm confused... it's already the case, no?
I'm currently on several networks, each with their own configuration (SSL, IRC server, nickname there, etc.). This is also true whether you are using a public or private instance.

However, note that [the demo](https://avatar.playat.ch:1000/) (currently down) does not allow connecting to any server but the one it's configured to connect to.
