### ISSUE TITLE
100.0k message limit in channels

### ISSUE THREAD

**Issue by Thumpxr** [thelounge/lounge#545]
In the Channel panel the unread message number wont raise above 100.0k. It stays like this since 2 days.

![image](https://cloud.githubusercontent.com/assets/3073030/17458002/4e629f2e-5c06-11e6-97ff-2660ae7efaa1.png)

**Comment by Thumpxr** [comment]
somehow the channel was inactive for ~2 days... nvm

**Comment by astorije** [comment]
That's a funny one! :)
