### ISSUE TITLE
Show hostmask on join/part/quit

### ISSUE THREAD

**Issue by v0l** [thelounge/lounge#55]
Add host info for people who join a chan, 

``` v0l (v0@ip) has joined ```

~~Also add quit messages~~

**Comment by xPaw** [comment]
Quit messages are already shown, do you not see them?

**Comment by v0l** [comment]
Oh yea i see it, needed update sorry.

**Comment by astorije** [comment]
I really don't think we shout display host info when someone joins. It's noisy, doesn't add much information, and can be retrieved using a `/query`. I find that negatively affecting the UX so I'm :-1: on this, sorry!

**Comment by dgw** [comment]
Gonna go out on a limb here and say that themes should be able to add or remove info in event messages, regardless of whether core does this. (If that's not currently possible/planned, please do correct me!)

@astorije You mean a /whois, no?

**Comment by astorije** [comment]
Sorry yes, a `/whois`. And I disagree with this, themes should be about UI, not data/info. Anything else too specific and not UI-related should go in a package.

**Comment by xPaw** [comment]
> It's noisy, doesn't add much information, and can be retrieved using a /query.

It can't be retrieved using commands when you're trying to ban someone that just quit.

**Comment by easymac** [comment]
I'm on the side of adding visible hostmasks that can be hidden/shown with CSS as it's an easy way to identify when someone joins under an alias or when a user is being impersonated.

**Comment by vectr0n** [comment]
+1 Would love to see at least the option to show the ident@host in join/part.

**Comment by Jay2k1** [comment]
A huge +1. This is a must-have for me.

**Comment by richrd** [comment]
Big :+1: for the possibility for themes to show the hostmask.
Could be off by default but would be nice if it would be an option.

**Comment by astorije** [comment]
Added in #94, closing.
