### ISSUE TITLE
Long URLs overflow the chat window and create a transparent yet present horizontal scrollbar

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#550]
Look at that guy, for example:

![bug-long-urls](https://cloud.githubusercontent.com/assets/113730/17470488/c848976c-5d0a-11e6-9161-590a2d25d35e.gif)

Shot on Chrome (Mac OS). Could not reproduce on Firefox on that same OS.

**Comment by maxpoulin64** [comment]
Hmm, I think #523 might be fixing it, I don't see that on my instance:

![capture d ecran_2016-08-08_01-59-56](https://cloud.githubusercontent.com/assets/5481612/17470643/f2318cb8-5d0b-11e6-95b9-184a782c0463.png)

**Comment by astorije** [comment]
On `#chat .msg`:
- `word-break: break-word` seems to work exactly like we want but is only for Webkit :-/
- `overflow-wrap: break-word`... does nothing on Chrome
- `word-wrap: break-word` seems to do nothing on Chrome either

Checking this on Firefox, bug does not appear there, so maybe `word-break: break-word` is the answer?

**Comment by astorije** [comment]
> Hmm, I think #523 might be fixing it, I don't see that on my instance:

Possibly, but reading code and comments, removing table layout might/will lead to a whole new set of bugs, so I'll need to review and test this carefully...
