### ISSUE TITLE
Textarea sometimes show an extra empty line

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#556]
For example:

![input-reset-height](https://cloud.githubusercontent.com/assets/113730/17579278/3d758ac4-5f61-11e6-9135-04ddd4c2f958.gif)

I can't really provide reproduction steps because I'm consistently reproduce this. So far I have noticed that it depends on the width of the nick label however, so it might be worth looking into that.

The screenshot above was generated with:
- Current commit checked out is the one behind tag `v2.0.0-pre.6`
- Browser is Chrome on Mac OS X and window is the smallest width Chrome lets me do
- Text is: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`

Any help is appreciated 😅.

**Comment by maxpoulin64** [comment]
I can't seem to reproduce, no matter how insanely small I make the window.Have you checked with the dev console what the boxes are?

So far I suspect the text might not wrap properly when we make the box tiny and it ends up making it one line bigger than needed. That's very odd and might be somewhat pixel-perfect to trigger it too, if that's really it.

**Comment by dgw** [comment]
I actually ran into this earlier tonight while having a reasonably lengthy PM conversation in The Lounge on my phone. As I typed longer messages, sometimes the textarea would expand some characters before the text actually wrapped to an additional line.

Not sure if this is related to sometimes seeing a vertical scroll handle appear in the textarea even when empty. I've seen that behavior on both desktop window of 1280px by ~700px in Chrome for Mac, and on Android with display of 1440x2560.

My instance is still running pre.5 as I just updated and don't need the LDAP support added in pre.6.

**Comment by astorije** [comment]
Thanks for the additional details, @dgw. I have noticed that from my phone more often than from laptop as well. Definitely a bug.

**Comment by xPaw** [comment]
Might be related to this bug:
> 15:29	+xPaw	#form #input has a line-height of 1.5, and height of 18px, which causes a scrollbar to appear even when there are no characters typed in
> 15:30	+xPaw	also, textarea height is not recalculated on window resize

**Comment by astorije** [comment]
> 15:29 +xPaw #form #input has a line-height of 1.5, and height of 18px, which causes a scrollbar to appear even when there are no characters typed in

Agreed, there might be something there.

> 15:30 +xPaw also, textarea height is not recalculated on window resize

This is a good point and I already noted that (but never opened an issue for it), but FYI note that this bug happened to me without resizing the window.

**Comment by astorije** [comment]
Removing 2.0.0 milestone from this. This is not critical so it should not be blocking release, but if someone takes a stab at it, I'd be more than happy to add it back.

**Comment by xPaw** [comment]
I am able to repro this bug in at least Morning theme. I believe the bug is that `scrollHeight` calculates as if the scrollbar is visible, so when the new `height` is set, it's higher but there is no scrollbar visible, and thus it doesn't overflow the text.

**Comment by astorije** [comment]
I don't recall seeing this bug anymore. Either I got used to it or it got silently fixed. Closing this issue for now, we'll reopen if it is still there in v2.2.2 / future-v2.3.0.

**Comment by xPaw** [comment]
Is this still a problem on master? I am not longer able to reproduce it.

**Comment by YaManicKill** [comment]
I have not seen it in a long time.

**Comment by astorije** [comment]
Odd, I can still see this just like before, I have just learned to live with it lol.
