### ISSUE TITLE
Buffer scroll position is incorrect on page load

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#558]
When the page finishes loading and the first buffer is displayed, it does not start scrolled all the way to the bottom. Changing to another buffer via the sidebar fixes this, and it does not appear to recur unless the page reloads.

Observed using 2.0.0-pre.5, but AFAIK only LDAP stuff changed in pre.6.

**Comment by astorije** [comment]
Damn, I thought this was fixed by https://github.com/thelounge/lounge/pull/484...

I cannot reproduce this, can anyone else do?
@dgw, what browser/OS?

**Comment by dgw** [comment]
Behavior observed on both Android and Mac. Presumably Chrome in both cases (I added The Lounge to my phone home screen from Chrome).

**Comment by astorije** [comment]
@dgw, are you able to provide any reproduction step?
Do you happen to run specific PRs on top of the main codebase, or custom CSS?

I tried many things, but couldn't reproduce this issue at all, even though I'm using Mac OS/Chrome as well... Sorry 😕
Other @thelounge/maintainers, any luck reproducing this?

**Comment by omnicons** [comment]
I haven't been able to reproduce this on my iOS or Android devices on
'master'

**Comment by dgw** [comment]
Hmm. I don't run master, so let's close this for now and I'll reopen if the issue still exists after the next release (pre or stable).

**Comment by xPaw** [comment]
This bug is still happening for me on android using chrome.

**Comment by williamboman** [comment]
I can't repro on macOS (Firefox, Safari, Chrome) or Android (Chrome).

**Comment by astorije** [comment]
Considering it's a rare one, and not a critical one, removing from the `2.0.0` release. If someone wants to take a stab at it, we would of course add it back ;-)

**Comment by xPaw** [comment]
@dgw Does this happen on current master for you?

**Comment by dgw** [comment]
Appears to be fixed in 2.0.0.rc-1. I'll reopen if the issue reappears in a later RC.
