### ISSUE TITLE
No indication is given in a query buffer that the other user is offline

### ISSUE THREAD

**Issue by zmc** [thelounge/lounge#559]
I replied to a ping yesterday, and didn't notice until several hours later that the other person was offline. The "No such nick/channel (no_such_nick)" message was in the server buffer, and not in the query buffer.

It would be nice if:
1. The message displayed in the query buffer
2. Bonus: some visual indication before messaging an offline user, that they are offline

**Comment by xPaw** [comment]
Duplicate of #337
