### ISSUE TITLE
Show all messages from server

### ISSUE THREAD

**Issue by v0l** [thelounge/lounge#56]
Show all info on server chan instead of just motd and notice messages. 

![img](https://void.cat/5cb1efb4bdb8861273a0e48fb09ddf223b73d7ad)

PS: The good snipping tool!

**Comment by xPaw** [comment]
I don't think slate-irc sends any events with that information. Another issue for #24

**Comment by v0l** [comment]
Ah, I doubt it would be difficult to implement your own client code for IRC, its a very basic protocol.

**Comment by vectr0n** [comment]
+1 Would be a good option to see server messages, or the option too.

**Comment by easymac** [comment]
Slate uses the `motd` event for these messages; definitely supported.

**Comment by xPaw** [comment]
#167 shows connection related messages, nothing about server capabilities yet though.

**Comment by xPaw** [comment]
"all messages" is not very descriptive. master now shows all the connection related messages that are raised by irc-fw. If you would like to see other specific information (e.g. server capabilities), create a new issue for each of these please.
