### ISSUE TITLE
Show all WHOIS data

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#560]
Not all WHOIS replies are shown. Things like idle time, sign-on time, and nickserv identification status do not appear in either the opened query buffer or the server buffer. (as of 2.0.0-pre.5)

**Comment by astorije** [comment]
[This `irc-framework` doc page](https://github.com/kiwiirc/irc-framework/blob/16728e3165d04afce5502ec6c8cd848638b2c4b7/docs/events.md) shows some information returned that [we do not use](https://github.com/thelounge/lounge/blob/f824036225aa2763ff3a25d1b330735f324d3e8a/client/views/actions/whois.tpl). It should not be difficult to add.
Real question is: what do we want to display and what do we not want to display? @maxpoulin64?

**Comment by richrd** [comment]
What about having a toggle to show and hide the extra whois data?

**Comment by YaManicKill** [comment]
I'm normally all for toggles, but that feels incredible unnecessary for
showing some data on the whois. Let's be honest, the whois is technical
info anyway that not a huge number of people use, so show it all.

It also brings up the other issue of where we show whois. I still think
that a modal is a much better place to show whois as it's very quick "I
want to see the current state of this information right now, and then I'm
done". Having it in a query just feels weird.

**Comment by astorije** [comment]
> I'm normally all for toggles, but that feels incredible unnecessary for showing some data on the whois. Let's be honest, the whois is technical info anyway that not a huge number of people use, so show it all.

I agree with this, though if the whois paragraph gets out of hand, we might want to cherry-pick. 

> It also brings up the other issue of where we show whois. I still think that a modal is a much better place to show whois as it's very quick "I want to see the current state of this information right now, and then I'm done". Having it in a query just feels weird.

I'm not too sure about a modal, it has UX issues and as soon as we have our first modal, people will dream of modals everywhere. Then we'll hear that our app is gross because it has so many modals... :-)
A nice alternative, I think, would be to display that data in a right column similar to the user list on channels. But I think this will be for later, and definitely a different discussion. We don't have to delay the current issue because of this.

**Comment by dgw** [comment]
I've expressed my opinion on this before, but if whois moves to a modal I will likely never use it—or only do so in dire circumstances. It bothers me that if I do `/ignore` in Textual, it brings up a modal pane that blocks interaction with the rest of the client until I've settled my changes and closed it out. Basically, I agree with @astorije that modals are bad for UX, and starting to use them in one place will lead to a proliferation. (I disagree that adding another column, or adding a temporary area to the existing user list for whois display, is the right solution—but I'll stop and bring the rest of my thoughts to the appropriate discussion when the time comes.)

**Comment by maxpoulin64** [comment]
I agree with the toggle and modals: not needed, and needlessly complicated. There isn't that much information in a WHOIS, so people can just ignore it. It's not like joins and parts in channels where they can take pages and pages of space for nothing. The WHOIS is a reply to a user action that's very rarely used, would be really silly to have a toggle for that (although it would be easy to make an expand button like the link expander with just a tiny bit of CSS).

**Comment by JacobEdelman** [comment]
I'd like to poke this issue, I'm having some difficulties as an server admin on a server with masked ips seeing the real ips via whois.
