### ISSUE TITLE
Unread marker does not show on current channel when initially loading the page

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#561]
To reproduce:

- Go to a channel
- Close the browser window
- Make sure you receive a message on that channel (for example, by running a different instance with a different nick, etc., like production instance + development instance)
- Reopen the closed instance: the unread marker does not show up above that message

**Comment by dgw** [comment]
Noted this myself, that the unread marker does not appear when first loading The Lounge. Thought it was intended for some reason, but I guess not 😁

**Comment by astorije** [comment]
Removing this from the 2.0.0 milestone (releasing super soon) as PR needs more testing and I don't want to block 2.0.0 for this.

**Comment by astorije** [comment]
Fixed by #636, 💥‼️
