### ISSUE TITLE
Changes do not reflect in default/config.js

### ISSUE THREAD

**Issue by spencerthayer** [thelounge/lounge#564]
Not every change is reflected in the default/config.js.

For example the Nick is still _lounge-user_ and the channels is still _#thelounge_ in addition to a slew of other configurations that are not changing. I have ran _npm run build_ after saving the config.js file but nothing changes.

**Comment by maxpoulin64** [comment]
`default/config.js` is the default configuration file, the one that's copied to `~/.lounge/config.js` on the first start. It is still read, but your config gets applied on top of it so it's normal that it doesn't do anything.

**Comment by spencerthayer** [comment]
Got it. I have a question @maxpoulin64. I plan on making serious changes to the config.js and including some variables from the URL string. When I make these changes to the JS file how will I force my `default/config.js` file to overwrite `~/.lounge/config.js`? Or is the only option `mv`?

**Comment by maxpoulin64** [comment]
Why not simply make your changes to `~/.lounge/config.js`? The default one really isn't meant to be changed. If you need to stack multiple configs on top of eachother, this can be done in `~/.lounge/config.js` as it's just a Javascript file like any other, so you can have logic in it, including loading/merging other files as needed. As long as the final result is set to `module.exports` you'll be good :)

**Comment by spencerthayer** [comment]
My only gripe with this is that it moves files outside of the node directory making a command like `pm2 start ~/lounge/index.js -i max --watch` ineffective. In addition to this it complicates using GIT to version everything.

Is the reason for keeping the config file in `~/.lounge/config.js` one of security? I'm trying to understand why this practice was chosen when more generally configuration should be handled by environment variables followed by a configuration file. Configuration usually should be something to do during deployment not in design.

Thanks @maxpoulin64.

**Comment by maxpoulin64** [comment]
The reason it is this way is that The Lounge is not actually designed to run from the git repository. Most people install it globally using npm, so it acts like any other command/service on the system. This has the very big implication that the directory is not writable by the user that runs lounge.

You can however move this file elsewhere, including inside the repo as you wish. You can just start lounge with the `LOUNGE_HOME` environment variable or with the `--home` launch parameter to set the directory to whereever you want.

**Comment by spencerthayer** [comment]
Thanks @maxpoulin64. I get it. The Lounge is focusing on private personal use rather than public use?
