### ISSUE TITLE
Customization Of The Lounge

### ISSUE THREAD

**Issue by spencerthayer** [thelounge/lounge#566]
Right now The Lounge is branded as such in core files. For example in https://github.com/thelounge/lounge/blob/master/client/index.html on lines 48, 72, 111, 327 the branding is hard coded. This is true in numerous other files but index.html is perhaps the most important.

This is a bad practice. In many use cases users will likely want to brand their installation. 

If I add a line in the config as an option to allow customization of the name in the config.js would the Lounge community accept the Pull request?

**Comment by astorije** [comment]
> This is a bad practice.

How is that a bad practice?
Based on a study of all open source projects hosted at GitHub, a remarkable 98.7% of these did not provide such thing. Yes I completely made this up, but so would be any good/bad practice for this :D

More seriously, The Lounge is an open source project. And it's called The Lounge. If you want to call it "This Is An IRC Client My Company Totally Made", then, sure, fork it and replace the names, we won't go after you and your dolla dolla bill y'all, but I don't think we should/will provide a way to do so ourselves.
I'm closing this as `wont fix`, but I'm curious: @thelounge/maintainers, am I totally wrong on this? If so, please re-open...

Well, if someday we have a professional offer with dedicated support and a proprietary version and we're called "The Lounge by Red Hat" then maybe, yes, but until then... 😄 

@spencerthayer, if you really want to contribute, we have an outstanding number of [open issues](https://github.com/thelounge/lounge/issues), [some being easy to grasp for newcomers](https://github.com/thelounge/lounge/issues?q=is%3Aissue+is%3Aopen+label%3A%22up+for+grabs%22), and [some others we want to tackle before shipping the next release](https://github.com/thelounge/lounge/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0) (careful, some already have PRs), so there is a lot to choose from already :-)

**Comment by maxpoulin64** [comment]
Yeah, I feel about the same as @astorije there. This is a very niche thing to add, and I don't think adding complexity for the sake of changing a name is worth the hassle of templating everywhere it mentions The Lounge. Good practices is not to make everything configurable, it's to find the right balance between configurability and simplicity.

If you really need to rebrand, I suggest just applying a local patch. Takes 10 seconds to do and you're set :P
