### ISSUE TITLE
Implement History Web API

### ISSUE THREAD

**Issue by williamboman** [thelounge/lounge#574]
I think it would be nice to be able to traverse between views by going back/forward in history. Thoughts?

**Comment by xPaw** [comment]
Fine by me as long as it doesn't fill browser history with every channel change. Also would work nicely for public servers

**Comment by williamboman** [comment]
> Fine by me as long as it doesn't fill browser history with every channel change.

That's sort of the point of it though. All web-based chat clients I've used does this, I like it.

> Also would work nicely for public servers

Not sure I'm following?

Implementation demo available at http://pluto.redwill.se:9000/ (demo:demo login)

**Comment by xPaw** [comment]
> That's sort of the point of it though. All web-based chat clients I've used does this, I like it.

I meant browser history (not the buttons).

> Not sure I'm following?

Links. `http://example.com/irc/freenode.net/9999/#freenode` or something like that.

**Comment by williamboman** [comment]
> I meant browser history (not the buttons).

Ah, no it should not. The history web API works against a session history and not a traditional "page" history.

> Links. http://example.com/irc/freenode.net/9999/#freenode or something like that.

Ah, gotcha. #575 does not include URLs for states as of now, not sure how one would serialize the states. Would also require some changes to the routing mechanism on the backend unless URLs are hashed (yuck :P).
