### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by Evlos** [thelounge/lounge#582]
Hi all,

After I got this error message, The Lounge doesn't show new message on IRC channels any more. I have to restart The Lounge to fix that.
```
Client#connect():
Error: read ECONNRESET
```

Any help plz?
Thanks!

**Comment by astorije** [comment]
@Evlos, do you have a bigger stack trace to provide? Full output of the error would be nice.
Also, what version are you using? What OS is the server running on and what Node.js version?

**Comment by xPaw** [comment]
This should be fixed in 2.0
