### ISSUE TITLE
Bold text emits weird spans

### ISSUE THREAD

**Issue by kode54** [thelounge/lounge#583]
I am running a copy of master that I upgraded to from 2.0.0-pre.6, and it's emitting this when bold text occurs in a channel:

```
<span< span=""> class='irc-bold'&gt;[the text that is supposed to be bold]</span<>
```

**Comment by kode54** [comment]
It seems to be related to occurring immediately after a number sign:

    <span class="text">♪ <span class="irc-bold">マクロスMACROSS 82-99 </span>- Night In Tokyo Pt. II [A Million Miles Away <span class="inline-channel" role="button" tabindex="0" data-chan="#05]&lt;span">#05]<span< span=""> class='irc-italic'&gt; · <a href="youtube video" target="_blank" rel="noopener">youtube video</a></span<></span></span>

**Comment by astorije** [comment]
Considering these happen to us repeatedly, a good place to start, I think, would be to manage to add the message parser to our (small) test suite. That way we could include so many potential entries and their expected output without worrying when changing a regex or considering a rewrite...

Lots of bonus point to the person who will do that 😄

**Comment by astorije** [comment]
Hey @kode54, #972 should have fixed that. Mind testing your examples on `master`?

**Comment by kode54** [comment]
Verified fixed, but it does still pick up the #05] as a channel name link.

```[07:54:31] <Spring> ♪ マクロスMACROSS 82-99 - Night In Tokyo Pt. II [A Million Miles Away #05] · http://youtu.be/-aEvgivMy5o```

**Comment by astorije** [comment]
> it does still pick up the #5] as a channel name link

I don't think it's possible to flag this as an preventable bug. @xPaw, what do you think?

**Comment by dgw** [comment]
Given that the IRC spec allows channel names like `#5]`, it's probably not preventable.
