### ISSUE TITLE
The Lounge does not respect orientation locking on Android

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#586]
Since #310, orientation handling has changed: after setting The Lounge as a homescreen app from Chrome, The Lounge changes orientation from portrait to landscape mode even if user has locked the portrait mode on the phone (i.e. disabled auto-rotate).

Before that, preference would be honored, i.e. The Lounge would rotate if auto-rotate was enabled, or stay in portrait if auto-rotate was disabled.

**Comment by vectr0n** [comment]
Can also confirm this happens, it's been this way for awhile now, just never mentioned it.

**Comment by astorije** [comment]
Yeah, I only noticed that recently as I just removed and recreated the homescreen shortcut, and it's been a pain since then.

**Comment by YaManicKill** [comment]
What version of Android are you guys on? I have not seen this issue at all. It respects the setting fine. I'm on 7.0.

**Comment by vectr0n** [comment]
6.0.1 here.

**Comment by YaManicKill** [comment]
Hmm, so I just had an investigate, and it does indeed happen on my 6.0.1 Nexus 7, so it's looking like it might be an issue with pre-nougat. Trying to search on google I find basically nothing, though, which is odd. I've found a few things specific to cordova, which seem to imply that setting a theme can cause it, but that should be unrelated to a chrome app.

Anyone else have 7.0 and can confirm that it's not just I have something on my phone that is causing this to not happen for me?

**Comment by vectr0n** [comment]
Also can confirm on my old tablet it happens on 5.0.2 as well.

**Comment by astorije** [comment]
Forgot to specify my version indeed: Nexus 4 / Android 5.1.1 (won't upgrade any further 😢) / Chrome 52.0.2743.98.
