### ISSUE TITLE
Draging on the mobile client

### ISSUE THREAD

**Issue by JacobEdelman** [thelounge/lounge#589]
Add the feature to allow dragging the channels list and the users list on the mobile client rather than having to click a button to bring the up. I think this would be a big improvement in so far as making the mobile client nice to use.

**Comment by MaxLeiter** [comment]
Do you mean https://github.com/thelounge/lounge/pull/400?

**Comment by astorije** [comment]
I believe @JacobEdelman is talking about this yes. We'll have that eventually, it's just a matter of time :-)
Closing as duplicate.
