### ISSUE TITLE
Review and cherry-pick commits from erming/shout's dev branch

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#59]
Early 2015 erming made 64 commits to a `dev` branch that never made it to `master`. The diff is at https://github.com/erming/shout/compare/dev.

It would be great to go through each of them and see what we can do with that.

Listing here all the commits, with the following legend:

1. Not looked at yet
1. ~~Not interesting for The Lounge potentially with a very short explanation~~
1. [ ] Interesting for The Lounge, and either not cherry-picked/implemented yet or cherry-picked but not merged (add PR link)
1. [x] Interested, cherry-picked and merged

Can someone help me with that? :-)

1. Cleaning up [`f66dab1`](https://github.com/erming/shout/commit/f66dab1)
1. Cleaning up [`f9868bf`](https://github.com/erming/shout/commit/f9868bf)
1. Update grunt build [`3aa25b4`](https://github.com/erming/shout/commit/3aa25b4)
1. Code formatting [`0091e0f`](https://github.com/erming/shout/commit/0091e0f)
1. Add config [`86317e1`](https://github.com/erming/shout/commit/86317e1)
1. Add travis [`9bf9023`](https://github.com/erming/shout/commit/9bf9023)
1. Add socket.io  [`c012640`](https://github.com/erming/shout/commit/c012640)
1. Render template [`7d671da`](https://github.com/erming/shout/commit/7d671da)
1. Update config [`122719b`](https://github.com/erming/shout/commit/122719b)
1. Configurable root path  [`3e478c2`](https://github.com/erming/shout/commit/3e478c2)
1. Update README.md  [`57663bb`](https://github.com/erming/shout/commit/57663bb)
1. Create lots of files  [`d812357`](https://github.com/erming/shout/commit/d812357)
1. Add models  [`48900eb`](https://github.com/erming/shout/commit/48900eb)
1. Add .editorconfig  [`8422020`](https://github.com/erming/shout/commit/8422020)
1. Use tape  [`21c417f`](https://github.com/erming/shout/commit/21c417f)
1. Update cli [`2888a26`](https://github.com/erming/shout/commit/2888a26)
1. Add templates [`e5a153a`](https://github.com/erming/shout/commit/e5a153a)
1. Update grunt [`73a5b11`](https://github.com/erming/shout/commit/73a5b11)
1. Update grunt [`1c3746c`](https://github.com/erming/shout/commit/1c3746c)
1. Add event-emitter [`d8b7498`](https://github.com/erming/shout/commit/d8b7498)
1. Add tests [`adb351c`](https://github.com/erming/shout/commit/adb351c)
1. Remove files [`c650c87`](https://github.com/erming/shout/commit/c650c87)
1. Add inputs [`8af1aea`](https://github.com/erming/shout/commit/8af1aea)
1. Add client class [`27541a9`](https://github.com/erming/shout/commit/27541a9)
1. Update README.md [`4db8f71`](https://github.com/erming/shout/commit/4db8f71)
1. Add helper [`9396368`](https://github.com/erming/shout/commit/9396368)
1. Update help [`b7c93b3`](https://github.com/erming/shout/commit/b7c93b3)
1. Add manager [`bcccc04`](https://github.com/erming/shout/commit/bcccc04)
1. Export cli commands [`1ac5d30`](https://github.com/erming/shout/commit/1ac5d30)
1. Add files [`ac952b0`](https://github.com/erming/shout/commit/ac952b0)
1. Add events [`fe42b59`](https://github.com/erming/shout/commit/fe42b59)
1. Add events [`1fe0946`](https://github.com/erming/shout/commit/1fe0946)
1. Update README.md [`8376f6b`](https://github.com/erming/shout/commit/8376f6b)
1. Minor changes [`3dc9444`](https://github.com/erming/shout/commit/3dc9444)
1. Update README.md [`c68f7f4`](https://github.com/erming/shout/commit/c68f7f4)
1. Update lodash [`be1c2bd`](https://github.com/erming/shout/commit/be1c2bd)
1. Add message event [`e941f6b`](https://github.com/erming/shout/commit/e941f6b)
1. Add mode event [`6618f8f`](https://github.com/erming/shout/commit/6618f8f)
1. Remove faucet [`19c0396`](https://github.com/erming/shout/commit/19c0396)
1. Update mode event [`82bf208`](https://github.com/erming/shout/commit/82bf208)
1. Add motd event [`286be74`](https://github.com/erming/shout/commit/286be74)
1. Add names event [`397935a`](https://github.com/erming/shout/commit/397935a)
1. Add nick event [`b00ac6f`](https://github.com/erming/shout/commit/b00ac6f)
1. Add notice event [`224e7c0`](https://github.com/erming/shout/commit/224e7c0)
1. Add part event [`bd0b66a`](https://github.com/erming/shout/commit/bd0b66a)
1. Add quit event [`67e4677`](https://github.com/erming/shout/commit/67e4677)
1. Add topic event [`58b294b`](https://github.com/erming/shout/commit/58b294b)
1. Add welcome event [`d693344`](https://github.com/erming/shout/commit/d693344)
1. Add whois event [`c70871a`](https://github.com/erming/shout/commit/c70871a)
1. Update README.md [`1de5fc6`](https://github.com/erming/shout/commit/1de5fc6)
1. Add command-line tests [`eb68a78`](https://github.com/erming/shout/commit/eb68a78)
1. Add init command [`1567548`](https://github.com/erming/shout/commit/1567548)
1. Add glob package [`c037e88`](https://github.com/erming/shout/commit/c037e88)
1. Update config [`569385d`](https://github.com/erming/shout/commit/569385d)
1. Implement 'shout init' cli command [`f2af49e`](https://github.com/erming/shout/commit/f2af49e)
1. Add cli commands [`84e5dcd`](https://github.com/erming/shout/commit/84e5dcd)
1. Add start page [`4fc9f47`](https://github.com/erming/shout/commit/4fc9f47)
1. Add login [`ea89d2f`](https://github.com/erming/shout/commit/ea89d2f)
1. Add connect page [`8cc7b6a`](https://github.com/erming/shout/commit/8cc7b6a)
1. Refactoring [`91ccd88`](https://github.com/erming/shout/commit/91ccd88)
1. Add client connect [`226a110`](https://github.com/erming/shout/commit/226a110)
1. Fix broken tests after fresh install [`4ecc3b2`](https://github.com/erming/shout/commit/4ecc3b2)
1. Rename function for creating new users [`1920b59`](https://github.com/erming/shout/commit/1920b59)
1. Update lodash template [`34e1016`](https://github.com/erming/shout/commit/34e1016)

**Comment by xPaw** [comment]
There's honestly not really many interesting commits in there, all he did is start from scratch, and most commits are just reimplementing existing features.

**Comment by xPaw** [comment]
Going to close this.

**Comment by astorije** [comment]
Mmmh, I'll reopen when I start taking a look at them for real then...
