### ISSUE TITLE
Server fails to reconnect on dodgy internet connection

### ISSUE THREAD

**Issue by dskrepps** [thelounge/lounge#595]
I've been running 3 instances of lounge pre-release 5 on the same Ubuntu 14.04.4 server on Node 6.2.2 for ~2 weeks with my very dodgy Comcast internet that goes out for a minute or few minutes several times a day.

Seemingly at random when these connection issues occur one or more instances fail to reconnect to one or more irc networks. Sometimes the server window (which is hard to notice, but that's another issue) will say "Ping timeout, disconnecting", sometimes it also has an ETIMEDOUT error and says it will not reconnect, other times it will not say anything at all and have ZERO indication I am not connected.

Usually typing /connect will work, but sometimes that will only say that I am already connected until I remove and re-add the server or restart lounge. Neither stdout nor stderr have anything logged.

A few other users in #thelounge have reported the same problem.

**Comment by MaxLeiter** [comment]
Same thing occsaionally occurs for me with stable internet

**Comment by dskrepps** [comment]
I've been watching and noticed there are actually two different error messages I might get. Here's exactly what the server tab says: 

```
18:55		Ping timeout, disconnecting…
19:09		Socket error: Error: read ETIMEDOUT
19:09		Disconnected from the network, and will not reconnect. Use /connect to reconnect again.
```
And another at the same time:
```
18:55		Ping timeout, disconnecting…
19:10		Socket error: Error: read EHOSTUNREACH
19:10		Disconnected from the network, and will not reconnect. Use /connect to reconnect again.
```

I expect it to reconnect instead of saying it won't try to.

Note that these were two different instances of lounge running, connected to two different IRC networks, but on the same internet connection. So it likely is my internet going out causing it. However I rarely see my internet go out more than 5 minutes at very most, usually less; those 15 minutes between the ping timeout and the error message can't be right as I or my roommate would definitely notice it out for that long.

Max might have intermittent connection issues that are brief enough he doesn't realize, or an unrelated problem.
