### ISSUE TITLE
Exiting with status 15 (Received SIGTERM)

### ISSUE THREAD

**Issue by Taronyuu** [thelounge/lounge#599]
I have been using Lounge for a few months now and while I love it there is 1 problem that keeps bugging me. Every once and a while the IRC server will close the connection and there is (as far as I know) no option to reconnect. This means I should either remove the IRC server and connect again (resulting in me having te manually join all the channels again) or restart the whole Node process resulting me in disconnecting from all the servers.

Message in Lounge itself:
`Exiting with status 15 (Received SIGTERM)`

Result in the console:
`Client#connect():
Error: This socket has been ended by the other party`

So is there a way to auto reconnect or at the very least a quick manual way to reconnect?

**Comment by MaxLeiter** [comment]
Does `/reconnect` not work?

**Comment by Taronyuu** [comment]
It does not, no response of any kind when executing it.

**Comment by dgw** [comment]
The Lounge has always told me to use `/connect` when disconnected. I don't know if `/reconnect` exists.

**Comment by MaxLeiter** [comment]
Oh my bad, I totally meant /connect

**Comment by Taronyuu** [comment]
`/connect` doesn't work either. The `Exiting with status 15 (Received SIGTERM)` message is the only message I'm getting. Nothing about any possibility to reconnect.

**Comment by MaxLeiter** [comment]
What version of Lounge are you running?

**Comment by Taronyuu** [comment]
```lounge -v
1.5.0```

**Comment by dgw** [comment]
Aha. Reconnection support didn't come until after that

**Comment by astorije** [comment]
Fixed in 2.0.0. Hopefully we'll get to a stable release very soon :-)
