### ISSUE TITLE
Optionally hiding ident/realname fields (e.g. for webirc)

### ISSUE THREAD

**Issue by GLolol** [thelounge/lounge#606]
For communities not too well versed in IRC, having fewer fields to type text in makes connecting more convenient.  It may also help networks used to having idents like `webchat` hardcoded for all web users.

**Comment by xPaw** [comment]
If each whois row had a unique class, then you could hide it in css. Like `whois-realname`, `whois-secure`, etc.

**Comment by xPaw** [comment]
I'm going to close this as nothing is going to happen with issue. If you want to hide these fields, you can manually edit `index.html` or edit the CSS.
