### ISSUE TITLE
webirc config

### ISSUE THREAD

**Issue by acid67** [thelounge/lounge#611]
Problems setting up webirc feature, would like better documentation; the default config.js file is vague as to what goes where?

**Comment by maxpoulin64** [comment]
Basically, you set it up like that:

```javascript
"webirc": {
    "irc.example.net": "YourVerySecretPassword12345"
}
```

Where `irc.example.net` correspond to the address of the IRC server you want to use webirc with, and the password is, well, your webirc password the network operator gave you.

Then, when a user connects to that server, Lounge will enable the webirc extension and pass the IP and hostname along to the server.

**Comment by acid67** [comment]
I still can't get the server to set the real ip of the connecting client, is there some special configuration I should be using in my ircd's config? (I am using inspircd, with m_cgiirc.so) I have followed the instructions on the inspircd wiki for configuring cgiirc. I am not even getting any server notices that webirc is being attempted/failed. Seems it should be simple, not sure if i'm just overlooking some small detail or theres actually a bug. Thanks for your reply.

**Comment by acid67** [comment]
Some basic information to assist in resolving this issue; I installed on debian with "npm -g install thelounge" as instructed by docs, after digging around looking at the files (/usr/local/lib/node_modules/thelounge/src/client.js) it does not have the same lines as src/client.js available here on this github, the lines here of src/client.js (218-237) that seems to contain the webirc code are not in my client.js

**Comment by dgw** [comment]
If you did `npm -g install thelounge`, it installed 1.5.0. WEBIRC support wasn't added until 2.0.0-pre.1. You can install the latest prerelease of 2.0.0 with `npm -g install thelounge@next`.
