### ISSUE TITLE
emoji completion

### ISSUE THREAD

**Issue by nornagon** [thelounge/lounge#620]
Typing a partial emoji name between `::` should bring up an emoji completion menu a la GitHub:

![emoji completion menu](https://cloud.githubusercontent.com/assets/172800/18643894/f30e8840-7e5b-11e6-8c44-a840b981c6c0.png)

when choosing an emoji from the list, it should replace the partially-typed emoji with the Unicode character for that emoji.

**Comment by MiniDigger** [comment]
found this lib that does the lookup, now we only need the UI ^^
https://github.com/andreruffert/emoji-suggestions

**Comment by yashsriv** [comment]
I would like to work on this if no one else is tackling this right now....

**Comment by MiniDigger** [comment]
@yashsriv as nobody said anything here I doubt that anyone works on this. Be sure to join the irc channel on freenode to discuss details! (#thelounge on freenode)
