### ISSUE TITLE
Can't see channel textarea on mobile

### ISSUE THREAD

**Issue by Arthaey** [thelounge/lounge#624]
I've installed and run the Lounge for the first time. It works great on my desktop browser, but all I can see is the input box on my phone:

![image](https://cloud.githubusercontent.com/assets/71912/18683082/a22102f0-7f23-11e6-84bf-95a8c0cdd531.jpg)

I'm running the Lounge v2.0.0-rc.1 and viewing it in Safari on an iPhone 6 running iOS 8.1.2 (I know, I know…)

**Comment by MaxLeiter** [comment]
Unable to reproduce on iOS 8.2 Safari (jailbroken, in case that matters)

**Comment by Gilles123** [comment]
I'm able to reproduce in iOS Simulator 8.4. In my testing, an instance of Lounge running pre4 (as the demo server is at the moment) works in iOS 8.4. pre5 and newer releases fail to work. Console shows nothing relevant, but given the testing, something was changed between pre4 and pre5 that broke iOS 8 somehow.

**Comment by Arthaey** [comment]
I downgraded to pre4 and now it works great on my phone! Thanks for the workaround.

**Comment by Arthaey** [comment]
I do hope you'll consider fixing the bug, though, because it looks like you've done a lot of good work since pre4!

**Comment by Gilles123** [comment]
Figured it out.

In client/css/style.css, flex was implemented. However, older versions of Safari don't support that directly and require their own extensions. So it's just a matter of implementing the WebKit equivalents along with them as necessary. I tested this and it works.

        display: flex;
+       display: -webkit-flex;
        flex-direction: column;
+       -webkit-flex-direction: column;
        flex: 1;
+       -webkit-flex: 1;
        flex: 1 0 auto;
+       -webkit-flex: 1 0 auto;
        align-items: flex-end;
+       -webkit-align-items: flex-end;

**Comment by astorije** [comment]
> I do hope you'll consider fixing the bug, though, because it looks like you've done a lot of good work since pre4!

@Gilles123 and @MaxLeiter are working on a solution right now ;-)

**Comment by astorije** [comment]
@Arthaey, v2.0.0-rc.2 has been released with a fix (thanks to the 2 folks mentioned above), let us know of the outcome :)

**Comment by Arthaey** [comment]
I upgraded to rc2 and it works great on my phone now. Thank you so much for the quick fix! I'm quite impressed. :)
