### ISSUE TITLE
broken gradients in channel list on osx 10.12

### ISSUE THREAD

**Issue by niv** [thelounge/lounge#643]
After upgrading to OSX Sierra, the channel list has some weird gradients in it.

These did not show up before upgrading, nor do they show with Windows. It happens with Chrome 53.x and Electron (nativefier), but not Safari (10).
![image](https://cloud.githubusercontent.com/assets/11712/18838367/7db47c24-8407-11e6-8160-19f45c6f5108.png)

Inspecting the DOM with the debug console, looks like there is a ::after inserted that has this gradient specified in css.

**Comment by MaxLeiter** [comment]
Do you have any custom CSS? I had a similar problem yesterday but assumed it was my own CSS; I can comment a temporary fix here soon.

**Comment by niv** [comment]
I don't have any custom css running. Nativefier doesn't even support that, I think.

**Comment by MaxLeiter** [comment]
Just a note, by custom CSS I meant CSS in the settings menu, which nativefier should support

**Comment by niv** [comment]
Nope! Nothing in there. This is pure vanilla. It shows up both with the Example theme and Morning - I assume, they share that part of the code.

**Comment by astorije** [comment]
Is anyone able to reproduce this?!

**Comment by niv** [comment]
Seems to have been fixed with 10.12 final + lounge 2.1.0.
