### ISSUE TITLE
Thelounge 2.0.0 Random Crash

### ISSUE THREAD

**Issue by Rosiak** [thelounge/lounge#649]
Hi there,

Just upgraded this eve'.
I'm facing difficulties reconnecting to freenode(No shit), after some time I also experienced that the client itself crashed - with the following error message:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 91.217.189.42:6697
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
```

**Comment by maxpoulin64** [comment]
This is unfortunately a known issue we have a hard time isolating. There's a few other open issues about this (hence the duplicate label I just added), but I can't find them right now.

It appears to be a concurrency problem that causes the error to be thrown in the wrong place and it bypasses the error handler meant to deal with this and attempt another connection.

**Comment by hho** [comment]
I also have reconnect issues (see #648, maybe related?) and I got the exact same crash (same IP and everything) about 75 minutes ago. Flaky Freenode.

Could it be that a `/connect` in _The Lounge_ doesn't reset all state properly? So it works reliably the first time, but not on the n-th reconnect?

**Comment by omnicons** [comment]
I just had the same around the same time with freenode which crashed The Lounge for me through ZNC.
