### ISSUE TITLE
grunt build fails to build client/js/lounge.templates.js

### ISSUE THREAD

**Issue by diddledan** [thelounge/lounge#65]
the build task does not compile the file client/js/lounge.templates.js

running the command it is supposed to spawn manually does successfully compile the file which suggests that the task is not running at all when using grunt.

this is on Windows 10 with node.exe in the system PATH.

**Comment by astorije** [comment]
I am unable to reproduce this bug (on a different OS though). Anyone else having this issue?

@diddledan, did you successfully run `npm install` including the `devDependencies`?

**Comment by xPaw** [comment]
Yeah can confirm, templates aren't being built on Windows.
