### ISSUE TITLE
Add a "you" window to share links or text passages between clients.

### ISSUE THREAD

**Issue by MiniDigger** [thelounge/lounge#650]
I am using (abusing) the pm function to send small text passages or links between my clients. I am doing this by pm'ing myself. due to the nature of an irc client I see the message duplicated. (the message that I typed and the pm i got). A "you" window could disable the display of send messages in that window.

**Comment by astorije** [comment]
I'm not in favor of this, to be honest. I understand your use case, but I don't think that has anything to do with an IRC client :D
Also, you can already do that actually! (but the message does appear twice)

**Comment by MiniDigger** [comment]
is there any easy fix to not make the message appear twice?

**Comment by YaManicKill** [comment]
@astorije This could tie into #791

**Comment by astorije** [comment]
> @astorije This could tie into #791

it could, but I'd argue we are a messaging system and not a personal note-keeping app :)
I understand the use case and such, I may even use it once in a while (definitely now that I realized I can do it already lol), but there are also soooo many things on our plate right now that I would much rather focus on actual features dedicated to the core logic than these nice-to-haves 😅.

I will definitely change my mind when we can chop down 100+ of our open issues, but right now the load is just overwhelming.

**Comment by astorije** [comment]
> is there any easy fix to not make the message appear twice?

Maybe a check "if previous message is same nick + same text + posted < N seconds ago"? I don't know, this is probably less obvious than that. If you want to play with this in a PR, please do so, I don't think we'll decline such contribution (assuming it can be done without having to maintain 50 lines of code lol).
