### ISSUE TITLE
Change default maxHistory

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#665]
We currently have no reason to keep all the messages in memory, perhaps a default of like 5-10k would do the job.

**Comment by thisisdarshan** [comment]
That make sense, but what about the older messages?  It would be great if we could archive it to some datastore - like postgres.  Thoughts?

**Comment by xPaw** [comment]
@thisisdarshan that would be #442.

**Comment by astorije** [comment]
@xPaw, what's wrong with keeping them all by default and letting users change that setting if needed?

**Comment by xPaw** [comment]
@astorije not all users are aware that we keep infinite amount of messages in memory by default and then wonder why their server runs out of memory. We really have no purpose if keeping all the messages in memory.

**Comment by astorije** [comment]
> not all users are aware that we keep infinite amount of messages in memory by default

That could be greatly improved by updating our documentation :/

> then wonder why their server runs out of memory

This could still happen on small servers like Raspberry Pis when limiting to a few thousands, with several users and multiple channels, and then it would be even more confusing.
While I agree with you that it could reduce servers blowing up in some cases, it would not work in all cases.
Not sure what's the best course of action here, but I'm wondering if a default limit is a reasonable thing to do.
(As a side note, I think an improved version of #663 could help with this, with a future option to use DB or whatever people prefer, but defaulting to logs to keep memory usage low whenever possible)

> We really have no purpose if keeping all the messages in memory.

Sorry, I didn't get that statement.

**Comment by astorije** [comment]
Addressed by #899.
