### ISSUE TITLE
Replace bootstrap.js with alternatives

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#67]
At the moment, /client/js/libs/jquery/bootstrap.js is only used for transitions and tooltips. Once #62 is complete, we should probably replace it with [hint.css](http://kushagragour.in/lab/hint/) and CSS transitions or something

**Comment by xPaw** [comment]
Or we can take tooltips from Primer (GitHub's css), they look nicer than hint.css: http://primercss.io/tooltips/
