### ISSUE TITLE
fs.existsSync() is deprecated

### ISSUE THREAD

**Issue by toXel** [thelounge/lounge#672]
This method (e.g. used [here](https://github.com/thelounge/lounge/blob/master/src/command-line/index.js#L18)) is [deprecated](https://nodejs.org/api/fs.html#fs_fs_existssync_path) since Node v1.0.0.

I think it's best to use something like `fs.statSync(path).isFile()` or `fs.statSync(path).isDirectory()` as a replacement.

**Comment by xPaw** [comment]
We have `fs-extra` which has a method for it I believe.

**Comment by toXel** [comment]
Yes there is `ensureFileSync()` in `fs-extra` but this will also create the non-existent file.

**Comment by DaneEveritt** [comment]
As far as I can tell `fs-extra` doesn't actually have `existsSync()` in it, but it does make use of the function for a lot of its tests and internal functions.

**Comment by toXel** [comment]
Okay so as we can see [here](https://github.com/nodejs/node/issues/1592#issuecomment-147423014) and [here](https://github.com/nodejs/node/blob/master/lib/fs.js#L221-L229) there is not a big difference between fs.statSync() and fs.existsSync(). I think this issue could be closed. Sorry for the false alarm ^^

**Comment by toXel** [comment]
With Node 6.8.0 `fs.existsSync()` is now [undeprecated](https://nodejs.org/en/blog/release/v6.8.0/). I'll close this issue now.

**Comment by astorije** [comment]
lol @ https://nodejs.org/en/blog/release/v6.8.0/, https://github.com/nodejs/node/pull/8364, https://github.com/nodejs/node/issues/1592 and others. A big WTF really.
Anyhow, we'll definitely pursue this when getting rid of the non async calls. Thanks for closing the loop.
