### ISSUE TITLE
Replace URIjs with alternative

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#68]
We currently only use it once in /client/js/libs/handlebars/parse.js, we can probably create our own function or find one online that doesn't require a whole library to use.

**Comment by xPaw** [comment]
I suggest looking at how Kiwi IRC does it.

**Comment by xPaw** [comment]
I took a look at it again, and I think URI.js should stay, as they handle a lot of different and obscure cases with URLs.
