### ISSUE TITLE
Make it possible to listen to UNIX socket file

### ISSUE THREAD

**Issue by ilmaisin** [thelounge/lounge#686]
Offering services to the world by listening some TCP high port is not particularly secure, since a hostile unprivileged user can replace the server with a hostile server that steals user's passwords shall the actual server crash.

While this can be prevented with SELinux, it is quite a heavy-weight solution. My proposal is to allow listening of UNIX sockets. Then the reverse proxy or xinetd could be configured to redirect connections to that socket.

**Comment by astorije** [comment]
Hey @ilmaisin, that would be great! Do you think you could help us with that by opening a PR with your proposal?
Thanks!

**Comment by ilmaisin** [comment]
My development skills are unfortunately quite rudimentary, but maybe I can try and take a look at it.

**Comment by astorije** [comment]
Sounds good! And if you have any question, feel free to post them here and/or to open a PR early, even with non-functional or pseudo-code, and we can work with you in order to make that happen 😄.

**Comment by ilmaisin** [comment]
I made a tentative request here: https://github.com/thelounge/lounge/pull/691

Things that need yet to be done:

- Modify the stdio output to tell when we listen to socket
- Add a code to clean up old socket if the server has exited non-gracefully due to power outage or service crash
- Possibly add a command line option for socket listening
