### ISSUE TITLE
Lounge not Autoscrolling the whole way

### ISSUE THREAD

**Issue by acz13** [thelounge/lounge#690]
if a message goes off the bottom of the screen, the client should autoscroll...

however, it doesn't actually autoscroll until you press a key after the message was sent

**Comment by komradefox** [comment]
Seeing the same here

**Comment by TheSonAlsoRises** [comment]
Same here, Lounge does not autoscroll when new messages arrive in a channel. Running from source on 7e39ae0.

**Comment by xPaw** [comment]
The bug lies here: https://github.com/thelounge/lounge/blob/93c4c14b72f8fd235a1287624bfa0fced52f177e/client/js/libs/jquery/stickyscroll.js#L38

I will fix it today.
