### ISSUE TITLE
Nick change info message does not display old nick.

### ISSUE THREAD

**Issue by Raqbit** [thelounge/lounge#696]
When someone changes their nick, the old nick is not desplayed in the info message.

![image](https://cloud.githubusercontent.com/assets/113730/19413314/88ccbc58-92f7-11e6-9edc-9806651f82e1.png)

**Comment by astorije** [comment]
I need to check if this was not introduced by https://github.com/thelounge/lounge/pull/685, which is very likely. Holding on 2.1.0 release.

**Comment by astorije** [comment]
I can't reproduce this on master, can anyone else try to repro?

**Comment by Raqbit** [comment]
It turns out to be a user error. Did not run "npm run build" correctly, making stuff mess up :P
