### ISSUE TITLE
Add Cloudron as a deployment option for Lounge

### ISSUE THREAD

**Issue by gramakri** [thelounge/lounge#698]
Hey Guys, thanks for Lounge!

We are making an opensource platform for self-hosting at cloudron.io. I have packaged the app for Cloudron. You can find the MIT-licensed code here: https://git.cloudron.io/cloudron/thelounge-app.

You can try out lounge in our demo: https://my-demo.cloudron.me (You can then choose lounge from the Appstore navbar link).

Would you be open to adding a link to the Cloudron at https://thelounge.github.io/docs/ (deployment section) ? If so, I can submit a PR.

**Comment by astorije** [comment]
Hi @gramakri, welcome!
I believe this is more appropriate for [this wiki page](https://github.com/thelounge/lounge/wiki/Alternative-Install-methods), in which Cloudron already has an entry but could use some improvements. We can discuss here the changes required to the wiki page if you want.

What do other @thelounge/maintainers think?

**Comment by MaxLeiter** [comment]
I added the sentence about Cloudron last night; should we say something about what Cloudron is? 
Also, because we don't have an official logo, it seems it currently just has the example one I made a while back, but I think that's fine until we decide on an official logo in #282

**Comment by gramakri** [comment]
@MaxLeiter @astorije I was hoping to get Cloudron added as a deployment platform like Docker/Heroku (which is what we are, we are not a hosting provider) at https://thelounge.github.io/docs/. I hadn't seen the wiki page before, thanks for adding it already!

**Comment by MaxLeiter** [comment]
Ah, I see. This image probably belongs in the web repo, then: https://github.com/thelounge/thelounge.github.io/issues

**Comment by astorije** [comment]
@gramakri, the docs should and will only contain the "official" deployment methods, essentially ones that can be found in https://github.com/thelounge and maintained by the team itself. All third party deployments should be kept in the wiki (at least for now).

And actually, I have been willing to move the Heroku documentation from the website to the wiki for quite a while now, as none of the team members is actually using nor maintaining this. It's highly possible it's not outdated.

**Comment by gramakri** [comment]
Fair enough, I will close this issue. I will update the wiki to give more information.

If there is any interest in helping us out on the Cloudron app, please let me know and I am happy to move the app code under your github org.
