### ISSUE TITLE
No spaces in /away command (just the first word shows)

### ISSUE THREAD

**Issue by ranyyy** [thelounge/lounge#705]
When I try to set my /away status, I can't use spaces.

**Comment by xPaw** [comment]
Can confirm, for some reason only the first word is shown.

**Comment by stepie22** [comment]
Suspect it is being sent as is, and the irc specs require parameters that have spaces in them to be preceded with a `:`, which is also a workaround (typing `/away :my away message here`)

**Comment by xPaw** [comment]
Irc-fw is supposed to do that, the question is why it doesn't.
