### ISSUE TITLE
routines:SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by DaneEveritt** [thelounge/lounge#710]
So, I'm not entirely sure if this is something that can be fixed with The Lounge, or if it is something I need to fix on the server itself, but when I connected to a BNC network about a minute later my browser force refreshed the lounge and this error was in the logs immediately before it shows The Lounge rebooting.

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: 140387057076096:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

    at Error (native)
```

This is on `v2.0.1`.

**Comment by xPaw** [comment]
That stack trace does not provide any useful information for us to act upon. Seeing as this is a single report of this issue, I'm thinking this is most likely not an issue with Lounge. I will close this, if you get more details, feel free to reopen.
