### ISSUE TITLE
Custom notifications should only trigger when the message contains the keyword as word

### ISSUE THREAD

**Issue by lb1c** [thelounge/lounge#719]
Version 2.0.1
I'm using 2 different nickname frequently and i configured my lounge account to highlight the keywords 'lb, lb1a, @all'. But the highlighting keeps getting triggered when the string 'lb' is part of a complete different word: e.g: too**lb**ar .
I tried different keyword lists with and without empty strings
- lb, lb1a, @all
- lb,lb1a,@all
- lb , lb1a , @all

A fix would be to check if the keyword is not only part of the message string but also has empty strings around it (aka, is a whole word).
This was verified by PolarizedPumpkin in the lounge channel with current source.

**Comment by stepie22** [comment]
Can confirm, added `polar` as a custom highlight. Received a highlight when he said `polarbear`

**Comment by MiniDigger** [comment]
this is something I spoke about in the channel before but forgot to create an issue for. 
I think a regex bases system for custom notifications would be nice, altho more complex for users who never touched regex.

**Comment by lb1c** [comment]
@MiniDigger sure a regex system would be nice, but i didn't really intended to start a discussion about another hl system. I just wanted to use the existing system (keywords) but they don't work like i expected them to work.
