### ISSUE TITLE
does not autoscroll on new text

### ISSUE THREAD

**Issue by saveyour** [thelounge/lounge#726]
i'm not sure if it's intentional or not but when i'm in a chat i have to either keep typing something into the textarea or manually scroll down in the room to see the new messages. is there anyway to enable autoscroll ?

**Comment by Gilles123** [comment]
Which version are you on?

**Comment by saveyour** [comment]
93c4c14

**Comment by Gilles123** [comment]
Upgrade to 2.1.0. That issue was fixed.

**Comment by saveyour** [comment]
thanks for the help Gilles123 i'll upgrade and report back

**Comment by Gilles123** [comment]
git master is going to be newer than 2.1.0. I don't know for sure things will work properly on that. If you don't want to use npm to install it, you can always just download it from the release page: https://github.com/thelounge/lounge/releases/tag/v2.1.0

**Comment by saveyour** [comment]
it worked. thanks again for the help Gilles123
