### ISSUE TITLE
GUI connection doesn't work; /connect does

### ISSUE THREAD

**Issue by Krakob** [thelounge/lounge#733]
I tried connecting to irc.quakenet.org:6697 with the GUI with no luck. It would time out.

    Network created, connecting to irc.quakenet.org:6697...
    Socket error: Error: connect ETIMEDOUT 66.225.225.66:6697
    Disconnected from the network, and will not reconnect. Use /connect to reconnect again.

However, connecting with `/connect irc.quakenet.org` worked just fine.

**Comment by maxpoulin64** [comment]
As I just explained on IRC, this makes no sense as both end up taking the code path. The reason it works here is that both connection settings are not equivalent, but if you enter the exact same settings it will work fine.

With the GUI, you're connecting over port 6697 using TLS. With the connect command, you're connecting over port 6667, plain text. If you used the exact same settings with the connect command, `/connect irc.quakenet.org +6697`, you get exactly the same result. Lounge fails the TLS negociation and times out,

There's already a bug open for that TLS error.
