### ISSUE TITLE
Security issue - access without being logged in

### ISSUE THREAD

**Issue by zeten30** [thelounge/lounge#734]
Malicious user can change user settings even before logging into the system.
Access to this settings is not protected by authentication, but is only hidden in the HTML itself
and can be changed to visible by simple changing form variable to “window active” from
“window”. Malicious user can get to various user settings including password change.

By overwriting the classes to “window_active” in ID windows you get access to all id
subdirectories (loading, chat-container, connect, settings)

[report.pdf](https://github.com/thelounge/lounge/files/591734/report.pdf)

**Comment by xPaw** [comment]
Not a bug as these settings completely client side (stored in local storage), and you can't affect other users settings this way.

**Comment by williamboman** [comment]
You're not really *gaining* access to anything though. You're essentially gaining access to a different UI than your favorite browser's devtool, that can modify stuff stored locally in the browser (such as the user settings, stored in LocalStorage).

> Access to this settings is not protected by authentication

Access to anything stored on the server is protected implicitly by authentication. Attempting to change the user password by manually modifying the DOM state to gain access to the password form will most likely just yield a bunch of Type and ReferenceErrors in the client.

**Comment by zeten30** [comment]
Ok, thank you for clarification.

**Comment by astorije** [comment]
I really appreciate the effort however, it's great to know some people are looking around to make sure we are as secure as we should!
Thanks a lot, @zeten30!
