### ISSUE TITLE
Npm Prepublish will be changing

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#737]
So, with regards to #722, we do need to do **something** about it.

As mentioned, here is my suggestion:

* Add prepare to do the same as prepublish

This should mean that npm 1-4 will work with prepublish, while npm 5 (when released in Q1 2017) will work with prepare (having prepublish as well will mean that it is run twice on publish, but it's just building, so it'll just overwrite).

As far as I can see, there should be no side effects of this. Am I missing anything?

**Comment by xPaw** [comment]
Here's what I think we should do:
1. Change prepublish` to `prepublishOnly`, only @astorije makes releases, so not a big problem.
2. Explicitly document running `npm run build` after installing, as the new `npm prepare` doesn't run in 100% cases after `npm install` (e.g. when using root). #725.

**Comment by astorije** [comment]
https://github.com/thelounge/lounge/pull/858 resolves that issue.

> Change `prepublish` to `prepublishOnly`, only @astorije makes releases, so not a big problem.

Actually, only Travis does it. #858 now uses `prepublishOnly`, but that means deploying using v7 which is not a LTS, as it's the first version with npm v4. I'm OK with that, just an FYI.

> Possibly add a compilation marker (e.g. in lounge.js) and confirm it when starting the server to tell users to build the stuff (to alert users that they can possibly be running outdated scripts or not have them at all). We've had multiple issues already where users forgot to build and thought why the client was broken.

Agreed, too many people end up thinking their app is broken. #858 does not go as far as a compilation marker, I'm not sure how to do this reliably. It only checks that `client/js/bundle.js` exists (not that it's outdate), but that better than nothing.

**Comment by YaManicKill** [comment]
> but that means deploying using v7 which is not a LTS, as it's the first version with npm v4

Not necessarily, you can update npm separately from node.

**Comment by astorije** [comment]
> Not necessarily, you can update npm separately from node.

I'd rather avoid messing up with versions on CI at deployment time.
I think #858 does things nicely. What do you think, @YaManicKill?

**Comment by YaManicKill** [comment]
> I think #858 does things nicely. What do you think, @YaManicKill?

Yeah, looks fine for this. We will still need to change again once we get to npm 5, and change it back to "prepublish" as that'll replace "prepublishonly". But that's a while away, we probably won't get it till node 9, I expect, and we don't need to support it until node 10, because that'll be the first stable release with npm 5. So it's over a year away. But we'll keep an eye on it.

**Comment by YaManicKill** [comment]
Removed from milestone, as it isn't fully finished until we get npm 5 and sort that out, but we have done the first step.

**Comment by astorije** [comment]
Closing this now that #858 is merged. Rest is far future, so it makes little sense to keep that open in the meantime.
