### ISSUE TITLE
Make notifications stay longer or optionally persistent 

### ISSUE THREAD

**Issue by TheRealEscimo** [thelounge/lounge#738]
The Google Chrome notifications are disappearing too fast. They fade out after about 3 seconds.

It would be nice to have them last longer, or optionally persistent.
Should be possible by using the requireInteraction flag, which is new to Chrome 50:
https://developer.chrome.com/extensions/notifications#property-NotificationOptions-requireInteraction

**Comment by dgw** [comment]
Seems to duplicate #594 (which was closed as won't fix, oddly). Ref #739, which implements a fix for this.

**Comment by stepie22** [comment]
Since #739 was merged, this can be closed.
