### ISSUE TITLE
Sent PMs don't get synced

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#74]
I imagine this might be a limitation with IRC, but if you are connected to something like ZNC, and you connect with another client and send a PM to someone, it doesn't go to thelounge so you end up with a very confusing looking history.

It might not be possibly to sort out, but worth bringing up.

**Comment by xPaw** [comment]
Perhaps removing this check will fix the problem? https://github.com/thelounge/lounge/blob/master/src/plugins/inputs/msg.js#L22-L23

**Comment by dgw** [comment]
I forget what the capability is currently called, as it's been renamed, but adding support for the [IRCv3 `self-message` capability](http://danieloaks.net/ircv3-specs-web/specs/extensions/self-message-3.2.html) would resolve this, and likely improve bouncer playback handling in general.

**Comment by astorije** [comment]
Fixed by #270.
