### ISSUE TITLE
Oidentd not giving different idents

### ISSUE THREAD

**Issue by ronilaukkarinen** [thelounge/lounge#754]
Hello. Been trying to ask for help with this via IRC since didn't find anything worth trying by googling, so decided to open an issue.

My problem is, I'm getting ident, but it's always *rolle@pulina.fi* which is exactly the same ident than my irssi connection has for example. It's always the same for *all* users that use lounge, even if the username is completely different. So every lounge webchat user has the same ident than me - that's obviously a problem.

/etc/oidentd.conf
````
# Configuration for oidentd
# see oidentd.conf(5)
#
default {
	default {
		deny spoof
		deny spoof_all
		deny spoof_privport
		allow random
		allow random_numeric
		allow numeric
		deny hide
	}
}
user root {
     default {
          force reply "UNKNOWN"
     }
}
user rolle {
        default {
                allow spoof
                allow spoof_all
                allow random
                allow hide
       }
}
````

~/.oidentd.conf
````
# Warning: file generated by The Lounge: changes will be overwritten!
to 104.207.136.203 lport undefined from undefined fport 6667 { reply "lounge-user" }
to 104.238.168.67 lport undefined from undefined fport 6667 { reply "Bulibuli" }
to 83.140.172.210 lport undefined from undefined fport 6667 { reply "pulisijasafti" }
to 83.140.172.211 lport undefined from undefined fport 6667 { reply "pulisijasafti" }
to 80.65.57.26 lport undefined from undefined fport 6667 { reply "rollefromlounge" }
to 45.32.162.3 lport undefined from undefined fport 6667 { reply "rolle_test" }
to 66.225.225.66 lport 47541 from 139.59.208.244 fport 6667 { reply "pulisafti" }
to 104.207.136.203 lport undefined from undefined fport 6667 { reply "lounge-user" }
````

Currenly running lounge with debugger on in separate screen session, on user rolle.

**System**: Ubuntu 14.04 LTS server (Digital Ocean VPS)
**lounge**: v2.1.0
**node**: v7.0.0

**Comment by MAGICCC** [comment]
Will this get postponed until the next release or can we expect it earlier with some setting(file) where we can specify our ident when connecting to a network?

**Comment by ronilaukkarinen** [comment]
I haven't been using our webchat at all because this bug is practically untolerable for public webchats, risk for trolls to misuse it. No rush and not trying to be rude here, but I'm with @MAGICCC; equally interested about the ETA.

**Comment by xPaw** [comment]
ETA is "when it's done". This is an open source project where developers work on it in their free time.

**Comment by ronilaukkarinen** [comment]
Don't know why I asked it since as open source advocate I hate hearing the question myself as well, already knew the answer. Thank you and sorry 😄

**Comment by ronilaukkarinen** [comment]
[This PR](https://github.com/thelounge/lounge/pull/804) fixes identd, but I have irssi instance running fine on oidentd at the same time, so right now having to choose between irssi or lounge, both can't use the same port 113, obviously.

With latest release oidentd now saves ~/.oidentd.conf properly (earlier it has undefineds), but because irssi is running oidentd with one user, lounge for some reason still uses that same ident for all lounge connections for all users.

**Comment by astorije** [comment]
@ronilaukkarinen, #804 was merged, did that fix your issue?

**Comment by ronilaukkarinen** [comment]
Just tested it, still having the exactly the same identd `rolle@pulina.fi` in every lounge user which is the same than on my irssi.

````
rolle@pulina:~$ cat .oidentd.conf 
# Warning: file generated by The Lounge: changes will be overwritten!
to 91.217.189.21 lport 46677 from 139.59.208.244 fport 6667 { reply "rolletest" }
````

The nick `rolletest` is not part of the ident at all, however it's written in the ~/.oidentd.conf file. Any idea on how to fix this?

**Comment by xPaw** [comment]
I am going to close this as we have not had any updates on this.
