### ISSUE TITLE
Date-markers showing diffrent dates for link expander (on znc playback)

### ISSUE THREAD

**Issue by stepie22** [thelounge/lounge#760]
As you can see here, the link expander and the messages have diffrent dates. I believe this is because I am behind znc with playback buffer enabled, which sends the date with the messages, and the server only fetched the links now, hence why they are today's date. (This happened after a restart after updating to master)

A check should probably be made to ignore the prefetch's date

![](http://image.prntscr.com/image/5a9e7ad4d156471ba9d3e319a11fd8fa.png)

**Comment by YaManicKill** [comment]
Good catch, thanks. 

Just to check, the messages (not the link expanders) are in the correct date, yeah?

**Comment by stepie22** [comment]
Yes, thanks to the `znc.in/server-time-iso` capability thelounge supports and the znc playback buffer

**Comment by xPaw** [comment]
I think the bug is that expander button doesn't use server-time as it should.
