### ISSUE TITLE
List of keybindings/shortcuts

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#764]
We should have a page/overlay that shows the keybindings and shortcuts that we have.

Options for showing it:

* A page like the settings page
* An overlay like in most modern web apps

Options for invoking it:

* Button under channel list (next to the other buttons there)
* "Ctrl-?"
* "?" when not in input box

**Comment by MaxLeiter** [comment]
I think a table (two columns - command | effect/action) of IRC commands could be included in this
