### ISSUE TITLE
Git sign the tags/releases

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#766]
`git tag -s`.

This is mainly for @astorije to do. Github releases will also show a signed badge.

**Comment by astorije** [comment]
I guess I need to read more about signing tags. Note to self, read https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work and https://docs.npmjs.com/cli/version (which mentions signing tags) since I'm tagging with `npm version`.

Just to be sure, did you mean this for future tags or there is also a value in signing existing ones?

**Comment by xPaw** [comment]
Future. I don't think you can sign existing tags.

**Comment by astorije** [comment]
Alright, I should be all set for future commits and tags. We'll see with v2.3.0.
I looked quickly and it doesn't seem like you can sign existing ones, so :man_shrugging:. Happy to be proven wrong obviously!

**Comment by williamboman** [comment]
> I looked quickly and it doesn't seem like you can sign existing ones, so 🤷‍♂️. Happy to be proven wrong obviously!

You could remove all tags (locally and on GitHub) and re-tag them with signatures, I'm having a hard time seeing how this would break anything.

But by signing a later release you sort of implicitly sign all previous tags that share the same commit history, which in this case would be all tags in the repo.

**Comment by astorije** [comment]
https://github.com/thelounge/lounge/releases/tag/v2.3.0-rc.1 shows I got it right, so closing this now :)

> You could remove all tags (locally and on GitHub) and re-tag them with signatures, I'm having a hard time seeing how this would break anything if you do it quickly (for reals).

Yeah, I'm good leaving them as is...
