### ISSUE TITLE
Remove pencil icon next to nick

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#767]
I'm making this more for discussion then as a TODO to actually remove the pencil icon. 

While I think its helpful, I think its an eyesore and instantly stands out. I realize requiring the user to know the command `/nick` isn't great, but I feel there could be another way to have them change their nickname. The downside to being a web-based client is we can't have a menubar like other clients, so maybe we leave it until we implement being able to change user settings (or we add it as a context menu option when you right click on the server?)

**Comment by williamboman** [comment]
This has already been discussed to some extent in #551.

**Comment by richrd** [comment]
I support removing it, but also agree to most argumens for it in #551. On the other hand I'm not very bothered by it either.

What would really be worthwhile is making  the entire nick clickable, not just the icon. The icon is tiny on my OnePlus3.  
I can't imagine any other action that clicking the nick should do. Changing nick would surely be the most logical action by default, no?

**Comment by astorije** [comment]
There are alternatives (custom CSS) to whomever really doesn't want that button, and I think we should keep it around until channels/servers have settings. When this happens, we can move the nick changing logic to the settings.
Closing for now due to this.
