### ISSUE TITLE
[feature request] Show a error message in query window if messaging someone who isn't online

### ISSUE THREAD

**Issue by stepie22** [thelounge/lounge#769]
Currently it just shows `No such nick/channel (no_such_nick)` in the server window, which is easy to miss. It is also not very descriptive.

Ideally an error message should be put in the query window, as well as some indication that your message is not received.

**Comment by MaxLeiter** [comment]
duplicate of #337?

**Comment by stepie22** [comment]
Not exactly, but that would solve this, so closing
