### ISSUE TITLE
Figure out module system

### ISSUE THREAD

**Issue by YaManicKill** [thelounge/lounge#77]
So, thought I'd get a proper issue up for discussion on the module system that we will end up using.

There are 2 cases that we need to solve. These may use the same system, or they may use a different one.
### 1. Modularising the client

There are 2 parts to this: 3rd party libraries and lounge.js

Now, the next question is whether we want to be building this into 1 or 2 bundles, or whether we want to have them stay modularised, give thelounge http2 support and make that the default.

As a quick recap for those that don't know the difference between http 1.1 and http 2:
- http 1 can't download multiple files at once. Browsers have a hack to allow at most 10 to download simulataneously, because of this it is standard practice to concatenate as much as possible, and download as few files as possible, as this speeds it up
- http 2 has multiplexing and can download many, many files in parallel, and the standard practice for this is not concatenating, but keeping modules seperate as that speeds up downloading.

[If you look at global http2 usage](http://caniuse.com/#feat=http2) you'll see that >70% of people can use http 2. And if we focus on http2, http1 will still work, it'll just be a little slower than normal.

So, for us to decide what to do about modularising the client, we need to decide if we want to focus on http 1 or 2 just now.
### 2. Packages

So, @astorije brought up the point with me that it would be ideal to have a situation where a user can just install a new client package in thelounge and not need to reload the server to have it running. So, we need a way to dynamically include them on the browser (not needing a build step).

One option for this would be SystemJS, as that runs in the browser and allows you to include things programatically using any of the usual module systems. 

With all of these, we then need to decide on what syntax of module we want to code in.

Personally, I would suggest that we code everything in the same module syntax, as that means that people don't have to learn 1 syntax for core features and 1 syntax for packages. Any of the systems we use (browserify, rollup, systemjs) all support both commonjs and ES6 modules.

Seeing as browsers will support ES6 modules in the future (none support it yet), and probably not commonjs modules, I would suggest using ES6. This also allows us to use tree shaking if we wish in the future.

So, we need to decide:
- [ ] Module syntax?
- [ ] Bundle client JS or not?
- [ ] If bundle, how many bundles?
- [ ] What to use to allow programmatic modules for packages?

**Comment by xPaw** [comment]
> If you look at global http2 usage you'll see that >70% of people can use http 2. And if we focus on http2, http1 will still work, it'll just be a little slower than normal.

There's no magic behind support http2. And in our case, we shouldn't really be thinking about it too much. All our javascript/css files are downloaded on the page load, and as the application is meant to be long-running (we're a chat app after all), we can afford to do more requests to retrieve smaller payloads (we do need to set up proper caching though).

**Comment by YaManicKill** [comment]
> There's no magic behind support http2. 

I think that's a bit disingenuous to say. Of course there's no magic behind it, but it is true to say that it changes things enough to mean that we need to think about it.

> we can afford to do more requests to retrieve smaller payloads 

Well, this is what I'm suggesting anyway, and http2 means there would be no disadvantage to doing this. And it means that caching works really well with it (if we change 1 module, it doesn't need to redownload everything)

**Comment by lindskogen** [comment]
Maybe I misunderstood, but it sounds pretty insecure that the user can upload their own code to be executed for them? 

Do you know of any other project that has a similar use case where they solved this problem?

**Comment by astorije** [comment]
Hey @lindskogen,

> Maybe I misunderstood, but it sounds pretty insecure that the user can upload their own code to be executed for them?

Users would not upload their code to be executed on the server, so far it would be administrators who manage which packages are installed (and some core packages would come bundled with The Lounge). Users would be able to enable or disable them.

> Do you know of any other project that has a similar use case where they solved this problem?

Some similar but not exactly the same. For example, [Atom](https://atom.io) as a very well done package system using the same approach, but the key difference is the software format: no server, native app, ...
I don't know of any app in our model that lets users install and uninstall packages on the server, which is why we will probably not be able to do that. Another alternative could be that server-side packages are installed on the server by admins, and client-side packages are installed by the users locally, like in a `localStorage` or equivalent, but this becomes esoteric and adds its whole new world of issues...

**Comment by ruspow** [comment]
Just to stick my oar in..

**Comment by YaManicKill** [comment]
Closing this just now. We have a module system now, and we have started work on themes (#1266) so we will get to this.

There probably needs to be discussion around how we deal with adding the plugins to the client without running the build, but those can come later, and this has been stagnant for a while. Will open issues for separate discussions when we need them.
