### ISSUE TITLE
Storing client settings in the user settings

### ISSUE THREAD

**Issue by exadeci** [thelounge/lounge#770]
I configure all my devices the same way and I would like to have my client config stored and loaded on any new device by default.

That could require a flag to choose if we want our usual settings or different ones on the current device with by default, using the usual ones.

Maybe users should have a folder in `users` so they can have their connections settings and configuration settings in 2 separate files.

ex: 
```
.config/lounge/users/exadeci/connections.json
.config/lounge/users/exadeci/clients_settings.json
```

Could be part of https://github.com/thelounge/lounge/issues/85 maybe?

**Comment by astorije** [comment]
This was attempted in https://github.com/thelounge/lounge/pull/275 however that PR is inactive right now.
This is a nice enhancement request, but sadly there were/are many higher things on the todolist we've been focusing on.

(#275 says it does not directly solve #85 which is UI-oriented, though to be correctly usable, it would need some UI/UX thinking, so discussion there would still be relevant).

Closing as duplicate as there is already an issue and a PR for this. It's also been discussed on individual features (like, store notification preferences on the server, store custom CSS on the server, etc.) but it's harder to link to.
