### ISSUE TITLE
Lounge setup command

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#773]
We should probabaly write a cli for setting up the config for new users to make deployment easier.

Maybe the first option can ask if you're a "simple" or "advanced" user; advanced could ask about useHexIp, WebIRC, etc and simple could just ask private/public, first account, etc.

**Comment by xPaw** [comment]
Advanced configuration would just be editing the config.json yourself.

As for the simple setup, we could ask a few simple options when starting the server for the first time. But we need to decide which options to ask for (can't ask for all of them obviously).

1. Public?
2. Logs?
3. Prefetch?
4. Port?
5. identd?
