### ISSUE TITLE
thelounge not starting on arch linux

### ISSUE THREAD

**Issue by lilmike** [thelounge/lounge#785]
Nodejs 7.2.1-1, I thought this upgrade (which I had heard was a big one) could have been the culpret so I reinstalled thelounge, no dice).
Thelounge 2.1.0-1 (installed from AUR).

Output of sudo journalctl -u thelounge |tail -n50 (only the last occurrance):

Dec 10 10:29:33 mtserver systemd[1]: Started The Lounge IRC client. 
Dec 10 10:29:33 mtserver lounge[20682]: fs.js:1061
Dec 10 10:29:33 mtserver systemd[1]: thelounge.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 10:29:33 mtserver systemd[1]: thelounge.service: Unit entered failed state.
Dec 10 10:29:33 mtserver systemd[1]: thelounge.service: Failed with result 'exit-code'.

-Michael.

**Comment by maxpoulin64** [comment]
Seems like the log is cut off. Can you try starting it manually from the command line instead to have the full log?

**Comment by xPaw** [comment]
Create this issue in https://github.com/thelounge/arch-lounge/issues
