### ISSUE TITLE
Bar appears on bottom of screen on mobile Chrome Canary and Beta

### ISSUE THREAD

**Issue by tomatosoupcan** [thelounge/lounge#793]
Accessing the lounge from Android with Chrome Beta or Chrome Canary produces the following visual bug, where a bar appears at the bottom of the screen:

![](http://i.imgur.com/2rZ8SaN.png)

**Comment by xPaw** [comment]
Can confirm on Chrome Beta 56.

**Comment by xPaw** [comment]
The fix is simple: Change `100%` to `100vh` on `height` properly in `html, body` selector.

cc @astorije
