### ISSUE TITLE
Allow users to provide custom CSS in settings

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#80]

**Comment by MaxLeiter** [comment]
huge :+1: from me

**Comment by astorije** [comment]
For similar reasons than #45, the font family is very much the choice of the theme creator. Granted, theme management is very poor at the moment, but it will clearly get better :-)
This sadly opens the door to much more very specific and fine-grained settings: you might personally dislike the margins, the icons used, ... and we reasonably cannot provide a setting per thing a user might dislike in a theme.
In such case, if you are making changes to a theme that you want to distribute (and opening a PR on the theme does not work for any reason), you should be able to extend a theme with your very own theme (like `thatTheme` and `thatTheme-monospace`, ...).

That being said, as @xPaw mentioned on IRC, themes are managed by the administrator (at least at the moment, and it might be that it stays that way) and it's a pain to have a theme just for a minor UI stuff you don't want/like.
A very elegant solution I see is an editable textarea for CSS that overrides the current theme, and the content gets stored as-is in the user settings. That way:
- You can fiddle with the most detailed things of a theme without needing a specific setting for it
- Theme authors do not have to take into account the ton of settings we provide for UI things
- Theme authors can still provide all the defaults they want, and casual users will be very happy with an empty textarea.
- You can publish a gist with your CSS customizations if you want to provide a recipe for other users :-)

Note that this follows the adaptive learning experience I mentioned a few times: The Lounge comes with a decent default that newcomers use; slightly more advanced users pick the theme they want in the settings (not available yet); even more advanced users write their own CSS that overrides everything.

Another advantage of this is that we can quickly add this feature independently of how we improve theme management, which will most likely be longer.

Regarding font-size, I have a slightly different point of view: while font family is really a matter of personal visual preference, size might be something more accessibility related. In such case, maybe a relative selector would work better, like a slider or, simpler, a `select` with `Normal`, `Big` and `Bigger` values would work globally for the interface. And nothing prevents you to be more picky by using the CSS textarea described above.

What do you think? :-)

**Comment by xPaw** [comment]
> Regarding font-size, I have a slightly different point of view: while font family is really a matter of personal visual preference, size might be something more accessibility related.

As I mentioned on IRC, if we go the way of customized css field, we should have it pre-filled to allow to easily change font settings. Something like this:

```css
.user-set-font {
  font-size: 14px;
  font-family: Consolas;
}
```

**Comment by astorije** [comment]
Yes, it can be as simple as that, so this may definitely happen earlier than handling themes a better way :-)

However, I don't think we should pre-fill it at all. First because it's very personal (why font-family and font-size in particular?) and also because it's fairly difficult (if themes use different fonts, which one do we pre-fill it with? `inherit`? Then why one really) and because the underlying theme can evolve over time (we can't always be backward compatible when you provide your own custom CSS), ...
My take is that if you are advanced enough to edit custom CSS, you are definitely advanced enough to know what to change :-)

But yeah, this will be great! :-)

**Comment by astorije** [comment]
I won't close this because of the open PR (#83) but extended discussion about better settings can be found at #85.
