### ISSUE TITLE
Allow more options in The Lounge

### ISSUE THREAD

**Issue by theredv** [thelounge/lounge#806]
Not sure if I posted this to the right place, I usually have others do requests.

Allow lounge to run in both public and private mode, and allow public to connect to a certain source server, and private to connect to its specific source server.

Make it so you can specify which servers a client can connect to in the config, for example https://lounge.snoonet.org - When enabled, clients can select irc.snoonet.org (6697), bnc.snoonet.org (5457), irc.freenode.net (6697) but not be able to add custom addresses to connect to. This would be easier and defeat the purpose of running in both public and private mode.

I haven't yet loaded/played with the MYSQL storage and playback, however I had a different idea for lounge.snoonet.org, so clients can connect with whatever client they want and receive the logs across all devices:
Allow the lounge to connect to a BNC instance and authenticate with submitted user:pass, and then respect the playback logs from the BNC playback. With this idea I'd set playback in the lounge to 0, and utilize playback lines through ZNC.

Allow IRCv3 capab for time stamped messages

**Comment by xPaw** [comment]
Creating issues like this that are just dump of thoughts is not very productive.

> Allow lounge to run in both public and private mode, and allow public to connect to a certain source server, and private to connect to its specific source server.

#185 

> Make it so you can specify which servers a client can connect to in the config

Server limiting is implemented, but it only allows a single server.

> Allow the lounge to connect to a BNC instance 

Lounge itself is a bouncer. But it can also connect to other bouncers just fine (e.g. znc).

> I haven't yet loaded/played with the MYSQL storage and playback,

#442 

> Allow IRCv3 capab for time stamped messages

It's already implemented.
