### ISSUE TITLE
Inconsistency between favicon / channel list

### ISSUE THREAD

**Issue by nicoulaj** [thelounge/lounge#808]
Scenario:
 - Join an invite-only channel without being invited (in my case `#intellij` on freenode)
 - Forget about it
 - The channel will contain a message such as `ChanServ has kicked nicoulaj (Invite only channel)`
 - Restart lounge service
 - The favicon shows red, but the channel does not have the counter with white background
=> Hard to find where this notification comes from without cycling all the channels

**Comment by nicoulaj** [comment]
By the way, I'm running thelounge 2.1.0 on Arch Linux using [the AUR package](https://github.com/thelounge/arch-lounge).

**Comment by xPaw** [comment]
I believe this bug is fixed in `master` after I've reworked how unread/highlights work.
