### ISSUE TITLE
Add option to hide networks (flat channels view)

### ISSUE THREAD

**Issue by nicoulaj** [thelounge/lounge#809]
Ideally, I would like to have a flat list of all my channels sorted alphabetically, whatever the network is.
It would be nice to have a "Show networks" option in settings.

**Comment by astorije** [comment]
I am in favor of closing this issue as `won't fix`. I am fairly against the idea in the first place, as I can think of a few issues that cannot be solved without compromises. If there is this someday, it will be in plugins, if we ever implement them. @xPaw, what do you think?

**Comment by mikrobyte** [comment]
i think it would be nice to have...

but of course, i dont know what would the compromises be or how does such feature could possibly affect other functionalities.

**Comment by astorije** [comment]
This is extremely unlikely to ever be implemented or needed by a majority of users, so I will close this for now.
Also, considering the current code and UX, there are at least 2 non-trivial issues that I can think of that would make this much harder than it seems: 1) it would be hard to differentiate 2 channels with the same name on 2 different networks, 2) drag and drop to re-order channels would not be happy with this as is.
