### ISSUE TITLE
Can we remove fonts used solely for themes

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#81]
I would like to keep the codebase smaller but not having extra font files.

Crypto uses Inconsolata-g, Morning and Zenburn use Open Sans. The default font, which is Lato, is not bad by any means and is a good default for all these themes.

This should simplify things for #80

**Comment by astorije** [comment]
Very soon themes should be self-contained and contain their own fonts. I would hold off with removing them until then. If you remove them anyway, how will themes be able to use the fonts their authors have set?

**Comment by xPaw** [comment]
> how will themes be able to use the fonts their authors have set?

Just use Lato in Morning and Zenburn, it's very close looking to Open Sans.

Monospace fonts can be used in Crypto.

**Comment by astorije** [comment]
While I agree with you that we cannot reasonably host all fonts for all themes, I think they should stay right now. Hopefully very soon we'll provide better theme management and that will resolve this.
Changing that means that people using them will have their UI changed for the only sake of reducing the size of the repo.

**Comment by xPaw** [comment]
@thelounge/maintainers, would like to hear your opinions.

**Comment by YaManicKill** [comment]
I think we should leave this until we get some sort of better theme management. I know that probably won't be anytime soon, but I don't see the necessity in cutting it down.

**Comment by astorije** [comment]
> I think we should leave this until we get some sort of better theme management. I know that probably won't be anytime soon, but I don't see the necessity in cutting it down.

Agreed.

One first step I unsuccessfully attempted was to make themes independent from the base theme. I think that's the first requirement for better theme management. As @xPaw mentioned the other day on IRC, it's fairly difficult to create a theme because you have to override all defaults, and each new release is a potential theme breaker. By making each CSS independent of the default theme, we would reduce the risk (of course, changes to the markup has the same consequences, but that's a next step :-) ).

**Comment by maxpoulin64** [comment]
> As @xPaw mentioned the other day on IRC, it's fairly difficult to create a theme because you have to override all defaults, and each new release is a potential theme breaker.

An idea for that could be to split the default theme into two pieces: one very basic stylesheet that positions the things into the right place, and the default theme to add the colors, margins, alignment and all. That way themes don't have to start from scratch, but don't have to fight with the default theme either.

As for the fonts, maybe themes could load them from Google Fonts? One `@import` and it's done.

**Comment by astorije** [comment]
> An idea for that could be to split the default theme into two pieces: one very basic stylesheet that positions the things into the right place, and the default theme to add the colors, margins, alignment and all. That way themes don't have to start from scratch, but don't have to fight with the default theme either.

Yes it's a good idea for a start, at least until more freedom is given to theming (like using your own templates/markup, etc.).

> As for the fonts, maybe themes could load them from Google Fonts? One `@import` and it's done.

I believe they were originally but that was changed for privacy concerns, which I strongly support.

Anyway, as @YaManicKill said, when better theme management is achieved, this will be fixed as themes will be able to live in their own repos.
