### ISSUE TITLE
Give unhandled messages css class name with numeric

### ISSUE THREAD

**Issue by DanielOaks** [thelounge/lounge#814]
So in my theme I'd like to special-case the display of some messages like MAP, which TheLounge currently doesn't parse out specially. Right now I'm not able to do so since they show up with just the `unhandled` class:

![thelounge-msg-unhandled](https://cloud.githubusercontent.com/assets/251281/21291584/246eba56-c531-11e6-8097-91807db73184.PNG)

It'd be really cool if the command/verb could be slugified, prepended with "unhandled-", and added to that as well (final css classes ending up as something like `msg unhandled unhandled-015`.

Any chance something along these lines could be done? Basically, it'd allow themes to react specially to specific messages that are currently unhandled.

**Comment by xPaw** [comment]
Yeah the slug idea is great. I've been thinking about doing slug classnames also for nicknames, channels, servers, to allow for more customization.
