### ISSUE TITLE
Update packages before shipping 2.2.0

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#823]
As webpack will move client side vendor libraries to npm, we can update them.

**Comment by YaManicKill** [comment]
We should use greenkeeper for that. @astorije Did you ever have a look to see why it wasn't working?

**Comment by astorije** [comment]
I think when we looked at it, it was requiring admin rights, so we didn't look further. Not sure if still true or if that was a mistake.

However, I would not rush updating client-side packages, as we already know some will break stuff.

**Comment by xPaw** [comment]
It now exists as a native github integration. Check #826.

**Comment by astorije** [comment]
Sweet! So you didn't need to give it all sorts of permissions to enable it?
I'll look at #826 ASAP.

**Comment by xPaw** [comment]
@astorije the old bot acted on my behalf, e.g. branch creations appeared under my name.
