### ISSUE TITLE
Input field line-height bug

### ISSUE THREAD

**Issue by realies** [thelounge/lounge#827]
I've noticed this happning in v2.0.1 and v2.1.0. Screen grab from latest stable Chrome.

![capture2](https://cloud.githubusercontent.com/assets/5107843/21347590/3694141c-c6a1-11e6-87a9-500f6a513d20.png)

Adding this in the custom stylesheet field fixes it: `#form #input { line-height: normal; }`

Update: @xPaw mentioned there's a scroll-related issue and I've noticed hovering under the text shows up something looking like a horizontal scroll. I guess the question would be why would a horizontal scroll appear on something that's not beyond the visible area.

![capture](https://cloud.githubusercontent.com/assets/5107843/21348331/88b12cd2-c6a4-11e6-86cf-c5def9f59c1d.PNG)

Tempfix changes to: `#form #input { overflow-x: hidden; }`

**Comment by xPaw** [comment]
#556 is the related issue.

**Comment by YaManicKill** [comment]
```
11:24	realies	YaManicKill, bug is window size independent, windows scaling is set to  175%
11:24	realies	happens on retina macos devices as well
11:24	+YaManicKill	175%? Bloody hell.
11:25	+YaManicKill	And I do see it at that scaling
11:25	+YaManicKill	Well now, that's fun.
11:25	realies	4k at 15"... I sometimes go down to 150% for productivity
11:25	realies	it's always fun when you can't replicate the issue :D
11:25	+YaManicKill	That was me replicating it.
```

So, to replicate, zoom in to 175%.

**Comment by xPaw** [comment]
Is this still a problem on master? I can't reproduce it.

**Comment by dgw** [comment]
I've not seen it in 2.4.0 or while testing master, no.

**Comment by realies** [comment]
Looks as expected even at 500% zoom (Chrome, latest stable).
