### ISSUE TITLE
Small default font size

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#841]
Is it just me or is the font sizes we have defined are incredibly small? Default theme seems to define 12px, and morning 13px.

**Comment by MiniDigger** [comment]
I think its just fine.  all web chat clients I use have 12-13 (whatsapp web, skype, telegram), the forums I use have 12px too. 
have you just got a high res monitor? :D

**Comment by xPaw** [comment]
Morning uses Lato font in chat, which is why it increases to 13px. Default theme uses monospace font at 12px, which I do find more legible than the Morning font setup.

**Comment by astorije** [comment]
I find the message a bit small as well, especially on mobile. On laptop, I'm hardly ever bothered but it looks a tiny bit smaller than Slack/Telegram. On mobile however, it's way too small IMO.

**Comment by astorije** [comment]
I definitely would like to see this, especially on mobile where the text is tiny. Marking as up-for-grabs, it should be an easy fix if anyone wants to take a stab at it!

**Comment by bews** [comment]
So, how much font size should be increased? I think 14px is the best option. It looks great on my desktop and mobile, also GitHub uses 14px in comments too :)

**Comment by astorije** [comment]
Consolas looks really big at 14px. We currently have the same size as Telegram on desktop (we are at 12px right now), and increasing to 13px would put us similar to Slack.

For mobile, I'm not sure, I'd need to test.

@xPaw, whaddya think?

**Comment by bews** [comment]
> Consolas looks really big at 14px

This depends on screen resolution, for my display it's perfect.
Maybe we should discuss UI scaling again >_>

> increasing to 13px would put us similar to Slack

Actually Slack has 15px font size:

![2017-04-29_23-00-54](https://cloud.githubusercontent.com/assets/3627488/25558486/5331cbf0-2d30-11e7-940d-bd63c0427fa7.png)


which is a bit **bigger** than Consolas at 14px:

![2017-04-29_23-02-24-2](https://cloud.githubusercontent.com/assets/3627488/25558492/818c0164-2d30-11e7-8b8d-30ca32ec9c09.png)

**Comment by YaManicKill** [comment]
We have custom CSS, it's not difficult. I think the current one is too big.

**Comment by astorije** [comment]
> I think the current one is too big.

You mean you think the current font size is too big already?! Surely not on mobile, where it's super tiny, correct?

In general, I think we should avoid making it bigger or smaller based on personal preferences or setup (monitor, etc.), but as much as we can make it roughly the same as other messaging apps (or apps in general).
I only use Slack and Telegram on my laptop and mobile, so I don't have broad comparisons to make (especially on laptop), but on mobile, The Lounge is significantly smaller than other apps.

**Comment by astorije** [comment]
Reopening this one because switching from monospace to sans-serif in #1540 made this valid again.
