### ISSUE TITLE
Unable to use the websocket transport

### ISSUE THREAD

**Issue by fbm-static** [thelounge/lounge#848]
1. Edit ~/lounge/config.js and set

```
transports: ["websocket"],
```

2. After restarting the server, the client just keeps reloading.

I had to edit `client/js/lounge.js` and add

```
transports: ['websocket'],
```

in the `io()` call.

Browser: Google Chrome (Win) Version 55.0.2883.87 m (64-bit)

**Comment by ericbarch** [comment]
Running v2.1.0 in Docker. With the default server config:

transports: ["polling", "websocket"]

I'm also seeing Chrome failing to upgrade to a websocket.

WebSocket connection to '(my host's wss URL)' failed: WebSocket is closed before the connection is established.
