### ISSUE TITLE
Front-end develop/debug experience is much worse than pre-Webpack era

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#857]
I was trying to work on #856 and kept bashing my head against the wall: many things that were possible and helping code or debug are now gone.

Granted, part of my frustration is caused by my current lack of understanding of Webpack/Babel and the like, but I am going to only list here the technical issues that I encountered.
I'm happy to RTFM, but at the very least it should be as easy to code/debug/test as it used to be.

- [x] `debugger` statements are being dropped when running Webpack. This is due to `UglifyJsPlugin` which drops them by default.
  Current workarounds include adding `drop_debugger: false` to the `compress` object in the Webpack config or commenting out the plugin locally. What do we want to do in repo? Both options are meh, but first one is less meh since ESLint ensures `debugger` statements do not end up in `master`. Is there a better solution?

- [x] When reaching breakpoints, it is now not possible to evaluate code using the browser REPL. To reproduce, add `var foo = "bar"; debugger;` anywhere, run webpack, open the browser devtools and make sure to reach the breakpoint. When evaluating `foo`, browser says `VM72:ReferenceError: foo is not defined`.
  I did not find an alternative yet and this is driving me crazy 😅

- [ ] ~~Likely a symptom of the same issue, but~~ none of the globals are available anymore. This means it is not possible to open a browser console, select an element and evaluate `$($0)` anymore because `$` is undefined<sup>1</sup>.
  Temporary workaround I have found is to add `window.$ = $;` in `lounge.js` to have access to `$`. We obviously will not be able to ship this in production, which means that it will be hell to debug a production instance after next release if not fixed (hence `priority` label).

- [ ] Sometimes `npm run start-dev` loses it and will not rebuild anymore. This forces a whole server restart, which is annoying as we lose history and such. Not sure what to do here, I ended up restarting the server every time so far...

---

<sup>1</sup> `$0` simply references the element currently selected by the inspector

**Comment by astorije** [comment]
[This](https://webpack.github.io/docs/list-of-hints.html#developer-performance) has some recommendations:

> Use webpack devtools for debugging in browser: Better debugging experience, real source code, real module names, at the cost of slower build and difference to production build (Developer, for every app)

But this does not solve the 3rd point (and yay, more complexity...).

**Comment by astorije** [comment]
> I would consider this actually a win for us, because we no longer pollute globals, and thus the entire client code is contained and less likely to be tampered with.

I don't entirely agree as things like jQuery are indeed available globally within the client code, so it's not a super clear win (though when we start expanding the client, it will be). However, I do not call making debugging harder a win :)
What solutions do we have? Is it reasonable to have a function (say `debugMode()`) available in the client code which, once called from a browser console, unleashes the globals? I don't know, maybe it's stupid, but I'm open to ideas and suggestions.

> Could be an OSX issue.

I don't think so (at least not the `OS-X fsevents bug` as  they have a check for it, warn the user, and it's rare enough to not affect me).
I've noticed that, sometimes, when a build fails, Webpack won't rebuild anymore. It seems more like a Webpack bug than an OSX bug. Right now I'm running `npm start` and `npm run watch` in 2 different terminal windows. Not a huge deal, but still a pain, and it kills the point of `npm run start-dev`. Not sure what to do about that.

**Comment by astorije** [comment]
BTW, for whomever ends up here, @xPaw is attempting to fix the first 2 items of the list above in his PR #858. I have yet to test it.

**Comment by astorije** [comment]
> Likely a symptom of the same issue, but none of the globals are available anymore. This means it is not possible to open a browser console, select an element and evaluate `$($0)` anymore because `$` is undefined.
> Temporary workaround I have found is to add `window.$ = $;` in lounge.js to have access to `$`. We obviously will not be able to ship this in production, which means that it will be hell to debug a production instance after next release if not fixed

@xPaw, any idea how we can go around this for v2.2.0? I understand that not leaking globals is a good thing conceptually, but it also means that debugging a production issue will be way more painful and that easily cancels out the win.

Throwing some ideas out there, maybe they're all 💩 so feel free to suggest anything better:

- `?debug=1` would load a page where these globals are available. This is not ideal because it forces a page reload.
- A function knowingly accessible as a global (like `debug()` or `enableDebug()` or whatever) that makes the globals available. Advantage is you run it from the browser devtools so no need to refresh.

Note that these ideas are very similar (one could add a debug checkbox in the settings to the list, but it's the same, and does not provide anything more, except localStorage persistency at the cost of an unpleasant extra parameter to normal users), but I don't know how feasible it is in practice...
Again, taking any better idea than that.

**Comment by astorije** [comment]
@xPaw, any ideas? I'd hate to ship our next version without being able to use jQuery selectors, among other things.
For example, my main instance of The Lounge is actually the npm release and I very often open the dev tools to debug it with real data. We wouldn't be able to do so afterwards. This is also true when running from master with `NODE_ENV=production npm run build` (after #858 lands), so only way to have a "debuggable" instance would be to run from source AND no in production mode. Not good :S

**Comment by YaManicKill** [comment]
So, what's the current state of these issues, @astorije ?

**Comment by astorije** [comment]
> Regarding the globals, the idea is that you can access $ and stuff from breakpoints. So most of the time bugs come up in a function. So we can set a breakpoint in that function, and everything should be available there. Do we really need them globally available outside of this? If so, then I would be happy with either of the options that @astorije suggests.

For example, you can't open a console and start fiddling with `$('#input')` as `$` is undefined.
This could be addressed at least short term by doing `window.$ = $;` in `lounge.js`. It would allow for v2.2.0 to go out shortly and be correctly debuggable while we have a better solution in v2.3.0.

Also, setting breakpoints does not work correctly in production environment because of the uglification. That being said, I need to re-try that now that #858 has landed. I'll do that tomorrow.

> I think this is just an issue with webpack. I don't think there's anything we can do here.

I'm afraid you are right... I guess I'll use `npm start` and `npm run watch` in 2 terminals instead of `npm run start-dev`.

**Comment by YaManicKill** [comment]
> For example, you can't open a console and start fiddling with $('#input') as $ is undefined.
This could be addressed at least short term by doing window.$ = $; in lounge.js. It would allow for v2.2.0 to go out shortly and be correctly debuggable while we have a better solution in v2.3.0.

Meh, fine I guess. I mean, [you could just load it in the console manually](http://stackoverflow.com/questions/7474354/include-jquery-in-the-javascript-console), but I'm not really bothered.

> Also, setting breakpoints does not work correctly in production environment because of the uglification. That being said, I need to re-try that now that #858 has landed. I'll do that tomorrow.

So, you've ticked this in the post description, so does this mean that it's fixed now? The map should have sorted this, so I assume the fix worked for that.

**Comment by astorije** [comment]
> Meh, fine I guess. I mean, you could just load it in the console manually, but I'm not really bothered.

Turns out, when running `NODE_ENV=production npm run build`, `$` is now available from the dev tools console. So one can run things like `$("#input")` or else to debug an issue specifically on a release and/or in production.
Not sure what we did that could have changed that. It was definitely not possible prior to #858. It also does not make sense to me that it's now possible, but I won't complain. Note that it's not true for other globals, except `Mousetrap`. Some kind of wild west in there. Ah, the magic of obscure build systems :)

> So, you've ticked this in the post description, so does this mean that it's fixed now? The map should have sorted this, so I assume the fix worked for that.

Yes, but I wanted to test the behavior on `production` post-#858. It's still the case: while you can place a breakpoint somewhere from the dev tools and it will correctly be reached, you can't evaluate the content of variables from the console. It's possible to temporarily turn off the source maps and evaluate the uglified variable names (breakpoints are shared between `lounge.js` and `bundle.js`) though. There might be some configuration issue here, or maybe that's how source maps are supposed to work. Either way, this is not impeding the release.

---

So between `$` now being accessible (random) and last item being Webpack-related and/or OSX-related and/or magic (what is this, Ruby on Rails?!), we are good here, closing.
Thanks for your efforts and patience! :)
