### ISSUE TITLE
Feature Request - Scripting Interface

### ISSUE THREAD

**Issue by saveyour** [thelounge/lounge#866]
i've already hacked together my own sort of autojoin scripting interface by adding an autojoin.js to client/js/autojoin.js and linking to it in the index page with a <script src> tag. it only has the ability to autojoin channels on my znc but it's pretty handy. 

```
setTimeout(function(){
 $('textarea').val('/server znc +7000');
 $('#submit').trigger('click');
},1500);
```

this got me thinking that it would be nice if there was some kind of scripting interface / ui element we could use to manage different scripts. just basic things like set timers and triggers similar to how mirc used to work.. 

for example what i did above would just look something more like

`sleep 1500
server znc +7000`

sorry if i'm missing something here, but i think this would be very useful in making this a more useful irc client in general. thanks for hearing my suggestion

**Comment by MiniDigger** [comment]
There is a whole plugin api coming soon (tm), see #444 or the wiki pages https://github.com/thelounge/lounge/wiki/Package-system-design-and-plan https://github.com/thelounge/lounge/wiki/Initial-Package-System-Interface
