### ISSUE TITLE
Autocomplete and send buttons are too close together on mobile

### ISSUE THREAD

**Issue by PolarizedIons** [thelounge/lounge#869]
On mobile, it is extremely easy to hit the wrong button, or both.

I  know you can hide them with css, but I feel that you shouldn't have to add custom css to be able to use thelounge properly.

**Comment by astorije** [comment]
This was a less-than-ideal-but-better-than-nothing solution. It will be elegantly fixed by https://github.com/thelounge/lounge/pull/787.
