### ISSUE TITLE
Stable / security branch?

### ISSUE THREAD

**Issue by davepage-mcr** [thelounge/lounge#871]
I'm looking at deploying an Internet-facing instance of TheLounge, using npm.

Since upgrading thelounge (and its dependencies) via npm can break connections and lose backscroll for users who aren't currently connected, I'd like to minimise upgrades while still making sure that known security vulnerabilities are addressed.

Are there any plans to have a "stable" branch between major releases of npm which only receives security fixes until the next major release happens? And if that were possible in git, would there be a way to track that branch with npm? Possibly the stable branch could use stable branches of dependencies where available to avoid unnecessary upgrades to those.

**Comment by YaManicKill** [comment]
> Since upgrading thelounge (and its dependencies) via npm can break connections and lose backscroll for users who aren't currently connected, I'd like to minimise upgrades while still making sure that known security vulnerabilities are addressed.

So, a quick point is to note that we are planning on having this fixed. There are a couple of PRs currently up to fix these, so if these issues are fixed, would you still want this?

Currently, we have no plans for this, but if there was a lot of demand for it, we certainly would think about it.

**Comment by xPaw** [comment]
I don't know if we can maintain very well, since the codebase changes a lot, and it would be a lot of work to keep a security branch.

**Comment by compuguy** [comment]
@davepage-mcr Have you considered using the docker container of thelounge? That makes upgrades more streamlined.

**Comment by astorije** [comment]
Agreed with @xPaw, it would be very hard for our small team to pull that off.

Closing this for now until there is a real need for it.
