### ISSUE TITLE
feature request: configurable actions on events

### ISSUE THREAD

**Issue by niv** [thelounge/lounge#874]
Hello,

what I'm missing with lounge is a way to configure actions when some event triggers; a simple execve() for events like "being highlighted in a channel as configured", "connect/disconnect from server", and so on.

Intended usecase is simply redirecting important events to other messengers/mobile notifications. This could then, for example, work through a simple curl call that could run asynchronously.

Is something like this on the roadmap?

**Comment by MiniDigger** [comment]
well, this is kinda covered by the plugin system that is coming soon (tm)
see #444 and https://github.com/thelounge/lounge/wiki/Package-system-design-and-plan https://github.com/thelounge/lounge/wiki/Initial-Package-System-Interface

**Comment by niv** [comment]
Ah, well, thank you. I'll wait for that then. :)  Still a good thing to show there's interest for it, I think.
