### ISSUE TITLE
Websocket connection failed: Establishing a tunnel via proxy server failed

### ISSUE THREAD

**Issue by pinkeshbadjatiya** [thelounge/lounge#877]
I am using lounge from behind proxy. I receive this error on opening it for the first time, but it seems to work fine(unless i open the console and look for this error) as it reconnects almost at the same instant.
![image](https://cloud.githubusercontent.com/assets/14854424/21927297/731fe538-d9ab-11e6-8af3-a146e3f44561.png)

This line throws the error.
![image](https://cloud.githubusercontent.com/assets/14854424/21927395/98abc0ba-d9ab-11e6-8b0b-db69660d18fa.png)

**Comment by xPaw** [comment]
Sounds like your prozy setup is not allowing websockets and it falls back to polling. Unlikely to be a bug on our side.

**Comment by pinkeshbadjatiya** [comment]
Is Fallback to polling permanent? I mean does it use polling every time by default as long as the server is running because it is frequently asking to reconnect.

**Comment by xPaw** [comment]
Socket.io handles it for us. It tries to open WS with fallback to polling. Unlikely that it keeps memory of failed WS connections between page reloads.
