### ISSUE TITLE
/part doesn't get send to znc

### ISSUE THREAD

**Issue by MiniDigger** [thelounge/lounge#886]
Whenever I part a channel using /part to which I am connected using znc, lounge only closes the windows but does not leave the channel in znc. 
when I then get a message in that channel, it is displayed in a pm window (with the name #name).
I can tell that it is a pm window since there is no user list and I get the sounds. disconnecting and reconnecting to the network restores the old state. 
lounge version is b67836f
znc version is 1.6.3

**Comment by xPaw** [comment]
Is your znc configured to do some kind of unattachment? Unless you are closing an already broken window (that is not considered a channel), then it will send part.

**Comment by MiniDigger** [comment]
mmh, I don't think that I configured anything in znc. 
I just tried again to reproduce it and I couldn't do it, strange.
could reproduce it on ever try before. 
closing for now
