### ISSUE TITLE
Channel assign with URL

### ISSUE THREAD

**Issue by daniel-hyuuga** [thelounge/lounge#888]
It is a little trick where I can give out TheLounge URLs with intended channels defined.

lounge.js (line 881)
-------------
```
        document.title = title;

        var t=window.location.href.split("?");

        if (t.length > 1) {
            if (t[1].indexOf(",") > -1) {
                t = t[1].split(",");
            }
            else {
                t = new Array(t[1]);
            }
            $("#connect\\:channels").val(t.join(" "));
        }
```

With this, you can give out urls like `http://chat.exampleirc.net/?#lobby,#help`
**EDIT**: Fixed issue where the javascript would add URL instead of channel if no channel specified in URL

**Comment by YaManicKill** [comment]
Huh, I'm surprised this doesn't exist as an issue already.

First of all, we'd need a way to define the server as well, not just the chan (most people have multiple servers). This was mentioned in #574 as a good idea.

**Comment by MaxLeiter** [comment]
Once 2.2.0 is released, you can do this in public mode as of #674

**Comment by astorije** [comment]
Closing this as this will part of v2.2.0, which is just around the corner.

**Comment by YaManicKill** [comment]
But this won't be the case in private mode, which is still a legitimate
feature.
