### ISSUE TITLE
User search should support regular expressions

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/lounge#891]

**Comment by GiacomoCaruso** [comment]
I could work on it this weekend if you like.

**Comment by MaxLeiter** [comment]
We should probably hear a few more opinions

**Comment by astorije** [comment]
👎 to regex search. Regexes are the worst kind of UX you could expect 😅 

However, 👍 for a more flexible search. I have something in progress in #856. It's working exactly as it should but implementation is a bit meh.
I'd love some opinions on how to make it better :)

**Comment by MaxLeiter** [comment]
Well, what if it was implemented in a way where you definitely -want- to use regex? i.e. starting the search with / and making sure its valid; if not, just search for it like normal

**Comment by dgw** [comment]
User search, as in finding users in the user list? What are the use cases for regex there?

@astorije is quite right that the UX of regex is terrible for the average user. Fuzzy matching, already being worked on as stated, is much less arcane and still very useful for filtering through long lists of nicknames.

**Comment by YaManicKill** [comment]
Yeah, I'm not sure why you would want regex search, tbh. Fuzzy searching should give you all the advantages, yeah?

**Comment by MaxLeiter** [comment]
Yeah fuzzy is all that's needed
