### ISSUE TITLE
plaintext HTTP 2 on a separate port

### ISSUE THREAD

**Issue by nhooyr** [thelounge/lounge#893]
I run lounge behind a TLS terminating reverse proxy. Unfortunately, this means lounge will not serve http 2 requests for me because it wants to control TLS itself. A simple way to get around this would be to allow for plaintext http 2 mode on a separate port. I can get my proxy to route to different ports based on the negotiated protocol of the request.

**Comment by nhooyr** [comment]
I might try a different approach. @xPaw on irc suggested to have my reverse proxy handle http 2 and dial back in http 1.0.

**Comment by xPaw** [comment]
We're unlikely to do this so I'm going to close this.
