### ISSUE TITLE
remap keys to move up/down a channel

### ISSUE THREAD

**Issue by nhooyr** [thelounge/lounge#894]
I prefer to have different shortcuts for moving up/down channels.

**Comment by astorije** [comment]
At the moment, shortcuts are not customizable (and to be fair, they are not on most "modern" chat apps like Telegram or Slack) so this is not likely to be changed anytime soon.

<kbd>Cmd</kbd> + <kbd>↑</kbd> / <kbd>↓</kbd> and <kbd>Ctrl</kbd> + <kbd>↑</kbd> / <kbd>↓</kbd> are actually pretty standard, so there is no way we can please everyone without a full shortcut refactor, or better an API that let people write plugin for this.

Closing this for reasons explained above.
