### ISSUE TITLE
web app crashes when entering a link

### ISSUE THREAD

**Issue by nhooyr** [thelounge/lounge#897]
thelounge crashes when I enter https://dropbox.aubble.com/Screen%20Shot%202017-01-28%20at%205.07.32%20PM.png into a channel. Nothing appears in the debug output, it just crashes. If I reload the page, then everything seems to work fine again.

**Comment by nhooyr** [comment]
In case it was unclear, the server runs fine, just the webapp crashes and I have to reload the page.

**Comment by nhooyr** [comment]
I've recorded a screencast to make it more clear: https://youtu.be/Dgp7eTRL2vw

**Comment by nhooyr** [comment]
turns out, lounge was crashing my reverse proxy (it serves both dropbox.aubble.com and lounge.aubble.com) when trying to get a preview of dropbox.aubble.com. I've fixed it now.

**Comment by dgw** [comment]
As a side note, I'm interested to know what your toolchain looks like for uploading screenshots to your dropbox domain. It looks handy, and probably lighter weight than Puush/Dropbox/ShareX… :)

**Comment by nhooyr** [comment]
@dgw it's all custom. https://github.com/nhooyr/sync monitors a folder on my laptop. Whenever any file in it changes, it calls rsync to sync the folder to my server and then copies a link to this file to my clipboard (and gives a nice popup notification). On the the server, I have https://github.com/nhooyr/serveHTTP running serving that directory to serve the links.

Lastly, I've changed macOS to put screenshots that it takes with standard shortcuts into this directory.
