### ISSUE TITLE
Actions containing Highlights display incorrectly

### ISSUE THREAD

**Issue by easymac** [thelounge/lounge#90]
Actions have the sender's nickname to the right of the bar which separates nicknames and messages.

When an Action contains a Highlight, the action displays correctly except the nickname appears to the left of the aforementioned bar.

[Here's an example](http://i.imgur.com/8bs3M2Z.png)

([Here's an example from the other side, courtesy of IRC user vectr0n](https://vectr0n.net/img/uploads/big/ac443ec62b006ffc37a512d3dbd75dee.png))

This is likely a minor fix to move the name back across the bar. I would also encourage changing the color to the red highlight color. The placement of the nick and the star icon both clearly indicate that it's an Action, but nothing indicates that it's a Highlight except the sound and badge. I believe we would be better served by having Actions that contain Highlights appear red.

**Comment by astorije** [comment]
:+1: 
@xPaw, do you think you could take a look at this?

I also agree with @easymac regarding the color: always color in red mentions, even in `/me` actions.
