### ISSUE TITLE
Mark buffer as read when receiving self-/echo-message

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#911]
The Lounge makes a great "always-on" client for ZNC that I can load up if I'm away from a computer, without having to keep a client running on my phone all the time. But the experience is a little frustrating when it comes to unread statuses for channels and PMs. Things I've sent messages to from another client still appear as unread in The Lounge, and I have to remember whether I've actually read them.

Since #270 added support for the `echo-message` extension of IRCv3 (and ZNC's version of it, `znc.in/self-message`), I wonder if it wouldn't be possible for The Lounge to mark buffers as read on incoming echoed messages.

Granted, I haven't yet seen any other client do this…but I'd argue that more clients should, as it's much better UX for bouncer users—especially given The Lounge's explicit design goal of being "always on", unlike a traditional desktop IRC client.

**Comment by xPaw** [comment]
It's not a bad idea, and easy to implement. I'm trying to think of a reason why we shouldn't, but nothing obvious comes to mind.

**Comment by dgw** [comment]
I'm lining up issues in various repos that I might want to try and tackle during Hacktoberfest, and this looks like a good candidate—especially since I would love to have this more than ever. Would be great if a maintainer could assign me (I'm using assigned issues as a shortlist of what to work on during HF). :smile_cat:
