### ISSUE TITLE
Option to disable notifications on spesific servers or channels

### ISSUE THREAD

**Issue by TheRealEscimo** [thelounge/lounge#912]
As of now, thelounge supports mentions that will trigger an notification as well personal message seems to trigger notifications. But it would be nice to be able to turn off notifications on certain servers or channels that is really active, in order to suppress notification "spam". 
Notifications main purpose should be to notify the user about messages that have some sort of urgency.

**Comment by dgw** [comment]
See #85. Previous issues about this include #44 and #248.

**Comment by YaManicKill** [comment]
Closing as duplicate, as @dgw mentioned
