### ISSUE TITLE
Notification when disconnected from channel/network

### ISSUE THREAD

**Issue by jleew526** [thelounge/lounge#915]
It would be nice to get notifications for disconnects like messages.

Ex. ) in freenode, when you time out and disconnect, then the client reconnects, until the old nick is ghosted or times out in the network, you must use an alternate nick. This results in you being disconnected from all channels that require identifying with NickServ before joining (many of the larger channels), which means you miss out on a lot of conversations.

**Comment by bews** [comment]
This can be done by using "Custom highlights" in settings.

**Comment by YaManicKill** [comment]
As @bews says, this can be done with custom highlights, and you will clearly see that there are messages in the server window. I don't think we want to be adding situations like this that always notify the user. Seems awkward.
