### ISSUE TITLE
Deleting a user should log them out

### ISSUE THREAD

**Issue by astorije** [thelounge/lounge#916]
If a user is connected (private mode), even though `lounge remove <user>` says `User <test> disconnected and removed`, user is being disconnected from the IRC networks but not from the app.
User should be logged out and therefore sent to login page when their config file is removed.

**Comment by xPaw** [comment]
Does this not work? https://github.com/thelounge/lounge/blob/master/src/clientManager.js#L40-L47

**Comment by astorije** [comment]
It does remove the config file and disconnects **from the IRC networks** but it did not log me out of the app.

**Comment by xPaw** [comment]
Are you not losing connecting in browser? It should be killing all existing websocket connections for the client here: https://github.com/thelounge/lounge/blob/213a4b0f13b9a56493761aba4a1d4960f87f4d1a/src/client.js#L458-L465

**Comment by astorije** [comment]
I don't completely remember now, need more testing.
