### ISSUE TITLE
"Use /connect to reconnect" doesn't

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#917]
In v2.2.0, using `/connect` shows "Connected to the network", but about two minutes later gets disconnected again. No channels are joined.

Note: I am connecting to a ZNC, not directly to a network.

**Comment by dgw** [comment]
Ugh, new Android app for github, wrong button.

**Comment by Cldfire** [comment]
I actually just started experiencing this issue on 2.2.0 myself. I had no problems connecting to ZNC with any prior version.

**Comment by dgw** [comment]
Yep. This worked in 2.1.0, before I updated my instance to 2.2.0. Seems to be a regression.

**Comment by rib** [comment]
When I loose my connection to my znc proxy I see `Disconnected from the network, and will not reconnect. Use /connect to reconnect again.` but using `/connect` doesn't seem to do anything for me (no log output from lounge running in the foreground of a terminal on localhost or in the server tab in the UI).

I'm not aware of automatic reconnection ever working for me (even since #18) so I'm not sure this is the same more-recent regression others are describing.

**Comment by dgw** [comment]
@rib I've never seen auto-reconnection work either, on my instance. It sounds like what you're experiencing is the same issue (same error message, same symptom), but perhaps it's not a regression—just a bug with ZNC specifically?

**Comment by drkitty** [comment]
I'm having this issue too. I'm running git tag `v2.2.0` in dev mode with nginx as a reverse proxy. I turned on the `debug.ircFramework` setting and forced a disconnect by null routing the server. Then I restored the route and ran `/connect`, and it failed to reconnect. [Here's the TL server output and what I saw in the web app.](https://gist.github.com/drkitty/319b2851658ba53c3967da4ed7356e96)

**Comment by astorije** [comment]
Thanks @drkitty!

@xPaw, is that any useful to you?

**Comment by xPaw** [comment]
Looks like ping timeout is the initial trigger for the issue.

**Comment by xPaw** [comment]
https://github.com/kiwiirc/irc-framework/issues/56

**Comment by drkitty** [comment]
@xPaw Shouldn't you still be able to manually reconnect, though? Because that's what I was testing here. Or are auto and manual reconnect related somehow?

**Comment by xPaw** [comment]
I'm thinking the quit is throwing it into some invalid state. cc @prawnsalad

**Comment by xPaw** [comment]
Confirmed the bug, there's definitely some weirdness that doesn't do anything after issuing /connect.

**Comment by astorije** [comment]
@xPaw, do you think that would come from us or `irc-framework`?

**Comment by xPaw** [comment]
I haven't dug into the code, but I expect it to be in the framework.

**Comment by xPaw** [comment]
This should have been fixed in 2.2.2
