### ISSUE TITLE
CLI options are ignored when given in a specific order

### ISSUE THREAD

**Issue by nhooyr** [thelounge/lounge#925]
at https://thelounge.github.io/docs/getting_started/usage.html under start it says

```
lounge start --port 80 --private
```

that should be

```
lounge start -- --port 80 --private
```

or

```
lounge start --private --port 80
```

(edit: for the last one I meant `lounge --private --port 80`)

**Comment by astorije** [comment]
This is an error with The Lounge and not the docs, unfortunately.

Could you specify how you installed The Lounge (through `npm install -g thelounge`? From source using `git clone && npm install`? Using one of our OS packages?), as well as the actual behavior please?

Thanks!

**Comment by nhooyr** [comment]
I used nix. I created a nix package based off of the latest npm package (like just a few hours ago).

**Comment by astorije** [comment]
FYI, I could reproduce this on v2.2.1. However, none of the following worked:

```sh
lounge start --port 80 --private
lounge start --private --port 80
```

The alternative using `--` worked.
https://github.com/thelounge/lounge/pull/799 should have fixed that issue but it looks like it didn't fix it completely (because this has different root cause).

**Comment by nhooyr** [comment]
sorry for the last one I meant `lounge --private --port 80`

**Comment by astorije** [comment]
Wow, indeed, that works and that's even more messed up as `lounge` without any subcommand shouldn't do anything.

Definitely a lot of work needed on the CLI! If someone passes by and wants to contribute, lots of room for improvement!

**Comment by xPaw** [comment]
> lounge without any subcommand shouldn't do anything

https://github.com/thelounge/lounge/blob/00a3e3f14c01b2e8bd596af8f0bf5d102e091df7/src/command-line/index.js#L45-L47

**Comment by astorije** [comment]
Good point! We should have `lounge` == `lounge --help` instead of `lounge` == `lounge start` when this bug gets fixed though!

**Comment by msaun008** [comment]
I did a little digging into [commander](https://github.com/tj/commander.js) and saw that the lounge is only defining the ```options``` and the ```action``` callback function.  The lounge is not actually parsing ```process.argv```. 

Created PR https://github.com/thelounge/lounge/pull/929.
