### ISSUE TITLE
Bold formatting control character issue

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#928]
I've noted in The Lounge 2.2.1 (connected to multiple ZNC 1.6.3 nets) that **bold text** may display as `bold text` instead. I do not recall this issue manifesting in previous versions, but it also did not appear until my server rebooted itself some time after the update.

If I _send_ `something` by copying the character, the output in The Lounge chat window is **something**.

Note: As observed, and while writing this issue, I see (and copy/paste) `┐`. When I preview, I see instead ``. This may be entirely client-side, an issue with my Windows 7 system, but I have not seen it before this week. The system has not been updated or rebooted for over a month.

**Comment by dgw** [comment]
This may be related to #654.

**Comment by xPaw** [comment]
I'm noticing this issue on some channels too, not entirely sure if this regressed in 2.2 or not.

**Comment by xPaw** [comment]
Repro, at least for the issue I see: `\x0303test\x03 test`. Basically `\x03` without a color does not get stripped.

**Comment by astorije** [comment]
@dgw, can you test this as well on `master` now that #972 has shipped?

**Comment by dgw** [comment]
Cannot reproduce on `master` with #972 merged. Fixed! 🙌
