### ISSUE TITLE
docs are unclear as to what reverseProxy does.

### ISSUE THREAD

**Issue by collinanderson** [thelounge/lounge#945]
I've been using shout/thelounge behind nginx for a year and now just noticed this setting. What am I missing out on?

**Comment by PolarizedIons** [comment]
This might help? https://github.com/thelounge/lounge/wiki/Reverse-Proxies

> This makes The Lounge available under https://yourdomain.net/irc/.

**Comment by collinanderson** [comment]
Right, it's just that the official docs say almost nothing: https://thelounge.github.io/docs/server/configuration.html#reverseproxy

**Comment by xPaw** [comment]
This option uses `X-Forwarded-For` if enabled to get correct user IP address when sitting behind a proxy (e.g. nginx).
