### ISSUE TITLE
Add support for EmojiOne

### ISSUE THREAD

**Issue by tmiland** [thelounge/lounge#949]
Hi,

i just wanted to propose adding support for EmojiOne: https://github.com/Ranks/emojione

Regards,
Tommy

**Comment by astorije** [comment]
#620 adds emoji support. For now it's in the v2.3.0 roadmap.
I don't know/think we specifically need EmojiOne however. @thelounge/maintainers, thoughts?

**Comment by astorije** [comment]
I am going to close this because it seems that we are not going for EmojiOne. That doesn't mean we don't want emoji, it is in progress and still hoping to have it by next release, but not the one you linked in this issue.

Thanks for your report! 😃
