### ISSUE TITLE
Add option to append random numbers to nick on the config file and a few more ideas

### ISSUE THREAD

**Issue by TheMythPT** [thelounge/lounge#950]
Hello. I'd like to know if it's possible to somehow append randow numbers to a nick, on the config file.
 on config.js:
defaults: {
...
// Nick
                //
                // @type     string
                // @default  "lounge-user"
                //
                nick: "lounge-user",

- In here, adding an option like "nick_?" where ? corresponds to at least 3 random numbers.

-  If a network dont have The Lounge set in webirc mode on their IRCd conf file, if two users  connects at the same time, one of them will be unable to connect due to nick collision

                //
                // Username
                //
                // @type     string
                // @default  "lounge-user"
                //
                username: "lounge-user",

- If blank and if "useHexIp: false," & " webirc: null," set the same as nick, otherwise if "useHexIp: true," that will send the hexed ip of the user.

                //
                // Real Name
                //
                // @type     string
                // @default  "The Lounge User"
                //
                realname: "The Lounge User",

                //
                // Channels
                // This is a comma-separated list.
                //
                // @type     string
                // @default  "#thelounge"
                //
                join: "#thelounge"
        },

I've searched but didn't found the PR/Issue with something related to this one:
If private server is restarted/dies, all "log" are lost, even with the option to save logs to disk enabled.
That's one thing that could be improved.

The overall of The Lounge is very good and it fits very well even on smartphones.

Keep up the good work.

**Comment by xPaw** [comment]
Just wondering, what would this accomplish? What's the use case?

**Comment by TheMythPT** [comment]
at least the append random numbers to nick is due to the fact if two users of same thelounge instance tries to connect with the same nick, the second user will not be able to connect, as the nick is already in use.

**Comment by xPaw** [comment]
Lounge already handles that case on its own. And it does so by appending random numbers.

**Comment by TheMythPT** [comment]
my idea was to set it with numbers since the first user connecting.. even if was the 1st user connecting, would be 'lounge-user-number', in example. and also for each "?" append 2 numbers, so if i choose "lounge-user-??" there will be 4 numbers appended..
but i see it handles it pretty well, and maybe the nick collision i've saw was something weird..

**Comment by TheMythPT** [comment]
and one more.. if i use the public server, even with lockNetwork: true, the network and server appears there, but i know it cant be changed..
is there anyway to hide Network Settings and leave just User Preferences?

**Comment by astorije** [comment]
@TheMythPT, look at [the `displayNetwork` option](https://thelounge.github.io/docs/server/configuration.html#displaynetwork), I believe that's what you are looking for :)

Closing this feature request as it is already implemented as @xPaw mentioned. If you notice this again, that would be a bug rather than a feature request, and we can reopen this ticket. Just make sure to get as much info as you can so we can reproduce and/or understand better where the issue comes from.
