### ISSUE TITLE
"show more" is constantly checked on an interval

### ISSUE THREAD

**Issue by xPaw** [thelounge/lounge#96]
https://github.com/thelounge/lounge/blob/1e8ca51d47f78e30e8d429cfc164258386e0f5d7/client/js/lounge.js#L818-L825

This should just happened whenever a new message is received or something like that.

**Comment by astorije** [comment]
Wow, that's a nasty one, :+1:
Maybe not at every new message though, because some channels, sometimes posts much more than once every 10 seconds, and that would be a killer when there is spam or netsplits as it happened today on Freenode. Some design required then, but good catch!

**Comment by lindskogen** [comment]
Probably a debounce on new message with `delay = 1000` would do the trick https://lodash.com/docs#debounce

**Comment by xPaw** [comment]
That might be awful if you load more history and a new message comes in, it's going to trim the history again.

**Comment by lindskogen** [comment]
Well, it's only run when the channel is not active so that won't be a problem

**Comment by xPaw** [comment]
Ah, you are correct. But we might want to trim active channels too?
