### ISSUE TITLE
User settings should save "Messages" preferences

### ISSUE THREAD

**Issue by bnvk** [thelounge/lounge#963]
Currently, upon each user login to a Lounge instance, the users preferences for the following settings are reset:

```
Show joins
Show MOTD
Show parts
Show nick changes
Show mode
Show quits
```

The `.lounge/users/name.json` should persist in saving these settings!

**Comment by xPaw** [comment]
These are saved in local storage in your browser. There is a branch for server saving.

**Comment by bnvk** [comment]
> These are saved in local storage in your browser

Yah. With strong browser privacy settings enabled this gets wiped on each new
session.

> There is a branch for server saving.

Assuming this is the `settings` branch- is this going to merged in or is
there some holdup?

**Comment by xPaw** [comment]
Yes the branch is stale, needs someone to work on it.

**Comment by bnvk** [comment]
@xPaw okie doke. I can take a stab at bringing it current. Any specific
changes / things to be aware of? There's lots of branches and pull-reqs that
look > 2 months old.

**Comment by MaxLeiter** [comment]
@bnvk probably just that there have been lots of client-side changes like switching to webpack

**Comment by xPaw** [comment]
I just rebased that branch onto master, it "works" but needs a very close look at each setting to bring all the client code up to date, as there were a lot of changes.

**Comment by xPaw** [comment]
Closing in favour of #85.
