### ISSUE TITLE
array of IP's

### ISSUE THREAD

**Issue by rastaval** [thelounge/lounge#966]
how do I make Lounge choose randomly from serveral IP's that I have. so for example, I have 

192.168.1.10 as my main ip, and I have several IP's on my server like 192.168.1.11-19.
I wish lounge to randomly pick or choose any IP within the range upon connecting so lounge will not only use 1 IP or the main upon connecting. Thank you.

**Comment by astorije** [comment]
I believe this is very unlikely to be implemented anytime soon, but I might be wrong. @xPaw, what do you think about this? Closing or asking community for contribution?

**Comment by xPaw** [comment]
This could be done with DNS, but i don't think node's DNS resolver rotates IPs.
