### ISSUE TITLE
configuration help

### ISSUE THREAD

**Issue by rastaval** [thelounge/lounge#967]
We have our own IRCD and we wish to connect lounge to it. but the lounge will launch or will be running in the same box as the IRCD. My question is how do I correctly configure lounge so we can have the same as this:

lounge-user81 (769ee33c@gateway/web/thelounge/ip.118.158.227.60) has joined the channel

118.158.227.60 is the ip of the user and not the IP of the box where lounge is running. thank you..

**Comment by xPaw** [comment]
On freenode we use the hexip option. Freenode set a iline for us. You could also look into using webirc.
