### ISSUE TITLE
Timestamp Show Seconds

### ISSUE THREAD

**Issue by vectr0n** [thelounge/lounge#98]
It would be really handy to be able to see the seconds in the time stamps.

**Comment by TheSonAlsoRises** [comment]
Agreed. Along with #89, I would say the two would make the messages much more legible.

**Comment by YaManicKill** [comment]
We had 2 different PRs trying to fix this, and neither ended up being agreed, so we should probably agree on how we want this.

There were 2 approaches:

1. Just having a setting to show or hide seconds
2. Having an input to choose a time format

If anyone has any other ideas, share them now. For me, I guess 1 makes most sense. @astorije pointed out that that would be the absolute most common reason to want to change the timestamp, and that having a text input for time format would be confusing.

**Comment by vectr0n** [comment]
I think it would be easier to just have a show seconds or hide seconds option, or maybe have the option for a custom time format in the server config?

**Comment by Dr-Horv** [comment]
1. seems much easier and less confusing for the end user. Should cover most people needs. Could reopen this issue if anyone desires anything else.

**Comment by hho** [comment]
Can you please add the date as well?

**Comment by dgw** [comment]
And this is why 2. was proposed…because everyone wants slightly different information in their timestamps.

**Comment by hho** [comment]
Maybe there's some middle ground, like having a dropdown with different formats? That'd be more user friendly (though not as flexible). Or output complete timestamps and have CSS classes for date, second, etc. so that themes can hide the different parts.

**Comment by YaManicKill** [comment]
Alright I suggest that we have a setting to enable seconds, but we have a hovertext on the time to show the full date time.

That coupled with a date seperator on the page should be enough to satisfy everyone?

**Comment by dgw** [comment]
Setting for seconds and hovertext with the full timestamp…sounds good to me. ISO8601 style for the hovertext?

**Comment by YaManicKill** [comment]
> ISO8601 style for the hovertext?

**Comment by dgw** [comment]
That'd be a hell of a long tooltip. Twitter's hoverstamps (is that a good name for them?) read e.g. "8:21 AM - 27 May 2016", nice and concise. Why include the timezone when the UTC date can be passed to the client and converted to the useragent's local timezone for display?

**Comment by DanielOaks** [comment]
I like to get my instance of lounge to hook up to my ZNC box. Since messages can sometimes come from days or weeks back, I find having dates on the messages really useful as well (at least month/day, kinda like `09/23 12:38:04`).

I can hack it in myself if necessary, but if this is being looked at this anyway, would it be possible to be able to show `mm/dd`, `yy/mm/dd`, or something similar as well?

**Comment by astorije** [comment]
Ideally we will have a marker for days at some point, similar to the unread marker in terms of design, for that stays displayed. Not sure when this is going to happen though.
In the meantime, we should add a title on the current timestamp, similar to what many other services do:
<img width="416" alt="screen shot 2016-09-30 at 11 42 10" src="https://cloud.githubusercontent.com/assets/113730/18997610/3a85260c-8703-11e6-840a-73a5a698e571.png">

This is actually trivial to implement, if someone wants to take a look at it (note that the GitHub example displays time in the user timezone, so this is done with JS on the front-end, but this is neat!).

**Comment by xPaw** [comment]
Fixed by #1141
