### ISSUE TITLE
Raspberry Pi 2 issues with login in private mode

### ISSUE THREAD

**Issue by rockhouse** [thelounge/lounge#982]
I tried today to install TheLounge on my raspberry pi. Unfortunately, the private mode did not work, the public without user management worked fine. After some digging into the code I think I found the culprit to be the bcrypt function call. My guess is that the pi is not fast enough in calculating the hashes and therefore nodeJS throws a time-out as during the login the CPU is at 100%. 

It does not go beyond: https://github.com/thelounge/lounge/blob/c409328ddf38db3b421c61bf2f688317f8e07f9d/src/server.js#L270

Hardcoding the return value to `return true` lets me use TheLounge without further issues. 

I tried reducing the rounds of bcrypt [here](https://github.com/thelounge/lounge/blob/c409328ddf38db3b421c61bf2f688317f8e07f9d/src/helper.js#L124) to as low as 3 but it did not help.

Node.JS Version: v6.10.0
NPM Version 3.10.10
TheLounge Version: v2.2.2 - 2017-03-13
Raspberry Pi 2 

I wrote this issue on request of @MaxLeiter

**Comment by MaxLeiter** [comment]
Currently we use `bcrypt-nodejs`, which is written in javascript. Maybe we should try `bcrypt` (https://github.com/kelektiv/node.bcrypt.js) which is in C++ and should have improved performance

**Comment by williamboman** [comment]
Here's how my, otherwise idle, RPI2 performs;

```js
const bcrypt = require('bcrypt-nodejs')

const WORK_FACTOR = Number(process.argv[2])

console.time('total')

console.time('hashing')
const hashed = bcrypt.hashSync('foobar123', bcrypt.genSaltSync(WORK_FACTOR))
console.timeEnd('hashing')

console.time('comparing')
bcrypt.compareSync('foobar123', hashed)
console.timeEnd('comparing')

console.timeEnd('total')
```

```sh
$ node index.js 3
hashing: 6196.849ms
comparing: 5889.733ms
total: 12151.383ms

$ node index.js 11
hashing: 11534.611ms
comparing: 11273.490ms
total: 22872.446ms
```

@rockhouse How much time do you give TL before concluding it has somehow timed out? Does the process crash or does it just keep chugging at 100% cpu?

**Comment by MaxLeiter** [comment]
@williamboman can you try with `bcrypt`?

**Comment by williamboman** [comment]
```sh
$ node index.js 3
hashing: 21.675ms
comparing: 11.148ms
total: 96.173ms

$ node index.js 11
hashing: 1118.579ms
comparing: 1113.744ms
total: 2294.730ms
```

Installation time was quite brutal though.

**Comment by williamboman** [comment]
I can't find a documented reason why erming [switched to `bcrypt-nodejs` from `bcrypt`](https://github.com/erming/shout/commit/316fba3c084bfed3b72c2dde5322e8b7cf37eac5).

**Comment by MaxLeiter** [comment]
Heavy dependency but the improvement is major. Thoughts @thelounge/maintainers?

**Comment by williamboman** [comment]
I'd rather switch to a better JS implementation such as https://github.com/dcodeIO/bcrypt.js. 

```sh
$ node index.js 3
hashing: 489.621ms
comparing: 44.254ms
total: 599.109ms

$ node index.js 11
hashing: 3657.484ms
comparing: 3059.422ms
total: 6782.621ms
```

**Comment by rockhouse** [comment]
I tried bcrypt.js on my raspberry but it is still too slow

**Comment by astorije** [comment]
I'm not entirely sure the source of this is bcrypt. I am using a Rpi 2 as well, and I know of people using an even lighter RPi and I am not seeing any issues. It does take a few seconds to login, but that's all.
