### ISSUE TITLE
Connection loss without notice

### ISSUE THREAD

**Issue by Philipp91** [thelounge/lounge#990]
I run lounge-irc as a systemd service on a Raspberry Pi 3 (Ethernet connection, stable internet). Until a week ago, I had v2.1.0 (installed last year, never updated) and everything worked fine. Then I reinstalled Raspbian and lounge-irc, presumably the same way I did before but v2.2.2 this time. Maybe something else changed that I can't think of now.

My v2.2.2 on Raspbian shows symptoms where it just does not send and receive anymore. 10 minutes after reconnecting (or even rebooting the Pi), I try some command like `/whois test` and sometimes I receive a response, sometimes the response takes over a minute to arrive and sometimes nothing happens forever. When I wait longer, all commands do not work anymore, though sometimes it detects that it must have disconnected and automatically reconnects.
In particular, it doesn't receive any messages after a couple minutes of inactivity.
The web client is always perfectly responsive.

There are several possibly related issues. https://github.com/thelounge/lounge/issues/648 https://github.com/thelounge/lounge/issues/917 https://github.com/thelounge/lounge/issues/915

I tried to activate the debug logging, but can't find any debug log file anywhere.

**Comment by maxpoulin64** [comment]
If it takes minutes for responses to arrive, it would seem that your internet connection is nowhere as stable as you think it is, or your Pi is overloaded and can't keep up with the load. I can't think of any reason why things would be so slow or delayed on the Raspberry Pi. Maybe something's up with your node installation?

**Comment by Philipp91** [comment]
It's the same hardware as before when it worked fine and now nothing else running on there, whereas before I had Kodi and TVHeadend and a VNC client, too. This time, I installed the headless "lite" version of Raspbian, though -- that might be the culprit?

After an hour of absence, during which `top` was running fine over SSH without interruption, the latest message in the IRC network output is still "You are connected using SSL cipher ...", but when I send `/whois test`, it says "Disconnected from the network. Reconnecting in 11 seconds… (Attempt 1 of 360)" and then it's immediately reconnected and my next `whois` works normally.

So somehow it gets disconnected without noticing, while the Raspi was running fine the whole time, almost no CPU load. Even if the internet connection _was_ spotty, which it isn't on my PC at least, I'd expect lounge to notice that it got disconnected. Doesn't it send some sort of keep-alive/heartbeat messages? Maybe I turned those off accidentally?

**Comment by xPaw** [comment]
Sounds like a silent network failure. We had ping timeouts for that, which were disabled in 2.2.2 due other issues.

**Comment by Philipp91** [comment]
Thanks for the hint! Downgraded to 2.2.1, problem is gone. I can live with that, not going to need it for long anyway (you can close this issue). But if you're interested in debugging this, I'm happy to help.

**Comment by TheRealEscimo** [comment]
I have the exact same issues. Tried with dev and 2.2.2. 
Tried different virtual machines as well, both Hyper-V and VirtualBox and the problem persists. When the issue happens, no messages are recieved and the clients time out from the connected server, but TheLounge still seems like it is online. when looking from a connected clients perspective. The user can type messages within channels and direct PMs without getting any errors, but it does not reply to whois however. 

All my installations had Nodejs7 and https enabled. Don't know if that helps. Also, Ubuntu server.

**Comment by xPaw** [comment]
This should be improved or fixed entirely on master.
